### ISSUE TITLE
Skim doesn't automatically update on Mac with macOS High Sierra

### ISSUE THREAD

**Issue by brucejk** [lervag/vimtex#1003]
I have added let g:vimtex_view_method = 'skim' to my .vimrc, and \lv does open the document in the Skim app but it doesn't automatically update when it finishes compiling the document. I have to use \lv again and then it'll update. ps I'm using MacBook Pro with macOS High Sierra operating system. 

Thanks for this AWESOME plug-in:)

**Comment by brucejk** [comment]
Oh I found that I need to set the auto-reload in the preference setting. It works now!

**Comment by lervag** [comment]
Thanks for the kind words! :)

Also, I'm happy to hear that things are working. I am, unfortunately, no expert on MacOS and Skim, and the reason it is implemented and should work is mainly due to kind other users who have helped implement something that should work. See #997 and #982 for recent issues that might be interesting and relevant, if you are up for some reading.

One thing: I was not aware that one needed to set any settings for things to work. @clason Is this right, and should we add something in the docs about this?

**Comment by clason** [comment]
@lervag No, the switch should have been transparent; I only have 
```
let g:vimtex_view_method = 'skim'
```
in my `.vimrc`.

But I believe @brucejk is referring to **Skim's** auto-reload setting, not vimtex's, so the latter still seems not to working for him. Maybe he has to set `g:vimtex_compiler_progname` as well for the callback to trigger?

**Comment by lervag** [comment]
That was actually what I suspected.

@brucejk Obv., since things are working, you might be just as happy. But if you should want to figure out why things are not working without that auto-reload setting in Skim, then I suggest you provide some more information:

1. Which version of Vim/neovim?
2. Which settings are you using for vimtex?
