### ISSUE TITLE
Formatting of .tex files

### ISSUE THREAD

**Issue by 3e4** [lervag/vimtex#1020]
I recently started using vimtex and enjoy it very much. Thank you for your work.

However, I am a bit confused about what is the recommended method of formatting the source files.
I have found that there is the `gq` command, which will redistribute words in a paragraph to fill each line. This is required after deleting words but would be better if it happened instantaneous. Then there is `formatexpr` which can be enabled by `g:vimtex_format_enabled`. This only affects comments in latex?

If I do `gqip` on a math environment, everything is moved into one line. If I add `a` to `formatoptions`, this happens as I type. Is there a way to apply gq to all paragraphs on save and protect the environments?

So the information I struggle to find is **what is known to not (yet) work in vimtex**? You have a long list of Features, but do you keep anywhere a list of Limitations or a roadmap?

I could find some related issues:
https://github.com/lervag/vimtex/issues/517
https://github.com/lervag/vimtex/issues/226

**Comment by lervag** [comment]
I happy you like it!

There are actually several ways to format the source files, although vimtex only supports one style: hardwrapping at a given line length. The style is implemented through the `formatexpr`. Note, though, that you can also use `gw` for formatting, but this will only format according to Vim specific options and is independent of the `formatexpr`.

For automatic formatting, as you say, you must add `a` to `formatoptions`. However, I would suggest that you do not enable that, as I would expect it to not provide the best of results for every kind of element in a LaTeX document (e.g. math).

Formatting LaTeX is actually a difficult task, because there is not one canonical way of formatting. Also, there are different styles. I am currently personally adhering to the "one sentence per line" style, which works well when you work in teams, because it is very easy to `(git|hg) diff` between versions. It also gives the benefit of making it easy to spot very long lines, which is a symptom of bad writing. I have been thinking about adding this style as a new `formatexpr`, but I have not had the time to test it out yet.

As to your question about applying `gq` on save: What do you mean by "protect the environments"? In principle, you could try whether `gggqG` gives satisfying results. I expect that it will _not_, but if it does, then you can add an autocommand on save in order to apply the formatting before saving.

However, as I said above: I personally do not recommend that you apply such formatting automatically. First and most importantly because I expect it will not work perfectly, but also because you will lose control over what happens. IMHO, the benefits of autoformatting and similar is not worth the risk of it failing or adding unwanted changes that I might not notice immediately.

Finally, for your last question: there is a list of limitations, sort of, see `:h vimtex-non-features`. However, there is no roadmap. I do not plan to add more features per se, but I tend to develop new features based on good suggestions from the community. That is, I find vimtex is mostly complete for my own use, but if anyone opens an issue with a suggested new feature or enhancement that I think will be good for vimtex, then I am often tempted to try to implement that feature.

**Comment by 3e4** [comment]
Thank you for your detailed explanation of how you use vimtex. As this helps to use it properly.

Do you set softwrap and what is your `formatoptions`? Currently I have `ctq` when editing `.tex` files, and it makes a hard wrap when exceeding my `textwidth=79`.

It appears you use 
```
:set wrap
:set linebreak
```
and adjusted key mappings to navigate through the wrapped lines? Is this correct? (http://vim.wikia.com/wiki/Move_through_wrapped_lines)

**Comment by lervag** [comment]
No, I use `textwidth=79`, which enables hard wrapping. I typically toggle the `wrap` option on/off depending on the current text (i.e., for long lines I turn it on). For `.tex` buffers, my `formatoptions` is `tcqronl1j`.

Note that `wrap` does not affect formatting, it only affects the view. Same for `linebreak`. This is explained in `:h wrap` and `:h linebreak`.

I do remap `j` and `k`:

```vim
nnoremap <expr> j v:count ? 'j' : 'gj'
nnoremap <expr> k v:count ? 'k' : 'gk'
```

So, as you see: My config is still based on formatting my LaTeX code with a fixed textwidth of 79 characters, and not as I suggested in my first reply. However, this may change in the future. As said, I think using one sentence per line seems as the best solution to me for LaTeX files.
