### ISSUE TITLE
Any way to have zathura scroll along with the cursor in vim?

### ISSUE THREAD

**Issue by GijsTimmers** [lervag/vimtex#1029]
Hi, thanks for writing this plugin, it's proven very useful to me.

I often use `\lv` to have `vimtex` focus `zathura` on the line I'm currently editing. I was wondering if it's possible to have `zathura` scroll along with my cursor automatically, in real-time so to speak.

Thanks

**Comment by lervag** [comment]
I'm happy you like it! :)

Regarding your question: No, I do not know any way to do that. I guess one could use the `CursorMoved` autocommand from Vim and write a function that calls the `\lv` mapping (or, rather, a variant of the underlying function) whenever the cursor moves to a different line. However, I would not expect this to work very well, and I am not sure if it is possible to focus a line in `zathura` without it being highlighted. In any case, since i) I don't really think this will work very well, and ii) I don't find this feature very necessary, I think I will not try to implement it. If you have some knowledge of vimscript yourself, then it should not be too difficult to follow my suggested idea above and write a proof of concept to test it.

**Comment by GijsTimmers** [comment]
OK I understand that totally. Thanks for pointing me in the right direction!

**Comment by lervag** [comment]
No problem :)
