### ISSUE TITLE
latexmk process still running after exiting vim

### ISSUE THREAD

**Issue by bulibuta** [lervag/vimtex#1032]
Hi,

My setup is the same as the one from #1018, but I notice that everytime I close vim there is a latexmk process still running.

```
$ pgrep -lf vim
33680 perl /usr/local/bin/latexmk -verbose -pdf -synctex=1 -interaction=nonstopmode -pvc -e $new_viewer_always = "0" -e $pdf_update_method = "2" -e $pdf_update_signal = "SIGHUP" -e $pdf_previewer = "mupdf " -e $success_cmd = "vim --servername VIM --remote-expr \"vimtex\#compiler\#callback(1)\"" -e $failure_cmd = "vim --servername VIM --remote-expr \"vimtex\#compiler\#callback(0)\"" dl_book.tex
1705 sh -c max_print_line=2000 latexmk -verbose -pdf -synctex=1 -interaction=nonstopmode -pvc -e '$new_viewer_always = "0"' -e '$pdf_update_method = "2"' -e '$pdf_update_signal = "SIGHUP"' -e '$pdf_previewer = "mupdf "' -e '$success_cmd = "'""'vim'""' --servername 'VIM' --remote-expr \"vimtex\#compiler\#callback(1)\""' -e '$failure_cmd = "'""'vim'""' --servername 'VIM' --remote-expr \"vimtex\#compiler\#callback(0)\""' 'dl_book.tex'
```

Is this expected? How can I fix this? I browsed `compiler/latexmk.vim` for a bit, but it was not obvious how the callback mechanism is used to stop the compiler.

Happy New Year,
Paul

**Comment by lervag** [comment]
Does this happen with the following minimal example:

```tex
% mwe.tex
\documentclass{scrartcl}
\begin{document}
Word
\newpage
Word2
\end{document}
```

```vim
" minivimrc
set nocompatible
let &rtp = '~/.vim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable

let g:vimtex_quickfix_method = 'pplatex'
let g:latex_view_method = 'mupdf'
```

That is, with the above files:

1. `vim -u minivimrc mwe.tex`
2. `\ll`
3. `:qa`
4. `pgrep -lf vim`

**Comment by bulibuta** [comment]
Yes it does. I just had to add `vim --servername VIM` to your first command.

```
10998 perl /usr/local/bin/latexmk -verbose -pdf -synctex=1 -interaction=nonstopmode -pvc -e $pdf_previewer = "xdg-open" -e $success_cmd = "vim --servername VIM1 --remote-expr \"vimtex\#compiler\#callback(1)\"" -e $failure_cmd = "vim --servername VIM1 --remote-expr \"vimtex\#compiler\#callback(0)\"" mwe.tex
41503 sh -c max_print_line=2000 latexmk -verbose -pdf -synctex=1 -interaction=nonstopmode -pvc -e '$pdf_previewer = "xdg-open"' -e '$success_cmd = "'""'vim'""' --servername 'VIM1' --remote-expr \"vimtex\#compiler\#callback(1)\""' -e '$failure_cmd = "'""'vim'""' --servername 'VIM1' --remote-expr \"vimtex\#compiler\#callback(0)\""' 'mwe.tex'
```

**Comment by lervag** [comment]
Ok, I see. Silly question: You are sure that before you do the test, there are no latexmk processes?

Now to get our hands dirty: the problem is either with the code that actually stops the process, which is here: [compiler/latexmk.vim:318 - `s:compiler.stop()`](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/compiler/latexmk.vim#L318). It depends on the backend which `kill` function is used. If you are on a modern Vim, I believe the relevant method is this one: [compiler/latexmk.vim:448 - `s:compiler_jobs.kill()`](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/compiler/latexmk.vim#L448).

However, it may be there is a problem with the autocommand and related function, see here: [compiler.vim:284](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/compiler.vim#L284). Also, see [compiler.vim:221 - `vimtex#compiler#stop_all()`](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/compiler.vim#L221).

And finally, there is also some relevant stuff happening in [vimtex.vim](https://github.com/lervag/vimtex/blob/master/autoload/vimtex.vim) in lines 20, 345-348. I think perhaps the `s:quit()` function should be the one that is fired first and that should actually do the cleanup and process killing through [state.vim](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/state.vim#L456) line 456: `s:vimtex.cleanup()`.

I would probably first try to do some `echo`-debugging. When doing that, it is useful to use statements like `unsilent echo` or `unsilent echom`, since in some cases the `echo`s are silenced.

I hope you are able to do some investigations on your side, as I don't have any BSD systems to reproduce this issue on.

**Comment by bulibuta** [comment]
Double checked, no latexmk process is running before testing.

Is  [`let s:vimtex_states[b:vimtex_id] = b:vimtex`](https://github.com/lervag/vimtex/blob/d6bb7898a3e233bbf05307e34b0c24990135b51b/autoload/vimtex/state.vim#L27) the only place where `vimtex_states` is set? Because `b:vimtex` returns nothing when ran by hand in vim (while using vimtex and latexmk).
This array is used by the [`stop_all` routine](https://github.com/lervag/vimtex/blob/648050424631f908d480f9216404cc82044a5f98/autoload/vimtex/compiler.vim#L222) and if it is empty then nothing gets stopped. Am I right?

**Comment by lervag** [comment]
`b:vimtex` is the local vimtex state. Since a multi-file project has the same state, I use `s:vimtex_states` as a container for all vimtex states (in order to handle that one possibly edits several tex projects at the same time).

If you do `\li` or `:VimtexInfo` after opening the file, you will see some relevant information. It could be interesting to see this output here as well.

I am 99.9% sure that `b:vimtex` is properly set, because if it was not, then _nothing_ would work (e.g. `\ll` would not work).

To be more specific, the code you refer to does one of two things:
- When you initialize a vimtex state, we first check if there is currently already a state for the current project. If there is, then we set `b:vimtex` to point to it.
- If not, then we create a new state in b:vimtex and add that to the (script specific and thus "secret") state container.

**Comment by bulibuta** [comment]
```
System info
  OS: OpenBSD sci.irofti.net 6.2 GENERIC.MP#246 amd64
  Vim version: VIM 8.0 (1-1255)
  Has clientserver: true
  Servername: VIM

vimtex project: mwe
  base: mwe.tex
  root: /home/bulibuta
  tex: /home/bulibuta/mwe.tex
  out: /home/bulibuta/mwe.pdf
  log: /home/bulibuta/mwe.log
  aux: /home/bulibuta/mwe.aux
  fls: /home/bulibuta/mwe.fls
  document class: scrartcl
  packages:
    keyval
    scrbase
    scrkbase
    scrlfile
    tocbasic
    typearea
  compiler: latexmk
    backend: jobs
    output: /tmp/vAHmzZ9/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -synctex=1
        -interaction=nonstopmode
    job: process 56402 run
    cmd: max_print_line=2000 latexmk -verbose -pdf -synctex=1 -interaction=nonst
  viewer: General
  qf: LaTeX logfile using pplatex
    setqflist: 53
```

**Comment by lervag** [comment]
Yes, this confirms my thought that we use the `jobs` backend here. For some reason, it seems like the autocommands that should run when you quit, i.e. `VimLeave` does not work as it should.

I would start by looking at [compiler/latexmk.vim:448 - `s:compiler_jobs.kill()`](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/compiler/latexmk.vim#L448), which should kill the job. I would add some simple echo's, then try to toggle compilation on and off to confirm that the output is shown. Next I would try to combine a `echo "..."` with `sleep n` to see if the function is called when you do `:q`.

**Comment by chuckmasterson** [comment]
I'm still having this issue (Neovim 0.2.3 under MX Linux 18.1, vimtex pulled from Git on Feb 26). It perplexed the heck out of me when I couldn't figure out why my external hard drive was refusing to unmount. Turned out latexmk was keeping it busy. What can I do to make the perl latexmk process end, short of `killall perl`?

**Comment by lervag** [comment]
Can you open a new issue and provide a minimal example that reproduces this? If it is a bug in vimtex, then the only way for me to fix it is if I can reproduce the problem.

Note: In general, vimtex _should_ kill the latexmk process when you close vimtex/vim/neovim. This works for me on Vim and neovim, and there are few to no issues related to this the last year or so.
