### ISSUE TITLE
Compiler does not update PDF

### ISSUE THREAD

**Issue by lobachevzky** [lervag/vimtex#1033]
## Explain the issue

1. Steps to reproduce
    ```
    ❯ ls -a
    .	..	hw1.tex
    ❯ nvr --servername VIM hw1.tex
    ```
    I type `\ll` and my pdf viewer (Preview) pops up displaying 'Hello World!'
    I delete 'Hello World!', write 'Hello vimtex!', and save.

2. Expected behaviour: The pdf viewer should update to display 'Hello vimtex!'

3. Observed behaviour: The pdf does not change. I type `\lv`. Still no change. I type `\ll`. Messages displays
    ```
    vimtex: Compiler stopped (hw1.tex)
    ```
    I type `\ll` again. Messages displays
    ```
    vimtex: Compiler started in continuous mode
    ```
    Still no change to the pdf.

## Minimal working example

```tex
\documentclass{minimal}
\begin{document}
Hello World!
\end{document}
```

## Minimal vimrc file

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
```

I have been able to reproduce the issue with the provided minimal files. I have tried using Skim instead of Preview, but this does not solve the issue. One thing that would help me debug the file is if I had a clearer sense of exactly what `latexmk` command the plugin is calling when I update the source file.

Another thing worth mentioning is that when I start `nvr` I get the following error:

```
❯ nvr --servername VIM hw1.tex

[!] Can't connect to: VIM

    The server (nvim) and client (nvr) have to use the same address.

    Server:

        Expose $NVIM_LISTEN_ADDRESS to the environment before
        starting nvim:

        $ NVIM_LISTEN_ADDRESS=VIM nvim

        Use `:echo v:servername` to verify the address.

    Client:

        Expose $NVIM_LISTEN_ADDRESS to the environment before
        using nvr or use its --servername option. If neither
        is given, nvr assumes "/tmp/nvimsocket".

        $ NVIM_LISTEN_ADDRESS=VIM nvr file1 file2
        $ nvr --servername VIM file1 file2
        $ nvr --servername 127.0.0.1:6789 file1 file2

    nvr is now starting a server on its own by running $NVR_CMD or 'nvim'.

    Use -s to suppress this message.

[*] Starting new nvim process with address VIM
```

I am probably misinterpreting the error message, but `NVIM_LISTEN_ADDRESS=VIM nvr --servername VIM hw1.tex` and `NVIM_LISTEN_ADDRESS=VIM nvr hw1.tex` hang indefinitely, until I `C-c`, at which point they open a blank vim terminal.

Thanks for your help on this. Love the plugin!

**Comment by lervag** [comment]
> Love the plugin!

Thanks!

So, I'm curious: why do you use `nvr --servername VIM ...` instead of just `nvim ...`? I suspect you might have misunderstood the point of `nvr` (unless it is I who misunderstand). When you start `nvim`, it will automatically set a servername. Then you can use `nvr` to do stuff like `nvr --servername VIM --remote[...]` to communicate with a neovim instance. However, I think you should generally use `nvim` when you start to edit stuff, not `nvr`. Also, you should notice the `:h vimtex-faq-neovim` and set `g:vimtex_compiler_progname = 'nvr'`.

After you do `\ll`, could you do `\lo` and copy the output here?

Finally: I took the liberty of cleaning your post and removing stuff that is not relevant.

**Comment by lobachevzky** [comment]
So, one update. After I wrote the post, the pdf started updating when I typed `\lv`. Following your advice, I switched to plain nvim and observed the following change: now the pdf updates whenever I actually select the Preview/Skim window. So I no longer have to type `\lv` but I do have to actually click on the pdf window to get it to update. Maybe it's some weird OS X thing.

> You did not provide the configuration that you use for Preview (unless Preview is the default with no extra configuration).

Preview is the default pdf viewer for OS X.

> After you do `\ll`, could you do `\lo` and copy the output here, as well as the output/content of `\li`?

`\lo` is empty.

`\li`:
```
1 System info
2   OS: Mac OS X 10.13.2 (17C88)
3   Vim version: NVIM v0.2.2
4   Has clientserver: true
5   Servername: /var/folders/bd/8nh4kyg933zcxm7n90n2m98r0000gn/T/nvimvn9zBS/0
6
7 vimtex project: hw1
8   base: hw1.tex
9   root: /Users/ethan/homework/issue
10   tex: /Users/ethan/homework/issue/hw1.tex
11   out: /Users/ethan/homework/issue/hw1.pdf
12   log: /Users/ethan/homework/issue/hw1.log
13   aux: /Users/ethan/homework/issue/hw1.aux
14   fls: /Users/ethan/homework/issue/hw1.fls
15   document class: minimal
16   compiler: latexmk
17     backend: nvim
18     output: /var/folders/bd/8nh4kyg933zcxm7n90n2m98r0000gn/T/nvimvn9zBS/1
19     configuration:
20       continuous: 1
21       callback: 1
22       latexmk options:
23         -verbose
24         -pdf
25         -file-line-error
26         -synctex=1
27         -interaction=nonstopmode
28   viewer: General
29   qf: LaTeX logfile
30     config:
31       fix_paths: 1
32       packages:
33         default: 1
34       default: 1
```

**Comment by lervag** [comment]
> So, one update. After I wrote the post, the pdf started updating when I typed \lv. Following your advice, I switched to plain nvim and observed the following change: now the pdf updates whenever I actually select the Preview/Skim window. So I no longer have to type \lv but I do have to actually click on the pdf window to get it to update. Maybe it's some weird OS X thing.

It seems the problem is mostly fixed, then. Regarding Preview, I know nothing. I have never used OSX myself. But I know that Skim should work well. Have you read `:h vimtex_viewer_skim`? Which settings are you using when you use Skim?

Also: `\lo` (or `:VimtexCompileOutput`) should open a buffer that shows the output of the `latexmk` process. So, after you open the tex file and start compilation with `\ll`, doing `\lo` should show some output. Could you please try again? (Possibly wait some seconds after doing `\ll` before doing `\lo`.)

**Comment by lobachevzky** [comment]
> Have you read :h vimtex_viewer_skim? Which settings are you using when you use Skim?
Yes. It doesn't give any directions as far as things that need to be added to the vimrc or anything.

As for `\lo` and `:VimtexCompileOutput`, still getting a blank buffer. I even tried to introduce a syntax error to see if it would give me some output. I also double checked that the compiler was started. Very strange.

I'll run this again on a linux computer when I have the chance. Perhaps it's an OS X issue.

**Comment by lervag** [comment]
> Yes. It doesn't give any directions as far as things that need to be added to the vimrc or anything.

No, that's wrong, but you should have read the context as well. You should have `let g:vimtex_view_method = 'skim'` when you use Skim as a viewer.

> I'll run this again on a linux computer when I have the chance. Perhaps it's an OS X issue.

I'm pretty sure things should be working on OSX. Could you test with normal Vim as well? (Start with `vim --servername VIM` if you work in a terminal, else the server feature is not enabled.)

**Comment by clason** [comment]
I've never used Preview as a previewer (ha) with `latexmk`, but I know that it never reloads changed files in the background, only when it regains focus. I'm not aware of any option to change this, and I've even read somewhere that this is "by design". It might be possible to adapt the AppleScript in the `skim` callback to manually reload the file after compiler completion, but unless there is a specific reason to stick with Preview (which I'd be curious to hear), switching to Skim seems to be by far the easier option.

**Comment by lobachevzky** [comment]
Ok. So I'm going to resolve this issue.

Going back to the minimal example, it seems that the essential item that I was missing was `g:vimtex_compiler_progname = 'nvr'`. Adding that spares me from having to type `\lv` every time. 

I think @clayson's comment resolves the problem with preview, and I have been happily using skim ever since.
