### ISSUE TITLE
Changing preview without saving

### ISSUE THREAD

**Issue by throwup** [lervag/vimtex#1034]
I am unsure if this is the right place to ask questions about the functionality of vimtex, however I have seen some similar "question" posts, so I hope this is ok.

Is it possible to get instant recompilation of the preview when changing something in the file (like [vim-latex-live-preview](https://github.com/xuhdev/vim-latex-live-preview))? I have seen people talking about "live previews" in vimtex, however seem to only be able to get compilation after saving to work.
Does a feature like that exist and if so, how would I enable it?

**Comment by lervag** [comment]
Vimtex does not support this "level" of live preview. Vimtex relies on compiler backends such as `latexmk`, `arara` and similar. Here `latexmk` is the default one and the one I use myself. `latexmk` with the `-pvc` option (which is used by vimtex by default) will recompile whenever any file in the project has changed (been saved).

Although I would not recommend it, you could add an autocommand for LaTeX files in order to save the file whenever you leave insert mode, something like this:

```vim
autocmd InsertLeave *.tex update
```

Since the file is saved, `latexmk` will start to recompile (if the previous compilation was finished).

----

To explain why I don't recommend this: Writing LaTeX should be _more_ about the LaTeX code and less about how it looks in the preview. That is, I find it useful to update the preview often to check that I'm doing the right thing, but in general, I think it is more important to focus on the editing part. Thus, I think it is more than adequate to compile on save. To take this further: Complex LaTeX projects typically take quite some time to compile. In this case, it is not possible to get "instant" feedback anyway. This means that a feature that gives more "live preview" than the one already present will tend to either "fail" or not work very well on such complex projects (e.g. theses, books, etc). In such cases, and I also think generally, it is better to have explicit compilation, either manually or on each save.

**Comment by throwup** [comment]
I completely agree with you, I have been playing arround with Vimtex today and realized that compiling after saving is completely adequate for my needs. I was (and still am) completely new to LaTeX and overvalued the importance of being able to see changes in real time. Anyways, thanks for your elaborate answer!

**Comment by lervag** [comment]
No problem! :)
