### ISSUE TITLE
Forward search not working with include/input

### ISSUE THREAD

**Issue by scarlehoff** [lervag/vimtex#1040]
When I am editing a document with \include{some_other_text.tex} forward searching (\lv) doesn't work. Instead, it opens visual mode.

\lv works perfectly when I am in the main latex faile (main.tex in the example below), however, when I change to input.tex (be it in a window, or a tab) it stops working. 

I've tried adding the following option to my .vimrc file: `let g:tex_flavor = 'latex'` as I have read in a different issue (#438) that it might be a fix. Howver, all it does for me is to make vimtex believe input.tex is a main latex file and \lv complains it cannot find input.pdf.

The example below will probably explain the problem better than I do.

I'm running the latest version of vim available in Arch's repositories. Same for zathura (0.3.8) with pdf-mupdf plugin (0.3.2)

## Minimal working example:
Two files in the same folder, main.tex and input.tex
# main.tex
```
\documentclass[]{article}
            \begin{document}
            Test file
            \newpage
           with several
            \newpage
            \input input.tex
            \newpage
           pages
\end{document}
```

# input.tex
```
Just some text
```

# Minimal .vimrc
```
set nocompatible                                                                                                   
execute pathogen#infect()                                                                                          
syntax on          " Syntax highlighting on                                                                        
filetype plugin on " Use filetype plugins                                                                          
filetype indent on " Use filetype indent                                                                           
set mouse=a        " Allow use of the mouse                                                                        
let g:vimtex_view_method = 'zathura'   
  ```

**Comment by j-jith** [comment]
`\lv` starts visual mode is because your filetype is `plaintex` (check `:set filetype?`). vimtex is not loaded for plaintex files (I'm not sure why). But if you change your input.tex to something like this

````tex
\begin{section}{A section}
Just some text
````
then your filetype will be correctly identified as `tex`, and `\lv` will work.

However, you will still get an error saying that input.pdf is not found. If you check `:VimtexInfo` you will see that the `base` file is still input.tex. Ideally it should be main.tex. 

When I changed your `\input` line to `\input{input.tex}`, vimtex was able to correctly identify the base file as main.tex. I'm not sure why the curly brackets are important.

So this seems to be some sort of weird edge case.

**Comment by scarlehoff** [comment]
Funny thing is I had tried with the curly brackets but before I set  `let g:tex_flavor = 'latex'` to ensure the file was [tex] instead of [plaintext].

Thank you very much, it works now ^__^

**Comment by lervag** [comment]
@j-jith First, thanks for pitching in and solving the issue! Just a comment: vimtex still depends on the "internal" syntax plugin for LaTeX, which separates from plain TeX, LaTeX and ConTeXt. I guess one could decouple vimtex completely at some time, but not right now. The gain is not really that much, and it would require that I wrote a full syntax file. And considering I've documented quite clearly that one should use `let g:tex_flavor = 'latex'`, I find this to be pretty much a non-issue.

@scarlehoff As far as I know, it is not correct LaTeX syntax if you do not include the curly brackets. However, if you happen to have a valid reference that this should be possible, then I might consider to update the regexes. Note, I might also decide not to, as I don't see any advantage in allowing such an inconsistent syntax...

I'm closing, since it seems this is solved. :)
