### ISSUE TITLE
automatic align at alignat environment

### ISSUE THREAD

**Issue by joaocortes** [lervag/vimtex#1042]
Hi,

Is it possible to make vim automatic align several `&&` used inside the `alignat` environment? That is, starting from

```tex
\begin{alignat}{3}
	& a &&  b && c \\\\
	&1     &&  2              && 3 \\\\
\end{alignat}
```

getting 

```tex
\begin{alignat}{3}
	& a &&  b && c \\\\
	&1  &&  2 && 3 \\\\
\end{alignat}
```

after forcing the alignment with `=`. 

I've seen something similar used to create tables on vim, automatically aligning columns. Maybe its not so straightforward, because the alignment must take in consideration the positions of all `&&` on all lines at the same time.

Thanks.

**Comment by j-jith** [comment]
You can use the fantastic plugin [vim-easy-align](https://github.com/junegunn/vim-easy-align). In your case, simply select the lines you want to align in visual mode and do `:EasyAlign /&&/`. If you don't want to go into visual mode, move your cursor into the align environment, and in normal mode press `gaip` (align paragraph). Then vim-easy-align will prompt you for a delimiter to align around. Since the delimiter here is two ampersands, you need to use a regex. This can be done by pressing `^X` at the prompt and then entering `&&` at the next prompt.

**Comment by lervag** [comment]
@joaocortes No, sorry, this is not possible in vimtex. And I don't plan to add this feature. The reason is simply that there are other plugins that does this in a much more general manner (i.e. it works for more/all filetypes). With that said, I heartily agree that `vim-easy-align` is very good, but I would also mention [tabular](https://github.com/godlygeek/tabular) and [vim-lion](https://github.com/tommcdo/vim-lion) as popular alternatives.

**Comment by lervag** [comment]
@j-jith I think you should also mention the `:LiveEasyAlign`, which is similar to `:EasyAlign` but shows a live update while configuring the alignment.

**Comment by j-jith** [comment]
@lervag I was not aware of this feature. This seems very handy. Thanks for the heads-up.

**Comment by lervag** [comment]
No problem :)

**Comment by joaocortes** [comment]
Thank you both. I will try the vim-easy-align plugin.
I understand my issue isn't exactly related to vimtex. 
Just asked because it seems vimtex automatically aligns & in the align environment. I thought this would be a generalization of that case.

**Comment by lervag** [comment]
Yes, `vimtex` aligns the first `&`s, but this is more related to indentation than tabular alignment. I understand that you would be interested in a generalization, but I think you will find the suggested plugins provide very good alternatives for exactly this.
