### ISSUE TITLE
Can not get vimtex running in arch

### ISSUE THREAD

**Issue by thomase1993** [lervag/vimtex#1057]
In arch Linux my current installed version of vim is 8.0
one activated features is +clientserver
vimrc:
```
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
```
minimal tex (i tried it with an empty file):
```
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

I run vim as follow: `vim --servername VIM test.tex`
I tried the commands as follow:
```
:let maplocalleader = "\\"
:let mapleader = "-"
\lv --> example command of vimtex
```
The command `:h vimtex` is working.
The command `:VimtexInfo` is not working. The error message is "E492: Not an editor command: VimtexInfo 0,0-1 All"

**Comment by lervag** [comment]
I've updated the [issue template](https://github.com/lervag/vimtex/blob/master/ISSUE_TEMPLATE.md), as I can understand it might be difficult to understand. I've tried to simplify it. **Please read it**.

So, first, can you do the following:

1. Open a LaTeX file with `vim --servername VIM test.tex`.
2. Do `:VimtexInfo` and copy the output here.

**Comment by thomase1993** [comment]
:VimtexInfo is not working. I tried to copy the command and wrote it myself :-)
I also did again :PlugInstall and it says vimtex is already installed.
It says after your suggested command: 
E492: Not an editor command: VimtexInfo                       0,0-1         All

**Comment by lervag** [comment]
Ok. So, see below (I've copied the issue template here) and please note steps 1 and 2. Also, it would be easier if you could make sure to format your posts according to the guide. In addition to adhering to the template, it would also be good if you do `set filetype` after you've opened a LaTeX file. It should be `tex`, but I'm guessing it might be `plaintex`.

# Explain the issue

A good issue ticket typically consists of the following parts. For feature requests, step 3 may often suffice (although steps 1 and 2 are always very much appreciated!). Also, please read [this guide](https://guides.github.com/features/mastering-markdown/) on how to format Github issues.

1. A minimal `vimrc` file, for instance:

    ```vim
    set nocompatible
    let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
    let &rtp .= ',~/.vim/bundle/vimtex/after'

    " Load other plugins, if necessary
    " let &rtp = '~/path/to/other/plugin,' . &rtp

    filetype plugin indent on
    syntax enable

    " Vimtex options go here
    ```

2. A minimal `.tex` file, such as:

    ```tex
    \documentclass{minimal}
    \begin{document}

    Hello World!

    \end{document}
    ```

3. A concise description of the issue and **the steps to reproduce** it. This should include something like `vim --servername VIM -u vimrc mwe.tex` to show that one understands the use of minimal vimrc files.

   Often it is useful to describe the *expected behaviour* and the *observed behaviour*.

   Note: On Windows most people use the GUI `gvim`, and it may seem difficult with a custom `_vimrc` file. In this case, I suggest that one makes a copy of ones `_vimrc` file, then deletes the content and uses the above template instead.

4. A `.latexmkrc` file [*if relevant*].

**Comment by thomase1993** [comment]
the command `set filetype=tex` solved the issue. How can I set the default to tex and not to plaintex. I do not understand the difference, because I am quite new to vim.

**Comment by lervag** [comment]
It is explained in the introduction of the vimtex documentation. You need `let g:tex_flavor = 'latex'` in your vimrc file.

**Comment by thomase1993** [comment]
Thank you for your help and your patience. :-)

**Comment by lervag** [comment]
No problem! Happy to help (please forgive me if my comments where somewhat brisk/rude). Feel free to open more issues if you have other problems. :)
