### ISSUE TITLE
Forward search doesn't work with Okular or mupdf

### ISSUE THREAD

**Issue by samaursa** [lervag/vimtex#1071]
Given a minimal vimrc file and LaTeX file as below:

```vim
set shell=bash
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'lervag/vimtex'

call vundle#end()
filetype plugin indent on

let g:vimtex_latexmk_options="-pdf -pdflatex='pdflatex -file-line-error -shell-escape -synctex=1'"
let g:vimtex_fold_enabled = 0
let g:vimtex_quickfix_mode = 2
let g:vimtex_quickfix_open_on_warning = 1
let g:vimtex_toc_resize = 0
let g:vimtex_toc_hide_help = 1
let g:vimtex_indent_enabled = 1
let g:vimtex_latexmk_enabled = 1
let g:vimtex_latexmk_callback = 1
let g:vimtex_complete_recursive_bib = 0
let g:vimtex_view_method = 'mupdf'
```

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

----

I am fairly new to `vimtex` and I have a fairly basic setup. I cannot seem to figure out why `vimtex` insists on opening multiple `mupdf` instances when I press `\ll` and why forward search does not work with either `mupdf` or `okular`. In both cases, multiple viewers are opened and I do not get any forward search capabilities.

I do start vim with `vim --servername VIM`

I have read the other issues that seem to be related to mine. Not sure how to go about fixing this.

**Comment by lervag** [comment]
First, I took the liberty of reformatting your post and remove some unecessary details.

Second, please note that your vimrc is _not_ minimal:
- In the issue template I'm suggesting a minimal variant that uses `let &rtp ...` instead of a plugin manager. This should work for you as well, and would remove the Vundle dependency.
- There are no options called `g:vimtex_latexmk_...`. And for many of the other options you are setting them to default values; this again means your vimrc is _not_ minimal.

So, for your issue with mupdf:

- Do you have `xdotool` installed?
- Which versions are you using of Vim and xdotool?

**Comment by samaursa** [comment]
I apologize for the delayed reply.

I did not have `xdotool` installed. I installed it and the multpile Okular windows problem disappeared.

The reverse search is still not working. After trying to do a reverse search, the VIM cursor is placed at an unrelated position in the VIM document. The Okular document is unaffected.

**Comment by lervag** [comment]
With reverse search, you mean that you are doing the `\lV` mapping, right?

Please note the difference between forward and reverse search. Forward search is to go to corresponding line in PDF wrt the LaTeX file. Reverse search is the opposite. With MuPDF, I've implemented a "silly" strategy where I get the page number from mupdf and then jump to the line in Vim that corresponds to the top of that page. I personally never used this, because it never felt very convenient. If you want proper reverse search, please look into the Zathura viewer instead.

So, just to be clear: When you write "unrelated position", I am not quite certain that it is really unrelated. Perhaps unexpected, but I think it is probably a position that should correspond to the top of the page viewer in MuPDF (or close to it).

**Comment by samaursa** [comment]
Thank you Karl! That makes more sense. With Zathura, things are pretty much perfect. Everything works as (or better!) than expected.

**Comment by lervag** [comment]
Great, I'm happy to hear it! :)
