### ISSUE TITLE
synctex with the comment package 

### ISSUE THREAD

**Issue by heiderich** [lervag/vimtex#1087]
When using the [comment](https://ctan.org/pkg/comment) package, clicking on text within a comment in the PDF makes vim open the comment.cut file instead of the comment in the original .tex file.

1. A minimal `vimrc` file:

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable
```

2. A minimal example:

```tex
\documentclass{article}
\usepackage{comment}
\usepackage{xcolor}
\specialcomment{mycomment}{\begingroup\sffamily\color{blue}}{\endgroup}

\begin{document}

before

\begin{mycomment}
   first comment
\end{mycomment}

between

\begin{mycomment}
   second comment
\end{mycomment}

after

\end{document}
```

3. Open the minimal example above, compile it, view it using zathura and use the inverse search on "first comment" (Ctrl + click). I expect that vim moves the cursor to the corresponding place in the minimal example .tex file. Instead vim opens the file `comment.cut`, which contains the text `second comment`.

**Comment by lervag** [comment]
I don't think this is a vimtex issue. It is rather an issue with the comment package. That is, you can easily replicate this problem with any editor, since what is happening here is that the synctex program connects the location in the PDF with the `comment.cut` file, and not with a specific line in the `main.tex` (or whatever name) file.

So, sorry: Please send an email to the developer of the comment package.
