### ISSUE TITLE
How do we use g:vimtex_quickfix_blgparser ?

### ISSUE THREAD

**Issue by phcerdan** [lervag/vimtex#1090]
I have noticed that bibtex error are not very detailed in the quickfix errors/warnings in vimtex, however you have this option to parse the `.blg` file. Is this always on? The documentation is unclear about it.

```
*g:vimtex_quickfix_blgparser*
  This option controls the parsing of `blg` log files (created by bibtex or
  biber) for warnings and errors.  The option is a dictionary with the
  following keys:

    disable~
      Disable the parsing of `blg` entries.

  Default value: {}
``` 
If it is on by default, I am note getting in the quickfix list the blg errors. (I got one entry there complaining about missing the field 'pages` in one reference.

**Comment by lervag** [comment]
Yes, I can see that this is somewhat confusing. The option was defined like this because I was thinking there might be more related options that I could "include" in the same dictionary to control bibtex errors. However, so far, there are no such new options.

So: Yes, this feature is enabled by default. It should list errors/warnings such as the one you describe about missing the field "pages" in one reference.

**Comment by phcerdan** [comment]
Ok, better this way then. However it wasn't showing that error in the quickfix, but i was in blg.
I fixed the bibliography already, but I will report here if I am able to reproduce the lack of info in the quickfix again.
Thanks.

**Comment by lervag** [comment]
Strange. If you get the same error again, please send me the relevant part of the `.blg` file.
