### ISSUE TITLE
Changing default language

### ISSUE THREAD

**Issue by hbrunie0** [lervag/vimtex#1091]
In French there is a whitespace before punctuation mark "?". But the vimtex default language is english, thus I have the automatic window open with 'Whitespace before punctuation mark in "?".

How can I precise to vimtex that my document is in French? Moreover, How is it explain how the whole stuff of options works? `let g:...` for me is like Chinese, and I did not find anything in doc/ tex file.

Thank you for your work,

Best regards,
Hugo

**Comment by lervag** [comment]
Some initial comments:

> the vimtex default language is

vimtex does not have any default language. LaTeX does, and your issue here is related to LaTeX in general, not vimtex. It is quite easy to find a solution to this, see [here](http://lmgtfy.com/?s=d&q=change+the+language+in+LaTeX)... [The three top links should get you going...]

> the automatic window

There is nothing in Vim or vimtex that is named "automatic window". I understand that you are probably a new user of Vim and vimtex, and I understand that there is a lot of terminology to learn. I think what you are talking about must be the _quickfix window_ which shows the list of errors/warnings after compilation. Is that right?

> How is it explain how the whole stuff of options works?

Options for vimtex is similar to options for other Vim plugins. I strongly suggest that you do the vimtutor, i.e. `:Tutor` in Vim. I can also recommend [A vim Tutorial and Primer](https://danielmiessler.com/study/vim/) (by Daniel Miessler), which is a good introduction that among other things describe how to setup your vimrc file and plugins with some options.

**Comment by hbrunie0** [comment]
Thank you for all the links. Nevertheless you did not answer my question (which was not well formulated) : 

If I have well understood there is a feature in vimtex which enables the quickfix window which pops up whenever I save the file with a syntax error (white space before '?') 

Nevertheless I can not put my whole document in french with \usepackage[french]{babel} because I have some english abstract. 
How can I precise to vimtex to consider my text as french while proceeding to its correction ? 

Thank you,

**Comment by lervag** [comment]
I beg to differ: I _did_ answer your question. In particular, I wrote:

> vimtex does not have any default language. LaTeX does, and your issue here is related to LaTeX in general, not vimtex. It is quite easy to find a solution to this, see here... [The three top links should get you going...]

Repeated: The language issue is _not_ with vimtex, it is with your LaTeX code.

The vimtex feature that opens the quickfix window is more general, in that it opens a window of errors/warnings when there are any. But vimtex is not responsible for those errors or warnings, LaTeX is. The syntax error you mention can not be fixed through vimtex configuration. It needs to be fixed in your LaTeX code.

I think the following link may be more relevant:
- https://tex.stackexchange.com/questions/20987/changing-babel-package-inside-a-single-chapter

**Comment by hbrunie0** [comment]
Ok, that is completely clear ! 
Thank you, 
sorry for your time. 
- Hugo

**Comment by lervag** [comment]
No problem, I'm happy to help.
