### ISSUE TITLE
MuPDF not executable in vimtex on MacOS

### ISSUE THREAD

**Issue by jeremiahwilson** [lervag/vimtex#1093]
# Explain the issue

When opening a .tex file in vim, I get the error:
```
vimtex: MuPDF is not executable!
    - vimtex viewer will not work!
```
And when compiling the .tex file, it opens in my system default pdf viewer (Adobe Reader) rather than MuPDF. 

The only vimtex option I have changed in my .vimrc is:

`let g:vimtex_view_method = 'mupdf' " use mupdf for LaTeX`

I have also tried using 'mupdf-gl' instead of 'mupdf'.

I have no other LaTeX plugins installed. 

Running 

`mupdf example.pdf`
or 
`mupdf-gl example.pdf`

in terminal opens the .pdf in MuPDF as expected. 

I'm running macOS 10.12.6 if that makes a difference. Any suggestions appreciated. Thanks!

**Comment by lervag** [comment]
If you are on MacOS I would suggest you try Skim instead. See `:help vimtex_viewer_skim`.

Regarding this issue: The problem is exactly as stated: the MuPDF viewer is not executable from vimtex. The problem is probably that you vim is not set up with the same `$PATH` as your terminal. This can easily be checked. After opening Vim as you normally do, what happens if you try `:!mupdf`?

**Comment by jeremiahwilson** [comment]
Vim is set up with the same $PATH as my terminal, but I tried Skim and I suppose I do like it better than MuPDF anyways. Thanks!

**Comment by bemeurer** [comment]
@lervag Upon hitting this same issue and investigating, I think this is due to the fact that the cli for MuPDF on macos is `mupdf-gl`, and not `mupdf`.

**Comment by lervag** [comment]
I see. I think the most simple solution is to [create a symlink](https://apple.stackexchange.com/questions/175773/creating-a-symbolic-link-in-bin-is-not-working) and linking `mupdf` to `mupdf-gl`.

**Comment by bemeurer** [comment]
That sort of works, but it behaves really weirdly. I think Skim is the only way for it to work well in macOS.

**Comment by lervag** [comment]
What do you mean "behaves really weirdly"?

**Comment by bemeurer** [comment]
@lervag It's a bit too erratic to explain accurately, but basically it will open two MuPDF windows at once, then close one after I make an edit, keeping the other one open. Then it won't update the pdf as I make changes (and save) to the LaTeX source, even if I change focus to the MuPDF window. I will try to get a video of it later.

**Comment by lervag** [comment]
This sounds a little bit like either 1) you have some `.latemkrc` file that sets something to open the pdf file with MuPDF, and vimtex still opens, which leads to two windows, or 2) that you have a sporadic latexmk process running.

I am not 100% sure that MuPDF will work fully as expected on MacOS, since the vimtex code relies on `xdotool` to "control" the MuPDF window.

**Comment by lervag** [comment]
A side note/question: As far as I understand, Skim really works quite well on MacOS. Why would you want to use MuPDF instead? (I guess that keybindings might be one reason?)

**Comment by Researchnix** [comment]
Hi, I just ran into the very same issue as @bemeurer described above.
After the two instances of mupdf open, the second window that was opened closes immediately when vimtex completed the first compilation. The first window (further in the background when both are open) is "stable" but only updates its content upon the "r" command in the window.
I was able to kind of fix the two window issue by adding this hook function to my init.vim as recommended in the vimtex help manual:
`let g:vimtex_compiler_callback_hooks = ['MyTestHook']`
`
function! MyTestHook(status)
echom a:status
endfunction
`
It does open only one window, but the window that opens is the one that closes at the first compilation. I did install xdotools with brew, but didn't see a difference.
As you said, @lervag, when I start continuous mode, the files `main.fdb_latexmk`, `main.fls` and `main.synctex.gz` are created. What does this mean?

Any help is greatly appreciated!

**Comment by Researchnix** [comment]
The reason I find MuPDF is superior to Skim is that it doesn't flicker when it updates the pdf.

**Comment by lervag** [comment]
@Researchnix Please do this:

0. Copy your related vimtex settings here.
1. Open some LaTeX file with Vim.
2. Do `\li` and copy the output here.
3. Do `\ll`, this should start compilation and start MuPDF when the file is compiled.
4. Do `\li` again and copy the output here (preferably only the `compiler` and `viewer` sections).
5. Close Vim and MuPDF, then open the same file again and do `\lv`.
6. Di `\li` yet again, copy the output here (only the `viewer` section).

This might provide me some clues on what the problem is.

**Comment by lervag** [comment]
Thanks. This does provide some useful information: `xwin id: Warning: XTEST extension unavailable on '(null)'. Some functionality may be disabled; See 'man xdotool' for more info.` That is, it seems `xdotool` is not working properly.

In order for the mupdf viewer to work seamlessly with vimtex, you need xdotool. This is because we use xdotool to communicate, e.g. with passing the `r` key to mupdf after successful compilation.

Note, you can always use the general viewer like this:

```vim
" 'general' is the default value, so you don't need to set it,
" but don't set the option to anything else either.
" let g:vimtex_view_method = 'general'

let g:vimtex_view_general_viewer = 'mupdf'
```

For things to work with vimtex, you need to be able to do things like this with
`xdotool` in a terminal:

```sh
# This returns the <xwinid>
xdotool search --class MuPDF

# This uses the <xwinid> for various things
xdotool getwindowname <xwinid>
xdotool type --window <xwinid> "12g"
xdotool type --window <xwinid> "r"
```

**Comment by Researchnix** [comment]
When I tried to run `xdotool search --class MuPDF` I got the same error as in the warning above:
```Warning: XTEST extension unavailable on '(null)'. Some functionality may be disabled; See 'man xdotool' for more info.```
A google search came up with these commands fixing the warning:
```
defaults write org.x.X11 enable_test_extensions -boolean true
defaults write org.macosforge.xquartz.X11 enable_test_extensions -bool yes
```
But now when I run `xdotool search --class MuPDF` there is no output whatsoever.
When I open a .tex file and do `\ll` there appears a `1` in the nvim output line where `"main.tex" 7L, 13C written` appears when a file is saved, and the document only refreshes when I bring it in focus and press `r`.
I was not able to find a solution to the xdotool problem I have on my Mac on the internet. Any ideas? If not, I'll post this question in another more appropriate forum elsewhere and get back here when I find a solution.

**Comment by lervag** [comment]
No, sorry, I'm on Linux. I don't know how to make xdotool work on OSX. If you get it to work, then I think the MuPDF stuff should work with vimtex.

**Comment by lervag** [comment]
If you _do_ get it to work, then let me know how, and I can add some text to the docs to help other users.

**Comment by dpo** [comment]
I get a similar error message that the viewer isn't executable on macOS. I set
```
let g:vimtex_view_general_viewer = 'open -a TeXShop ' . expand("%:t:r") . ".    pdf"
```
to open my PDF using TeXShop. Is there a way to disable those error messages? VimTeX is happy to open my PDF in spite of them. Thank you.
