### ISSUE TITLE
vimtex: Viewer cannot find Zathura window ID! (i3 wm)

### ISSUE THREAD

**Issue by sebastianst** [lervag/vimtex#1117]
1. Relevant `vimrc` config entries:
    ```
   let g:vimtex_view_method = 'zathura'
    ```

2. Suddenly, running `<leader>ll` or `<leader>lv` doesn't open zathura anymore. Instead, gvim shows the error message `vimtex: Viewer cannot find Zathura window ID!`
I'm using most recent `gvim 8.0` and Arch Linux. It used to work for 2 years and I didn't change my wm (i3) or any relevant vim configuration.
With any zathura open, `xdotool search --class Zathura` shows two window ids. Is it normal that always two ids are shown even though there's only one zathura open? (I double checked and did a `killall zathura` before opening zathura).

3. `.latexmkrc`
   ```
   $pdf_mode = 1;
   @default_files = ('main.tex');
   push @generated_exts, 'sta';
   push @generated_exts, 'bbl';
   ```

**Comment by sebastianst** [comment]
Apparently, zathura removed the `-x` option in version 0.3.9. Running the viewer command shown in `:VimtexInfo`, I get
```
error: Error parsing command line arguments: Unknown option -x
```
Using `--synctex-editor-command=` instead of `-x` still shows the same error. Maybe it's an upstream bug/decision/feature that they (accidentally) removed the `-x` option. It is still described in zathura's man page but missing from `zathura --help`.

**Comment by sebastianst** [comment]
The Arch maintainer of zathura decided to disable synctex support for some weird incompatibility reasons.
https://bugs.archlinux.org/task/58403
Nothing vimtex can fix.

**Comment by andymass** [comment]
Thanks for the warning.  This is disappointing but hopefully it is fixed by package maintainers soon. 
Perhaps vimtex could provide a better error message in this case.

**Comment by sebastianst** [comment]
It would indeed be good if vimtex throws a warning that the viewer couldn't be launched if the viewer command fails. Currently, it fails silently and only at the point where the window id is requested does an error occur.

**Comment by lervag** [comment]
Yes, I've noticed this problem today as well. Annoying!

The viewers use my simple process "API", which basically uses a vim command like `!zathura ... &`. Notice the final `&`, which is used to start the viewer in the background. This also prevents me to read the exit code from `v:shell_error`, and so it becomes difficult to know if the process failed to start. Of course, I could spend a lot of time to update this code to allow more modern stuff like the `job_start` functions. But I'd rather not, because I find it works suitable well most of the time.

One thing I could do is to check for the `libsynctex` dependency during zathura initialization with `ldd`. I'm trying this now, let me know what you think.

**Comment by sebastianst** [comment]
IMHO, it's an unfortunate hack of the zathura Arch package maintainer to just disable synctex. They should sort this out among package maintainers without removing functionality. There seems to be some broken/missing libsynctex header in the texlive distro, see bug report I linked above.
So I think you shouldn't bother your plugin with detecting synctex support as it should be there in a normal installation of zathura.

**Comment by lervag** [comment]
I agree!

However, I think the current detection should work well, and it should make it easier to detect similar issues.

PS! Are you on the ["humble" or "honest" part of town[(https://xkcd.com/1989/)?

**Comment by sebastianst** [comment]
I was being *humble* this time ;)

**Comment by lervag** [comment]
:) (FYI, I actually never knew that anyone ever interpreted IMHO as ...honest..., which is why I asked.)

**Comment by paulrougieux** [comment]
I'm running into this error. It's not a big issue since the forward search does work and I can use alt-tab to move focus to the pdf viewer. I'm wondering what you meant by :

> " I think the current detection should work well".

Since vimtex still cannot find the find Zathura window ID. I guess the above sentence means that the detection should work as soon as something is fixed on the Zathura side?

**Comment by lervag** [comment]
> I'm running into this error.

No, I'm sorry, but you're not. Zathura from Arch Linux repos works fine (I'm using it), and this issue was related to a minor "bug" that was fixed upstream.

Thus, you're issue is not the same. As such, it is more appropriate if you open a new issue. Notice also that this thread is two years old.

> I'm wondering what you meant by :
>
>    " I think the current detection should work well".

I mean vimtex has a simple check to determine if Zathura is compiled with support for libsynctex, and I think this check works well.

> Since vimtex still cannot find the find Zathura window ID. I guess the above sentence means that the detection should work as soon as something is fixed on the Zathura side?

I don't know, as I don't know what your issue is. Please open a new issue and give a more complete description (the issue template should give some good hints about what you should include).
