### ISSUE TITLE
Syntax highlight block detect issue

### ISSUE THREAD

**Issue by vanabel** [lervag/vimtex#1121]
### The issue
I believe this is not a issue of `vimtex` along, since the google says the same issue happens for `clang`. 

I get into the issue when I typing the blocking (I don't know how the repeat this issue, so I will try to explain it clearly):

```tex
\begin{align*}
    `a
\end{align*}
```
The above block is just a demo. The problem is that the `imap` `` `a ``, which should be expand to `\alpha` by default, not work this time (most of the time it works, but it doesn't work occasionally).  I finally get that it is caused by the **highlight** scheme, since when it does not work, the `\end{align*}` is in red color, which is not the same as `\begin{align*}`, and shows that they are not be properly paired. Moreover, I can fix it by hand:
```vim
:syn sync fromstart
```
After this, the paring are correct and `` `a `` expand to `\alpha`.

### The expected fix

So I came here to

1. Show the issue, in case anybody involved with the same issue;
2. Expect more convenient way to fix this instead of execute the vim command each time (of course we can bind a vim auto-command to `tex` file:
```vim
au BufEnter,BufWrite *.tex syn sync formstart
```
Do you think it is a good idea?

**Comment by lervag** [comment]
I think this issue is more related to the internal syntax plugin. I also sometimes have similar issues, and I fix it in a similar manner as you. I don't think I want to change anything with this, because increasing the number of sync lines will also decrease performance.

I would add the `syn sync` line either to your personal `ftplugin/tex.vim` file, or perhaps to an `au FileType tex` autocommand.
