### ISSUE TITLE
Problem with selector in equation

### ISSUE THREAD

**Issue by RoneH** [lervag/vimtex#1126]
1. A minimal `vimrc` file

    ```vim
    set nocompatible
    let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
    let &rtp .= ',~/.vim/bundle/vimtex/after'

    filetype plugin indent on
    syntax enable

2. A minimal `.tex` file, such as:

    ```tex
    \documentclass{article}
    \begin{document}
    \begin{equation}
    {(x+y)}^2 = x^2 + y^2 + 2xy
    \end{equation}
    \end{document}
    ```

3. A concise description of the issue and **the steps to reproduce** it.
When the cursor is inside the equation and I am in normal mode and I type `vie` I expect the whole line to be selected. However the first part of the equation between bracket is not selected, as shown below [![Screenshot_from_2018-05-23_21-58-34.png](https://s9.postimg.cc/lk63nhyin/Screenshot_from_2018-05-23_21-58-34.png)](https://postimg.cc/image/mz7oc7zln/)

**Comment by lervag** [comment]
The reason is that the algorithm that selects the inner part of environments have no way of knowing (in general) how many arguments the `\begin{env}{...}[...]` construct has. The current implementation assumes that all following `{...}` blocks are arguments. This makes sense e.g. for

```
\begin{frame}{frametitle}
...
\end{frame}
```

And many more environments.

Besides, your example does not really make sense, because `{(x+y)}^2` can be simplified to `(x+y)^2`, i.e., there is no need for the surrounding `{...}`s.

**Comment by RoneH** [comment]
In my minimal example it does not really make sense but there are many cases where you need such a syntax. Such as in
```tex
\begin{equation}
{\mathbb{P}(X \leq a)}^2
\end{equation}
```
Without the brackets the exponent is misplaced.

**Comment by lervag** [comment]
No, I don't think so. I just tested, see picture below. I've tested your variant, as well as two modifications, the final one without the extra brackets.

![screen](https://user-images.githubusercontent.com/998898/40485782-c41bd768-5f5f-11e8-9c69-5cc0a8e213b1.png)

**Comment by RoneH** [comment]
The exponent in the first picture is slightly higher because it takes into account the height of `\mathbb{P}`.
Maybe you can see it see more easily on the example
```tex
(a^{-1})^{-1} = a
{(a^{-1})}^{-1} = a
```
[![Screenshot_from_2018-05-24_15-00-23.png](https://s9.postimg.cc/r3fj74na7/Screenshot_from_2018-05-24_15-00-23.png)](https://postimg.cc/image/vck99aqjf/)
This is definitely not critical but the second output looks nicer.
When I need such syntax I found an easy workaround as follows
```tex
\begin{equation}%
{(a^{-1})}^{-1}
\end{equation}
```
And everything works as expected.

**Comment by lervag** [comment]
Ah, I see. And I can see that one sometimes need this. But I would prefer if you could use the workaround, because it is really impossible to tell if the `{...}` is a second option to `\begin` or something else. The implementation of a fix would therefore be very hard.

I hope you can live with this, even though I understand it is somewhat dissapointing.

**Comment by RoneH** [comment]
I did not think of the use of `begin{frame}{frametitle}` and so when I opened this issue but I think it is much more common than my particular use. And the workaround is very easy so no worries

**Comment by lervag** [comment]
Thanks!
