### ISSUE TITLE
Support asy and asydef environments

### ISSUE THREAD

**Issue by minijackson** [lervag/vimtex#1132]
The [asymptote](http://texdoc.net/texmf-dist/doc/asymptote/asymptote.pdf) package defines `asy` and `asydef` environments with inside them Asymptote code (section 7 in the documentation).

It would be nice to disable syntax highlighting in these environments so it does not mess the highlighting of the rest of the document, like with `minted` environments.

Thank you! (for the issue, and the awesome plugin)

**Comment by lervag** [comment]
This was discussed in #724, see [here](https://github.com/lervag/vimtex/issues/724#issuecomment-287532756). Support for asymptote was added as a result, but it depends on a custom syntax file that does not ship with Vim by default. It is easy to install, and if you do as suggested in #724, you will get improved highlighting inside asymptote environments.

However, I pushed an update now that should fix things so that asymptote environments are highlighted similar to lstlistings (i.e. no highlighting) if the custom syntax plugin for asymptote is not available.

Also, see #1113 where we discussed "automatic compilation of asymptote files".
