### ISSUE TITLE
Backward searching in skim [MAC]

### ISSUE THREAD

**Issue by vanabel** [lervag/vimtex#1140]
It seems that the default setting in the new version of skim [1.4.35] not work properly, I mean if you choose the default setting of MacVim, the default value is given by
```
--remote-silent +"%line" "%file"
```
in such case, `CMD+Shift+click` will always open a new macvim window, which cause an warning since the `swp` file are created...

To fix it, I tried to change it by use a custom setting:
```
vim --remote-silent +"%line" "%file"
```
which works, although I don't know why...

I hope @lervag could update this setting in the manual.

**Comment by lervag** [comment]
I do not understand. `--remote-silent +"%line" "%file"` seems to not be a valid setting, as it lacks the command.

**Comment by JackXu1993** [comment]
`mvim vim --remote-silent +"%line" "%file"`
indeed solves the problem that backward search would open a new macvim window and cause a warning about swp.

**Comment by lervag** [comment]
If anyone wants to open a small PR to add docs for how to set backward search with Skim, that would be appreciated.

**Comment by JackXu1993** [comment]
I know several points about setting backward and forward search with Skim:
1. Make sure there is no conflict plugin in vim, like Latex-Suite, which invalidates the forward search shortcut in vimtex. Now, my forward search works well with the one-line configuration
`$pdflatex = 'pdflatex -synctex=1 -interaction=nonstopmode --shell-escape %O     %S';`
in .latexmkrc and one line
`let g:vimtex_view_method = 'skim'`
in .vimrc.
2. Make sure that "mvim" command works in bash, because many people use zsh on mac. If `mvim: command not found` in bash, they have to link mvim in bash or make a alias in .bash_profile file (.bash_profile is a little bit different from .bashrc in linux).
3. Be careful when there are different versions of vim, I mean, the default vim with macos, macvim installed by homebrew and macvim downloaded from the [official websit](http://macvim-dev.github.io/macvim/). Use `which mvim` to check which mvim you are using. I recommend that you keep the macvim downloaded from the official website which seems more compatible than the homebrew version. If you are using two versions of macvim simultaneously, backward search may open a macvim that is different from the current one, which will cause a swp warning.
I recommend use this setting in Skim instead of the default one.
![image](https://user-images.githubusercontent.com/16731479/44956118-d3fc9380-ae8c-11e8-92a4-e7984e9f065b.png)
This command `/Applications/MacVim.app/Contents/bin/mvim` force to use the macvim binary file in the macvim application downloaded from the official website (make sure that command `/Applications/MacVim.app/Contents/bin/mvim` opens a gui macvim in your bash), so this command also solve the second point. Use `shift command double click` in Skim, it will jump to the macvim that is already opened.

**Comment by invisiblecloak-slw** [comment]
Thanks! Here is one question:
My Vim is the system edition, not macvim. And I try to set the backward search in Skim.

First, I trired to set the parameters in Skim like:
Command: result by "which vim" in command line
Args:--remote-silent +"line" "file"
This solution didn't work.

Second, I refer to the vim document:
https://sourceforge.net/p/skim-app/wiki/TeX_and_PDF_Synchronization/#choosing-an-editor-command-for-backward-search
follow the link served by document, and make an executable bash file, set the parameters as recommended.
But the solution still didn't work.

It seems that I have tried all solutions of vim document, quite sadly.
Could you offer some suggestions about how to make skim backward run?
Thanks in advance!

**Comment by JackXu1993** [comment]
What is the command result by “which vim”? What does this command produce, a view window in shell or a GUI vim? I guess you may need a vim with GUI.
On Oct 17, 2019, 7:39 AM -0400, invisiblecloak-slw <notifications@github.com>, wrote:

Thanks! Here is one question:
My Vim is the system edition, not macvim. And I try to set the backward search in Skim.

First, I trired to set the parameters in Skim like:
Command: result by "which vim" in command line
Args:--remote-silent +"line" "file"
This solution didn't work.

Second, I refer to the vim document:
https://sourceforge.net/p/skim-app/wiki/TeX_and_PDF_Synchronization/#choosing-an-editor-command-for-backward-search
follow the link served by document, and make an executable bash file, set the parameters as recommended.
But the solution still didn't work.

It seems that I have tried all solutions of vim document, quite sadly.
Could you offer some suggestions about how to make skim backward run?
Thanks in advance!

**Comment by invisiblecloak-slw** [comment]
Thanks for sending e-mail, I have read your solution for mvim.
My vim is not mvim, it's just the vim provided by mac OS.
I open the zsh shell and input
which vim
to find the content to fill in Skim-sync-command

so, there exits any solution for realizing backward search in Skim with
system vim?

Thanks you

JackXu1993 <notifications@github.com> 于2019年10月17日周四 下午8:51写道：

> What is the command result by “which vim”? What does this command produce,
> a view window in shell or a GUI vim? I guess you may need a vim with GUI.
> On Oct 17, 2019, 7:39 AM -0400, invisiblecloak-slw <

**Comment by JackXu1993** [comment]
I am not sure about the workaround for system vim. Maybe you can try macvim.

On Oct 17, 2019, at 9:01 AM, invisiblecloak-slw <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for sending e-mail, I have read your solution for mvim.
My vim is not mvim, it's just the vim provided by mac OS.
I open the zsh shell and input
which vim
to find the content to fill in Skim-sync-command

so, there exits any solution for realizing backward search in Skim with
system vim?

Thanks you

JackXu1993 <notifications@github.com<mailto:notifications@github.com>> 于2019年10月17日周四 下午8:51写道：

> What is the command result by “which vim”? What does this command produce,
> a view window in shell or a GUI vim? I guess you may need a vim with GUI.
> On Oct 17, 2019, 7:39 AM -0400, invisiblecloak-slw <

**Comment by lervag** [comment]
Good. If you have problems with MacVim, could you please open a new issue? I think it is better than to add more noise to old issues.
