### ISSUE TITLE
"-pdf" breaks a latexmk compilation

### ISSUE THREAD

**Issue by teruo41** [lervag/vimtex#1142]
Hi,

The recent commit 144e60649a0214b09ee78d3aeff4eb569daea194 breaks my `vimtex` + `latexmk` environment.

I'm using `vimtex` + `latexmk` + `(p)latex` + `dvipdfm(x)`. Though I set `-pdfdvi` in `g:vimtex_compiler_latexmk['option']`, vimtex adds `-pdf` in the last of `latexmk` command.

In my understandings, there is no way to suppress `-pdf` or other options, and `vimtex` lacks some flexibilities by the commit.

Are there any ideas using `latexmk` with `-pdfps` or `-pdfdvi` from `vimtex`?

Best,

**Comment by lervag** [comment]
Sorry! The idea behind the commit was to make a more clear division between the latex engine and other options. This might not really be as smart as I thought it was, and one obvious solution is to revert. However, I want to be sure before I do. So, the main parts here are that we should respect TeX program directives in the early part of the main TeX file, e.g. `%! TeX program = lualatex`. If the directive is not provided, then the current implementation uses `-pdf` by deafault. One can control this with `g:vimtex_compiler_engine`. However, this variable uses a dict to translate the directive to the appropriate option. Perhaps it is better to instead let this option define the desired option, instead of passing it throught the dict filter.

I assume my above text is somewhat technical, let me know if I should explain more for a better discussion.

**Comment by teruo41** [comment]
Thank you for your reply :)
I understand the intention of the commit and agree with the direction.

Solutions I think worth discussing are:

1.  Adding a parameter that leave configuration to the choice of `latexmk`
    - A parameter like: `%! TeX program = latexmk`  
      Someone may expect the default behaivior as this (but changing default involves pain)
2. Implementing possible typeset choices
    - I'm not sure how many choices should be listed when considering 2 or 3-pass pdf generations  
      (tex->dvi->pdf or tex->dvi->ps->pdf)
    - Though we may should respect other tools like TeXShop and TeXworks, I am unable to find specifications currently...

**Comment by lervag** [comment]
Ok, I've done a big update on this now. I think this should give the desired flexibility. By default, things should work mostly as before. However, I've added options `g:vimtex_compiler_latexmk_engines` and `...latexrun...`. This is a map between the TeX program directive and a desired "engine". The default for `latexmk` is the `-pdf` option. However, this may now be changed with `g:vimtex_compiler_latexmk_engines = { '_' : '-pdfdvi' }`. One may also add support for custom directives as desired.

**Comment by teruo41** [comment]
Thank you! The problem is now solved :)

**Comment by lervag** [comment]
Great :)
