### ISSUE TITLE
Suggestion for doc: set iskeyword in ftplugins

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#116]
Hi, this is not really an issue. I am putting this here in the hope that can help someone like myself and save him or her for wasting an hour ;-). 

I had in my .vim/ftplugins/tex.vim 

```
" TIP: if you write your \label's as \label{fig:something}, then if you
" type in \ref{fig: and press <C-n> you will automatically cycle through
" all the figure labels. Very useful!
set iskeyword+=:
```

but that suddenly stopped working. In my LaTeX buffers, it was reset to the standard value. After quite a bit of head-banging (without internet...) I discovered https://sourceforge.net/p/vim-latex/mailman/message/32406415/ and the magic of `:verbose set isk?`... so now to make it work I have to use 

```
let g:tex_isk='48-57,a-z,A-Z,192-255,:'
```
(not elegant, but working). Is this the correct way to fix the thing?

**Comment by lervag** [comment]
Hi! For the convenience your are talking about here: I've already implemented an omnifunction that will complete labels. This renders the mentioned functionality redundant. That is, in the example below,
```tex
\begin{equation}
\label{eq:some_equation}
f(x) = 1
\end{equation}
Reference to Equation \ref{eq:<c-x><c-o>
```
the `<c-x><c-o>` should now complete the equation label. This will work for all kinds of labels (figures, tables, ...), as well as citations with the `\cite` commands.

If you have supertab installed you may simplify the above so that `<tab>` will complete with omnifunction. Perhaps even better, if you have neocomplete or YouCompleteMe installed, the completion will be fully automatic (no keypresses needed).

I agree that the tip about `g:tex_isk` may be interesting and good, but at the moment it does not seem like it is important since it is already covered by the omnicomplete.

**Comment by lervag** [comment]
I'm closing this. Feel free to reopen if you feel that my reply was not sufficient.

Btw: Since `g:tex_isk` is part of the `tex` plugin that ships with vim. I've added links and comments about this in the introduction in my own docs, although not specifically about `g:tex_isk`.
