### ISSUE TITLE
Enhance gf to open figure in external program.

### ISSUE THREAD

**Issue by szsdk** [lervag/vimtex#1168]
Recently, I am using beamer to write slides. Then I find **opening and editing figures back and forth** is quite annoying. I hope I can use gf directly to open a figure with the external program immediately.

And please notice one situation is that the included figure may not be the source file(e.g. a pdf file generated from SVG)

**Comment by lervag** [comment]
I'm not sure how sensible it is to add this feature, because people will want very different behaviour. I think an implementation of this would need careful consideration and e.g. allow custom file open functions or similar.

But: In a sense I think it could be equially simple for a user to add this in ones vimrc file or a custom `ftplugin/tex.vim` file.

Something like this should work as a template:

```vim
nnoremap <silent> gf :call CustomGF()<cr>

function! CustomGF() abort
  let l:cmd = vimtex#cmd#get_current()

  " Try to open file with custom program
  if !empty(l:cmd) && l:cmd.name ==# '\includegraphics'
    let l:filename = l:cmd.args[0].text
    if l:filename =~# '\.pdf$'
      let l:svg = fnamemodify(l:filename, ':r') . '.svg'
      call system('my_program ' . l:svg . '&')
      return
    endif
  endif

  " Fall back to "regular" gf
  normal! gf
endfunction
```

I understand that this requires some knowledge of vimscript, but as I mentioned initially, I think it is difficult to get around since users would likely want different behavoiur.

**Comment by Rmano** [comment]
Another option would be to define a command that calls `xdg-open` on the file. In a modern desktop environment, it should call the "preferred application" for the file type.

**Comment by lervag** [comment]
That would be a semi "sensible" default, but it would not quite do. As the OP says, if he `gf`s on a pdf, he wants to open the corresponding "svg" file. I.e., I think this feature will most likely require quite a lot of user customization based on user preferences, and as such, I think it may be better to just add something like I've suggested and adapt to personal preferences. I think my template should mostly work as expected.
