### ISSUE TITLE
Synctex forward search: how does it work?

### ISSUE THREAD

**Issue by nasenatmer** [lervag/vimtex#117]
Hey guys (@Konfekt & @lervag),

the past few weeks I was just a by-stander reading in awe the marvellous things you accomplished with regards to synctex forwards and backwards search with mupdf.

Today I wanted to try myself whether this is of any use for me, but I don't seem to understand this quite well.

[I have activated *synctex* in my `~/.latexmkrc` and set `g:latex_view_method` to `mupdf`, too. Now if I compile a document and open it via `\lv` this works almost fine (the vim window is blanked, I have to redraw with `C-l` in order to see my tex again and although the mupdf window is in the foreground, vim is still in focus) and I can actually use inverse search by hitting `\lr`.]

**But what I haven't yet understood is: how can I jump from cursor posititon in vim to the equivalent position in mupdf?** I wasn't able to find any function in the docs that I could map a key to or anything like that? Is that supposed to happen automatically?

[And additionally, is there anything special to implement to make synctex work with [**zathura**](https://pwmt.org/projects/zathura/)? It supports synctex and this functionality is enabled by default so I wonder whether it takes more to enable forward search with zathura than just mention it in the docs?]

**Comment by Konfekt** [comment]
Hmm... Perhaps there is no default key map for it, but regarding your question in bold letters, I'm using `:VimLatexView<CR>` to jump from Vim to MuPDF. If `\lr` works, so should `:VimLatexView<cr>`.

Regarding inverse search for zathura, it should be a matter of adding
```
let g:latex_view_general_viewer = 'zathura'
let g:latex_view_general_options=shellescape('--synctex-forward' . '".exepath(v:progpath).' --servername '.v:servername.' +{%lline} {%ffile}"')
``` 
to `.vimrc`. Then for forward search, add
```
nnoremap <expr><buffer><silent> gb 	':!zathura --synctex-forward '.line(".").':'.col('.').':% ' . shellescape(g:latex#data[b:latex.id].out()) . ' >/dev/null<CR>'
```
to `.vimrc` to call it hitting `gb`. See http://wiki.math.cmu.edu/iki/wiki/tips/20140310-zathura-fsearch.html

This is just a rough scratch. @lervag can explain you how to do it better using `:VimLatexView<cr>`.

**Comment by nasenatmer** [comment]
Wow, thanks for this great answer!

You were right about the two lines missing from my `~/.latexmkrc`, but adding them doesn't seem to change anything. Whenever I hit `\lv` or enter `:VimLatexView` followed by `Enter`, another mupdf instance opens but they all show page 1 of the pdf while I'm at a different point in the tex file.

Same if I set `general_viewer = zathura`. New instance opens but doesn't show the page I'm currently working on or change when I save the file and a new compilation is started.

I added the `gb` mapping and this indeed works flawlessly. The corresponding line is highlighted in zathura and I guess this is how it's supposed to work. Nice thing!

However, when adding this line
```vim
let g:latex_view_general_options=shellescape('--synctex-forward' . '".exepath(v:progpath).' --servername '.v:servername.' +{%lline} {%ffile}"')
```
I get the following message: **E121: undefined variable: servername**, although `:echo v:servername` yields `VIM`

When replacing `--servername` by `'--servername'`, I still get an error: **E116 Invalid arguments for function shellescape(…)** and **E15: invalid expression: shellescape(…)**.

Thanks so much for your help! If we can sort out the invalid expressions, it might actually be possible to include zathura in the list of supported viewers?!

**Comment by lervag** [comment]
@nasenatmer `\lv` should open the current page in mupdf if mupdf is chosen as the view method. Do you have `xdotool` installed? I think you do, based on the other information in your post. However, it seems strange that it does not work.

When you open a `tex` file and then hit `\ll`, then `latexmk` should start in continuous mode. After a successful compilation, `latexmk` should open mupdf. A callback is then issued that should:
1. Return focus to vim
2. Set page in mupdf to the current page

Note that to make latexmk open mupdf you need
```
$pdf_previewer = 'start mupdf';
```
in your `.latexmkrc` file.

Regardless of latexmk: If you open a tex file that has already been compiled and issue `\lv`, then the pdf should be opened with mupdf, and it should open at the page corresponding to the current line in vim. Further, focus should stay in vim (this is by design, and is currently not customizible). Successive `\lv`s should now simply change the page to the current page.

Regarding zathura: It seems I should implement full support for zathura. It is rather easy to do, I think, based on the information given by @Konfekt. I'll open a new issue for this and solve it when I get the time. When it is solved, the idea is that you can choose zathura through `g:latex_view_method`, after which forward search should work automatically. I will also try to add support for inverse search.

**Comment by lervag** [comment]
Oh, and it should be (I think):
```vimL
let g:latex_view_general_options = shellescape('--synctex-forward "' . exepath(v:progpath) . ' --servername ' . v:servername . ' +{%lline} {%ffile}"')
```

**Comment by Konfekt** [comment]
@nasenatmer there were some typos, try
```
let g:latex_view_general_options = shellescape('--synctex-forward "' . v:progname . ' --servername ' . v:servername . ' +{%line} {%file}"')
```
Does that work?

**Comment by Konfekt** [comment]
Regarding the ever new instances of zathura, perhaps you have something different from
```
# If zero, check for a previously running previewer on the same file and update it.  If nonzero, always start a new previewer.
$new_viewer_always = 0;
```
set in `.latexmkrc`?

**Comment by nasenatmer** [comment]
Wow, so much input. Yes, I have xdotools installed (love the auto-updating window-title during compilation.

Firstly, I wanted to collect all those settings for `.latexmkrc`:
```sh
# Set pdf viewer as in 'start VIEWER'
$pdf_previewer = 'start mupdf';

# If zero, check for a previously running previewer on the same file and update it.  If nonzero, always start a new previewer.
$new_viewer_always = 0;

# How to make the PDF viewer update its display when the PDF file changes.  See the man page for a description of each method.
$pdf_update_method = 2;

# When PDF update method 2 is used, the number of the Unix signal to send
$pdf_update_signal = 'SIGHUP';
```
I was not familiar with those settings and were quite surprised at their multitude. Had to read up on them but now I'm in the picture as the Germans say… Are they meant to replace the settings for vim-latex? I mean they are in a way agnostic to what `vim-latex` is doing and duplicate `vim-latex` functions (such as `\lv` or  the great `gb`). Because if I have set up vim-latex to use `zathura` as viewer and am not too lazy to press `\lv` once at the beginning of a session there isn't a huge benefit in using `$pdf_previewer` instead, right?

Except of course if everything worked, which it doesn't on my end (I'm especially sad about `$new_viewer_always`, but that again isn't a big surprise if `$pdf_previewer` is forked to the background and it's title is changed by xdotools all the time). So for me they seem to make things more complicated than necessary. But I'll surely fiddle around with them for a bit more and see if I can adapt them to my needs.

**Comment by nasenatmer** [comment]
When thinking about it, `$new_viewer_always = 0;` can't prevent `\lv` from opening new instances of the viewer that is set in *vim-latex*, can it? Isn't the `$new_viewer_always` setting pureliy latexmk-specific and not sourced by *vim-latex*?

**Comment by Konfekt** [comment]
Hm.. Maybe they are not necessary and I am not sure if `$new_viewer_always = 0` always detects properly if a viewer is already running. Perhaps before discussing fiddling around with `.latemkrc` we should get the ` g:latex_view_general_options` correct, and then look at any other causes of confusion.

@lervag can tell you best in what order vim-latex mingles the `.latexmkrc` with its own options. Supposedly its own options take precedence.

**Comment by nasenatmer** [comment]
Yeah. I think as long as `gb` does such a nice job and there's no need to use `\lv` for that, there's no real reason (for me) to use these latexmkrc settings as zathura auto-updates by itself and that's that.

**Comment by lervag** [comment]
Sorry about taking so long to reply. The discussions is somewhat cluttered to me now, and I'm not entirely sure what the main topic is any longer. I'll assume we talk about `mupdf` here, since I think it is better to discuss the `zathura` specific things in the new issue #118.

Regarding the `.latexmkrc` settings and `vim-latex`: `vim-latex` does not know any settings from `.latexmkrc`. I think there should be a better explanation of these things in the docs, but I've unfortunately not had the time to work on the docs yet. Anyway: What happens is that when we run `latexmk` with the `-pvc` option we start `latexmk` in the continuous mode. This ALSO opens the pdf through `latexmk` with the chosen viewer, which is PURELY a `latexmk` feature. However, for `mupdf`, `vim-latex` has now implemented a functionality that detects whether the current file is being viewed through the use of `xdotool`. This is done (amongst other things) in order to avoid opening a second `mupdf` window if one was already opened when the continuous compilation was started.

@nasenatmer I agree that the `xdotool` trick of changing the window title is neat. However, as  @Konfekt discovered [here](https://github.com/lervag/vim-latex/issues/89#issuecomment-69758005), this trick also breaks the new implementation of forward search between `vim-latex` and `mupdf`. I did not find a way to fix this, but I implemented an improved callback that writes a status message to your vim window when compilation was finished with either success or fail. Thus, I think perhaps (one of) your problem(s) might be this trick: I propose that you remove those lines from your `.latexmkrc` file.

To answer the question ask in the initial post: Forward search from `vim-latex` to `mupdf` should "just work", as long as you have `synctex` and `xdotool` installed, and you have set `g:latex_view_method = "mupdf"`. If it does not, then there is some kind of bug or similar. To investigate this issue, I suggest that you provide a minimal working example:
1. A minimal tex file
2. Preferably a minimal vimrc file (however you may skip this in the first iteratation if you want to)
3. The content of your `.latexmkrc` file
4. Your `vim-latex` settings
5. The sequence of commands/operations/keypresses necessary to reproduce the issue. Here it would help if you could explain what you are trying to do and what you expect to happen.

If there were other issues or problems in this particular thread, then I propose that you open new issues. Since I do not have that much time, it is very helpful to me to keep the discussions isolated and on topic.

**Comment by nasenatmer** [comment]
I'm probably not the best one to debug mupdf support as I'm not using it, but as work volume is low today, why not try:

[vim-latex-settings](https://github.com/nasenatmer/dotfiles-bone2/blob/master/vim/ftplugin/tex.vim), [vimrc-minimal](https://github.com/nasenatmer/dotfiles-bone2/blob/master/vimrc-minimal),latexmkrc is empty except for one line: `$pdflatex = "xelatex -synctex=1 %O %S";`

MWE:
```tex
\documentclass{scrartcl}
\begin{document}
Word \newpage Word2
\end{document}
```
1. Open tex file, press `\ll`, wait a bit
2. press `\lv`, mupdf opens on page 1
3. Move cursor in vim to Word2, press `\lv`, mupdf doesn't change.

But if others are using `vim-latex` in combination with `mupdf` and don't have problems, I can't imagine that I'm doing everything correctly here?

I agree that more documentation on latexmk and latexmkrc would be gread. Maybe I can do this as this is the least-technical part of development?!

**Comment by Konfekt** [comment]
This should in theory work because ` s:mupdf_forward_search()` passes line and column number to synctex. But still the situation that a new page starts in the same line is unlikely and it also fails over here. However
```
\documentclass{scrartcl}
\begin{document}
  Word
 \newpage
  Word2
\end{document}
```
worked. Does it as well for your config?

**Comment by nasenatmer** [comment]
It's irrespective of that. I just drew it together into one line to make it more compact here on github. But as I said, I'm not using `mupdf` actively so we don't need to debug this here for me. But is there anybody else at all also using mupdf with `vim-latex` default settings? Or are you, @Konfekt using the latexmkrc-based setup?

**Comment by Konfekt** [comment]
I am using mudpf with
```
  let g:latex_view_method = 'mupdf'
  let g:latex_view_mupdf_options = '-r 96'
```
in `.vimrc` and
```
$pdflatex = 'pdflatex -synctex=1 --shell-escape %O %S';
$pdf_previewer = 'mupdf -r 96';
```
in `.latexmkrc`.

**Comment by lervag** [comment]
@nasenatmer We don't need to debug this issue, no, since it works for me and @Konfekt, and I also have simple settings as @Konfekt. However, if we can figure out what is going on here, then we might solve an issue that could also affect `zathura` (when I get to implement the full support).

After `mupdf` has opened, could you again print the command as given by `\li`. Also, did I understand correctly that the inverse search was OK, that is, `\lr`?

If so, could you please provide the values for the following variables, after you have tried `\lv`:
```
  g:latex#data[b:latex.id].cmds.view_mupdf_synctex
  g:latex#data[b:latex.id].cmds.view_mupdf_synctex_page
  g:latex#data[b:latex.id].cmds.view_mupdf_xdotool
```

**Comment by nasenatmer** [comment]
Alright, I'll do my best! With `view_method` set to `mupdf` and `$pdf_previewer = 'mupdf -r 96';` set, `\li` outputs the following after a successful compilation:
```vim
  command: compile
    cd '/home/jakob/tmp/latex/minimal' && max_print_line=2000 latexmk -pdf -e '$pdflatex =~ s/ / -
file-line-error /' -outdir=. -pvc -e '$success_cmd .= "vim --servername VIM --remote-expr \"latex\
#latexmk\#callback(1)\""' -e '$failure_cmd .= "vim --servername VIM --remote-expr \"latex\#latexmk
\#callback(0)\""' 'mwe.tex' &>/tmp/jakob/vqW8HjS/1
  command: view_mupdf_xdotool
    xdotool type --window 29360211 "1g"
  command: view_mupdf_synctex_page
    1
  command: view_mupdf_synctex
    synctex view -i 2:2:'/home/jakob/tmp/latex/minimal/mwe.tex' -o '/home/jakob/tmp/latex/minimal/mwe.pdf' | grep -m1 'Page:' | sed 's/Page://' | tr -d '
'
```

But still, `\lv` doesn't change mupdf. `\lr`, on the other hand, actually changes the cursor position in vim. Not exactly to where it is. For instance if cursor is on page 1 (word), pressing `\lr` puts it on  the second `e` in `\newpage`. But there is something happening for sure.

```vim
:echo g:latex#data[b:latex.id].cmds.view_mupdf_synctex
synctex view -i 2:2:'/home/jakob/tmp/latex/minimal/mwe.tex' -o '/home/jakob/tmp/latex/minimal/mwe.
pdf' | grep -m1 'Page:' | sed 's/Page://' | tr -d '
'
:echo g:latex#data[b:latex.id].cmds.view_mupdf_synctex_page
1

:echo g:latex#data[b:latex.id].cmds.view_mupdf_xdotool
xdotool type --window 29360211 "1g"
```

**Comment by lervag** [comment]
@nasenatmer Thanks! I'm curious, where was your cursor in the output you provided here? If you are on `word2`, which should be on page 2, then there really is something strange going on.

So, to be explicit. We have the following MWE:
```tex
\documentclass{scrartcl}
\begin{document}
Text on page 1

\newpage

Text on page 2
\end{document}
```
If you use `mupdf` as view method, open the MWE and then issue `\ll` with the cursor on "Text on page 2", then at least for me the document is openend with mupdf on page 2 after it has been compiled.

**Comment by nasenatmer** [comment]
I can't remember where the cursor was when I did that back then.

But trying again with your minimum working example it still doesn't work: 
1. cursor in vim in line 7 (Text on page 2)
2. `\ll` opens mupdf on p. 1
3. `\lv` doesn't open a new instance, but also doesn't change to page 2.

Tried with [minimal vimrc](https://github.com/nasenatmer/dotfiles-bone2/blob/master/vimrc-minimal), too. Same same.

**Comment by lervag** [comment]
I've just pushed an update to the `\li` command in order to show more info. Could you please pull the latest changes and then repeat the example and provide the output of the `\li` command?

**Comment by nasenatmer** [comment]
Alright, new [`vimrc-minimal`](https://github.com/nasenatmer/dotfiles-bone2/blob/testing-mupdf/vimrc-minimal).

1. open mwe from above, cursor is put in line 7 (Text on page 2)
2. `\ll` opens mupdf on page 1, `vim` buffer goes blank, just like in #125 
3. `\lv` doesn't open a new instance, but also doesn't change `mupdf` to display page 2

Here's the output of `\li` with cursor in line 7
```vim
b:latex
  id : 0
  fold_parts :

g:latex#data[0] : mwe-lervag
  root : '/home/jakob/tmp/latex/mwe'
  aux : '/home/jakob/tmp/latex/mwe/mwe-lervag.aux'
  log : '/home/jakob/tmp/latex/mwe/mwe-lervag.log'
  out : '/home/jakob/tmp/latex/mwe/mwe-lervag.pdf'
  tex : '/home/jakob/tmp/latex/mwe/mwe-lervag.tex'
  tmp : '/tmp/jakob/vSDQg4v/1'
  pid : '9845'
  cmd_latexmk_compile : 'cd ''/home/jakob/tmp/latex/mwe'' && max_print_line=2000 latexmk -pdf -e ''$pdflatex =~ s/
/ -file-line-error /'' -outdir=. -pvc -e ''$success_cmd = "vim --servername VIM --remote-expr \"latex\#latexmk\#cal
lback(1)\""'' -e ''$failure_cmd = "vim --servername VIM --remote-expr \"latex\#latexmk\#callback(0)\""'' -e ''$new_
viewer_always = "0"'' -e ''$pdf_update_method = "2"'' -e ''$pdf_update_signal = "SIGHUP"'' -e ''$pdf_previewer = "s
tart mupdf "'' ''mwe-lervag.tex'' &>/tmp/jakob/vSDQg4v/1'
  base : 'mwe-lervag.tex'
  labels : function('<SNR>35_gather_labels')
  viewer :
    page : '2'
    xwin_id : '37748819'
    class : 'MuPDF'
    cmd_synctex_view : 'synctex view -i 8:2:''/home/jakob/tmp/latex/mwe/mwe-lervag.tex'' -o ''/home/jakob/tmp/latex
/mwe/mwe-lervag.pdf'' | grep -m1 ''Page:'' | sed ''s/Page://'' | tr -d ''
'''
    cmd_forward_search : 'xdotool type --window 37748819 "2g"'
    start : function('10')
    forward_search : function('11')
    reverse_search : function('12')
    latexmk_callback : function('13')
    latexmk_append_argument : function('14')
    init : function('8')
    view : function('9')
    focus_viewer : function('<SNR>33_focus_viewer')
    focus_vim : function('<SNR>33_focus_vim')
    xwin_exists : function('<SNR>33_xwin_exists')
    xwin_get_id : function('<SNR>33_xwin_get_id')
    xwin_send_keys : function('<SNR>33_xwin_send_keys')
```

**Comment by lervag** [comment]
Thanks! This is interesting. As you can see, the viewer has parsed the `synctex` command and finds `page = 2`. It seems the problem is in the forward search command. Can you repeat the above procedure, and then (while everything is open) check the output of `xdotool search --class MuPDF`? The number reported should be the same as the `xwin_id` number.

Could you also report which version of mupdf you are using? I'm using version `1.6` here.

**Comment by nasenatmer** [comment]
My mupdf version is 1.6, too.

Interestingly, `xdotool search --class MuPDF` reports the same ID as `xwin_id`: 37748819

**Comment by lervag** [comment]
This is very strange. Ok. Let's try again, now skip step 2 (don't do `\ll`). After you have verified that forward search still does not work, could you now try the commands in the terminal. That is, do something like the following and report the output/outcome:
```
# Should report "2"
synctex view -i 8:3:'/home/jakob/tmp/latex/mwe/mwe-lervag.tex' -o '/home/jakob/tmp/latex/mwe/mwe-lervag.pdf' | grep -m1 'Page:' | sed 's/Page://' | tr -d `\n`

# Should make mupdf open page 2
xdotool type --window 37748819 "2g"
```

**Comment by nasenatmer** [comment]
I had to remove the last tr statement, then I get `2` indeed:
```sh
synctex view -i 8:3:'/home/jakob/tmp/latex/mwe/mwe-lervag.tex' -o '/home/jakob/tmp/latex/mwe/mwe-lervag.pdf' | grep -m1 'Page:' | sed 's/Page://'
2
```

When doing `xdotool type --window `xdotool search -class MuPDF` "2g"`, just nothing happens (exit code `0`, while if the id is wrong, I get an error by xdotools), so it seems the "2g" command to mupdf is not doing anything to my instance of it. Note: I don't have any config files for mupdf set up.

**Comment by lervag** [comment]
Then I propose you next do
```
# Get window ID
xdotool search --class MuPDF

# Send keys to mupdf
xdotool type --window ID "2g"
```
The first command should give the correct window ID, which you should use for the second command. The second command should change the page to page 2.

What happens if you inside mupdf type `2g`? What happens if you instead try the following?
```
xdotool type --window ID "q"
```

I think we are getting closer. It seems the problem is not directly related with `vim-latex`.

**Comment by nasenatmer** [comment]
Ah, my command above got mis-highlighted: I issued `xdotool type --window <correct id> "2g" with nothing happening already. I did this by doing the following:
```sh
xdotool type --window `xdotool search -class MuPDF` "2g"
```
If pressing `2g` in `mupdf`, it switches to the correct page, `q` closes it, but

```sh
xdotool type --window `xdotool search --class MuPDF` "q"
```
also doesn't close mupdf. Tried with both `zsh` and `bash`, no luck. It seems it is more related to `xdotools` or `mupdf` indeed!

**Comment by lervag** [comment]
So, it seems `xdotool` is not a ble to send keystrokes, for some reason. Could you try this:

1. Open some pdf file with `mupdf`
2. Use `xdotool search --class mupdf` to get the window ID
3. Try to send keystrokes to MuPDF with for instance `xdotool type --window ID KEYS`

You can try both with and without quotes around the `KEYS`. I'd appreciate if you could paste the commands and the output/outcome here. Also, just for clarity, could you use the window ID number instead of the output of the search command for the `xdotool type` command? I don't think that should be a problem, really, but it would make things slightly more  verbose.

Which version of `xdotool` are you using?

**Comment by nasenatmer** [comment]
Weird, it seems something on my system is preventing `xdotool` from acting properly.

```sh
jakob ❯ xdotool search --class MuPDF                               ~
44040275
jakob ❯ xdotool type --window 44040275 "q"                         ~
jakob ❯ xdotool type --window 44040275 q                           ~
jakob ❯ print $?                                                   ~
0
```

So, there is a mupdf window open but it won't close neihter with nor without quotes. Entering `q` in mupdf directly closes it instantly.

`xdotools` is `2.20110530.1-3.

But then this is apparently not a problem of `vimtex` but of a specific setup of xdotool, systemd (using ArchBang Linux on both systems) and therefore should be marked as `non-reproducible`

**Comment by lervag** [comment]
Agreed: Non-reproducible. This is unfortunate, because I want to get the issues down to 0... :(

Can you try if `xdotool` works properly with other applications? For instance, if you try to send text to `zathura`, does that work?

**Comment by nasenatmer** [comment]
Nope, neither. However, it works for my browser, `dwb`. That's strange. But entirely a fault on my side.

**Comment by lervag** [comment]
Ok. I would be happy if you could let me know if you ever find out what the problem is. It might be a suitable thing to comment on in the docs.

**Comment by michaelmior** [comment]
Are any changes still expected to be required for forward search? I'm using qpdfview and I can open the PDF with the predefined `\lv` shortcut, but it doesn't open at the correct position. This may have something to do with the fact that my document is built from multiple `.tex` files...

**Comment by lervag** [comment]
Please open a new issue. Things should work.

Den tir. 12. jun. 2018, 16:34 skrev Michael Mior <notifications@github.com>:

**Comment by michaelmior** [comment]
Sorry to pollute this. It looks like it was because I was using old versions of the setting names :)
