### ISSUE TITLE
Add an option to supress forward/backward search warnings.

### ISSUE THREAD

**Issue by uinput** [lervag/vimtex#1175]
I'm using the latest version of `vimtex`, together with `neovim 0.3.0` and `zathura 0.4.0`.

When opening a file, I'm always getting reminded that my version of zathura is missing support for synctex and that I do not have xdotools installed. However, I do not need forward or backward search (I only want to open those files), but I have not found a way to disable these warnings.

I already tried disabling `g:vimtex_view_forward_search_on_start` which didn't help.

Here is the message printed when opening a `.tex` file.
```
vimtex: Zathura is not linked to libsynctex!
vimtex: Zathura requires xdotool for forward search!
```

Is there any way to disable forward/backward search completely, without using the ability to view the document from inside vim?

**Comment by lervag** [comment]
Yes, sorry, I've never imagined that anyone would _want_ to use Zathura without `xdotool` and `libsynctex`, and so this has been raised as a warning to make people aware that these features are not available.

One simple way to solve this is to use the general view method. If you've setup your system so that Zathura is the default viewer, then you should not need any settings at all. On Linux, `xdg-open` is used which should run Zathura out of the box (if properly configured).

Alternatively, you can set 

```vim
let g:vimtex_view_general_viewer = 'zathura'
```

Note, though: Repeated use of `\lv` will open new instances of Zathura.

I'm curious, why would you not want to include a fully working Zathura setup?

**Comment by uinput** [comment]
Great, thanks a lot!

> Note, though: Repeated use of \lv will open new instances of Zathura.

As long as I can switch there manually, this doesn't hurt. Most of the time zathura is opened on another screen anyway. Still, could you imagine there to be any way around that?

> I'm curious, why would you not want to include a fully working Zathura setup?

Well, I'm thinking about switching over to Wayland, which is why I want to avoid using `xdotools`. Do you know about any plans on how this is going work if Wayland becomes the de facto standard?
By using zathura, you can quickly switch your position anyway, for example by using the quickmarks. So it's not a big deal if I loose forward search.

Keep up the good work!

**Comment by lervag** [comment]
> As long as I can switch there manually, this doesn't hurt. Most of the time zathura is opened on another screen anyway. Still, could you imagine there to be any way around that?

Yes, I think this should work:

```vim
let g:vimtex_view_general_viewer = 'zathura'
let g:vimtex_view_general_options = '--synctex-forward @line:@col:@tex'
```

> Well, I'm thinking about switching over to Wayland, which is why I want to avoid using xdotools. Do you know about any plans on how this is going work if Wayland becomes the de facto standard? By using zathura, you can quickly switch your position anyway, for example by using the quickmarks. So it's not a big deal if I loose forward search.

I've not delved deep into Wayland yet myself. So sorry, I don't know so much about any plans.

> Keep up the good work!

Thanks! :)
