### ISSUE TITLE
Weird "something went wrong when parsing log files" error

### ISSUE THREAD

**Issue by gipert** [lervag/vimtex#1185]
I'm experiencing a very strange behavior of the quickfix window with this very specific project:

Consider the following minimal `vimrc`
```vim
set nocompatible
let &rtp  = '~/.vim/plugged/vimtex,' . &rtp
filetype plugin indent on
syntax enable

let g:vimtex_compiler_latexmk = { 'build_dir'  : 'log' }
```
and the following mini-latex project:
* `article.tex`:
```tex
\documentclass{revtex4-1}
\usepackage{lipsum}
\begin{document}
\lipsum[1]
\cite{pas2015}
\bibliography{mybib}
\end{document}
```
* `mybib.bib`:
```
@article{pas2015,
  author       = {Päs, Heinrich and Rodejohann, Werner},
  date         = {2015},
  doi          = {10.1088/1367-2630/17/11/115010},
  eprint       = {1507.00170},
  eprintclass  = {hep-ph},
  eprinttype   = {arXiv},
  journaltitle = {New J. Phys.},
  number       = {11},
  pages        = {115010},
  title        = {Neutrinoless Double Beta Decay},
  volume       = {17},
}
```

The project compiles fine with `\ll`, but when I try to open the quickfix window with `\le` I get
```
vimtex: something went wrong when parsing log files!
```
Can you reproduce that?

I got into this error with a very large project and I spent hours to get to this MWE, apparently the problem vanishes with a different `documentclass` (e.g. `article`) or with a different bibtex entry or without putting the log files in a separate `log` folder.

Do you have any clue about the source of this error?

**Comment by gipert** [comment]
Argh, why is it always like that!

Here's the nasty log file: [article.log](https://github.com/lervag/vimtex/files/2257070/article.log)

That warning is just what I want the quickfix window to show me :)

**Comment by lervag** [comment]
Ok, I've reproduced, thanks. I forgot to use the option you supplied. Sorry!

**Comment by lervag** [comment]
And fixed. :)

**Comment by gipert** [comment]
Great! Fixed also in the big project the MWE was coming from. Thanks!

**Comment by lervag** [comment]
No problem! Thanks for reporting :)

**Comment by gipert** [comment]
Uhm, I'm getting again the same error (in the very same big project) right now, do you remember by chance what was the problem? [Here](https://github.com/lervag/vimtex/files/2593233/gerda-bkg-paper-ph2.log)'s the nasty log file.

**Comment by lervag** [comment]
Strange. I can't reproduce this. If I use your log file, I can parse it without any issues.

Can you try to make a new minimal example for this (and a new issue)?

**Comment by gipert** [comment]
I realised that it happens when compiling from an included file, like `chapters/chap1.txt`, so I guess vimtex cannot actually find the log file, does it make sense? Note that I still have `build_dir` set to `log`.

**Comment by lervag** [comment]
It makes some sense, I'll try to reproduce.

**Comment by lervag** [comment]
I tried, but I still can't reproduce. I would be happy to fix this, but I will need more help to reproduce. I propose that you take the following approach:

1. Begin with your current setup and document and find the steps to reliable reproduce it.
2. Copy your vimrc file to the document working directory and reduce it as much as possible, include only whatever is necessary to reproduce the problem. I propose having the vimrc file open in one terminal/Vim window and have another terminal open where you do `vim -u minivimrc file.tex` and perform the steps.
3. When you can not reproduce the vimrc file more, then reduce the LaTeX file. Remove everything that is not necessary.

This procedure should land you a fully minimal example. If you are inexperienced in performing these steps, it might take some time. Personally, I think it would take me 1-5 minutes starting from the full version, unless the issue is very cryptic (heisenbug like). :)

**Comment by gipert** [comment]
Sorry for the late reply, I've been super busy recently...

Anyways, I discovered that the issue shows up only if I run the compilation from an included tex file and not from the main one. I guess that Vimtex might be confused by the fact that a) the included file sits in a different folder b) I put all the auxiliary files in a separate folder. Does this tell you anything?

**Comment by lervag** [comment]
@gipert No. And you already suggested the issue might come from included files. If the issue is related to a specific pattern of how you structure your project, then please provide a clear example that reproduces the issue. See my previous comment and the issue template.
