### ISSUE TITLE
Possible to do surround with \[ \]?

### ISSUE THREAD

**Issue by j2kun** [lervag/vimtex#1189]
I stumbled upon a beautiful feature of this plugin whereby using vim-surround with `\` opens a dialog to specify `\begin{$1}` and wraps the selection with the chosen environment. Wow!

I am wondering if there's a way with this plugin to do surround with "offset math mode," i.e., `\[ \]`

I wasn't able to find anything in the documentation referring to this, except that it recognizes the delimiters.

Cheers, and thanks for writing this plugin!

**Comment by lervag** [comment]
There is `csd` and `cse` to change the surrounding delimiter/environment. But there is not really anything for creating delimiter pairs or environments. The reason is that this is better implemented by dedicated snippet plugins such as Ultisnips. I've written about it in the docs, see `:help vimtex-non-features` in the `Snippets/Templates` parts.
