### ISSUE TITLE
vim-latex not loading mappings with new vundle?

### ISSUE THREAD

**Issue by nasenatmer** [lervag/vimtex#12]
Hello, 

I just wanted to ask here first because I'm not yet sure whether this is a _vundle_ or a _vim-latex_ issue.

Since I upgraded to most recent _vundle_ (526d390854f14bc5886ca0606b3be51f7379eacb) and did the interface change, _vim-latex_ doesn't seem to be loaded when I open a tex file in _vim_ or _gvim_.

It seems related to [issue 430](https://github.com/gmarik/Vundle.vim/issues/430) of vundle. However, when I execute `:scriptnames` from the tex file, vim-latex is in the list:

```
 47: ~/.dotfiles/vim/bundle/vim-latex/ftplugin/tex.vim
 49: ~/.dotfiles/vim/bundle/vim-latex/indent/tex.vim
 52: ~/.dotfiles/vim/bundle/vim-latex/after/syntax/tex.vim: 
```

Yet, when I want to use `\ll`, I navigate up (due to my custom mappings) or with `\li` I get into insert mode. And that the mappings of a plugin weren't loaded, was peculiarly enough described by raghur [here](https://github.com/gmarik/Vundle.vim/issues/430#issuecomment-39978758) as well.

Can anyone else observe this behaviour?

**Comment by wsdjeg** [comment]
@lervag HI, thanks for create this project, and I am working on latex layer on SpaceVim, many people recommend to use this plugin in https://github.com/SpaceVim/SpaceVim/issues/2046, and we are also discuss this latex support in our chinese group. and I have tried to using this plugin , but I just encounter this old issue. when open `*.tex` file, the filetype is plaintex instead.

 first I think vimtex use tex.vim as name space, It should treat `*.tex` file as latex filetype, for people who want to use plaintex should enable this plugin by default. and vimtex do not provide ftdetect feature for latex, this should be noted on readme or help file, and a suggestion vim script snippet will be better:

```vim
  augroup vimtex_ftdetect
    autocmd!
    au BufNewFile,BufRead *.tex setlocal filetype=latex
  augroup END

```

**Comment by lervag** [comment]
@wsdjeg The reason is that vimtex does not adjust the ftdetect at all. This is already mentioned in the docs, see `:help vimtex-comment-internal`. You need

```vim
let g:tex_flavor = 'latex'
```

I guess for SpaceVim, it could make sense to set this as a default option. But
I don't want to do this in vimtex, as I think this should be up to the user.

**Comment by wsdjeg** [comment]
oh, got it, but I need to use lazy load feature, so I need to add fedetect autocmd myself. the files in `./plugins` is loaded by default in vim, so you can use this option, but for lazy loaded plugin, all files will not be loaded only when filetype is set to latex.

**Comment by lervag** [comment]
I don't quite understand why you need lazy load feature? vimtex is an ftplugin, so nothing is really loaded until a `tex` buffer is opened. You might be talking about SpaceVim internal stuff, in which case I wouldn't know since I don't know much about SpaceVim.

In any case, feel free to open new issues or email me directly if you have more questions (see email in git log). I think it is better than to continue in this ~4 year old thread.
