### ISSUE TITLE
Indentation problem with `\right\vert`

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#1210]
When I use pairs of `\left.` and `\right\vert`, the code is mis-indented (tested with a minivimrc): 

```
\documentclass{article}
\begin{document}
Text here
\begin{equation}
    \left. A \right\vert
    \end{equation}
    more text
    \begin{equation}
	\left. N \right\vert
	\end{equation}
	\end{document}
```

I am not sure if this is a problem of `vimtex` or of the underlying indenting mechanism... 
Thanks for the great plugin!

**Comment by lervag** [comment]
Actually, the problem here is that you use `\vert`. This is not a delimiter. Instead, you should use `\rvert` (and `\lvert`). See e.g. [here](https://tex.stackexchange.com/questions/498/mid-vertical-bar-vert-lvert-rvert-divides) for more info.

I'm happy to see that your example works as expected if you use `\lvert` instead. :)

**Comment by Rmano** [comment]
Oops, sorry for the noise. Thanks!

**Comment by lervag** [comment]
No problem! :)

man. 10. sep. 2018 kl. 10:16 skrev Romano Giannetti <
notifications@github.com>:
