### ISSUE TITLE
Create a command does not work under visual block mode

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1212]
`vimtex` does not correctly work when creating a command under visual-block mode.

Let us say in a table, one of our columns (say the 'remark' column) is as follows:

`note1`
`note2`
`note3`
`note4`

We wish to emphasize (italicize) these notes. So, one could select the entire block (column of text) using visual block mode, i.e. `Ctrl-v'.

Then if we issue `vimtex`'s create-command mapping (I have remapped it to `<leader>ac`), and create an `emph` command, we should get

`\emph{note1}`
`\emph{note2}`
`\emph{note3}`
`\emph{note4}`

Instead, we only get the first line in the selection correct.

`\emph{note1}`
`note2`
`note3`
`note4`

**Comment by kiryph** [comment]
If you need this urgently, there is the plugin [vim-sandwich](https://github.com/machakann/vim-sandwich). vim-sandwich provides out of the box the command `sa`+`c`+`emph` in visual block mode for LaTeX.

All tex recipes can be found here [`:h sandwich-filetype-recipes`](https://github.com/machakann/vim-sandwich/blob/master/doc/sandwich.txt#L340-L390).
The implementation is located in `macros/sandwich/ftplugin/tex.vim`:
https://github.com/machakann/vim-sandwich/blob/master/macros/sandwich/ftplugin/tex.vim#L43-L51

I use the surround-style mappings which change the command to capital `S` in any visual mode and in normal mode to `ys`: `{VISUAL BLOCK}Sc`+`emph`. This might be interesting if you have installed vim-surround and do not mind to switch to vim-sandwich.

**Comment by lervag** [comment]
Thanks @krishnakumarg1984, I think your suggested "correct behaviour" makes sense, so I've updated accordingly.

I also agree with @kiryph that vim-sandwich is very good and probably implements most/all of the vimtex surround type mappings in a slightly (or much) improved manner. It is still useful, I think, to keep the vimtex mappings, since they are now mostly stable and work as expected (I realize noone really suggested otherwise, I just felt like mentioning this).
