### ISSUE TITLE
some manual/minor errors

### ISSUE THREAD

**Issue by teto** [lervag/vimtex#1213]
# Explain the issue
Jsut a few comments running master cad3b43eca41b75cedab9ac86241f006aa3202ea

I followed the doc to get deoplete completion
```
if !exists('g:deoplete#omni#input_patterns')
    let g:deoplete#omni#input_patterns = {}
endif
let g:deoplete#omni#input_patterns.tex = g:vimtex#re#deoplete

```
but it gives  `E121: Undefined variable: g:vimtex#re#deoplete`

On startup, I had a similar problem with `g:vimtex_toc_config` but adding `let g:vimtex_toc_config={}` to vimrc fixed it.

Also `let g:vimtex_complete_img_use_tail=1` is not documented.

**Comment by languitar** [comment]
Do you use a plugin manager that conditionally loads vimtex depending on the ft?

**Comment by teto** [comment]
Yes `Plug 'lervag/vimtex', {'for': 'tex'}`

**Comment by languitar** [comment]
That's the reason then. You can, however, just remove that conditional loading because most parts of vimtex are an ftplugin that isn't run until a latex file is opened.

**Comment by languitar** [comment]
For the reference: I stumbled across this issues as well initially: https://github.com/lervag/vimtex/issues/885

Maybe some note in the help pages would be good.

**Comment by lervag** [comment]
Hmm. I don't really feel like adding this to the docs, because I don't think anyone would read it before opening an issue. I think instead this should be added to the README/docs for the various plugin managers. One should _not_ recommend anyone to lazy load filetype specific plugins, unless those plugins are badly written. (IMHO) And I think this should be made clear for the users of e.g. vim-plug, not to the users of vimtex.

That is, I think the problem here is that people are using vim-plug in a wrong way, and that should be fixed by updating the documentation fro vim-plug.

**Comment by languitar** [comment]
@lervag Maybe you could open an issue at vim-plug then and explain your reasoning about this?
