### ISSUE TITLE
Error when opening file with non-english characters in path

### ISSUE THREAD

**Issue by adrianadermon** [lervag/vimtex#1270]
When I open a file with a Swedish character (å, ä, ö) somewhere in the path (either in a directory or the file name itself), I get the following error message:

```vim
"~\Dropbox\täst.tex" 6L, 77C
Error detected while processing function vimtex#init[4]..<SNR>26_init_state[1]..vimtex#state#init[1]..<SNR>28_get_main[8]..<SNR>28_file_is_main:
line   10:
E484: Can't open file C:\Users\adria\täst.tex
```

Syntax highlighting still works, but commands such as `<leader>ll` do nothing at all.

I'm using Neovim 0.3.1 on Windows 10. I have the exact same problem on my other Windows 10 computer. For reproducibility, I'm starting Neovim from the CLI using the command `nvim -u init.vim täst.tex`, with the following minimal `init.vim` and `täst.tex` files.

Minimal `init.vim`:
```vim
call plug#begin('~/AppData/Local/nvim/plugged')

Plug 'lervag/vimtex'

call plug#end()
```

Minimal `täst.tex` file:
```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

**Comment by lervag** [comment]
Hmm. That's strange. I don't use Windows, so it's difficult to debug this directly. On Linux, there is no similar problem. So, you're saying that vimtex works fine, except in cases where the path to the file contains a Swedish character (and similar characters, I presume)?

Are you able to do some debugging on your end? It seems the problem is related to this line:
https://github.com/lervag/vimtex/blob/f0958a545d72a496de4c804692d8efa33c3a6670/autoload/vimtex/state.vim#L370

If you could edit that file and add some echo statements (perhaps necessary with `unsilent echom`) first to verify that `a:file` is the correct full path name that you expect. If so, then you can proceed by trying to run `:echo readfile("/path/...", 0, 5)` and try to reproduce the problem "outside" of vimtex.

**Comment by adrianadermon** [comment]
I added the line `unsilent echo a:file` in `state.vim`, and it does print the correct path. 

However, running `:echo readfile("f:/Dropbox/täst.tex", 0, 5)` prints this error:
```vim
E484: Can't open file f:/Dropbox/täst.tex
[]
```

I tried it with a path that only contains English characters, and that works as expected, so it seems the problem is in the `readfile` command. I took a brief look at the Neovim issues at GitHub, but couldn't find anything related to this. I guess I should open an issue there instead, since this does not seem to be a Vimtex-specific problem?

**Comment by lervag** [comment]
Yes, in principle I think that is best. Do you also have Vim installed, and could you test the same in Vim (preferably version 8 or newer)? I expect this should work in Vim.

**Comment by lervag** [comment]
Also, can you verify that the same command fails in neovim when you start with `nvim -u NONE`, i.e. without any configuration?

**Comment by adrianadermon** [comment]
I tried out the latest dev version of Neovim 0.3.2, and it seems like everything works like it should there. I'll just wait for the next release of Neovim, and everything should be fine. 

Thanks for the help, and for an excellent plugin!

**Comment by lervag** [comment]
Great, happy to hear it and for the kind remark!
