### ISSUE TITLE
Wrong filename in QuickFix window

### ISSUE THREAD

**Issue by nightuser** [lervag/vimtex#1289]
Error handling doesn't support multifile projects. The error list lists main tex file for all the entries.

To reproduce create `main.tex` file with the following content:

```tex
\documentclass{article}
\begin{document}
\input{second}
\end{document}
```

And `second.tex`:

```tex
%! TEX root = main.tex
\ref{badrefname}
```

Then compile (`<localleader>ll`) and QuickFix window will have wrong filename reference (`main.tex`). Similar to:
```
main.tex|2 warning| LaTeX Warning: Reference `badrefname' on page 1 undefined on input line 2.
main.tex|| LaTeX Warning: There were undefined references.
```

**Comment by lervag** [comment]
Yes, I know about this. This is because Vims errorformat is very difficult to use to handle the complex log format. I've tried to fix this several times, but I never manage to capture every edge case, and I find that the current situation is better than my attempts so far. And there is no new input to me that I think will help improve this, unfortunately.

However, I have added different log parsers, so you can intall e.g. `pplatex` and set `g:vimtex_quickfix_method = 'pplatex'`. This should work better in most cases, I think.
