### ISSUE TITLE
[Feature request] grammar analysis using textidote

### ISSUE THREAD

**Issue by sim590** [lervag/vimtex#1311]
So, this feature request may appear as premature, but I am posting it in case this could help motivate people to contribute on this. [Textidote][textidote] is a program that interfaces with language tool and preparses (removes) LaTex macros before passing the resulting text to LanguageTool. The final result displays in consistently regarding the initial LaTeX code and appears to be [the most viable option (to this day and to the best of my knowledge) to get LaTeX grammar checks][ltchecks].

I have opened [an issue][textidoteissue] on textidote's repository for a feature request that would enable output into parsable format. Once that would be implemented, Vimtex could follow by implementing grammar checks display into the *quickfix* (or *location*) window for example.

The only issue I see with implementing the plugin as part of Vimtex is that textidote also supports Markdown. Therefore, the grammar check error displaying plugin may have more sense as standalone. However, I don't think that textidote project will lead to support more languages other than that, so maybe it can still be considered as a LaTex only plugin check anyway if you will.

That being said, a [LanguageTool Vim plugin][ltvim] already exists and does a good job of what I'd like to see in Vimtex. However, this plugin interfaces with LanguageTool directly and not with textidote, therefore it cannot support LaTeX.

Consequently, as I see it, the best course of action would be to extract relevant code from the LanguageTool plugin which should be written as a standalone grammar error display plugin (decoupled from LanguageTool or any language checker). Then, make VimTex use that code so that it interfaces with textidote's output.

Finally, I think that this can be reasonably easy to implement, considering the amount of code already existing and doing more or less what we want. That being said, I have not checked how the Vim plugin for LanguageTool works, so maybe the request for textidote to implement a parsable output is not needed at all. I'll have to dig into the plugin.

I'm eager to know what Vimtex's user think about that. I hope this idea appeals to many.

[textidote]: https://github.com/sylvainhalle/textidote
[ltchecks]: http://wiki.languagetool.org/checking-la-tex-with-languagetool
[textidoteissue]: https://github.com/sylvainhalle/textidote/issues/60
[ltvim]: https://github.com/dpelle/vim-LanguageTool

**Comment by sim590** [comment]
I have just taken a look at the Vim plugin for LanguageTool and [it does use XML output][ltvim]. Therefore, the feature request I opened on textidote's repository is mandatory if we want to reuse the LanguageTool plugin's code.

[ltvim]: https://github.com/dpelle/vim-LanguageTool/blob/master/plugin/LanguageTool.vim#L282

**Comment by lervag** [comment]
I am sorry for responding so late! I've been very busy lately. Life and all.

I'm not familiar with LanguageTool. Can you describe (as briefly as possible):

- What is LanguageTool; how does it work?

- How would a Vim interface work, exactly? I.e.,
  - which mappings (or commands) should be available?
  - what are the results of performing them?

Other questions:

- Are you able to outline or start a PR for this feature yourself?

- In a way, this seems very related to linting in general. Would it perhaps be more appropriate to add this as a specific linter to plugins like [ale](https://github.com/w0rp/ale)? Ale already has some linters for LaTeX, see [here](https://github.com/w0rp/ale/tree/master/ale_linters/tex).

**Comment by sim590** [comment]
> I am sorry for responding so late! I've been very busy lately. Life and all.

This is all fine. We are all busy! :wink:

> I'm not familiar with LanguageTool. Can you describe (as briefly as possible):
>
> * What is LanguageTool; how does it work?

This is a grammar checking program which reports syntactical and lexical errors in human language (English, French, etc.) on standard output. You pass your text on standard input and LanguageTool reports errors on standard output.

> * How would a Vim interface work, exactly? I.e.,
>
>   * which mappings (or commands) should be available?
>   * what are the results of performing them?

This can be presented in Vim in the manner which [vim-LanguageTool][vlt] does.  As I said, the final result would essentially be a the same as `vim-LanguageTool`, but using [`textidote`][textidote] as a backend.

[vlt]: https://github.com/dpelle/vim-LanguageTool
[textidote]: https://github.com/sylvainhalle/textidote/

> Other questions:
>
> * Are you able to outline or start a PR for this feature yourself?

Yes. I'm waiting for [XML output feature request][xmltextidote] to arrive for `textidote` before working on it. If I have the time, I may contribute to `textidote` myself to add XML output feature, but I'm presently not very much available.

[xmltextidote]: https://github.com/sylvainhalle/textidote/issues/60

> * In a way, this seems very related to linting in general. Would it perhaps be more appropriate to add this as a specific linter to plugins like [ale](https://github.com/w0rp/ale)? Ale already has some linters for LaTeX, see [here](https://github.com/w0rp/ale/tree/master/ale_linters/tex).

I'm not sure how this would fit. From what I understand, ale is more for computer language linting while `textidote` and LanguageTool are for human language grammar (English, French, etc.).

**Comment by lervag** [comment]
As I've not been convinced otherwise, I'll take the liberty of closing this one.

**Comment by matze-dd** [comment]
Hi,

may I draw your attention to the project [YaLafi](https://github.com/matze-dd/YaLafi)? This is a LaTeX filter suitable for integration with an editor and a proofreading software like [LanguageTool](https://www.languagetool.org/). Initially, filtering has been based on recursive regular expressions (project [Tex2txt](https://github.com/matze-dd/Tex2txt)), but now it uses a more powerful scanner / parser for LaTeX analysis.

As other tools like [TeXtidote](https://github.com/sylvainhalle/textidote) and [vscode-ltex](https://github.com/valentjn/vscode-ltex), YaLafi provides mapping of character positions between the LaTeX text and the plain text seen by the proofreading tool. Therefore, messages from the proofreader can be properly related to the corresponding parts of the LaTeX text.  The current status is that it can be used with Vim plug-in vim-grammarous ([see here](https://github.com/matze-dd/YaLafi#interface-to-vim)) and Emacs plug-in Emacs-langtool ([see here](https://github.com/matze-dd/YaLafi#interface-to-emacs)).

I do my own LaTeX writing with "plain Vim", in a rather simple, Bash-script based environment. The above filter project grew out of the desire to use LanguageTool for the check of already existent LaTeX document trees. Therefore, I wanted to make it flexible and not to produce too many false positives from the proofreading tool. Now it is in a status that one might use it in a larger framework.

Would it be worth to put some effort into integrating YaLafi with vimtex and vim-grammarous? In order to keep things simple for the user, application via Docker seems sensible to me (combined usage of Java, Python, LanguageTool, Vim, ... and of course LaTeX).

Matthias

**Comment by lervag** [comment]
Thanks, Matthias, for pitching your thoughts on this. Let's continue this at #1684 - I'll give my comments when I get the time to consider it in more depth.
