### ISSUE TITLE
Custom Build Sequences?

### ISSUE THREAD

**Issue by Astrantia** [lervag/vimtex#1314]
Hi, how would I go on about making a custom build sequence when auto compiling with \ll?
Instead of calling latexmk only for compilation, I'd like to modify it to first run latex on the tex file I'm working on, then run pythontex on the file, and then run latex on the file again. I haven't seen support for this in the readme or in any of the closed issues. Thanks for the plugin.

**Comment by kiryph** [comment]
`latexmk` can be configured so that it also automatically invokes `pythontex`. This has been improved last October with `latexmk` version  4.61 2018-10-25. Therefore, I recommend that you have the newest version of `latexmk` installed. You can verify your version with
```
❯ latexmk -v

Latexmk, John Collins, 25 October 2018. Version 4.61
```


Additionally, you need following file
[`http://mirrors.ctan.org/support/latexmk/example_rcfiles/pythontex-latexmkrc`](http://mirrors.ctan.org/support/latexmk/example_rcfiles/pythontex-latexmkrc)

I illustrate the usage with a minimal example:

```
❯ mkdir demo-pythontex-latexmk
❯ cd demo-pythontex-latexmk
```
Download the above mentioned file and save it as latexmkrc.
```
 ❯ wget http://mirrors.ctan.org/support/latexmk/example_rcfiles/pythontex-latexmkrc -O latexmkrc
```
Create a demo tex file with following content:
```
❯ cat demo-pythontex-latexmk.tex
\documentclass{article}
\usepackage{pythontex}
\begin{document}
\begin{pycode}
print(r'\begin{center}')
print(r'\textit{A message from Python!}')
print(r'\end{center}')
\end{pycode}
\end{document}
```

And you are good to go.

To make sure it actually works, I would recommend to invoke `latexmk` on the command line for the first time:

```
❯ latexmk --quiet -pdf demo-pythontex-latexmk.tex
Latexmk: Run number 1 of rule 'pdflatex'
Latexmk: calling latex_python( "demo-pythontex-latexmk" "" pdflatex  -interaction=batchmode -recorder  "demo-pythontex-latexmk.tex" )
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
=== Pythontex being used
=== Creating rule 'pythontex demo-pythontex-latexmk'
Latexmk: Log file says no output from latex
Latexmk: For rule 'pdflatex', no output was made
Latexmk: Run number 1 of rule 'pythontex demo-pythontex-latexmk'
This is PythonTeX 0.16

--------------------------------------------------
PythonTeX:  demo-pythontex-latexmk - 0 error(s), 0 warning(s)

Latexmk: Run number 2 of rule 'pdflatex'
Latexmk: calling latex_python( "demo-pythontex-latexmk" "" pdflatex  -interaction=batchmode -recorder  "demo-pythontex-latexmk.tex" )
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
=== Pythontex being used
```

But it should work with no changes to the vimtex configuration as well:

Compile with
```
<Leader>ll
```
Open dvi/pdf and you should see the message from Python.

Check also the log output with
```
<Leader>lo
```
which should show a run of pythontex.

**Comment by lervag** [comment]
Thank you, @kiryph, for the very good information! As this topic is not really vimtex related, I think I'll close this issue. But I expect your informative reply to be helpful to others who might have the same question.

**Comment by kiryph** [comment]
@lervag: I actually contacted John Collins last October. I also asked him about deleting the empty directory. His response

> The next version of latexmk will be able to remove empty directories 
also.  (And pythontex-latexmkrc will be updated accordingly.)

So we have to wait.

However, noone should be worried about the empty directories. They cannot interfer with a fresh compilation: the recorder option of pdflatex and the file database of latexmk containing the checksums does not contain folders and therefore everything is newly compiled.

**Comment by Astrantia** [comment]
Confirmed it worked great for me too. Thanks @kiryph!

**Comment by kiryph** [comment]
@Astrantia You are welcome.
