### ISSUE TITLE
SyncTexForward is not working

### ISSUE THREAD

**Issue by xu-cheng** [lervag/vimtex#136]
`g:latex#data[b:latex.id].out()` would return `E121: Undefined variable: g:latex#data`.

**Comment by lervag** [comment]
I'm sorry, but how do you expect me to be able to help you with this if you do not provide more information?! A good issue template can be found [here](https://github.com/Shougo/neocomplete.vim/issues/236).

At the very least, you should try to explain how I can reproduce the issue.

However, I assume the problem is due to things you have in your vimrc file. Please note that the plugin has changed its name to `vimtex`. This resulted in me changing a lot of variable names as well. For instance, `g:latex` is now `g:vimtex`.

**Comment by xu-cheng** [comment]
I mean literally running the command `g:latex#data[b:latex.id].out()` would emit the error. And indeed, it's caused by variable rename. Thanks for quick responding.

Also, IMHO, breaking forward compatibility sucks unless there was a huge improvement in the features/performance.

**Comment by lervag** [comment]
I agree, I try not to break compatibility while developing. However, the change of name was really necessary in order to avoid the silly name clash with [vim-latex](http://vim-latex.sourceforge.net/). Also see the discussion in #129.
