### ISSUE TITLE
Viewer cannot read PDF file with "-jobname" in latexmkrc

### ISSUE THREAD

**Issue by anhnamtran** [lervag/vimtex#1366]
Hi,

Currently, I have a project specific latexmkrc file:

```perl
@default_files = ('main.tex');
$pdf_mode = 1;
$jobname = 'some-project-name'
```

I realize that vimtex ignores `@default_files` and that's okay. `:VimtexCompile` works fine, and `latexmk` properly opens the viewer. However, `:VimtexView` outputs this: `Viewer cannot read PDF file` with the path to `main.pdf`.

What would be the correct approach to telling vimtex to ignore that line (besides removing the line or using a different compiler)? I am unfamiliar with VimScript variables, but this is what tried to "append" to the default list of options:

```vim
let g:vimtex_compiler_latexmk['options'] += '-jobname=%A'
```

But this gave a "Variable not found" error.

Here is the relevant bit in my `.vimrc`:

```vim
set conceallevel=1

let g:tex_flavor='latex'
let g:tex_conceal='abdmg'

let g:polyglot_disabled = ['latex']

let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
let g:vimtex_imaps_leader='!'
```

**Comment by lervag** [comment]
Hi. I'm curious, why do you create that specific `latexmkrc` file? That is, what are you trying to achieve compared to not having the project specific file at all?

What I can understand from the `-jobname` option, you want the output files to be named something different than the base of the main file. That is, given `main.tex`, you want the output file to be e.g. `something-else.pdf`.

I think it could be possible to implement support for this, but I'm not quite sure if it's worth the "pain". That is, what is the initial reason that you want this?

To add `-jobname=STRING` to the options, you need to do this:

```vim
let g:vimtex_compiler_latexmk = {
      \ 'options' : [
      \   '-verbose',
      \   '-file-line-error',
      \   '-synctex=1',
      \   '-interaction=nonstopmode',
      \   '-jobname="string"'
      \ ],
      \}
```

Note, though, that I don't think you can use things like `%A` in the string (I've not tried it, though, so perhaps I'm wrong). Note further, that this does not currently allow `:VimtexView` and similar to work, because it does not know of the `-jobname` functionality and assumes that generated files have the same base name.

Finally, perhaps you could test if you can set the jobname in the top comments like [this](https://tex.stackexchange.com/a/139963/34697)?

**Comment by anhnamtran** [comment]
I did want to achieve:
> given main.tex, you want the output file to be e.g. something-else.pdf.

It's completely valid that this is not something worth going through the trouble of implementing! Hence why I phrased my question the way I did. 

It looks like I also had a bit of a misunderstanding of the compiler option itself, so thanks for clarifying that!

Perhaps I could try to find a workaround in the "vimtex-multi-file" section, but any hint on what might be the most helpful would be appreciated.

I will close the issue as soon as I am able to figure out a workaround and post it here.

**Comment by lervag** [comment]
> but any hint on what might be the most helpful would be appreciated

Could you please be more specific? If you can provide a full minimal example of what you want to achieve and state what is the expected and observed behaviour, then I will probably be able to help you.

**Comment by anhnamtran** [comment]
Hi, sorry about that. What I want to do is:
- Compile

**Comment by anhnamtran** [comment]
I managed to do achieve what I wanted by just having a separate latexmkrc file that I specify to latexmk if I'm running it from the terminal.

What I wanted to do was have a compiled pdf from `main.tex` that is `some_other_name.pdf` and make sure that when I run `latexmk -C` it gets rid of the correct files. This is achievable with `-jobname` for latexmk but conflicted with vimtex viewer.

**Comment by lervag** [comment]
Ok, I'm happy to hear that you've resolved the issue!

**Comment by trondbn** [comment]
I would just like to add that I managed this by using `g:vimtex_view_method = 'general'`and using Skim.

**Comment by trondbn** [comment]
> I would just like to add that I managed this by using `g:vimtex_view_method = 'general'`and using Skim.

It seems I spoke in haste, it seems that latexmk opens the file, but the VimtexView command does not work.

**Comment by lervag** [comment]
Feel free to open a new issue if you have a problem.
