### ISSUE TITLE
File path string not escaped correctly

### ISSUE THREAD

**Issue by gblanco92** [lervag/vimtex#1375]
When using vimtex in Mac OS with Skim, if the tex/pdf file path string contains a single quote `'`, vimtex does not open Skim automatically. The problem is the command:

```
osascript -e 'set theFile to POSIX file "/Users/user/foo'bar/main.pdf"' -e 'set thePath to POSIX path of (theFile as alias)' -e 'tell application "Skim"' -e 'try' -e 'set theDocs to get documents whose path is thePath' -e 'if (count of theDocs) > 0 then revert theDocs' -e 'end try' -e 'open theFile' -e 'end tell' >/dev/null 2>&1 &
```

which is not a valid `bash` command. If the `foo'bar` folder is replaced by `foobar` everything works as expected.

I am not sure what the right fix for this might be. Just escaping the single quote does not work. However, escaping the single quote `...user/foo\'bar/main.pdf` and adding `$` in front of the first single quoted string `osascript -e $'set theFile to POSIX file "/Users/user/foo\'bar/main.pdf"'...` makes it work. See, [Bash documentation 3.3.5](http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_03.html).

I do not know whether this bug may affect other PDF viewers or other operating systems.

**Comment by lervag** [comment]
Why would you include a quote in file name? I guess that's a bad question...

I don't work with MacOS/OSX myself, and so can't test things. Since the problem is tied to the osascript, it seems only related to OSX. Thus it is difficult me to fix this without anyone suggesting a fix that does not break things and that solves the current issue.

If I remember correctly, @kiryph uses OSX. Perhaps you would be able to help? Or @nasenatmer? Or @clason, @znculee, @lacygoill?

**Comment by gblanco92** [comment]
> Why would you include a quote in file name? I guess that's a bad question...

I wouldn't, but I was working on someone else's files and I took me quite some time to figure out what the problem was. The PDF viewer simply does not open, there is no error message. Anyhow, `/Users/user/foo'bar/main.tex` is a valid UN*X filename path which shouldn't make things stop working.

> I don't work with MacOS/OSX myself, and so can't test things. Since the problem is tied to the osascript, it seems only related to OSX. Thus it is difficult me to fix this without anyone suggesting a fix that does not break things and that solves the current issue.
> 
> If I remember correctly, @kiryph uses OSX. Perhaps you would be able to help? Or @nasenatmer? Or @clason, @znculee, @lacygoill?

*Maybe* this is not related only to Mac OS. *Sometimes*, the strings containing filepaths are not correctly escaped in vimtex. I do not known whether vimtex nests quoted strings with filepaths in other operating systems.

If you can confirm that this is only Mac OS related (which is probably the case due to the ugly calling syntax of osascript), I will try to fix it in `autoload/vimtex/view/skim.vim` and send a pull-request.

**Comment by clason** [comment]
The osascript command is taken from the `displayline` script distributed with Skim, so if it's incorrect it should ideally be reported upstream. (My personal view is that such filenames should be considered harmful, and correcting _them_ is a better approach than "fixing" every single tool in the chain that needs to work with them... YMMV.)

**Comment by clason** [comment]
Still, why would someone use such a filename? That's just... negligent. (Unless you have to deal with files from Windows users. Then all bets are off.)

**Comment by clason** [comment]
But I think there's a valid point here: That the script just fails silently is not very helpful. @lervag Is there any way to extract and/or forward error messages from called scripts to vim?

**Comment by lacygoill** [comment]
I don't use MacOS so I can't reproduce the issue.
I tried to `:vimgrep` my plugins to find an occurrence of `osascript`, and found these lines:
https://github.com/lervag/vimtex/blob/2e1687bd66c58fc37d47447c411f89895d8db4cd/autoload/vimtex/view/skim.vim#L45-L49

I could be wrong, but maybe the issue comes from the last line:

    \ '-e ''set theSource to POSIX file "' . expand('%:p') . '"''',

It seems that the current filename, given by `expand('%:p')`, must be protected from the `set theSource to POSIX file` token, hence the presence of two double quotes before and after:

    \ '-e ''set theSource to POSIX file "' . expand('%:p') . '"''',
                                        ^                     ^

But that's brittle, and may break if the current filename already contains a double quote. You can't use single quotes either, because the filename could also one. A better way to protect the filename would be `shellescape()` or the `:S` filename modifier. But there would be another issue, because it seems that the whole `set theSource ...` command must itself be protected from the shell which is going to run `$ osascript`. So, you would need a second `shellescape()`.

I can't test it, but I would try to replace this line:

    \ '-e ''set theSource to POSIX file "' . expand('%:p') . '"''',

With this line:

    \ '-e ' . shellescape('set theSource to POSIX file ' . shellescape(expand('%:p'))),

Or shorter:

    \ '-e ' . shellescape('set theSource to POSIX file ' . expand('%:p:S')),

I have no idea whether it would work though.

**Comment by clason** [comment]
@lacygoill Actually, from the issue report, the problem is more likely the `self.out()` in line 83. (If the TeX file (`theSource`) contains a quote, it has to be assumed that the PDF file (`outfile`) also does.)

Of course, the lines you mention will have the same problem, but they're only called when explicitly entering `<localleader>lv`.

**Comment by lacygoill** [comment]
Oh ok, then I would try to replace:
https://github.com/lervag/vimtex/blob/2e1687bd66c58fc37d47447c411f89895d8db4cd/autoload/vimtex/view/skim.vim#L83

With:

    \ '-e ' . shellescape('set theFile to POSIX file ' . shellescape(self.out())),

**Comment by gblanco92** [comment]
> Oh ok, then I would try to replace:
> https://github.com/lervag/vimtex/blob/2e1687bd66c58fc37d47447c411f89895d8db4cd/autoload/vimtex/view/skim.vim#L83
> 
> With:
> 
> ```
> \ '-e ' . shellescape('set theFile to POSIX file ' . shellescape(self.out())),
> ```

This does not work. It generates the following string:

`'\''/Users/user/foo'\''\'\'''\''bar/main.pdf'\'''`

which triggers the following error in `osascript`:

`26:27: syntax error: Expected expression, property or key form, etc. but found unknown token. (-2741)`


> The osascript command is taken from the `displayline` script distributed with Skim (which also fails with this file), so if it's incorrect it should ideally be reported upstream; I usually check for changes to that script when Skim is upgraded.

The `displayline` script from Skim works correctly. No problem with:

`/Applications/Skim.app/Contents/SharedSupport/displayline 1 /Users/user/foo\'bar/main.pdf`

> Still, why would someone use such a filename? That's just... negligent. (Unless you have to deal with files from Windows users. Then all bets are off.)

Just for the record, the pathname I was given was something along the lines of `.../John Doe's Thesis/main.pdf` which, IMO, is not such a *negligent* name for a folder. I wouldn't name my folders this ways, but as long as this is a valid UN*X folder name, the average MacOS/Linux user will use it at some point. But probably, the `vimtex` user is not the average user and it was my mistake not to sanitize my folder names...

**Comment by lacygoill** [comment]
What seems tricky is the fact that there are two levels of quoting, and I don't know what this `set theFile to POSIX file` token is/does/expects.

What about this?

    \ '-e ' . shellescape('set theFile to POSIX file ' . string(self.out())),

**Comment by znculee** [comment]
> > Why would you include a quote in file name? I guess that's a bad question...
> 
> I wouldn't, but I was working on someone else's files and I took me quite some time to figure out what the problem was. The PDF viewer simply does not open, there is no error message. Anyhow, `/Users/user/foo'bar/main.tex` is a valid UN*X filename path which shouldn't make things stop working.
> 
> > I don't work with MacOS/OSX myself, and so can't test things. Since the problem is tied to the osascript, it seems only related to OSX. Thus it is difficult me to fix this without anyone suggesting a fix that does not break things and that solves the current issue.
> > If I remember correctly, @kiryph uses OSX. Perhaps you would be able to help? Or @nasenatmer? Or @clason, @znculee, @lacygoill?
> 
> _Maybe_ this is not related only to Mac OS. _Sometimes_, the strings containing filepaths are not correctly escaped in vimtex. I do not known whether vimtex nests quoted strings with filepaths in other operating systems.
> 
> If you can confirm that this is only Mac OS related (which is probably the case due to the ugly calling syntax of osascript), I will try to fix it in `autoload/vimtex/view/skim.vim` and send a pull-request.

When I try to reproduce this problem, I did get the error messages as the follows.
![image](https://user-images.githubusercontent.com/15342165/56937947-fafd8900-6b31-11e9-8071-895e612f057e.png)
When press `<localleader>ll` to compile:
![image](https://user-images.githubusercontent.com/15342165/56937962-094ba500-6b32-11e9-972b-775d561112d2.png)
When press `<localleader>lv` to preview:
![image](https://user-images.githubusercontent.com/15342165/56937999-4021bb00-6b32-11e9-94ce-566c5be758f2.png)
Maybe we can provide a more friendly error or suggestions for user to avoid the path name with the quotation mark.

**Comment by gblanco92** [comment]
> What seems tricky is the fact that there are two levels of quoting, and I don't know what this `set theFile to POSIX file` token is/does/expects.
> 
> What about this?
> 
> ```
> \ '-e ' . shellescape('set theFile to POSIX file ' . string(self.out())),
> ```

I does not work either. I get the errors from the previous answer. What works for me is:

`  \ '-e $''set theFile to POSIX file "' . escape(self.out(), "'") . '"''', `

The other lines that should be modified are:
       
` \ '-e $''set theFile to POSIX file "' . escape(outfile, "'") . '"''', `
` \ '-e $''set theSource to POSIX file "' . escape(expand('%:p'), "'") . '"''', `

Since this solution only escapes the symbol `'`, it does not work if `foo'bar` is replaced, for instance, by `foo"bar` or `foo\bar`(which are IMO much less common, but still problematic).

**Comment by lervag** [comment]
Thank you @clason, @lacygoill, @znculee for joining the discussion!

I agree that we should aim towards avoiding surprises, and as such, I will be happy to try to handle weird file names in a better way. If I understand correctly, this particular issue concerns any project that contains a `'` in it's path, and similar with `"` and `\`. The problem is related to the Skim viewer through the osascript. Or is there more?

I agree that it could be possible to solve this by using the `escape(..., "'")` form. But it catches one of several cases. I'm surprised that it does not work for `\` as well, but I would guess that `"` must be escaped with `""` instead of `\"`.

Instead of actually handling these filenames, would it be possible to do as @clason suggests to catch a possible errormessage from osascript? This would require an update to the `process.vim` module, which currently does not handle errors. I'm not quite sure if there's a good way to do it with the current implementation, though, but we could modernize it to use the modern job api (when available).

**Comment by lervag** [comment]
As I don't use a Mac, it is not easy for me to work with this issue. Please feel free to reopen if you want to continue this discussion. Or, perhaps better, open a new issue with a concise summary and suggestion for change. Even better, a pull request.
