### ISSUE TITLE
[Feature request] add support for `ltx2any` (for its markdown-based log-file parser)

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1385]
Currently we have the following build automation solutions (invoked by `<leader>l`) .

* latexmk 
* latexrun
* arara

For error/log-file parsing, we have 

* standard latex log (unreadable by humans)
* pplatex (saner error parsing;, but no Windows binaries!; abandoned project)
* pulp (not as nice as `pplatex`; again no Windows binaries; looks unmaintained)

I am forced to work on a Windows machine at my libraries. While SSH-based remote compiling on a *nix machine is an option, real-time X11 feedback sometimes are problematic due to slow bandwidth etc.

I have been looking at a solution for this for over 18 months now, and I think have found it.
-  [ltx2any](https://github.com/reitzig/ltx2any), which looks newer and more active. This is more of a hybrid tool which does both build automation and error parsing.

__Two__ things about this are impressive:

1. The error parsing is by far the best (a nicely readable markdown file) & further as a beautiful PDF with syntax highlighting (if `pandoc` is available)
   * Can vimtex  maybe consider mapping `<leader>E` to bring up this error file. I think this feature supplements the existing quicklist based fixing, which must be present anyway. It is helpful to have a documented error summary (for self/colleagues) etc. If my eyes . I could just get a error-summary PDF printed out, and have a coffee while reading a human-readable error log - a first for latex :)

2. I liked the automatic parallel compilation on many cores.

Even if we don't get `ltx2any` as a build tool into `vimtex`, can we (pretty please) somehow provide access to the error-parser?

**Comment by lervag** [comment]
I don't mind adding support for ltx2any, although it would be quicker if someone would be willing and able to begin the work with a PR. Else it might be some time before I get the time to do it myself.

Some comments:

- vimtex should work well with latexmk and e.g. SumatraPDF on Windows. I am not quite sure what problem you are actually trying to solve.

- It is very easy to add a custom mapping for `<leader>E` to bring up the error file. It does not make sense to add such a mapping to vimtex until after the main backend is implemented.

- IMHO, the quickfix list provides a very readable and good interface to the LaTeX errors. The main problem is that there might be errors and warnings that are not parsed correctly. However, most of them should work quite well. If you can provide an example of an error/warning that is not parsed correctly, then let me know.

- Although I see that the markdown error log looks good, I do not quite understand what makes it more convenient than the quickfix based interface.

**Comment by krishnakumarg1984** [comment]
>vimtex should work well with latexmk and e.g. SumatraPDF on Windows. I am not quite sure what problem you are actually trying to solve.

* Yup. No problems with that. I am talking about only log-file parsing for improved error reporting. Unlike `*nix` and `macos`, `pplatex` cannot be easily built on Windows & binaries don't exist

* I am mainly interested in having a `vimtex` interface to the markdown and beautiful syntax-highlighted PDF generated by `ltx2any` from the standard latex error-log

>It is very easy to add a custom mapping for <leader>E to bring up the error file. It does not make sense to add such a mapping to vimtex until after the main backend is implemented.

* Agreed. I don't know how to implement the backend though.  `<leader>E` should just bring up the markdown/PDF file of the list of errors/warnings that `ltx2any` produces. So we can offload the work to `ltx2any`

>IMHO, the quickfix list provides a very readable and good interface to the LaTeX errors. The main problem is that there might be errors and warnings that are not parsed correctly. However, most of them should work quite well. If you can provide an example of an error/warning that is not parsed correctly, then let me know.
Although I see that the markdown error log looks good, I do not quite understand what makes it more convenient than the quickfix based interface.

* You misunderstood me. The quickfix-based workflow is certainly __required__.  The markdown-based workflow is in addition to the quick-fix workflow, which is why I propose the unused `<leader>E` mapping, which is semantically consistent with the existing `<leader>e` mapping.

**Comment by kiryph** [comment]
Just my 50 cents:

The feature request is at first sight not so clear:

**Do we need another build tool or parser of the log files or both and most importantly why?**

- Default parser does not capture everything
As mentioned if there are warnings/errors which vimtex does not capture, then we should try to fix this. 
  If the ltxany parser is better with respect to better support of external tools and their warnings and errors, again this is something we could improve for the default parser of vimtex as well. For example, vimtex already captures the errors from biber/bibtex log file and places them in the quickfix window as well.

  But I think this is not what the motivation for this issue was.


- Speed
If ltxany compiles e.g. a heavy tikz-externalized project significantly faster than latexmk/latexrun/arara, this would be a good reason for me. An example project would be nice to have.


- Nicer representation of warnings and errors than the quickfix list
I personally do not need a markdown/pdf representation of the warnings/errors and is for me not the most convincing reason. BTW a markdown representation could be done in principle by vimtex. Warnings/errors are parsed and could be written to a markdown file.

**Why is the markdown representation of the warnings/errors better than the quickfix list?**

If one follows the recommendation from [Why/When should I pay attention to warnings?](https://tex.stackexchange.com/a/109484/8917) to fix errors immediately and warnings when one is finished with writing, one could ask to filter warning messages from the quickfix list temporarily and show only errors. This is already possible. In this circumstance, one should only see a few errors which are handled immediately. Therefore, I do not see the reason for a high-quality typeset representation of the errors with this workflow. 

BTW one can also use the package https://ctan.org/pkg/silence and following type of tex setting to reduce the number of warnings:

```tex
\hbadness=10000 % disable warnings about underfull boxes
```

If one enables all warnings at the final stage, it is possible to end up with an overwhelmingly long list where I could understand that somone wants something more readable to make the huge task of solving them more pleasant.

This is one of the reasons why I do not fix all warnings at the final stages and obviously consider this not the best approach. I am more selective about which warnings I ignore during writing and those which I treat like errors, namely immediately. For example, when I have a larger picture than the `\textwidth` by intention, I use a special environment which redefines the textwidth for this instance and I do not get an overfull box. Warnings about duplicate labels can also be fixed on sight and many more. It is obvious that underfull boxes are warnings which one should not address before finalizing the document.

To fix warnings  quickly on sight is a reason for me to use the quickfix list and would not use an external representation to read the warning message.

**Comment by kiryph** [comment]
```
:h g:vimtex_quickfix_latexlog

*g:vimtex_quickfix_latexlog*
  This option configures the `latexlog` error parser. It is a dictionary that
  specifies which warnings to include. By default, all warnings are enabled
  and have to be specifically disabled. However, it is possible to use the
  entry `disable` to disable either all warnings, or all package warnings, if
  so desired.

...

  Some examples may be helpful: 

    " Disable all warnings
    let g:vimtex_quickfix_latexlog = {'default' : 0}

    " Disable undefined reference warnings
    let g:vimtex_quickfix_latexlog = {'references' : 0}

    " Disable overfull/underfull \hbox and all package warnings
    let g:vimtex_quickfix_latexlog = {
          \ 'overfull' : 0,
          \ 'underfull' : 0,
          \ 'packages' : {
          \   'default' : 0,
          \ },
          \}

```

**Comment by lervag** [comment]
Ok, so I understand that you like the Markdown/PDF output from `ltx2any`, but I still fail to see how this should be relevant as a feature for vimtex. As such, I've decided to mark this issue as "won't fix", unless you provide a more compelling reason.

However, if you want, I can try to assist you in creating a manual mapping for the desired feature. Do I understand correctly that what you want is for `<leader>lE` to:

1. Run `ltx2any` on the main document.
2. Open the resulting pdf file in a viewer.

?

**Comment by krishnakumarg1984** [comment]
@lervag I understand your concerns, and shall leave it at that.

Yes, Please help to create a manual mapping in my vimrc for the following sequence of steps:

1. Stop the currently running compiler to avoid conflicts
  * Issue `\lk` to pause the currently running build tool (`latexmk` for me)
  * Issue `\lC` to clean out log and error files
2. Issues `lL to run  `ltx2any` 
3. Run `\lE` to show the generated markdown error-log in a new buffer
4. Run `lV` to open the error PDF in the preferred reader set in `vimtex`

Sorry for asking your help for these tasks. I don't know much about `vimscripting`.

**Comment by lervag** [comment]
First attempt: Put the following snippet inside your `.vim/ftplugin/tex.vim` (or a similar location).

```vim
nnoremap <buffer><silent> \lE :call RunLtxToAny()<cr>
nnoremap <buffer><silent> \lV :call ViewLtxToAny()<cr>

function! RunLtxToAny() abort
  silent VimtexStop
  silent VimtexClean
  call system('ltx2any -synctex ' . b:vimtex.tex)
  edit b:vimtex.log() . '.md'
endfunction

function! ViewLtxToAny() abort
  silent VimtexStop
  silent VimtexClean
  call system('ltx2any -lf pdf -synctex ' . b:vimtex.tex)
  call b:vimtex.viewer.view(b:vimtex.log() . '.pdf')
endfunction
```

I am not surprised if this does not immediately work. I've tried to install ltx2any to test this, but I had some trouble with my Ruby install, it seems. In any case, I think this should give you an OK outline for how to do it.

**Comment by krishnakumarg1984** [comment]
@lervag  Thanl you so much. That indeed works!

**Comment by lervag** [comment]
Great, happy to hear it!
