### ISSUE TITLE
[feature-amendment request] Center the screen on `\begin{xxx}` for `]m` (alternatively provide `g]m` or other flexible navigation options)

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1393]
If we would like to move quickly between environments (eg. a figure, a table, a list), we can currently do `]m`. This places the cursor at the `\\begin{}` line of the next environment. However, it is very likely that the cursor will end up closer to the bottom of the screen. 

Normally, when navigating the environments, users would like to see their entire environment, between the `\begin{}` and `\end{}` lines, preferably with the start of the environment centered on the screen (at-least that is what I prefer).

Hence, could vimtex consider one of the following options

* Redefine `]m` to be equivalent to `]mzz` (backwards-incompatible. Inflexible)
* Provide a new mapping `g]m` to be equivalent to `]mzz` (inflexible)

The same argument could be made for section navigation i.e. `]]`, `][`, `[[` etc. 

Therefore a 3rd option could be do define a common setting for both `environment` and `section` navigation and could be called `g_vimtex_navigatation_screen_alignment`, with a valid option being one of `t`, `m`, `b`. (Very flexible).

If you disagree with me and are reluctant to introduce changes in navigation behaviour, could you at least help to customise my `vimrc` to get the desired behaviour?

**Comment by lervag** [comment]
Hi! My comments to your suggestions:

- Option 1: No, I don't find this very tempting, because it will be very subjective (and change existing mappings).
- Option 2: I think there are already very many mappings, and I don't quite see why we want to double the number of motion mappings.
- Option 3: I think there are already way too many options, and that this is a little bit too "obscure" to warrant a new one.

Still, I also often do `{motion}zz` to keep the cursor centered, and so I understand where you are coming form. I think the best solution is to create your own mappings for the motions that you want to change behaviour. I would suggest you add something like the following to your `.vim/ftplugin/tex.vim` file:

```vim
nmap <buffer> ]] <plug>(vimtex-]])zt
nmap <buffer> [[ <plug>(vimtex-[[)zz
nmap <buffer> ]m <plug>(vimtex-]m)zt
nmap <buffer> [m <plug>(vimtex-[m)zz
```

See `:h vimtex-default-mappings` for a list of the `<plug>(vimtex-{motion})` mappings.

**Comment by lervag** [comment]
A word about the `.vim/ftplugin/tex.vim`: This is my preferred strategy for adding personal customizations for different filetypes. You can do this in several ways, but the easiest and most straightforward way is to have a folder `ftplugin` inside your main `.vim` folder where you add customizations.

An alternative, if you insist on doing this in your vimrc file, is to use autocommands. E.g.:

```vim
augroup my_filetype_customizations
  autocmd!
  autocmd FileType tex nmap ...
  autocmd FileType tex nmap ...
augroup END

" Or perhaps like this
augroup my_filetype_customizations
  autocmd!
  autocmd FileType tex call TexCustomization()
augroup END

function! TexCustomization() abort
  nmap ...
  nmap ...
endfunction
```

**Comment by lervag** [comment]
I hope this helps. Let me know if something is still unclear.

**Comment by krishnakumarg1984** [comment]
@lervag Yes! This totally works for me. Thanks a lot for your help.

**Comment by lervag** [comment]
No problem, happy to help!
