### ISSUE TITLE
One sentence per line formatting

### ISSUE THREAD

**Issue by korsbo** [lervag/vimtex#1416]
I prefer to keep my latex documents formatted with one sentence per line. This makes sense to me both because it makes git behave and because line operations then allow me to manipulate sentences in a natural way. However, maintaining this formatting currently requires me to do manual work.

So, here is my feature request: automatic formatting options for one-sentence-per-line. 

I have dabbled a bit with `formatexpr` and with some helper functions but they do not do the trick for me.
```vim
function! SentenceFormatting(start, end)
    silent execute a:start.','.a:end.'s/[.!?]\zs /\r/g'
endfunction
autocmd FileType tex set formatexpr=SentenceFormatting(v:lnum, v:lnum+v:count-1)

function! SentenceBreakOut()
    execute "normal! l("
    if col(".") != 1
        execute "normal! i\<cr>"
    end
    execute "normal! dis"
    let s = @"
    let s = substitute(s, "\n", " ", "g")
    let @" = s . "\n"
    execute "normal! P"
    execute "normal! =j"
endfunction
autocmd FileType tex nnoremap <buffer> <leader>s :call SentenceBreakOut()<cr>
```

This automatic formatting works when writing a new sentence but has crippling side-effects for editing. The `SentenceBreakOut` function requires manual execution and it sometimes introduces unwanted empty lines.

I know that this has been mentioned in other issues (#1317, #1200, #1020) but those requests have all been a bit broader than this so I thought I'd make a specific request.

Also: thanks for your work on this plugin!

**Comment by lervag** [comment]
> Also: thanks for your work on this plugin!

I'm happy you like it! :)

> I know that this has been mentioned in other issues (#1317, #1200, #1020) but those requests have all been a bit broader than this so I thought I'd make a specific request.

I appreciate that you raise the more specific issue. It is easier to consider than the broader ones. However, I did spend quite a lot of time to make the current formatting expression work. As one might understand, formatting is a quite complicated feature.

Still, I'm tempted to make a try for it, since it could also be of use to myself. First, though, I'm curious about two things:

1. Is this possible to achieve with e.g. [latexindent.pl](http://ctan.uib.no/support/latexindent/documentation/latexindent.pdf)? It seems from section 6.2 that the answer is yes. So, if I understand correctly, I would think it is better to rely on a more weather tested tool. I assume that one can make latexindent.pl work well with Vim, although I have not done so myself.

2. In case we would attempt this, and in spite of the first point probably being true: How should we handle sentence breaks? That is, not all punctuation should end a sentence. Trivial examples: `e.g.`, `i.e.`, etc. This is probably the main obstacle for implementation, and it is made more complex in that it _should_ be language agnostic.

So, based on point 1, I think perhaps I would not go for this. In particular, if anyone knows how to use `latexindent.pl` with e.g. the plugins `Ale` or `coc.nvim` to either manually or automatically format based on "one sentence per line", then I would personally be grateful, and I think it could be added to the docs. If, on the other hand, it turns out that this is difficult, then I might be tempted to find some set of basic rules that we could follow to make a proof-of-concept implementation.

**Comment by Konfekt** [comment]
My plugin https://github.com/Konfekt/vim-sentence-chopper will use `latexindent` to put each sentence onto its own line if available, and falls back to a simple substitution otherwise.

**Comment by Konfekt** [comment]
However, this again only handles manual formatting. To have a line break inserted after every sensible punctuation mark, if I understand `:help 'formatexpr'` correctly, 

> 	The expression is also evaluated when 'textwidth' is set and adding
	text beyond that limit.  This happens under the same conditions as
	when internal formatting is used.  Make sure the cursor is kept in the
	same spot relative to the text then!  The |mode()| function will
	return "i" or "R" in this situation.

a low  textwidth coupled with a function (which `&l:formatexpr` is set to) that does the line breaking is the only option.

**Comment by lervag** [comment]
Thanks for the input, @Konfekt. I think your plugin deserves a mention in the vimtex docs. Further, it seems you raise a point that it may be hard to use an external tool for autoformatting.

So, there seems to be two options:
1. Implement a new solution. If I make it simple, it has a high risk of needing further development to solve issues due to edge cases (e.g. how to properly detect the end of a sentence, multilingual, etc).
2. Fall back to the more simple approach: To write one sentence per line, ensure to add line breaks manually while writing. This is not really a big issue, I think. Further, one may use one of several tools to automatically apply `latexindent` to manually format paragraphs according to the desired style. The benefit is that the tool is already there and is battle ready. The drawback is that you have to manually hit `<enter>` when writing your own text.

To me, it feels like option 2 is clearly the best approach. Keep things simple.

**Comment by krishnakumarg1984** [comment]
>  The drawback is that you have to manually hit <enter> when writing your own text.
This is a pretty-big deal for me (but probably, just me). It is unnatural to break every sentence like this. 

I strongly prefer automatic sentence chopping before committing to a VCS.

>Further, one may use one of several tools to automatically apply `latexindent` to manually format paragraphs according to the desired style. 
I am really interested in the automatic application of `latexindent`, like what you mention. Can you give a bit more detail on this?

**Comment by Konfekt** [comment]
If you use `git, then you could add a script to `.git/hooks/pre-commit` that runs `latexindent` on all committed files. See `man githooks`. Put it into `.config/git/templates/hooks/pre-commit` to ensure that it is copied into every cloned and initialized `git` repo.

**Comment by Konfekt** [comment]
Also, you could add
```vim
autocmd BufWrite *.tex %ChopSentences`
```
 to your `vimrc` to format the current buffer after saving the file. See `:help autocmd` for events other than `BufWrite`.

**Comment by nilsbecker** [comment]
i guess i'm late to the party; i have been using this in a project-specific vimrc file:
```viml
"vi SO 2846. formatexpr for one line per sentence.
function! MyFormatExpr(start, end)
    silent execute a:start.','.a:end.'s/[.!?]\zs \%[\n]/\r/g'
endfunction

au FileType tex setlocal formatexpr=MyFormatExpr(v:lnum,v:lnum+v:count-1)
```
i then manually format paragraphs with it, which works satisfactorily overall.
i don't trust it enough to make it fully automatic on commit/write.
as you can see i got it from stack overflow.

**Comment by nilsbecker** [comment]
it does not break a line on `e.g.~something` which is what one should to anyway. however, it does not join wrongly broken lines in a paragraph.
