### ISSUE TITLE
Dead link - vim-latexrefman is gone

### ISSUE THREAD

**Issue by 927589452** [lervag/vimtex#1421]
The Documentation at  [vimtex.tex](https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt) references a dead link for [vim-latexrefman](github.com/poppyschmo/vim-latexrefman) as the git repository is gone from @poppyschmo s page

edit: fixed link to file

**Comment by 927589452** [comment]
further research shows [refman](http://home.gna.org/latexrefman) seems gone

**Comment by lervag** [comment]
Thanks for the heads up! I've sent an email to @poppyschmo to ask him for the status. I will hold actions to allow some time for him to respond.

**Comment by lervag** [comment]
Is [this](https://puszcza.gnu.org.ua/projects/latexrefman/) a different latexrefman project?

**Comment by poppyschmo** [comment]
The Vim help project has indeed been removed because it was poorly written (by me) and unfit for automation, which it did not implement but should have. I apologize for not alerting anyone to its removal. Had I known it featured in the documentation, I would have archived it instead.

The upstream LaTeX Refman (also called latex2e in filenames) is alive and well. I like it because it mentions when third-party packages offer better solutions. It has also been translated by hand into many languages. The [link](https://puszcza.gnu.org.ua/projects/latexrefman/) from @lervag is correct.

**Comment by lervag** [comment]
Thanks. I've updated the docs accordingly.

**Comment by krishnakumarg1984** [comment]
How do we use the [plaintext version ](https://latexref.xyz/dev/latex2e.txt) as the keyword (K) program?
