### ISSUE TITLE
wrong character in completion preview window

### ISSUE THREAD

**Issue by cridemichel** [lervag/vimtex#1448]
**Describe the issue**
Wrong characters in preview window for `\varsupneqq`, `\varsupsetneq`, `\varsupsetneqq`, `\varsubsetneq` and `\varsubsetneqq` latex symbols.

**Steps to reproduce**

```vim
" file: minivimrc
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
filetype plugin indent on
syntax enable

set guifont=Hack\ Nerd\ Font:h19

let g:vimtex_view_method = 'skim'
```

```tex
\documentclass{minimal}
\usepackage{amssymb}
\usepackage{amsmath}
\begin{document}
Hello world!
\end{document}
```

1) Open the minimal tex file with

    `mvim -u ./minivimrc minimal.tex`

2) Type: `\varsu<c-x><c-o>` after `Hello world!`.

3) Question marks are shown instead of proper characters in the preview window

**Output from VimtexInfo**
```
System info
  OS: Mac OS X 10.14.6 (18G87)
  Vim version: VIM 8.1 (1-1722)
  Has clientserver: true
  Servername: VIM

vimtex project: minimal
  base: minimal.tex
  root: /Users/demichel/VIMTEX_BUG
  tex: /Users/demichel/VIMTEX_BUG/minimal.tex
  out: 
  log: 
  aux: 
  fls: 
  compiler: latexmk
    backend: jobs
    output: /var/folders/26/9q3nft3x4xg2zbj45nzm__100000gn/T/v9vu7zI/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: Skim
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: minimal
  packages:
    amsmath
    amssymb
```

**Comment by 927589452** [comment]
did some research:

in the complete [file](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/complete/tools/symbols) and in my enviroment they aren't shown either, so I suspect the fonts we are using do not support the used symbols

**Comment by lervag** [comment]
Yes, this is most likely due to the choice of font in your terminal. The symbols should display correctly if you have a font that supports them.

**Comment by cridemichel** [comment]
hack font (and many other nerd fonts) at least support u228A (\varsubsetneq) and u228B (\varsupsetneq), you can check here
 
[hack] (https://www.1001fonts.com/hack-font.html#character-map)

**Comment by 927589452** [comment]
Though I just looked at the codes and they seem to be "private use" so its rather font dependend; could you add against which font this was chosen?

**Comment by cridemichel** [comment]
> Though I just looked at the codes and they seem to be "private use" so its rather font dependend; could you add against which font this was chosen?

the font, which I am using, is in the minivimrc, it is the hack font (see also my previous post)

**Comment by 927589452** [comment]
```sh
line 2527, Output of :UnicodeName
'' U+E01A Dec:57370 Private Use Zone &#xE01A; /\%ue01a "\ue01a"
```

**Comment by lervag** [comment]
Ok, first: @cridemichel Please in future posts include the contents of minimal files as code snippets instead of uploading the files. It makes it much easier for me (and others) to quickly understand your issue. Further, please remove the parts from the issue template that you are not using, and finally, please use proper markdown. I've updated your original post, so feel free to edit it to see the proper syntax for the various elements. Notice I've further simplified your minimal vimrc file by removing unnecessary stuff (e.g. Youcompleteme and setting options to their defaults). The issue is reproducible with only vimtex and omnicompletion.

So, regarding the issue at hand: The entire feature is actually pretty much stolen from TeXstudio, in the sense that the list of macros for each package and the corresponding symbol is taken from their repos. I do not know which font is used in TeXstudio. I have the same issue in that a lot of the symbols do not work for me. Still, since on the other hand a lot of the symbols do work, I find it to be a little bit useful.

I don't feel like spending a lot of time with this, and I do not consider it a bug. Please try some different fonts and see if you can find a font that supports more of the symbols. I think it should be possible to specify several fonts, so that the secondary fonts are used for symbols that are not defined in the primary fonts.

**Comment by 927589452** [comment]
just a quick comment:

it seems in their [definition](https://github.com/texstudio-org/texstudio/blob/master/symbols-ng/relation.xml) they removed the unicode commands for `\varsu*`

would a bit of manual tweaks to the symbols file be welcome?

**Comment by cridemichel** [comment]
> just a quick comment:
> 
> it seems in their [definition](https://github.com/texstudio-org/texstudio/blob/master/symbols-ng/relation.xml) they removed the unicode commands for `\varsu*`
> 
> would a bit of manual tweaks to the symbols file be welcome?

maybe one can show a whitespace for those undefined symbols?

**Comment by lervag** [comment]
@cridemichel If it is possible, then I would be glad to do that. But then I would need to know how to detect when the current font does not have a valid symbol for the current keycode. If anyone should know how to do that, either in gvim, Macvim, or vim/neovim in a terminal, then that would be very helpful.

**Comment by lervag** [comment]
FYI: I've investigated, but I can't find a good method of detecting this, sorry. :\

**Comment by lervag** [comment]
Perhaps @kiryph knows?

**Comment by kiryph** [comment]
Sorry, no I do not know this. Maybe add an option to not show them and mention fonts with wide support for mathematical symbols.

**Comment by lervag** [comment]
Ok, thanks. I could consider to add an option, but I hesitate. Is it that big of an annoyance? I think perhaps that the convenience outweights the inconvenience.

But if someone feels strongly that they should be able to disable this feature, than I will consider to add an option.
