### ISSUE TITLE
Citation completion slow

### ISSUE THREAD

**Issue by alucardkoten** [lervag/vimtex#1454]
**Describe the issue**
I have a bib file including all my citations (around 1500 citations). I find it is very slow to complete the citation key even I use `let g:vimtex_complete_bib = { 'simple': 1 }`. It take about 3 or 4 seconds while it is instant on other editors such as vscode or Texpad.

*minimalvimrc*

```vim
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_complete_enabled = 1
let g:vimtex_complete_bib = { 'simple': 1 }
```

*minimal.tex*

```tex
\documentclass[letterpaper, 12pt]{article}
\usepackage{natbib}
\begin{document}
\cite{
\end{document}
\bibliographystyle{apa}
\bibliography{/Users/jiangtianli/MyWriting/mybib.bib}
```

Here is the bib file: [url](https://drive.google.com/file/d/1SD4CiLwZDwOd2bJiuhS8uSvasT-_s-hn/view?usp=sharing)

**Comment by lervag** [comment]
Hi. First, I updated your post with proper formatting. Please take the time to learn (github flavored) markdown (e.g. read [this guide](https://guides.github.com/features/mastering-markdown/)). It makes it much easier to quickly parse your text (IMHO).

Next, your example is not minimal, neither correct. Can I suggest that you:
1. Properly load vimtex (it is not loaded in your example now).
2. Avoid the use of `vim-mucomplete`, unless it is necessary to reproduce. I don't think it is. Instead of typing `<tab>`, you can type `<c-x><c-o>` (which is the standard key to invoce omnicompletion).

I'll consider your issue when you've updated your issue description and notified me that it is done.

**Comment by alucardkoten** [comment]
I have updated my issue.

**Comment by lervag** [comment]
You must also supply the bibliography file. If I try to reproduce this, it will fail, since `/Users/jiangtianli/MyWriting/mybib.bib` does not exist on my system. I understand if you don't want to share this file, but if so, please make a shareable version of it. If the file is very large, then simply attach it to the issue. If it is short, I prefer that you add it inline.

**Comment by alucardkoten** [comment]
I have provided the bib file now.

**Comment by lervag** [comment]
Ok, I've started this now. I've managed to improve it a bit, I think. Could you please go to the test files in `test/issues/1454` and do this:

```sh
git checkout 30839a3
make
git checkout master
make
```

You should get "Time elapsed: ..." for each `make`, and so with this you should be able to give me an indication of how much better it is now. For me, it is from ~3s to ~0.5s. Note, this measures the speed of doing two completions.

**Comment by lervag** [comment]
For me, it is now getting quite fast. I've implemented caching, so after the first time you complete, things should feel much more fluid.

Let me know what you think!

**Comment by lervag** [comment]
Great, I'm happy to hear it! Thanks for making a good reproducible example!
