### ISSUE TITLE
Improve texOnlyMath detection

### ISSUE THREAD

**Issue by Krasjet** [lervag/vimtex#1458]
**Is your feature request related to a problem? Please describe it.**
Superscripts (`^`) and subscripts (`_`) can appear in variable names, formulas in pgfplots environments, and possibly more instances. They will be incorrectly recognized as invalid math formulas (or more precisely the `texOnlyMath` highlight group).
![pic-selected-190826-1744-44](https://user-images.githubusercontent.com/5229241/63725837-83164580-c829-11e9-8e62-2fb27520fd51.png)

**Describe the solution you'd like**
Improve the built-in textOnlyMath matcher to include these cases, though I think the examples here are far from complete.

**Additional context**
Here is the tex file used in the screenshot.

```tex
\documentclass[12pt]{article}
\usepackage{pgfplots}

\pgfplotsset{3d_style/.append style={every non boxed x axis/.append style={x axis line style=-}, every non boxed y axis/.append style={y axis line style=-}, axis z line=none, axis x line=left, axis y line=left, xlabel=$x$, ylabel=$y$,colormap={graykst}{gray(0cm)=(0.35); gray(1cm)=(1)}, tick label style={font=\small}, label style={font=\small}, view={45}{45}}}
\pgfplotsset{compat=1.16}

\begin{document}

\begin{center}
    \begin{tikzpicture}
    \begin{axis}[3d_style]
        \addplot3 [surf,samples=15, domain=-2:2,miter limit=1 ] {0.1*exp((-x^2-y^2))};
        \coordinate (x_axis) at (0,0);
    \end{axis}
    \node at (5.8,3.5) {$f(x,y)$};
\end{tikzpicture}
\end{center}

\end{document}
```

**Comment by lervag** [comment]
Let's focus on the bad math stuff. The issue is that we need to explicitly add syntax rules for each command where `_` and `^` are allowed. For "clear" cases I'll be glad to add support, but if it will require a lot of work I might hesitate.

In this case, are there other commands than `\pgfplotsset` that I should fix?

Note, by the way: I believe pgfplots and tikz allows whitespace, and so you could probably change most of your `_`s to ` `s.

Regarding the `\addplot3 ...`, it would be easier to work with this if I had a clear list of possible commands and command variants where I should allow `^`. Your `addplot3` command is one example, but I assume there will be many more. Thus, to properly handle it, it would greatly help to have a good list of such commands.

**Comment by lervag** [comment]
Vimtex does nothing with `\begin{document}`, and I think it warrants a separate issue if you think we should do something about it.

**Comment by lervag** [comment]
I see; but as mentioned, it would still be very helpful if you could give me a more complete example that includes all of the commands and variants.

It seems the tasks are:
- [ ] Support `_` in `\pgfplotsset` command argument
- [ ] Support `^` in "function argument" to `\addplot* [...opts...] {...}`
