### ISSUE TITLE
Compiling Faliure Until multiple \ll Commands Have Been Issued to Vim

### ISSUE THREAD

**Issue by HenryTwiss** [lervag/vimtex#1459]
I've exported some larger `.tex` files from overleaf and I'm having an issue where when I type `\ll`, vimtex will say the compilation has failed, but if I repeat `\ll` multiple times vimtex will usual succeed and compile the file as expected. For a small test file such as

```
\documentclass{article}

\begin{document}
This is a test.
\end{document}
```

vimtex succeeds in compiling on the first try as suspected. Yet for some larger files, such as the `.tex` file found [here](https://github.com/posquit0/Awesome-CV), I get the type of error described above. By the way, when I exported the `.tex` file linked I just added all the files to a single directory and then opened one of the `.tex` files (say `cv.tex`). More generally, this issue is happening for any `.tex` file I download (even those from Overleaf). Might I need to do something after I download a `.tex` file?

**Comment by 927589452** [comment]
Please provide a minimal vimrc example as described in the bug template, as this might be due to your compiler backend.
A simple test might be to run `pdflatex file.tex` after downloading it; it will probably exit with a failure, as there are files missing (which will be generated by the `pdflatex` run) for the first few times.
You can also have a look at `:help vimtex-compiler` to learn more

**Comment by lervag** [comment]
As @927589452 correctly indicates, your issue is not really with vimtex, but instead with latexmk. That is, I'm not sure we can even call it an issue.

You should learn about how to properly compile LaTeX documents in general, using `pdflatex` and friends. `latexmk`, which is the tool used by vimtex behind the scenes, is a perl script that handles the various programs such as `pdflatex` and `bibtex` to fully compile a LaTeX manuscript. When you type `\ll` in vimtex, you can type `\li` to get information about the exact command line that is run by vimtex. It is something like `latexmk -pdf -file-line-error ... main.tex`.

I'm closing this, as it is not directly related to vimtex.
