### ISSUE TITLE
vimtex not loading when vim starts

### ISSUE THREAD

**Issue by MarioScappini** [lervag/vimtex#1473]
Hello there! I am unable to load vimtex when opening a .tex file. I have followed your instructions by implementing a minimal .vimrc like in #411. But, when I add the following line ` echom b:did_ftplugin` to `ftplugin/tex.vim` I experience the following error: `E121: Undefined variable: b:did_ftplugin`.

Thanks in advance.

**Comment by lervag** [comment]
An important part of the instructions is to also clearly present the minimal files so that I can attempt to reproduce your problem. Dont look at #411, but look at the issue template or the files in [test/issues/template](https://github.com/lervag/vimtex/tree/master/test/issues/template).

There is no way for me to help based on your original description, because I can't possibly reproduce based on that.

**Comment by MarioScappini** [comment]
[latexfile.txt](https://github.com/lervag/vimtex/files/3586847/latexfile.txt)
[vimrc.txt](https://github.com/lervag/vimtex/files/3586848/vimrc.txt)

**Comment by lervag** [comment]
Ok, now you've provided minimal files (I took the liberty of adding the content explicitly instead of just attaching as files). But what about the steps required to reproduce the issue?

Here is an example of what I want from you:

1. Put the minimal.tex and minivimrc files in a folder `test`.
2. In a terminal in that folder, do: `vim --servername VIM -u minivimrc minimal.tex`.
3. Do `:VimtexInfo`.

    - Expected: Display Vimtex information.

    - Observed: `E492: Not an editor command: VimtexInfo`.

**Comment by MarioScappini** [comment]
Nevermind, I found the reason why it wasn't working. I referenced the wrong folder in the .vimrc file.
Sorry for wasting your time. Have a nice day
