### ISSUE TITLE
Change xdg-open to gio

### ISSUE THREAD

**Issue by concatime** [lervag/vimtex#1485]
I think you should change `xdg-open` to `gio open`, which is more available across distros.
From Archlinux, glib2 is a “Low level core library”, and 284 packages depend on it, against 58 for xdg-utils.

**Comment by lervag** [comment]
Hmm. I think this warrants some more discussion. I didn't know about `gio` before. To me, it seems `xdg-open` works for (almost) everyone, regardless of distribution. I can not remember anyone having complained about it before. So if I should change the default to `gio open`, then I want to be very sure it is equally or more ubiquitous.

**Comment by lervag** [comment]
I've tested on the machines available to me right now. This is a **very** non-scientific test; I simply ssh'ed into various machines I have access to/control and checked if the tools were available. The results are:

Distribution                  | `gio` | `xdg-open`
------------------------------|-------|-----------
OpenSUSE Leap 15.0            | Yes   | Yes
Arch Linux                    | Yes   | Yes
CentOS Linux release 6.9      | No    | No
CentOS Linux release 7.5.1804 | Yes   | Yes
Ubuntu 12.04                  | No    | Yes

As mentioned, this is not a very good test. But at least it gives a small indication that `xdg-open` is not less available.

**Comment by concatime** [comment]
1. Ubuntu 12.04 reached End Of Life, so it should not be used as a reference.
2. On Archlinux, you way end-up w/o xdg-utils depending on your installation, so you cannot generalize.
3. On Archlinux, `glib2` is under repo. Core, against Extra for xdg-utils.
4. On my VoidLinux system, xdg-utils is only required by cups, against 73 packages for glib.

**Comment by lervag** [comment]
I guess my real point was not so clear. My point is that `xdg-open` seems a sensible choice for a default setting, and that there has never really been any reason to change it. No complaints, things work well for most people.

If I understand correctly, you propose me to change it to `gio`, because

1. `gio` is "more available", and
2. more packages depend on its existance.

Perhaps you are right, but I don't want to change unless I'm quite certain. You did not really provide any proof of 1. And so I just checked all systems I had at hand, and that did not really prove your point. (Although I agree, Ubuntu 12 is a bad reference.)

To me, changing this default could mean that I risk new issues due to people missing `gio`. You claim in your point 1 that this will not be the case. Do you have anything solid to back up this claim?

**Comment by concatime** [comment]
> Do you have anything solid to back up this claim?

Tomorrow, I will check for different versions of ubuntu and fedora. Except for Arch/Voidlinux, I cannot fully back up my claim.

**Comment by lervag** [comment]
> Tomorrow, I will check for different versions of ubuntu and fedora.

Thanks. Looking forward to hearing an update on this.

> Except for Arch/Voidlinux, I cannot fully back up my claim.

Ok. Is there perhaps some texts on this, e.g. Arch wiki, VoidLinux wiki/forums, documentations for gio and xdg-utils?

**Comment by lervag** [comment]
Some possibly relevant links:
- https://askubuntu.com/questions/1046400/what-should-be-used-instead-of-the-deprecated-gnome-open-in-ubuntu-18-04/1046404
- https://github.com/github/hub/issues/1473#issuecomment-303656214

To me, it seems `xdg-open` is recommended.

**Comment by concatime** [comment]
Relevant part:
> after it was deprecated, xdg-open has been updated to use gio open.

```sh
grep -r gio /usr/bin/xdg-open
    if gio help open 2>/dev/null 1>&2; then
        gio open "$1"
    if gio help open 2>/dev/null 1>&2; then
        gio open "$1"
    if gio help open 2>/dev/null 1>&2; then
        gio open "$1"
    elif gio help open 2>/dev/null 1>&2; then
        gio open "$1"
```
So gio is more generic.

**Comment by lervag** [comment]
No, I still think you are wrong. `xdg-open` is written to work with a lot of different desktop environments (DEs), and as such, it relies on different tools depending on the system. I don't know the details of this, but my links above clearly recommend that one rely on `xdg-open` and not `gio open`.

To be more specific, `xdg-open` rely on defining a lot of functions like `open_gnome()`, which looks like this:


```sh
open_gnome()
{
    if gio help open 2>/dev/null 1>&2; then
        gio open "$1"
    elif gvfs-open --help 2>/dev/null 1>&2; then
        gvfs-open "$1"
    elif gnome-open --help 2>/dev/null 1>&2; then
        gnome-open "$1"
    else
        open_generic "$1"
    fi

    if [ $? -eq 0 ]; then
        exit_success
    else
        exit_failure_operation_failed
    fi
}
```

I think this shows that `gio open` is more specific, not more generic. `xdg-open` allows to fall back to other methods/programs. Further, for other DEs, such as Deepin, it does not rely on `gio open`:

```sh
open_deepin()
{
    if dde-open -version >/dev/null 2>&1; then
        dde-open "$1"
    else
        open_generic "$1"
    fi

    if [ $? -eq 0 ]; then
        exit_success
    else
        exit_failure_operation_failed
    fi
}
```

I think this all indicates that `xdg-open` is a better bet than `gio open`, since it is built to work on a lot of differens DEs that might or might not have `gio open`. When I also account for the fact that I've never seen an issue related to someone not having `xdg-open` available, I think it feels wrong to change the default.

Note, you can change the setting if you prefer `gio open`, see `:help g:vimtex_view_general_viewer`.

**Comment by concatime** [comment]
```
Selected viewer is not executable!
- Selection: gio open
```

**Comment by lervag** [comment]
There was a bug in the init code for the general viewer. Should be fixed now.

**Comment by concatime** [comment]
I think it’s my fault:
```vim
let g:vimtex_view_general_viewer = 'gio'
let g:vimtex_view_general_options = 'open'
```
