### ISSUE TITLE
Section folds and non-ASCII characters

### ISSUE THREAD

**Issue by lahwaacz** [lervag/vimtex#149]
The text for closed section folds is formatted as the section title padded with spaces to a fixed width and dashes until the end of line. The problem is that the calculation probably involves byte-length instead of character-length, which results in bad visual effect when non-ASCII characters are present in the titles, for example:
```
  9 \begin{document}
 10       Section heading                                                          -------------------------
 12       Section heading ě                                                       --------------------------
 14       Section heading ěě                                                     ---------------------------
 16       Section heading ěěě                                                   ----------------------------
 18       Section heading ěěěě                                                 -----------------------------
 27 \end{document}
```
Is it possible to calculate display length instead of byte length?

**Comment by lervag** [comment]
Actually, the formatting should be simply the section title with spaces until end of line. This works as expected for me in both vim and gvim. I don't really see where the dashes might come from...

**Comment by lahwaacz** [comment]
Strange, I can reproduce it even with the [minimal vimrc](https://github.com/lervag/vimtex/issues/142#issuecomment-88802750). Do you have sufficiently wide window for testing? I think that you need [more than about 80 chars](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/fold.vim#L136) to see the dashes.

**Comment by lervag** [comment]
Yes, I tried to widen the window, both in vim and in gvim. And based on the foldtext function, I get the expected behaviour. The foldtext function ends with
```vimL
return printf('%-5s %-' . nt . 's', level, title)
```
where `nt = 73` is a constant. Perhaps you can figure out something by inspecting the foldtext function yourself? See `autoload/vimtex/fold.vim` and the function `vimtex#fold#text()`.

What is the value of `&foldtext` (just making sure you are actually using the vimtex function)?

**Comment by lahwaacz** [comment]
`&foldtext` is indeed `vimtex#fold#text()`. I think `printf` might be the problem, in [this comment](http://stackoverflow.com/questions/4964772/string-formatting-padding-in-vim#comment-5542190) it is recommended for padding only ASCII text.

Are there some system/vim variables in play that e.g. define dash as the default character to be repeated after the `foldtext()`? Do you have folds in other filetypes also padded with spaces? For me it's always dashes.

**Comment by lervag** [comment]
Yes, sorry, you are right: With minimal vimrc the problem is reproduced. I use `set fillchars=fold:\ `, which removes the dashes.

Unfortunately, `fillchars` is a global option, so setting it does not seem like the best approach. Alternatively, I could add spaces to the end of the fold text lines..? Do you have a suggestion?

**Comment by lahwaacz** [comment]
That's an interesting option, I think I'll use `set fillchars=fold:\ ` globally so thanks for the tip!

As for `vimtex#fold#text()`, I think that since dashes starting from column 80 until the end of line is not the desired visual effect, you can either add spaces to the end of line or add exactly one space as standard `foldtext()` does and mention `fillchars` in the docs.

**Comment by lervag** [comment]
Thanks, I agree and made the necessary change.
