### ISSUE TITLE
restore current &errorformat after single shot compilation

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#1496]
To use `:compiler ...`that sets a value of `&makeprg` and in particular of `&errorformat` alongside `vimtex`, it were convenient if vimtex set `&errorformat` only if continuous compilation is enabled, but, if instead  single shot compilation is used, sets `&errorformat` to the appropriate value, but then reverts to the value before compilation. 

This way,  `:compiler ...` for example `lacheck` to check the syntax, or `langtool`, to proofread, do not override the value of `&erroformat` set by `vimtex`. 

At this occasion, how about setting `b:current_compiler` and `&makeprg` to the  compiler `vimtex` uses?

**Comment by lervag** [comment]
Before I comment on your actual suggestion, I just want to clarify (if only for the sake of discussion): the quickfix feature is a separate feature that is not connected to the compiler. Instead, it has its own family of commands, mappings and configuration. The main command is `VimtexErrors`, which will use the configured `g:vimtex_quickfix_method` to parse the log files and fill/open the quickfix buffer.

So, to your suggestion: I immediately agree that you have a point. The present implementation is based on stuff that was implemented a very long time ago. Back then I was not aware of the compiler feature of Vim.

So, I think the correct approach here is to update the quickfix implementation so that it never overwrites the `errorformat` setting except intermediately. This would make vimtex compatible with any usage of the compiler feature.

What do you think?

Other people who might have an opinion: @kiryph @clason

**Comment by Konfekt** [comment]
> So, I think the correct approach here is to update the quickfix implementation so that it never overwrites the errorformat setting except intermediately

Agreed, that sounds cleanest. I admitted an exception for  continuous  compilation, but apparently there's no such need.

**Comment by lervag** [comment]
Ok, I've pushed an update for this now. It is easy to revert should it lead to any unexpected issues (which, obviously, I don't expect).

**Comment by Konfekt** [comment]
Looks good. Thank you!
