### ISSUE TITLE
Package completion hangs on Windows/MiKTeX

### ISSUE THREAD

**Issue by alexpolozov** [lervag/vimtex#1497]
**Issue**

On the latest MiKTeX on Windows, `kpsewhich --var-value TEXMFHOME` now returns an empty string (see MiKTeX/miktex#272). Because of this, package completion in vimtex after `\usepackage{` and its relatives simply hangs the whole Vim. As I understand, `s:get_texmf_candidates` in [complete.vim](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/complete.vim) returns an empty list, which for some reason causes the UI to hang. I haven't traced further whether this is due to vimtex, deoplete, or nvim-qt.

Currently, I resolved the issue by defining an environment variable that points to my actual TEXMFHOME, and patching `complete.vim`:
``` viml
  let l:texmfhome = get(vimtex#kpsewhich#run('--var-value TEXMFHOME'), 0, 'XX')
  if l:texmfhome == 'XX'
    let l:texmfhome = $TEXMFHOME
  endif
```
I'm happy to make a PR, but unsure if this is an acceptable solution for vimtex. Maybe we could create a vimtex config variable for that purpose or something like that?

**Comment by lervag** [comment]
Interesting issue. I think your solution is mostly spot on, and I've pushed some commits that I think should solve the issue. Very much based on your suggestion. Thanks!

**Comment by alexpolozov** [comment]
Thanks @lervag! One small thing: this environment variable is not set by default, so perhaps we should document it in vimtex docs.

**Comment by lervag** [comment]
Hmm. Not sure; this is not really changing anything for any users, except adhering to a users environment. If I understand things correctly (I might not), doing `kpsewhich --var-value TEXMFHOME` will be equivalent to the value of `$TEXMFHOME` if it exists. Thus, the recent update would only allow things to work for e.g. you when the `kpsewhich` method does not work.

The recent commit also fixes the issue with an empty `l:texmfhome` variable.

So, I'm not sure if we need to update/add to the (already very large) docs. But feel free to convince me otherwise! Also, I would be happy to get a suggestion for the update, if you still think I should update.

**Comment by alexpolozov** [comment]
Thing is, right now package completion will just silently fail for everyone on Windows. I'm not sure if it fails or hangs with your new fix (hopefully returning `[]` explicitly fixes the hang, but I haven't pulled and verified it yet).
MiKTeX does not define `$TEXMFHOME` either, it's a custom environment variable I invented. Currently, if one discovers a failing/hanging package completion, one would need to google this issue to discover how to fix it. I suggest putting it in the troubleshooting FAQ, that way the fix will at least be more discoverable.

**Comment by lervag** [comment]
> Thing is, right now package completion will just silently fail for everyone on Windows. I'm not sure if it fails or hangs with your new fix (hopefully returning [] explicitly fixes the hang, but I haven't pulled and verified it yet).

My point was that my recent commit should fix it, and aas such, completion should not fail on Windows. Worst case now is that completion might not catch locally installed packages. I think this is in any case a minor issue.

Feel free to suggest an update to the docs, e.g. in the faq section. However, note that it my comment above still holds (I think): things now work mostly as expected on Windows, but if the `TEXMFHOME` is not detected, and not set, then locally installed packages will not be completed.

**Comment by krishnakumarg1984** [comment]
@lervag  Even with the latest update, package completion hangs on Windows for me. I suspect that most users would prefer just a simple cross-platform config file. I wonder how texstudio does things correctly?

**Comment by lervag** [comment]
Yeah, sorry, I don't use Windows and have no idea how Texstudio does its things. So it is very difficult to help with this matter.

However, I am very open to discuss and accept pull requests or suggestions for improvements. So if you or anyone else who use Windows are able to find ways to reduce hangs and/or improve efficiency, then I'm definately happy to discuss and update vimtex!

**Comment by krishnakumarg1984** [comment]
@lervag Sorry, I didn't mean it in any specific way. I was just wondering out loud about `texstudio', that's all. 

Could we reopen this issues for @alexpolozov  or other users to respond? I am not certain the issue was resolved for them. I am unsure of running system call's like `kpsewhich` from `vim` since they tend to slow things down a lot.

**Comment by lervag** [comment]
> @lervag Sorry, I didn't mean it in any specific way. I was just wondering out loud about `texstudio', that's all.

No problem.

> Could we reopen this issues for @alexpolozov or other users to respond? I am not certain the issue was resolved for them. I am unsure of running system call's like kpsewhich from vim since they tend to slow things down a lot.

Yes, I try not to call `kpsewhich` so often if not necessary. For me, things work quite well and fast on Linux.

I am not sure if there is a good reason to keep the issue open, because there is already a lot of discussion that makes things "confusing" for potential helpers. I think it would be better if you wrote a new issue with a consise description. Then I could mark that issue with a tag like "help wanted", and we could let it stay open for anyone to pitch in.

**Comment by krishnakumarg1984** [comment]
@lervag 

>My point was that my recent commit should fix it, and aas such, completion should not fail on Windows. Worst case now is that completion might not catch locally installed packages. 

I just have a (perhaps misunderstood) feeling that maybe this issue was closed without a confirmation from the person who opened the issue. 

Please forgive if the above message comes across as needlessly challenging. I just wonder the point of repeating these points with a separate issue # when we could simply reopen this and raise `RFC`?

**Comment by lervag** [comment]
But that person (@alexpolozov) never objected or replied to my last comment.

The point of repeating the point in a new issue is to lower the bar for anyone who might want to help. Asking someone to first read several pages of comments is not the easiest way to get them to help. By creating a new issue with a short and concise description, perhaps a link to old, related issues, will make it much easier for someone to get into the matter and help.
