### ISSUE TITLE
vimtex viewer is not executable! and other errors

### ISSUE THREAD

**Issue by IbnSaeed** [lervag/vimtex#151]
Hello

I am using Vim 7.4 MS-Windows 64 1-691 patch

I am trying our vimtex and i have it enabled and i using it along side xuhdev/vim-latex-live-preview

I get the following error messages when opening a .tex file.

```
Error detected while processing function vimtex#init .. vimtex#view#init.. 146:
line    2:
vimtex viewer is not executable
line 3:
g:vimtex_view_general_viewer =
```

Here is what i have in my .vimrc
```
let g:tex_flavor = "latex"
```

**Comment by lervag** [comment]
Hi,

first: I don't know how well vimtex behaves with other latex plugins. Is there a reason you want to keep it alongside vim-latex-live-preview?

Next: The error message should already give a hint. The problem is that you have not set defined a viewer. There is no default viewer defined in Windows (if you know a general viewer command similar to `xdg-open` on linux or `open` on OSX, please let me know). Thus you need to set the viewer explicitly with the viewer options. Please read the documentation, e.g. `:h g:vimtex_view_general_viewer` and `:h vimtex-view`.

If you want to use vim-latex-live-preview, then perhaps the suitable option would be to disable vimtex's view functionality altogether with `let g:vimtex_view_enabled = 0`?

**Comment by IbnSaeed** [comment]
Thanks

I just need the vim-latex-live-preview for live previewing of the pdf file as i make changes. Does vimtex support this, if yes, i can disable the other plugin.

**Comment by IbnSaeed** [comment]
I tried sumatra pdf in the viewer, but same errors. 

I use the following in vim-latex-live-preview plugin

```
let g:livepreview_previewer = 'SumatraPDF -reuse-instance -inverse-search "gvim -c \":RemoteOpen +\%l \%f\""'
```

and it works fine, but the same is not working for vimtex

```
let g:vimtex_view_general_viewer = ' 'SumatraPDF -reuse-instance -inverse-search "gvim -c \":RemoteOpen +\%l \%f\""'
```

**Comment by lervag** [comment]
Vimtex uses [latexmk](http://users.phys.psu.edu/~collins/software/latexmk-jcc/) to continuously update the PDF file whenever you save the `tex` file. This is not live preview, but in my opinion it is preferable, especially on large projects.

I know people are using vimtex on windows with [sumatraPDF](http://www.sumatrapdfreader.org/free-pdf-reader.html), which should work well.

I've never used [vim-latex-live-preview](https://github.com/xuhdev/vim-latex-live-preview) myself, but according to the README file only UNIX-like systems are supported.

**Comment by lervag** [comment]
I once again urge you to read the documentation!

Regarding your attempted setting, it contains a syntax problem with two `'`s in the beginning. Further, the command `:RemoteOpen` is not a vim or vimtex command, rather it is most probably a vim-latex-live-preview command.

However, as you could have read from the documentation, to use SumatraPDF, please use `let g:vimtex_view_method = 'sumatrapdf'`.

**Comment by IbnSaeed** [comment]
Thanks, the double ' was a copy paste problem. 

you can close this issue now.

**Comment by lervag** [comment]
No problem! Please don't hesitate to report bugs and problems and/or feature requests (although, it is as I've mentioned recommended to read the docs first). :)
