### ISSUE TITLE
Cannot Switch Pane In Split Mode using <C-W><arrow key>

### ISSUE THREAD

**Issue by eggsbenjamin** [lervag/vimtex#1512]
**Issue**

When in splitmode I cannot easily switch between panes using <C-w><arrow key> as I normally would. It _occaisionally_ works once after entering the command multiple times in quick succession. I can move between panes using <C-w><hjkl> though.

Open a tex file with and then another file of any type in split mode. Enter `<C-w><direction to other pane>`

**minimal.vim**

  ```vim
set mouse=a
set clipboard=unnamed
set statusline=%<%f%h%m%r%w%y%=%l/%L,%c\ %P\ \|\ %n
set nocompatible 
set number
set ruler
set showcmd
set relativenumber
set nowrap
set backspace=2
set shortmess+=c
set tabstop=2
set shiftwidth=2
set expandtab
set rtp+=~/.vim/bundle/Vundle.vim
set foldmethod=indent
set foldlevelstart=99
set directory=~/.vim/tmp " store all swap files here
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o " disable auto-commenting
filetype off 
syntax enable
autocmd FileType yaml setl indentkeys-=<:> " diable auto indent for yaml files
  ```

**Commands/Input**

**Observed Behaviour**

Cannot easily move between panes using `<C-w><arrow key>`

**Expected Behaviour**

Should be able to move between panes easily using `<C-w><arrow key>`

**Output from VimtexInfo**

**Comment by lervag** [comment]
This is not a proper issue description. Your supplied minimal vimrc file does not load vimtex. Are you using the package system, so that it is loaded automatically?

I understand it can be difficult to understand how these things all work. I recommend to start with something like this:

A minimal vimrc file, call it `minimal.vim`:

```vim
set nocompatible
let &rtp = '/path/to/vimtex,' . &rtp
let &rtp .= ',/path/to/vimtex/after'
filetype plugin indent on
syntax enable

let g:tex_flavor = 'latex'
" Other options go here if necessary
```

A minimal LaTeX file, `minimal.tex`:

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

Put both files in the same folder, then do `vim --servername vim -u minimal.vim minimal.tex`. This should load your minimal settings and the minimal file. From here, try to reproduce your issue. If you can't then start adding your options and configurations until you can reproduce it.

**Comment by lervag** [comment]
I'm closing. Feel free to reopen if you can provide more relevant information as indicated in my previous comment.
