### ISSUE TITLE
By default, vimtex should override  `wildignore` (or provide an option to do so) for certain file extensions 

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1518]
One wouldn't typically edit binary files in Vim, atleast without the `-b` command-line option.  This typically means it is desirable to set `set wildignore+=*.pdf` and other file extensions in one's `vimrc`.

However, for `LaTeX` projects, it is hard to imagine a case where this would be relevant. Hence, this feature request proposes that if any of the packages `graphics`, `graphicx`, or` grffile` is detected, `vimtex` does a  `set wildignore-=*.pdf` for all `*.tex` files for easy inclusion of `pdf` graphics from the autocomplete popup/plugin being used.

**Comment by lervag** [comment]
I think you are attacking this from the wrong side. It is better (at least IMHO) to be explicit on what exactly does not work as expected. E.g., if the problem here is related to completion of filenames for `\includegraphics`, then I relatively recently submitted a fix where the `wildignore` option is not relevant.

So, could you please be explicit about what exactly does not work as you expect?

**Comment by lervag** [comment]
I'll close this, but feel free to reopen with more details if you have the time/interest!
