### ISSUE TITLE
Vimtex ignores my shell-escape option 

### ISSUE THREAD

**Issue by RaghuNaik** [lervag/vimtex#1521]
My _vimrc option for latexmk is as below in Windows 10

```vim
let g:vimtex_compiler_latexrun = {
        \ 'options' : [
        \   '-pdf' ,
        \   '-shell-escape' ,
        \   '-verbose' ,
        \   '-file-line-error',
        \   '-synctex=1' ,
        \   '-interaction=nonstopmode' ,
        \ ],
        \}
```

I get a compile error:

```vim
Package minted Error: You must invoke LaTeX with the -shell-escape flag.
```

Here is the relevant vimtex info:

```vim
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
    job: process 475580 run
    cmd: set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e "$success_cmd = 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = 'echo vimtex_compiler_callback_failure'" "test.tex"
```
Vimtex seems to be ignoring the shell escape option. 

Would appreciate any help. 

Raghu

**Comment by lervag** [comment]
I think you've mistaken `latexrun` with `latexmk`. In case you meant to use the latter, then change your option from `g:vimtex_compiler_latexrun` to `..._latexmk`.

Further, you should remove the `-pdf` option, since this is specified by the engine option (`g:vimtex_compiler_latexmk_engines`). This was done in order to become more flexible with regard to choosing between e.g. `lualatex`, `xetex`, etc.

If you want to use `latexrun`, then you should use the option `g:vimtex_compiler_method`.

**Comment by RaghuNaik** [comment]
Yes I did. Thank you for pointing that out. I knew I was screwing up somewhere.  New to Vimtex. 

It runs fine now. 

Regards.

**Comment by lervag** [comment]
No problem, happy it works!
