### ISSUE TITLE
Using vimtex with vim-latex breaks `\lv`, `\ll`

### ISSUE THREAD

**Issue by nkakouros** [lervag/vimtex#1522]
I am using `vimtex` as my primary latex plugin for vim. I am also using `vim-latex` for its snippets. I have disabled the tilde shortcuts of `vimtex` to use those of `vim-latex`.

I found that loading both `vim-latex` and `vimtex` breaks `vimtex` mappings (at least `\lv` and `\ll` that I use). The issue is that typing these mappings opens my pdf viewer anew, instead of scrolling to the pdf position.

I fount that [this line of vim-latex's code](https://github.com/vim-latex/vim-latex/blob/00f344033d5ab22c2cb48f5a01954f0a2aa10881/ftplugin/latex-suite/compiler.vim#L916) is to blame. The only way I found to overcome this is to have `let b:Tex_doneCompilerMaps = 1` in `after/ftplugin/tex.vim` to kindof disable this `vim-latex` feature. 

I just thought I would drop this here in case anyone stumbles upon this or anyone has a better solution.

**Comment by lervag** [comment]
Thanks for mentioning these things.

Note, though: I strongly recommend that you use a plugin like Ultisnips instead of `vim-latex` for the snippet support. These are more general and allow snippets for any kind of language, not just LaTeX. One can install a premade set of snippets or make ones own set.

It should also be clear that vimtex does not really support working alongside another LaTeX filetype plugin (such as `vim-latex`). There may be more conflicts than the ones you've seen, and I'm not interested in making vimtex play nice in these situations.
