### ISSUE TITLE
Example of VimtexCountWords in Status Line

### ISSUE THREAD

**Issue by norbert-op** [lervag/vimtex#1530]
Can you please give an example in the documentation for putting the output of `:VimtexCountWords` in the status line? I experimented with it but couldn't figure out the syntax. I'd like to have the word count displayed and update whenever I run the function.

**Comment by lervag** [comment]
You can use the `vimtex#misc#wordcount(...)` function as is already documented. Use it in your statusline as you would use any other function (see `:help 'statusline'` for how to do this).

Note, though: I've never tested it until now, and I observe some flickering of the cursor in Neovim. I'm not sure why, it might be due to the system calls to `texcount`. Personally, I don't really see the use of adding this to your statusline, though; I would instead make a mapping to make it easy to show the word count when you're interested in it. Of course, thats MHO.

Although, when I read your issue again, it seems you want the word count to only update whenever you run `:VimtexCountWords` manually. This is currently not possible, sorry. It seems to "edge case" for me to implement also.

**Comment by norbert-op** [comment]
Thanks for looking at it, I'll just use a mapping.
