### ISSUE TITLE
Base file not being correctly set for \input files

### ISSUE THREAD

**Issue by FreddieOliveira** [lervag/vimtex#1533]
**Issue**
When the `\documentclass{}` is `\input`ed into the main.tex instead of writing it directly in it, the base file for all subsequents  `\input`ed files is not set to the main.tex automatically, thus preventing forward searches to work (failing with `vimtex: Viewer cannot read PDF file!` error). One needs to manually put `%! TEX root = ../main.tex` in the sub.tex first line or create the `main.tex.latexmain` file.

To reproduce the problem consider the following directory structure:
 .
├── main.tex
├── preambule.tex
└── **dir**
                        └── sub.tex

and the following files contents:

**preambule.tex**

  ```tex
  \documentclass{article}
  ```

**main.tex**

  ```tex
  \input{preambule.tex}
  \begin{document}
  \input{dir/sub.tex}
  \end{document}
  ```

**sub.tex**

  ```tex
  \chapter{Hello World}
  Some text here...
  ```
**Observed Behaviour**
When running `:VimtexInfo` inside sub.tex window the oberserved base file is **sub.tex**

**Expected Behaviour**
When running `:VimtexInfo` inside sub.tex window the base file should be **main.tex** in the same way it works when not `input`ing the preambule and writing the `\documentclass{article}` directly in the main.tex

**Comment by lervag** [comment]
Yes, this is a known limitation. See `:help vimtex-multi-file` for the description of how vimtex handles multi file projects. There are several ways of detecing the main file. The "default" method is an automatic, recursive search. From the docs:

>   If no other method provides an appropriate candidate, then the recursive
  search detects the main LaTeX file by searching for a file in the current
  and parent directories that includes the present file and has the
  `\documentclass` line.

When I implemented this, I found it difficult to handle the situation that you are describing here. I could not find a robust method of properly detecting this case unless I defined `preambule.tex` as the main file. But that would be wrong, because the entire point of this proposed LaTeX structure is to let different "main" files use the same preamble header.

I still think this sounds too difficult to properly handle, and since there are alternative ways to handle it that does work well, I propose that you use them:

1. Use the `TeX root` directive, or
2. Use the `.latexmain` specifier.

**Comment by FreddieOliveira** [comment]
Thank you for the plugin and your response. It's totally understandable the not implementation for this limitation. Currently I'm using `.latexmain` specifier and it's working great.

**Comment by lervag** [comment]
> But I still can't understand why this problem doesn't occur when using \subfile. If, instead of \inputing the sub.tex I \subfile it, then its base is correctly set to main.tex

You did not mention this before. Could you make an example of this as well?

**Comment by FreddieOliveira** [comment]
Consider the same directory structure:
 .
├── main.tex
├── preambule.tex
└── **dir**
        └── sub.tex

and the following files contents:


**preambule.tex**

  ```tex
\documentclass{article}
  ```

**main.tex**

  ```tex
\usepackage{subfiles}
\input{preambule.tex}
\begin{document}
\subfile{dir/sub.tex}
\end{document}
  ```

**sub.tex**

  ```tex
\documentclass[main.tex]{subfiles}
\begin{document}
\chapter{Hello World}
Some text here...
\end{document}
  ```

When running `:VimtexInfo` inside sub.tex window the observed base file is **main.tex** as it should be.

Doing some tests I concluded that it will recursively look for a file with the same name that's inside the `\documentclass[-->main.tex<--]{subfiles}`. If that file exists, no matter its content (it can even be a blank file), then the base for sub.tex will be set to it. If the file doesn't exist, then the base will be the `sub.tex`. So, it's clear that sub.tex isn't smart enough to actually know who `\subfile`d it, it just set it's base to its `\documentclass` file, no matter if that file `\subfile`d it or not.

This is similar to using the `%! TEX root` directive. The .tex with this directive will just set its base to that file, no matter if that file `\input`ed it or not. With the difference that `%! TEX root` cannot recursively search backwards (child directories).

**Comment by lervag** [comment]
> Doing some tests I concluded that it will recursively look for a file with the same name that's inside the \documentclass[-->main.tex<--]{subfiles}. If that file exists, no matter its content (it can even be a blank file), then the base for sub.tex will be set to it and to sub.tex (there will be two vimtex project entries). If the file doesn't exist, then the base will be solely sub.tex. So, it's clear that sub.tex isn't smart enough to actually know who \subfiled it, it just set it's base to its \documentclass file, no matter if that file \subfiled it or not.

Yes and no. When you enter `sub.tex` in this case, vimtex recognizes the `\documentclass[<file>]{subfiles}`, where `<file>` specifies which file is the main file. In your example, you specify `<file>` relative to the parent directory `.` as simply `main.tex`. In order to compile `sub.tex` as a sub file, you need to compile it from the directory of `main.tex`. If you try to compile from `./dir`, i.e. with

```sh
cd dir
latexmk sub.tex
```

Then you get an error that `main.tex` is not found. Vimtex works as expected in that you can use `\ls` to change "focus" to the subfile, and you can use `\ll` to compile only the subfile. This works seamlessly. It would also work if you use `../main.tex`.

The heuristic that is used by vimtex is thus explained by the comment in the code:

```vim
        " Try specified path as relative to the project main file. This is
        " difficult, since the main file is the one we are looking for. We
        " therefore assume that the main file lives somewhere upwards in the
        " directory tree.
        let l:candidate = findfile(l:filename, '.;')
        if filereadable(l:candidate)
          let s:subfile_preserve_root = 1
          return fnamemodify(candidate, ':p')
        endif
```

The `s:subfile_preserve_root` is used to make sure that changing between the main file and subfile works as expected.

> ... So, it's clear that sub.tex isn't smart enough to actually know who \subfiled it, it just set it's base to its \documentclass file, no matter if that file \subfiled it or not.

So, to wrap things up: This particular example shows that vimtex does "the right thing" in a clearly very challenging case.

Note, though: The admittedly unexpected behaviour that `sub.tex` will also select a `main.tex` that does not include itself is a bug which I'm fixing now.

> This is similar to using the %! TEX root directive. The .tex with this directive will just set its base to that file, no matter if that file \inputed it or not. With the difference that %! TEX root cannot recursively search backwards (child directories).

Yes, this is how this directive works. It points to a file which is chosen regardless of if it exists or not. If there is an ambiguity, it should show a menu for choosing which candidate to use.

**Comment by lervag** [comment]
Update: Now `sub.tex` should no longer allow main files that do not directly include it.

**Comment by FreddieOliveira** [comment]
Perfect! Thanks 👍

**Comment by lervag** [comment]
No problem:)

**Comment by FreddieOliveira** [comment]
Oops, actually it's not perfect yet!

There are two things in the function `file_reaches_current` declared in file `autoload/vimtex/state.vim` that's preventing it to correctly check if the current file is really being `\subfile`d by the
`\documentclass[<file>]{subfiles}`

First one is in line 430:

```vim
if expand('%:p') ==# l:file    
      \ || s:file_reaches_current(l:file)    
  return 1    
endif    
```

It is comparing the absolute path of the current \subfiled folder (`expand('%p')`) with `l:file`. But `l:file` may be an absolute path, as well as a relative path. For example, if i have `\subfile{dir/sub.tex}` inside my main.tex, that if condition will be expanded to

```vim
if '/home/user/Documents/dir/sub.tex' ==# './subfile/sub.tex'
```

which will be false, even though the main.tex is really subfiling the sub.tex.

The second one is in line 422:

```vim
if !vimtex#paths#is_abs(l:file)    
  let l:file = fnamemodify(a:file, ':h') . '/' . l:file    
endif
```

If the l:file is not a absolute path, then prepend a `./` on it. This is unnecessary and may add complexity to the code.

I made a pull request which I believe fixes the issue. Let's move the discussion to there

**Comment by lervag** [comment]
> I made a pull request (#1538) which I believe fixes the issue. Let's move the discussion to there

Great, thanks!
