### ISSUE TITLE
ominifunc is not set for \cite 

### ISSUE THREAD

**Issue by dfguan** [lervag/vimtex#1550]
Hi Lervag,

Thanks for supplying such a nice tool. 

I have a question about how to cite references from a sub file, here is the file structure:
```
|-- main.tex
|-- reference.bib
|-- body
    |-- chapter1.tex
```
In the main.tex, I wrote:
```
\begin{document}
input{body/chapter1}
\bibliographystyle{plain}
\bibliography{reference}
\end{document}
```

everything works fine when I add citation in the main.tex, however when I try to cite a reference in chapter1.tex, I got this error: "ominifunc is not set", is there anything I need to set to solve the issue? Hope you can help me. 

Thanks in advance.  

Dengfeng

**Comment by lervag** [comment]
I think this is because the included file is not properly recognized as a `tex` file. Try to add `let g:tex_flavor = 'latex'` in your vimrc file. See also `:help g:tex_flavor`. This is not really vimtex specific, and theres a comment about this in the vimtex docs as well at the end of `:help vimtex-comment-internal`.

**Comment by dfguan** [comment]
Cool, that works for me. Thanks! Dengfeng.
