### ISSUE TITLE
Nested syntax highlighting for literate haskell

### ISSUE THREAD

**Issue by 4e554c4c** [lervag/vimtex#1570]
Hi! I've been trying to write literate haskell with vimtex and have been running into a few minor issues.

One of these is it would be nice to have syntax highlighting for haskell and tex at the same time.
I know it is possible to get syntax highlighting with packages such as lstlistings and minted, however, the haskell compiler only processes literate haskell in a certain way (it only compiles code from the `code` environment).

It would be nice to be able to give nested highlighting to arbitrary environments such as `code` or `spec` so I could work with those restrictions without any preprocessing.
e.g. consider the following file which ghc can compile and run
```tex
\usepackage{minted}
\newenvironment{code}{\VerbatimEnvironment\begin{minted}{haskell}}{\end{minted}}
\begin{document}
\begin{code}
main = pure () :: IO ()
\end{code}
```

**Comment by lervag** [comment]
Do I understand correctly that:

i) You are talking generally about `.tex` files similar to the one you present. The literate part is about getting the Haskell compiler to only compile anything within the `\begin{code}...\end{code}` blocks?

ii) What you want is to improve the `minted` support so that it can properly highlight the `\begin{code}...\end{code}`.

If I do understand this correctly, then I think you can already get this. Check out the minted documentation about the `newminted` macro.

**Comment by lervag** [comment]
Do I understand correctly that:

i) You are talking generally about `.tex` files similar to the one you present. The literate part is about getting the Haskell compiler to only compile anything within the `\begin{code}...\end{code}` blocks?

ii) What you want is to improve the `minted` support so that it can properly highlight the `\begin{code}...\end{code}`.

If I do understand this correctly, then I think you can already get this. Check out the minted documentation about the `newminted` macro.

Example:

```tex
\documentclass{article}
\usepackage{minted}
\newminted[code]{haskell}{}

\begin{document}

\begin{code}
  main = pure () :: IO ()
\end{code}

\end{document}
```

**Comment by 4e554c4c** [comment]
You are correct!

Sorry, I seem to have been misled by outdated haskell documentation and not knowing that vimtex worked this way.

Thank you very much!

**Comment by lervag** [comment]
No problem, I'm happy it works!

**Comment by 4e554c4c** [comment]
By the way,
There is another issue I am having related to #1537 where it is highlighting these `\begin{code}...\end{code}` blocks as haskell, but I am not sure if it is an issue with my syntax highlighter and not with vimtex.
e.g. see the difference in the two opening environments
![2020-01-23-150255_grim](https://user-images.githubusercontent.com/4743113/73027876-8b32db00-3df1-11ea-8f82-0a29a438b722.png)
If this is a vimtex issue i can move it to a new ticket.

**Comment by lervag** [comment]
I tried to reproduce, but I couldn't. That makes it difficult to understand what is happening and also difficult to know if it is a vimtex problem or not. Sorry. Could you provide a minimal example?
