### ISSUE TITLE
Support additional glossaries commands

### ISSUE THREAD

**Issue by vyasr** [lervag/vimtex#1583]
**Is your feature request related to a problem? Please describe it.**

In addition to commands like `\gls`, the glossaries package supports a wide range of commands that can be used to produce slightly different versions of the glossaries output. A large number of these are part of the [acronyms](http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/glossaries/glossaries-user.html#sec:acronyms) support in the package, such as `\acrshort`, but there are also abbreviations of existing commands (e.g. `\ac`). Currently, it's not clear exactly which commands can be autocompleted, or if there are any particularly reasons for the current set of choices. Since the package does support a pretty wide range of commands, it may not make sense to support every single one of them. I'd be interested to hear if other users of the glossaries package (or the maintainer @nlct) had opinions on which of these are worth including. In my opinion, at least a subset of the shortcuts in Table 13.1 on [this page](http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/glossaries/glossaries-user.html#sec:acronyms) would be worth supporting.

**Describe the solution you'd like**

Adding more of the glossaries commands to the list of commands that can be autocompleted. A draft PR of how this could be accomplished is ongoing in #1582.

**Comment by lervag** [comment]
Thanks for opening this issue; let's see if there are any other users who have a comment on this!

**Comment by nlct** [comment]
For the base `glossaries` package, there are the main set of commands (the [`\gls`-like comands](http://mirrors.ctan.org/macros/latex/contrib/glossaries/glossaries-user.html#sec:gls-like)): `\gls`, `\glspl`, `\Gls`, `\Glspl`, `\GLS`,  `\GLSpl` and `\glsdisp`. There's probably not much need for the all caps versions (`\GLS` and `\GLSpl`).

Then there are the [`\gls`-like commands](http://mirrors.ctan.org/macros/latex/contrib/glossaries/glossaries-user.html#sec:glstext-like): `\glslink`, `\glstext`, `\Glstext`, `\GLStext`, `\glsfirst`, `\Glsfirst`, `\GLSfirst` (and so on for all the fields `plural`, `firstplural`, `name`, `symbol`, `desc`, `useri`, …, `uservi`). Of these, `\glslink`, `\glssymbol` and the user commands are likely the most common, but I think it's best to support them all. Although, again, I think the all caps don't get much use.

There are the [commands that index without generating any text](http://mirrors.ctan.org/macros/latex/contrib/glossaries/glossaries-user.html#sec:glsadd): `\glsadd`, `\glsaddall` and `\glsaddallunused`. The last two shouldn't be used together and shouldn't be used more than once, so they don't need to be repeatedly typed throughout the document. I think `\glsadd` is most useful in the definition of commands, although it can be used explicitly in the document but I think that's not as common. Similarly for the cross-referencing commands like `\glssee`. So I wouldn't bother with these.

There are the [commands that don't index](http://mirrors.ctan.org/macros/latex/contrib/glossaries/glossaries-user.html#sec:glsnolink): ` \glsentrytitlecase`, ` \glshyperlink`, ` \glsentryname`, `\Glsentryname`, `\glsentrytext`, `\Glsentrytext` (and so on for all the other fields). These will usually be used in command definitions rather than explicitly in the document, although the field access commands like `\glsentrytext` may occur in captions or chapter/section headings. The other commands listed in that section of the manual like `\glossentryname` and `\glossentrydesc` are designed for use within glossary styles, so they won't typically be used explicitly in the document. The most common of this set are likely to be `\glsentrytext`, `\glsentrysymbol` and the user commands, `\glsentryuseri`, …, `\glsentryuservi`.

The [acronym commands](http://mirrors.ctan.org/macros/latex/contrib/glossaries/glossaries-user.html#sec:acronyms) are `\acrshort`, `\Acrshort`, `\ACRshort`, `\acrshortpl`, `\Acrshortpl`, `\ACRshortpl`, `\acrlong`, `\Acrlong`, `\ACRlong`, `\acrlongpl`, `\ACRlongpl`, `\acrfull`, `\Acrfull`, `\ACRfull`, `\acrfullpl`, `\Acrfullpl` and `\ACRfullpl`. Again I don't think there's much need for the all caps. (If the abbreviation should be in capitals then it should be defined that way.)

There are also commands for that don't index or form hyperlinks (analogous to `\glsentrytext`): `\glsentryshort`, `\Glsentryshort`, `\glsentryshortpl`, `\Glsentryshortpl`, `\glsentrylong`, `\Glsentrylong`, `\glsentrylongpl`, `\Glsentrylongpl`, `\glsentryfull`, `\Glsentryfull`, `\glsentryfullpl` and `\Glsentryfullpl`. Again these are more likely to be in commands definitions rather than explicitly used in the document, although they may be used in caption or chapter/section titles. 

The shortcuts are in the table already mentioned. I'm not sure how much use they get.

There are also the [entry counting commands](http://mirrors.ctan.org/macros/latex/contrib/glossaries/glossaries-user.html#sec:enableentrycount): `\cgls`, `\cGls`, `\cglspl` and `\cGlspl`.

There are also supplementary packages that provide additional commands.

[`glossaries-prefix.sty`](http://mirrors.ctan.org/macros/latex/contrib/glossaries/glossaries-user.html#sec:prefix) provides commands analogous to `\gls`: `\pgls`, `\Pgls`, `\PGLS`, `\pglspl`, `\Pglspl` and `\PGLSpl`. Again the all caps (`\PGLS` and `\PGLSpl`) are unlikely to be required in most documents, but I suggest supporting the others. The package also provides commands like `\glsentrytext` for the prefix fields, but again they're only really used within command definitions, so I wouldn't bother with them.

Similarly [`glossaries-accsupp.sty`](http://mirrors.ctan.org/macros/latex/contrib/glossaries/glossaries-user.html#sec:accsupp) provides commands like `\glsentrytext` for the accessibility fields. (These ones aren't even mentioned in the `glossaries` user manual. You need to read the documented code to find out about them. They're not really document commands, so again I don't think you need to include them.)

The `glossaries-extra` package provides more commands.

There are the [commands for use in field values](http://mirrors.ctan.org/macros/latex/contrib/glossaries-extra/glossaries-extra-manual.html#sec:nested): `\glsxtrp` and the shortcuts `\glspt` and `\glsps`. These are only used in entry definitions, but it may be worth supporting them.

There are the [commands for use in caption or chapter/section headings](http://mirrors.ctan.org/macros/latex/contrib/glossaries-extra/glossaries-extra-manual.html#sec:headtitle): `\glsfmtshort`, `\Glsfmtshort`, `\glsfmtshortpl`, `\Glsfmtshortpl`, `\glsfmtlong`, `\Glsfmtlong`, `\glsfmtlongpl`, `\Glsfmtlongpl`, `\glsfmtfull`, `\Glsfmtfull`, `\glsfmtfullpl`, `\Glsfmtfullpl`, `\glsfmttext`, `\Glsfmttext`, `\glsfmtplural`, `\Glsfmtplural`, `\glsfmtname`, `\Glsfmtname`, `\glsfmtfirst`, `\Glsfmtfirst`, `\glsfmtfirstpl` and `\Glsfmtfirstpl`. There are also all caps versions, but again I don't think you need to worry about them. It may be worth supporting the others.

The `glossaries-extra` extension package has its own [abbreviation handling](http://mirrors.ctan.org/macros/latex/contrib/glossaries-extra/glossaries-extra-manual.html#sec:abbreviations) that overrides the base package so it has commands that replace `\acrshort` etc: `\glsxtrshort`, `\Glsxtrshort`, `\GLSxtrshort`, `\glsxtrshortpl`, `\Glsxtrshortpl`, `\GLSxtrshortpl`, `\glsxtrlong`, `\Glsxtrlong`, `\GLSxtrlong`, `\glsxtrlongpl`, `\Glsxtrlongpl`, `\GLSxtrlongpl`, `\glsxtrfull`, `\Glsxtrfull`, `\GLSxtrfull`, `\glsxtrfullpl`, `\Glsxtrfullpl` and `\GLSxtrfullpl`. Again, I don't think there's much use for the all caps versions. If you're going to support `\acrshort` etc then I think you need to support the corresponding `\glsxtrshort` etc.

There are also the [record counting commands](http://mirrors.ctan.org/macros/latex/contrib/glossaries-extra/glossaries-extra-manual.html#sec:recordcount): `\rgls`, `\rGls`, `\rGLS`, `\rglspl`, `\rGlspl` and `\rGLSpl`. If you support `\cgls` etc then it's worth also supporting `\rgls` etc.

The extension package also has a [shortcuts option](http://mirrors.ctan.org/macros/latex/contrib/glossaries-extra/glossaries-extra-manual.html#sec:abbrshortcuts). This includes the shortcuts provided with the base package, but there are more.

The `glossaries-extra-bib2gls` package provides [some more commands](http://mirrors.ctan.org/macros/latex/contrib/glossaries-extra/glossaries-extra-manual.html#supplementarycommands): `\dgls`, `\dGls`, `\dGLS`, `\dglspl`, `\dGlspl`, `\dGLSpl`, `\dglsdisp` and `\dglslink`.

**Comment by lervag** [comment]
Thanks, @nlct. Summarized: There are a whole bunch of commands! :)

I think vimtex supports completion for almost all of them, except the acronyms and the `\[cprd]gls` variants. It should be easy to add support for these as well similar to how it is proposed in #1582.

**Comment by vyasr** [comment]
@nlct thank you for the extremely detailed answer! That should be all the information that we need.

**Comment by lervag** [comment]
I agree. As this issue should be settled by #1582, I'm taking the liberty of closing it now.
