### ISSUE TITLE
Auto completion with "completor" for vimtex

### ISSUE THREAD

**Issue by caixxiong** [lervag/vimtex#1593]
How could I enable auto completion with [completor](https://github.com/maralla/completor.vim) for vimtex? Thanks!

**Comment by caixxiong** [comment]
Sorry, I made a error label:"bug", it is not a bug!

**Comment by lervag** [comment]
> How could I enable auto completion with completor for vimtex? Thanks!

I don't know, as I've never used `completor`. Perhaps you could ask at their issue tracker?

> Sorry, I made a error label:"bug", it is not a bug!

No problem, that happens automatically when you open an issue.

----

By the way: I've edited your original post and the title. Your version is lacking because 1) the title title should not contain the question, and 2) the post did not state the issue/problem/question. A good title should be short and specify the topic. A good issue description should have the question and all relevant context.

**Comment by lervag** [comment]
I would think [this](https://github.com/maralla/completor.vim#other-languages) should be a starting point for making things work with vimtex. Perhaps something like this:

```vim
let g:completor_tex_omni_trigger = g:vimtex#re#neocomplete
```
