### ISSUE TITLE
Temporary files should be created in tmpdir

### ISSUE THREAD

**Issue by lahwaacz** [lervag/vimtex#160]
Some features of vimtex (e.g. bibliography completion) require creation of temporary files, which are currently created in the working directory. Even though they are properly removed when not needed anymore, it would be much better to create them in say `/tmp/`, which is often a tmpfs, and thus avoid writing the files to disk. The delay between invoking the completion and getting the results might be substantially reduced this way.

**Comment by lervag** [comment]
Yes, I agree. Have you noticed any other usages of temporary files that are not done correctly? I think the bibliography completion is the only one that is not good.

**Comment by lahwaacz** [comment]
Quick grepping did not reveal anything, so I guess these are the only ones...

**Comment by lervag** [comment]
One problem, though: I don't see how to do this in a reliable manner without doing a relatively large rewrite.

As far as I can understand, I need to do the following:

1. Create a temporary directory (must handle different OSes)
2. Go to temp dir
3. Parse bibliography files to get absolute paths (if relevant)
4. Write the aux file
5. Run bibtex
6. Parse the bbl file
7. Clean up

The first step is the main problem, especially since I only use Linux and thus can't test on OSX and Windows. Also, step 3 is slightly difficult since the bibliographies may or may not be files located in the LaTeX project (the Bibliography location may depend on environment variables and similar).

So, it seems this is not trivial. Which leads to the question: Is it necessary? Personally I have not really experienced a large delay in the completion...

**Comment by lahwaacz** [comment]
You could use [mkdir](http://vimdoc.sourceforge.net/htmldoc/eval.html#mkdir()), which seems to be portable. But the point 3 is difficult indeed, I don't see a way to solve it.

Anyway, I just realized that the major part of the delay on my config comes from a questionable mapping
``` viml
inoremap {<CR> {<CR>}<Esc>O<BS><Tab>
```
I will need to find a better way to have an opening brace followed by newline insert also the closing brace and place the cursor on the previous indented line... The bibliography completion is still noticeably slower than e.g. label completion, but that may come from running bibtex itself.

**Comment by lervag** [comment]
Yes, I agree the completion is noticable and clearly slower than label completion. But I think we'll leave this closed for now. In any case, thanks for making me aware of the fact that it will be more optimal to do file operations in the `/tmp` directory.
