### ISSUE TITLE
how can i use these map(`<plug>(vimtex-ac)`, `<plug>(vimtex-ie)`, etc) in other language?

### ISSUE THREAD

**Issue by Freed-Wu** [lervag/vimtex#1623]
i like this plugin especially its map about `<plug>(vimtex-ac)`, `<plug>(vimtex-ie)`, etc.
except latex, i also write latex in markdown(pandoc).
how can i use these map in markdown, pandoc, and other language(sometimes i write latex the comment of any language and by lsting or minted to show it)?

i have found `:set ft=tex` then `:set ft=pandoc` can work normally in pandoc. other language should be same. but i don't think it is a good solution... such as seprate `<plug>(vimtex-a/i c/d/e/$)` as an independent plugin? perhaps you have a better solution...

thanks. this is a feature request.

**Comment by lervag** [comment]
You can do `:call vimtex#init()` to initialize vimtex. This should suffice for loading vimtex mappings and similar. You could add it to your `after/ftplugin/{filetype}.vim` file to automatically load vimtex for a given filetype. Note, though, that this might not be quite what you want, because it will load _all_ features from vimtex.

I do agree it could be useful to allow more fine grained control to load specific parts, e.g. loading some stuff relevant to markdown files. However, this really is outside of the scope of vimtex, since it is a LaTeX filetype plugin. I don't have the time to make these changes. Sorry!

**Comment by lervag** [comment]
Note, though: If someone where to suggest the changes via a pull request, I would be happy to consider it!
