### ISSUE TITLE
Plugin clash with engeljh/vim-latexfmt

### ISSUE THREAD

**Issue by engeljh** [lervag/vimtex#1644]
**Issue**

I'm the author of [vim-latexfmt](https://github.com/engeljh/vim-latexfmt). It's a latex-aware modification of `gq`. [I was informed](https://github.com/engeljh/vim-latexfmt/issues/1) that it doesn't function when `g:vimtex_format_enable` exists.  In particular, it produces a "E20: mark not set" error when called (with `ff` when used with the .vimrc below) from the first line of the tex file below, and hangs when called from anywhere following `\begin{document}`.  The vimtex files in `autoload/` shouldn't be sourced, so I don't understand how `format.vim` could cause a problem.

FWIW, though the file below doesn't demonstrate it, I was told that navigation is very slow when this plugin has been called and `g:vimtex_fold_enable=1`.

**minimal.vim**

```vim
filetype plugin on
set nocompatible
let g:vimtex_format_enabled=1
map ff <Plug>latexfmt_format
```

**minimal.tex**

```tex
\documentclass{minimal}

\begin{document}
Here is some simple text to format. It contains a very long line that the plugin should easily wrap.  Here's some math to extend the line:  $\alpha+\beta = \gamma \frac{\sigma}{\sqrt{1.2}}$.
\end{document}
```

**Commands/Input**

* `ff` in the first line
* `ff` at `\begin{document}` or somewhere after in the text.

**Observed Behaviour**

Produces a "E20: mark not set" error when called (from the first line of the tex file), and hangs when called from anywhere in the text following \begin{document}.

**Expected Behaviour**

When called from the first line in the file it should do nothing, and it should behave like `gqap` without touching the latex markup when called within the text.

**Output from VimtexInfo**
```
Error detected while processing function vimtex#info#open[2]..vimtex#scratch#new[2]..290:
line    4:
E37: No write since last change (add ! to override)
```

**Comment by lervag** [comment]
> FWIW, though the file below doesn't demonstrate it, I was told that navigation is very slow when this plugin has been called and `g:vimtex_fold_enable=1`.

I'm using this extensively without issues. Note, however, that one should read `:help vimtex-folding` and consider to use the plugin FastFold to avoid the slow folds. Alternatively set `g:vimtex_fold_manual`; both of these points are documented in the referred section.

> **minimal.vim**

The minimal vimrc does not make sense, because it does not load vimtex or vim-latexfmt. Please update the description. If the plugins are loaded "automatically" because you put them in some `pack` directory, then please make that clear and explain how this is done. I don't use the package feature.

Summarized: Everything should be explicit! In the current state, the plugins are not specified to be loaded, and so no issue can be reproduced.

> ```
> Error detected while processing function vimtex#info#open[2]..vimtex#scratch#new[2]..290:
> line    4:
> E37: No write since last change (add ! to override)
> ```

I assume this error message appears because you did not have `set hidden` and had some modification in your file before doing `:VimtexInfo`.

**Comment by lervag** [comment]
I've responded in [your issue tracker](https://github.com/engeljh/vim-latexfmt/issues/1). Let's continue the discussion there.
