### ISSUE TITLE
Add visual mode version of tsf - toggle fraction

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#1651]
`tsf` from visual mode should split the selected text on `/` and turn it into `\frac{numerator}{denominator}`. Visual mode `tsf` should not do anything for `\frac{x}{y}`.

See also discussion at #1625.

**Comment by nilsbecker** [comment]
i'm thinking about the way back from `\frac`. for sure the visual version of the way back is less useful. however the mnemonic 'toggle surrounding fraction' suggests that it does go both ways. i wonder if (a) one could allow the way back by detecting `\frac` and using the non-visual version of `tsf` of (b) one could use a different key stroke, since the 'surrounding' is not really fitting for visual mode. as a reference for (b) one could look at vim-surround: there `csd` in normal mode changes the surrounding delimiters, while from visual mode one uses `S)` for instance to surround with `()`.

**Comment by lervag** [comment]
Agreed. I've implemneted a first version now that should toggle back and forth with `tsf` in visual mode. I'm going to add some tests and docs now, but let me know if you find some edge cases that does not work as expected.
