### ISSUE TITLE
b:undo_ftplugin not defined

### ISSUE THREAD

**Issue by deved99** [lervag/vimtex#1656]
**minimal.vim**
  ```vim
  let b:undo_ftplugin .= "|setlocal textwidth<"
  ```

**Observed Behaviour**
Vimtex overrides ftplugin/tex.vim. This isn't a problem, although ftplugin/tex.vim provided by vimtex doesn't define b:undo_ftplugin, so that when I add some elements to it, the following error is thrown every time I open a Tex file:
```vim
E121: Undefined variable: b:undo_ftplugin
```
I could just define it instead of adding elements, but that would clear the previous value of it, if in future you decide to define it and that could create some problems.

**Expected Behaviour**
The variable b:undo_ftplugin should be defined.

**Output from VimtexInfo**
System info
  OS: Linux 5.5.13-zen2-1-zen
  Vim version: NVIM v0.4.3
  Has clientserver: true
  Servername: /tmp/nvimIUo9d4/0

**Comment by lervag** [comment]
> although ftplugin/tex.vim provided by vimtex doesn't define b:undo_ftplugin, so that when I add some elements to it, the following error is thrown every time I open a Tex file:

Well, I don't think you should expect that vimtex defines `b:undo_ftplugin`. I don't think it makes sense to set this variable in vimtex, because there is no way to reliably undo everything that is set by vimtex.

Thus, I think you should rather change your own code. I propose that you change your code to something like this:

```vim
if exists('b:undo_ftplugin')
  let b:undo_ftplugin .= '|'
else
  let b:undo_ftplugin = ''
endif
let b:undo_ftplugin .= 'setlocal textwidth<'
```
