### ISSUE TITLE
Autocompletion for \cite: deoplete seems to suppress the omnifunction's searching for authors and title

### ISSUE THREAD

**Issue by chenny888** [lervag/vimtex#1661]
**Issue**

I'm not sure if it is a vimtex issue or deoplete issue. After \cite{s, the autocompletion menu by deoplete only shows the bib items whose key starts with s, not those whose authors start with s. If I press <C-X><C-O>, the typed string "s" will disappear with \cite{ and all the bib items showing up. 

Interestingly, if I disable deoplete, <C-X><C-O> will give the correct results.

**minimal.vim**

```vim
call plug#begin('~/Dropbox/vim/vimfiles/bundle')
Plug 'lervag/vimtex'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

let g:deoplete#enable_at_startup = 1
"let g:deoplete#enable_refresh_always = 1
call deoplete#custom#var('omni', 'input_patterns', {
            \ 'tex': g:vimtex#re#deoplete
            \})
```

**minimal.tex**

```tex
\documentclass[]{article}

\begin{document}
\cite{abc}
\bibliographystyle{plain}
\bibliography{ref.bib}
\end{document}
```
Here is the bib file.

```bib
@article{testkey,
  title={One two three},
  author={Abc, Def and Def, Abc},
  journal={Working Paper},
  year={2020}
}
@article{testkey2,
  title={Nothing here},
  author={Abc, Def and Def, Abc},
  journal={Working Paper},
  year={2020}
}
```
**Commands/Input**

If we insert abc into cite, which is the author name, then no item will pop up. 
**Observed Behaviour**

**Expected Behaviour**

**Output from VimtexInfo**

**Comment by lervag** [comment]
Yes, I don't think this is a vimtex issue. The completion is an omnicompletion which allows stuff like matching on both the completion key and other stuff. As you say, without deoplete, completion works as expected, because the text you input is manually checked against the author names first.

With deoplete, things are different. You can consider it a completion server. It will gather all completion candidates from vimtex without giving it any initial match text. It is similar to `\cite{<c-x><c-o>` (i.e., get _all_ candidates). Then deoplete combines the candidates with other sources and filters the candidates based on your input text. How this filtering is done is pure deoplete, and most likely it will filter the completion key/citekey.

Note, you can still use omnicomplete and vimtex with deoplete manually: if you write `\cite{abc<c-x><c-o>`, it should complete on authors as you expected. But the complete candidates may be refreshed when you start writing more.

There might be options for deoplete to allow it to filter candidates by other data from the completion candidates. You could open an issue with deoplete and ask about it. But I don't think it is possible.

**Comment by chenny888** [comment]
Thank you for the reply. This explains a lot!

However, the manual option doesn't seem to work. If I use `\cite{abc<c-x><c-o>}`, all the bib items pop up. In the example, this is what expected. But if I insert a third bib item with different author names, everything pops up too. So the screenshot is taken after I do `\cite{good<c-x><c-o>}`. Do you know what might be the reason? Thanks.

![image](https://user-images.githubusercontent.com/8396735/78989772-90efb100-7b02-11ea-8084-d86802858939.png)

**Comment by lervag** [comment]
With your minimal example without deoplete, I get the following:

1. `\cite{abc<c-x><c-o>` does not complete anything, because the matching is case sensitive.
2. `\cite{Abc<c-x><c-o>` completes testkey and testkey2, but not testkey3.
3. `\cite{<c-x><c-o>` completes all three entries.

On your side, could you repeat the tests without deoplete and confirm that things work as expected in that case? If so, next step: Write `\cite{good`, exit insert mode and enter again just after `good`, then type `<c-x><c-o>`. Does it work now?

**Comment by chenny888** [comment]
It seems that whenever I run `nvim -u minimal.vim test.tex`, the first attempt is always good. I got 1, 2, and 3 exactly as yours. And I got `\cite{good` correctly. This already different from deoplete. If deoplete is turned on, the first attempt (using omnifunc manually) would be incorrect.

But the second attempt would result in the same results as the first one. For example, I tried`\cite{Abc<c-x><c-o>`, which returned testkey and testkey2. Then I tried (without quitting neovim) `\cite{good<c-x><c-o>`, it is still testkey and testkey2. Somehow the results are not refreshing. Maybe I should search to see if it is the problem of omnifunc? Thank you for your time again.

**Comment by lervag** [comment]
Strange. For me, it works as expected every time. Can we focus on things without deoplete first? You write:

> For example, I tried\cite{Abc<c-x><c-o>, which returned testkey and testkey2. Then I tried (without quitting neovim) \cite{good<c-x><c-o>, it is still testkey and testkey2.

Can you very explicitly explain how you do this? When I try to repeat it, things work exactly as expected. For me, it works. I do this:

1. Write `\cite{Abc<c-x><c-o>`; observe the two first citekeys as expected.
2. Now delete and change to `\cite{Good` then type `<c-x><c-o>`, and the third entry is completed. Again as expected.

For me, this works regardless of how I try it. It just always works.

**Comment by chenny888** [comment]
Thank you again. I think the issue is resolved. It turns out that I or other program may have modified some local files of vimtex, so PlugUpdate always aborts when attempting to merge. I have removed and reinstalled vimtex and now everything works (with or without deoplete).

**Comment by lervag** [comment]
Great, happy to hear that. :)
