### ISSUE TITLE
Omnicompletion for inline math

### ISSUE THREAD

**Issue by zhuosongz** [lervag/vimtex#1667]
I am writing to request a new feature. For example, when I am editing a tex file, I often need to type, for example:

```tex
\sum_{a, b}^{c, d}
\sup_{e, f}
\max_{B \in \mathcal{E}}
\inf_{C \in \mathcal{A}}
```

Next time when I input some comments, typing

```tex
\max_{<C-x><C-o>
```

gives me a list of the contents in the braces of inline math formulas:

```
a, b
c, d
e, f
B \in \mathcal{E}
C \in \mathcal{A}
```

and then using `<C-n>/<C-p>` to choose from the list.

Does Vimtex have this feather? If no, I hope this feather might be interesting. Thank you very much!

---

PS: I tried to use:

```vim
let g:neocomplete#sources#omni#input_patterns.tex = '_{[^{}]\{-}}'
```

but it doesn't work.

**Comment by lervag** [comment]
> Does Vimtex have this feather? If no, I hope this feather might be interesting. Thank you very much!

No, vimtex does not have this feature, and I don't think it seems feasible. The reason is it seems very complex. That is, to properly handle it, we need very detailed parsing to detect all the various types of brace content that also keeps track of which content is relevant for such type of completion.

That is, for me it seems very prone to errors and issues without really providing much value. If I write complex expressions I tend to copy them when I need to repeat them. I use custom mappings, snippets, or I copy things to registers for easy access with insert mode `<c-r>{register}`.

> PS: I tried to use:
>
> ```vim
> let g:neocomplete#sources#omni#input_patterns.tex = '_{[^{}]\{-}}'
> ```
>
> but it doesn't work.

No, that won't work. The input patterns for neocomplete (and other autocompleters) are used to specify when the vimtex omnicomplete function should be called. They should match the various complete types (e.g. cite complete for `\cite` and label completion for `\ref`).

**Comment by zhuosongz** [comment]
Thank you a lot for your helpful comments. 

Best, 
ZS

**Comment by lervag** [comment]
No problem, and feel free to open new issues/feature requests! :)
