### ISSUE TITLE
Two zathura windows are opened when working in a symbolic link directory

### ISSUE THREAD

**Issue by gaoqiangks** [lervag/vimtex#1676]
Sorry for my poor English.

My working directory is `~/Latex/least area problem`.  To save a little typing, I create a symbolic link to this directory  `~/leastarea -> ~/Latex/least area problem`.  However, every time I started `VimtexCompile`, two zathura windows are opened.  When the compilation completed, a zathura window was opened to view the PDF file, and seconds later, another zathura window was opened by forward search.   This only happens when I just enter the symbolic link directory `~/leastarea`.  Everything works fine if I typed `cd ~/Latex/least area problem`.  I tried many times, it always works this way.
The following is a minmal `.vimrc` and `.tex` example.

```vim
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
"使用zathura为默认的pdf浏览器
let g:vimtex_view_method = 'zathura'
```

```tex
\documentclass{amsart}
\begin{document}
minimal tex file.
\end{document}
```

Create a directory test, create any `test.tex` file in the directory test.  Create a symbolic link `ttt -> test`, `cd ttt` and then `vi test.tex`, `\ll`, then it is reproduced. 

Any way to fix this ?

**Comment by lervag** [comment]
Thanks! I've made some minor changes that might affect/fix this. Can you please test?

**Comment by gaoqiangks** [comment]
> this

Thank you!  However, it seems that this issue still exists.

**Comment by lervag** [comment]
I'm sorry, but I can't reproduce this. Note, before my patches I did reproduce it. :\

**Comment by gaoqiangks** [comment]
Thank you very much. This is a minor issue.  Maybe the "xdotool" is not working properly on my system. I have encountered many times of the "xdotool" problems.   Thank you!

**Comment by lervag** [comment]
Ok, thanks, and no problem! I'm using xdotool version 3.20160805.1, which I think is a quite recent version (I'm on Arch Linux). For me, things work well with the current version of vimtex.

**Comment by daviddaiweizhang** [comment]
I have the same issue for files inside symbolically linked directories. However, a bigger problem is that if I do a backward search while a terminal is open in another window, the terminal window will be selected, and the mouse will be centered there. This bug significantly interrupts the workflow.

Some version info for my system:
Arch Linux
xdotool 3.20160805.1
vim 8.2
terminator 1.92
i3 version 4.18.2

**Comment by lervag** [comment]
@daviddaiweizhang 

> I have the same issue for files inside symbolically linked directories.

Then it does not seem like the exact same issue. This thread was closed, so if you have the _same_ issue, why should I reopen?

I think it is much better if you open a new issue and describe your problem in a clear and concise matter, preferably with a minimal example (minimal vimrc + LaTeX file and required steps, etc).

**Comment by daviddaiweizhang** [comment]
@lervag 

Both bugs (the original issue and the one I described) are present on my machine. They can be replicated in the same way. Moreover, the original issue is unresolved, since @gaoqiangks mentioned it's still there, and my machine is also experiencing it. I created a separate issue for the issue I described. Thanks.

**Comment by lervag** [comment]
> Moreover, the original issue is unresolved, since @gaoqiangks mentioned it's still there, and my machine is also experiencing it.

I know, but as I wrote to @gaoqiangks:

> I'm sorry, but I can't reproduce this. Note, before my patches I did reproduce it. :\

When I can't reproduce, it becomes very difficult to fix it. I don't mind trying, but then I need more help figuring out what is wrong. At first, perhaps you could try to describe again a minimal example?

**Comment by lervag** [comment]
Ok, perhaps I misunderstood the issue. Is this a correct step-by-step understanding?

1. Create test file in a directory, then create symlinked directory.
2. Open `test.tex` inside the symlinked directory.
3. `\ll` -> a single Zathura window opens.
4. `\lv` -> a __new__ Zathura window opens (making it two windows).

Expected is for step 4 to instead focus the first window and do forward search there.

**Comment by lervag** [comment]
I fixed the problem I've noticed, still not sure if that's the same problem you're having.

**Comment by daviddaiweizhang** [comment]
> 3. `\ll` -> a single Zathura window opens.
On my machine, two windows are actually opened during this step: one for the tex file in the linked directory (without forward search highlights or backward search capacity), and, a few seconds later, another for the text file in the original directory (with forward search highlights and backward search capacity).

Thanks for the fix. I updated my vimtex and noticed that the bug is fixed in some of my projects but remained unchanged in others. I'll try to figure out what makes the difference and make an updated minimal reproducing example.

**Comment by lervag** [comment]
> Thanks for the fix. I updated my vimtex and noticed that the bug is fixed in some of my projects but remained unchanged in others. I'll try to figure out what makes the difference and make an updated minimal reproducing example.

No problem. Happy to hear we are making progress, and I'm looking forward to seeing an updated example.

**Comment by kmarius** [comment]
I found some issues that I think are related to this which happen when using absolute paths. The file manager `lf` only uses absolute paths. Consider the folder structure

    .
    ├── a
    │   └── b
    │       ├── test.aux
    │       ├── ...
    │       ├── test.pdf
    │       ├── test.synctex.gz
    │       └── test.tex
    └── c -> a/b

When inside `c` using the absolute real path e.g. `vim /some/dirs/a/b/test.tex`, calling `vimtex#view#view()` (`<leader>ll`) twice will open two windows, all subsequent calls do forward searches on the second window. Calling `vimtex#compiler#compile()` (`<leader>ll`) will start a single instance, all calls to `view()` work correctly.

However, using the absolute path with symlink, e.g. `vim /some/dirs/c/test.tex`, the first call of `view()` or `compile()` opens the an instance correctly, but each subsequent call to `view()` opens another instance that is not showing the pdf. The reason is that the relative paths are not correct (one can see this by counting `../`s in zathuras command line).

I changed the lines

https://github.com/lervag/vimtex/blob/master/autoload/vimtex/view/zathura.vim#L62

to

    let self.texfile = vimtex#paths#relative(expand('%:p'), getcwd())
    let self.outfile = vimtex#paths#relative(a:outfile, b:vimtex.root)

(switched the second arguments) and it works, but it might break whatever it previously solved. From what I can tell, `expand('%:p')` and `getcwd()` always return the fully resolved absolute path, so at least that makes sense.

**Comment by lervag** [comment]
@kmarius I can't reproduce this from your instructions. I think this thread is too wide now, so I'll lock it. But please, if you have a way of actually reproducing this issue, then I would be very happy to see the explicit steps. You should provide the full minimal examples, including a minimal vimrc file and a minimal latex file, with a folder structure.
