### ISSUE TITLE
Comments within single-line minted commands break syntax highlighting

### ISSUE THREAD

**Issue by douglasgscofield** [lervag/vimtex#1678]
**Issue**

Comments within single-line minted commands, standard or custom, breaks syntax highlighting.

Thank you for providing support for these commands in #1098 !

Comments within minted environments, standard or custom, work great.

**minimal.vim**

```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
let g:tex_flavor='latex'
let g:vimtex_syntax_minted = [
    \ {
    \   'lang' : 'perl',
    \   'commands' : [ 'perl', 'perlinline' ],
    \ }
    \]
```

**minimal.tex**

```tex
\documentclass{minimal}
\usepackage{minted}
\newmint{perl}{}    % new \perl command
\newmintinline{perl}{}  % mew \perlinline command

\begin{document}

Using mintinline, the perl fragment does not include a comment: \mintinline{perl}{my $variable = 3;}

Using mintinline, the perl fragment includes a comment that breaks syntax highlighting: \mintinline{perl}{my $variable = 3; # and a comment!}

Using custom perlinline, the perl fragment does not include a comment: \perlinline|my $variable = 3;|

Using custom perlinline, perl includes a comment: \perlinline|my $variable = 3; # and a comment!|

Using mint, the perl fragment does not include a comment: \mint{perl}|my $variable = 3;|

Using mint, the perl fragment includes a comment: \mint{perl}|my $variable = 3; # and a comment!|

Using custom perl, the perl fragment does not include a comment: \perl|my $variable = 3;|

Using custom perl, the perl fragment includes a comment: \perl|my $variable = 3; # and a comment!|

\end{document}
```

**Commands/Input**
Simply load `minimal.tex` using `minimal.vim`, which specifies the additional custom minted commands.

Compile with `pdflatex -shell-escape minimal.tex`

**Observed Behaviour**
Syntax highlighting gets lost once one of these commands includes a comment in the minted language.  The end of the minted command, which is indicated either by curlybrace (in the standard minted command) or a matching delimiter (in a custom minted command) is swallowed into the comment and not recognised.

**Expected Behaviour**
The end of one of these single-line minted commands is indicated by the appropriate delimiter, which takes precedence over any other character within the code to be highlighted.  It is parsed correctly by latex/minted.

**Output from VimtexInfo**

```
System info
  OS: Mac OS X 10.13.6 (17G11023)
  Vim version: VIM 8.1 (1-1722)
  Has clientserver: true
  Servername: VIM3

vimtex project: minimal
  base: minimal.tex
  root: /Users/douglasscofield/tmp/minted-comments
  tex: /Users/douglasscofield/tmp/minted-comments/minimal.tex
  out: /Users/douglasscofield/tmp/minted-comments/minimal.pdf
  log: /Users/douglasscofield/tmp/minted-comments/minimal.log
  aux: /Users/douglasscofield/tmp/minted-comments/minimal.aux
  fls: 
  main parser: current file verified
  compiler: latexmk
    backend: jobs
    output: /var/folders/fd/xcn86wmd40j5f5b7dqxn11480000gn/T/vN0YAIN/0
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: minimal
  packages:
    minted
```

**Comment by lervag** [comment]
I'm sorry, but I don't really see any good way of fixing this. The problem is that the comments match to end of line, and I don't know any way to prevent it from going "out of its bounds".

When I read the docs on syntax highlighting it seems that the `keepend` option for `syntax region` could be relevant, however, it does not work.

These are (some of) the relevant lines of code:
https://github.com/lervag/vimtex/blob/32d72e57cf31440752158a8a16bc5efa4d684a3a/autoload/vimtex/syntax/p/minted.vim#L107-L127

The idea here is that the first `syntax match` will match the `\mintinline{perl}` part, which forces a `nextgroup` into the nested environment with `syntax region`. This region contains the nested syntax, where `perlComment` is included. However:

```
:syntax list perlComment
--- Syntax items ---
perlComment    xxx match /#.*/  contained extend contains=perlTodo,@Spell
                   links to Comment
```

Notice that `perlComment` has the `extend` attribute, which means it overrides the `keepend` that I mentioned above. I don't know any ways to avoid this, which means I don't know how to fix the issue or if it is even possible.

If anyone should know a way to do it, then I'd be happy to hear it!

**Comment by lervag** [comment]
I have [asked reddit](https://www.reddit.com/r/vim/comments/g99v9j/ask_rvim_override_contained_syntax_elements/) for help on this one.

**Comment by douglasgscofield** [comment]
Thanks for looking at it!

In the meantime, is there a way to ask vimtex not to syntax highlight a section of a file?  I'm using a couple dozen lines like these in one section of a document I'm writing and it leads to quite long delays during editing.  Simply telling vimtex not to attempt to highlight a block of lines would be an ideal workaround if this ends up not being fixable.

I could turn off highlighting on the complete file while editing this section, but I think this may also be the area that contributes to occasional timeouts while loading the file due to long compute times for syntax highlighting.

**Comment by lervag** [comment]
> In the meantime, is there a way to ask vimtex not to syntax highlight a section of a file? I'm using a couple dozen lines like these in one section of a document I'm writing and it leads to quite long delays during editing. Simply telling vimtex not to attempt to highlight a block of lines would be an ideal workaround if this ends up not being fixable.

That would be convenient, but I don't think it is possible, sorry. I think, at best, we could try to allow some directives to specify that some syntax elements should not be loaded on a file level. I'm not sure if it is worth the effort, though..?

The closest that is possible now is to use `let g:vimtex_syntax_enabled = 0`, which would disable vimtex's improved syntax highlighting.

> I could turn off highlighting on the complete file while editing this section, but I think this may also be the area that contributes to occasional timeouts while loading the file due to long compute times for syntax highlighting.

With "**this** may also be the area that contributes ...", you refer to the particular use of comments in inline code snippets? Or the nested syntax highlighting in general?

**Comment by douglasgscofield** [comment]
The former, comments in inline minted snippets.  The current chapter is ~8k lines and highlighting occasionally gets out of sync, but any editing that touches the area of these snippets results in long delays.

I'm going to work around the issue by moving ideas expressed in comments into text on the same line.  I like having vimtex's improved highlighting, turning that off is too steep a price to pay :-)

**Comment by lervag** [comment]
> The former, comments in inline minted snippets. The current chapter is ~8k lines and highlighting occasionally gets out of sync, but any editing that touches the area of these snippets results in long delays.

Ok, I see. At least good to hear that things mostly work fine, and that the issue is particular to the comment issue.

> I'm going to work around the issue by moving ideas expressed in comments into text on the same line. I like having vimtex's improved highlighting, turning that off is too steep a price to pay :-)

Personally, I think this sounds like a good work around. I prefer to keep code comments on separate lines and avoid inline comments. Since this issue is related to adding comments to code that you are putting inline in your text, I would think it makes sense to instead move those comments into the text and out of the code.

I'm afraid that I need to be somewhat pragmatic. I don't aim for perfect, I aim for good enough. I'm not sure if we're there, but it seems to me like my time is better spent on other issues. I'll let you decide if we should keep the issue open, in which case I will look into it again at a later time and consider to attempt a solution based on "rewriting" the nested syntax rules. It could work, but it seems a little bit error prone and very hacky.
