### ISSUE TITLE
vimtex init error when open latex hello world

### ISSUE THREAD

**Issue by tianzong2019** [lervag/vimtex#1692]
when i open Latex hello world occur Error:

```
"main.tex" 4L, 88C^[[2;2R
Error detected while processing function vimtex#init..vimtex#init_options:
line  303:
E121: Undefined variable: v:true
E116: Invalid arguments for function <SNR>24_init_option
Press ENTER or type command to continue
```

**main.tex**
```tex
\documentclass{article}
\begin{document}
This is the body of the article
\end{document}
```

the error is on 
```
"329   call s:init_option('vimtex_view_zathura_check_libsynctex', v:true)" 
in
~/.vim/plugged/vimtex/autoload/vimtex.vim
```

**Comment by lervag** [comment]
`v:true` was introduced in Vim 7.4 patch 1154 and is therefore quite old. You are using a very old version of Vim. I've updated the code to fix the issue, but I strongly encourage you to update your Vim.

**Comment by tianzong2019** [comment]
Thank you for your answer, but I don't think it's the VIM version.


My environment is to install Ubuntu 14.04 in VMware, VIM version is 7.4.52, vimrc configuration is as follows:


"""""""""""""""""""""""
call plug#begin("~/.vim/plugged")
Plug 'lervag/vimtex'
call plug#end()


let g:vimtex_version_check = 0    " Do not detect VIM version
let g:vimtex_view_method = 'zathura'


if empty(v:servername) && exists('*remote_startserver')with a server
  call remote_startserver('VIM')
Endif


filetype on
filetype plugin on
filetype indent on


let g:tex_flavor = 'latex' "
"""""""""""""""""""""""







At 2020-05-10 16:47:55, "Karl Yngve Lervåg" <notifications@github.com> wrote:

v:true was introduced in Vim 7.4 patch 1154 and is therefore quite old. You are using a very old version of Vim. I've updated the code to fix the issue, but I strongly encourage you to update your Vim.

**Comment by tianzong2019** [comment]
I updated vimtex. But the following error is reported:

"main.tex" 4L, 88C
vimtex: Zathura is not linked to libsynctex!
vimtex: Zathura requires xdotool for forward search!
vimtex: Can't use callbacks without +job, +nvim, or +clientserver
        Callback option has been disabled.
vimtex: latexmk is not executable
vimtex: Compiler was not initialized!
Press ENTER or type command to continue


Do you have time to try it ?

**Comment by lervag** [comment]
> I updated vimtex. But the following error is reported:

> ```
> vimtex: Zathura is not linked to libsynctex!
> vimtex: Zathura requires xdotool for forward search!
> ```

You've set zathura as your pdf reader, but zathura is not compiled with libsynctex. This means that forward and backward search won't work. Further, you don't have `xdotool` installed, which is also required.

> ```
> vimtex: Can't use callbacks without +job, +nvim, or +clientserver
>         Callback option has been disabled.
> ```

Your Vim version does not have capabilities to run callbacks. This is typically used to report compilation status and similar. Please use neovim or a Vim version compiled with more features.

> ```
> vimtex: latexmk is not executable
> vimtex: Compiler was not initialized!
> ```

Your LaTeX installation does not include latexmk, which is the default program/backend used by vimtex to compile your document.

----

These issues are very basic, and I have the impression that you're new to both Vim and LaTeX and similar. As such, I strongly recommend that you take your time. Instead of Zathura, use a more common viewer like evince, Okular, or similar.

Earlier, you reply:

> Thank you for your answer, but I don't think it's the VIM version.

Then you state that you are on Ubuntu 14.04 with Vim 7.4.54. Thus, it it **clearly** the Vim version. `v:true` was not recognized in this version of Vim, which is why I had to update vimtex to not use `v:true` to solve it.

Note, further: Ubuntu 14.04 is ancient. It is [still supported as a LTS release with extended security maintenance](https://ubuntu.com/about/release-cycle), but I very strongly recommend that you choose a newer Linux distribution as your base OS (if possible)!
