### ISSUE TITLE
XDG_CACHE_HOME is not respected by vimtex

### ISSUE THREAD

**Issue by yochem** [lervag/vimtex#1704]
**Issue**
I am on MacOS so I've set my `$XDG_CACHE_HOME` to `"$HOME/Library/Caches"`. However, after opening a LaTeX file with neovim, the folder `~/.cache/vimtex/` is created. This should be `$XDG_CACHE_HOME/vimtex/`, which would be `$HOME/Library/Caches/vimtex` in my case.

**minimal.vim**
I don't use vimtex, but I use vim-polyglot, which loads vimtex. A minimal vimrc for me would be:

```vim
call plug#begin(stdpath('data') . '/plugged')
Plug 'sheerun/vim-polyglot'
call plug#end()

au BufRead,BufNewFile *.tex setlocal filetype=tex
```

**minimal.tex**
`minimal.tex` can be a new file.

**Commands/Input**
`$ nvim -u minimal.vim minimal.tex +q`

Two options
1. `$ ls -a $HOME | grep '.cache'` OR
2. `$  fd -H -t d -p '[Cc]ache/vimtex'` if fd is installed

**Observed Behaviour**
1. grep prints `.cache/`
2. fd print `~/Library/.cache/vimtex`

**Expected Behaviour**
1. grep prints nothing
2. fd prints `~/Library/Caches/vimtex`

**Output from VimtexInfo**

```vim
System info
  OS: Mac OS X 10.15.4 (19E287)
  Vim version: NVIM v0.4.3
  Has clientserver: true
  Servername: /var/folders/7v/y8dtvn2s0m946nrp88m75ys00000gn/T/nvimVe6Ea9/0

vimtex project: minimal
  base: minimal.tex
  root: /Users/yochem
  tex: /Users/yochem/minimal.tex
  out:
  log:
  aux:
  fls:
  main parser: current file
  compiler: latexmk
    backend: nvim
    output: /var/folders/7v/y8dtvn2s0m946nrp88m75ys00000gn/T/nvimVe6Ea9/1
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    config:
      packages:
        default: 1
      default: 1
  document class:
```

**Comment by lervag** [comment]
I agree, we should respect `XDG_CACHE_HOME`. I'll fix when I get the time.

> I don't use vimtex, but I use vim-polyglot, 

I'll not comment that. ;)

**Comment by yochem** [comment]
Thank you for the quick response!

> I'll not comment that. ;)

Just heard of it because of this bug, will give it a try! :)

**Comment by lervag** [comment]
> > I'll not comment that. ;)
> 
> Just heard of it because of this bug, will give it a try! :)

Just to clarify: I personally think vim-polyglot is something one should keep far away from. Explicit is better than implicit. That is, you could of course feel free to be inspired by vim-polyglot for which plugins to use for various file types, but I would install plugins explicitly. That way you will have more control over your configuration.

I've spent quite some time to help people with issues related to conflicts with vim-polyglot. Luckily, vimtex is now part of it, so I probably won't experience that anymore. Still, the issues are "non issues" and only due to the fact that people don't know what they are doing. If they installed things explicitly, the issues would never have been raised.

So, I was not able to not comment it... :\

**Comment by yochem** [comment]
Ah damn, didn't know such issues are common with vim-polyglot. I liked it because it has a wide variety of syntax-highlighting files. When opening filetypes I don't even know they existed, vim-polyglot knows how to highlight it.

I'll try to switch to explicitly use syntax plugins. Thank you for the clarification and sharing the knowledge.

**Comment by lervag** [comment]
I've updated now so that `$XDG_CACHE_HOME` should be respected. Please test.

> Ah damn, didn't know such issues are common with vim-polyglot. I liked it because it has a wide variety of syntax-highlighting files. When opening filetypes I don't even know they existed, vim-polyglot knows how to highlight it.
>
> I'll try to switch to explicitly use syntax plugins. Thank you for the clarification and sharing the knowledge.

Yes, I can see why it is attractive. But Vim already does come with a bunch of bundled syntax files for the most popular file types. I think it is quite rare that one needs additional support, and in those cases it is better to either 1) accept the lack of support, or 2) explicitly add support by selecting an available plugin. vim-polyglot does work well as a reference for what might be a good canidate for a lot of file types, but in some cases, it might not select the plugin that best suits you.

In any case, I've expressed my opinion, and just to be clear: I respect if anyone has a different opinion! :)

**Comment by yochem** [comment]
Works like a charm! Thank you for your responsiveness and help.

**Comment by lervag** [comment]
Great, happy to hear it works, and I'm happy to help :)
