### ISSUE TITLE
Live Preview Capability

### ISSUE THREAD

**Issue by user3477071** [lervag/vimtex#1732]
I would like to find out if vimtex supports live preview with pdf readers like evince or okular. I checked docs but could not find any mention of this. Therefore, asking this question here.

**Comment by lervag** [comment]
No, vimtex does not support live preview, sorry. It uses latexmk "behind the scenes" to compile your document whenever you save. IMHO, this is "better", because compilation of any non-trivial latex document usually takes too long time for any sort of live preview to work very well. The use of latexmk is a very good compromise. Again, in my opinion.

**Comment by iago-lito** [comment]
@user3477071 I personally open my `output.pdf` file in evince, and it automatically gets reloaded each time I recompile. So once you have mapped `<yourFavouriteKeys>` to a vim command that compiles your doc, you will see the updated version in evince.
