### ISSUE TITLE
Warn when executables are not found

### ISSUE THREAD

**Issue by pedrominicz** [lervag/vimtex#1786]
**Is your feature request related to a problem? Please describe it.**
I just spent a bunch of time to figure that my document wasn't compiling because I was missing the Biber executable.

**Describe the solution you'd like**
vimtex warns me about the missing executable in the buffer it opens when compiling.

**Describe alternatives you've considered**
Verifying `:VimtexCompileOutput` is an obvious alternative, however, not as beginner friendly.

**Comment by lervag** [comment]
>  I just spent a bunch of time to figure that my document wasn't compiling because I was missing the Biber executable.

I'm sorry, but vimtex actually assumes that you already _know_ how to use latex. It is not meant to be a crutch that helps you figure out everything that might be wrong. In this particular case: how should vimtex recognize that you needed biber? We would have to parse the preamble and notice the `biblatex` package, but we would also have to check if the `backend=...` option is passed. Ok, this is possible. But now, say, someone uses a custom class that loads `biblatex`, and vimtex would again fail. So, we would need to parse the class and style files as well in order to be certain that biber is needed. I don't want to go that path.

So: Instead of asking for a warning from vimtex, you need to learn how to use LaTeX. `:VimtexCompileOutput` is very useful in these circumstances. Perhaps also `:VimtexErrors` would show an error (not certain about that). Barring all of that: when a document does not compile, and if you don't figure out why from inside vimtex, then you should know how to figure out what is wrong from directly executing latex commands. Vimtex is not meant to replace this type of knowledge. Sorry!

**Comment by jhossbach** [comment]
Sorry to necrobump this, but would it be possible to add this as part of the `checkhealth`? Similar to the check if `bibtex` is existing as an executable, we could do the same for `biber` and issue a warning if it doesn't exist? I was bugged by this problem for quite a while after setting up a new system.

**Comment by lervag** [comment]
Ok, I'll add it.

**Comment by lervag** [comment]
But please note: The issue you had here was FULLY unrelated to VimTeX. As I said before, people should already know how to use LaTeX, and it is not VimTeX's responsibility to help people figure out everything that might be wrong.

If `biber` is missing and you need it, then it will be clear from the compiler output. That's the first thing you should examine.

**Comment by lervag** [comment]
Also, just to be clear: I mean this in the best possible way; I'm not trying to be rude. So if it comes off as hostile or rude, that is not my intent.

**Comment by jhossbach** [comment]
I agree, the problem was that vimtex displayed `Comilation failed` but `VimtexErrors` didn't show any errors, and the logs didn't show any useful information either. Thank you for reconsidering!

**Comment by lervag** [comment]
Note that the relevant compiler output in this case is _not_ the log from `pdflatex` or `lualatex` or similar, but from `latexmk`. You can see the output with `\lo` or `:VimtexCompileOutput`, or by just running `latexmk` in a terminal.
