### ISSUE TITLE
Inline equation ( \[ <equation> \] ) doesn't move cursor immediately

### ISSUE THREAD

**Issue by ludwj61** [lervag/vimtex#1841]
**Issue**
When writing the last bracket in an inline equation (the ``]`` in ``\]``), the cursor takes a second or so to actually move past the bracket as it normally does when any character is typed. 

This does not occur without the plugin installed and occurs with the minimal vim and tex files given in the issue template.

I am using the latest neovim nightly build and latest version of this plugin.

**Comment by lervag** [comment]
This is because `]` is part of a default insert mode mapping `]]` (to close current environment/delimiter). Thus, after typing the first `]`, Vim waits for the next part before pushing the character to the buffer since it may be a `]` which triggers the `]]` mapping.

The behaviour is controlled by `set timeout` and `set timeoutlen`.

If you don't use `]]` and you find this annoying, then you can add something like this to your vimrc:

```vim
" Either remap the target map to something else
augroup vimrc_vimtex
  au!
  au FileType tex nmap <nop> <plug>(vimtex-delim-close)
augroup END

" Or disable with the option
let g:vimtex_mappings_disable = {'i': [']]']}
```
