### ISSUE TITLE
[Feature Request] Comment both environment?

### ISSUE THREAD

**Issue by yushangakki** [lervag/vimtex#1849]
**Is your feature request related to a problem? Please describe it.**

It is really convenient to use the mapping `cse` to change the environment. Inspired by this, it would be great if there is a way to **comment both environment**. In some cases (like adding effects to some texts), commenting the whole environment is conveninent.

**Describe the solution you'd like**

A mapping like `csc` (commment surround environments)
Before the mapping

```tex
\begin{hello}
\end{hello}
```
After the mapping 

```tex
%\begin{hello}
%\end{hello}
```

Then we could use the mapping to toggle the mapping.

**Describe alternatives you've considered**
Actually, the vim plugin nerd-commenter inspired me to think of this idea. However, doing research on both vimtex and nerd-commenter doesn't give me any alternative solutions.

**Additional context**

Nothing here, but thank you for this great plugin!

**Comment by lervag** [comment]
Thanks, but you don't want this. Instead, you want [vim-commentary](https://github.com/tpope/vim-commentary) (or a similar plugin; if you search, you will find several plugins like this). vim-commentary provides a comment command that works with text objects and motions. E.g., it maps `gc` to the command to comment anything, so that you can do `gcae` to comment out the current environment. Or `gc}` to comment out the remaining part of a paragraph.
