### ISSUE TITLE
complaint about the test folder 

### ISSUE THREAD

**Issue by tlannaax** [lervag/vimtex#1859]
I didn't notice this issue until recently reseting an old machine. When I synced my config files, including the vim plugins, to the old machine, I noticed that there are 1000+ small files in the test folder, which caused a significant delay in the sync process.

Probably the test files are handy for developers, however, I don't see why a normal user has to be forced to get such a large number of small files which are not necessary for the plugin to function properly.

Will the developer consider forking another release branch for normal users, and get rid of unnecessary files?

**Comment by lervag** [comment]
This is a valid and understandable complaint! I've been trying to clean up a little bit, but there's still a lot more work to do in that regards.

The last year (or perhaps slightly longer) I've made dedicated, automatic tests under `test/tests`. Before that, I used to make issue specific tests under `test/issues/[number]`. The latter was of course very useful when working on specific issues, but when the issues were resolved, the files are no longer really that necessary. Instead of just deleting these files, though, I've tried to go through them and migrate things that make good automatic tests into `test/tests`.

However, since my time is quite limited, it might be a better strategy to simply delete all the `test/issues` tests in one go (except for perhaps a very few that are currently relevant). If I ever need to go back, then the files are available in history. And I can just add new automatic tests when necessary as a response to fresh issues.

There are about 462 files in `test/tests` and 553 files in `test/issues`. I don't expect the number of files in `test/tests` to increase by a lot. Would removing `test/issues` in itself reduce the annoyance by enough?

**Comment by clason** [comment]
To be honest, this is an issue I've thought about on and off as well -- it's not an actual problem since the size we're talking is hardly a drop in today's storage ocean, but it _does_ feel kinda weird that the single largest file in my plugin folder is @lervag's thesis ;)

One thing you could do is simply move all tests into a separate repository? I don't think they _need_ to be in this repo since you're not using Github Actions for unit testing(?).

That might make your workflow a bit more tedious, though, although including it as a submodule might alleviate _some_ of the friction (after setup).

**Comment by lervag** [comment]
> To be honest, this is an issue I've thought about on and off as well -- it's not an actual problem since the size we're talking is hardly a drop in today's storage ocean, but it _does_ feel kinda weird that the single largest file in my plugin folder is @lervag's thesis ;)

Haha, yes, I do agree. Shameless stuff. :p

> One thing you could do is simply move all tests into a separate repository?

> That might make your workflow a bit more tedious, though, although including it as a submodule might alleviate _some_ of the friction (after setup).

It's not such a bad idea, actually. I'm not sure how smooth it would be, though. Having the tests in the same repo does have the benefit of allowing the README banner, as well as automated tests that are displayed in the PR UI.

> I don't think they _need_ to be in this repo since you're not using Github Actions for unit testing(?).

I do use Github Actions for unit testing:
* https://github.com/lervag/vimtex/actions
* https://github.com/lervag/vimtex/blob/master/.github/workflows/main.yml

----

Still, I would assume that reducing the number of files by half at least is a start, right?

**Comment by clason** [comment]
Submodules is definitely a bit more work (although it should work by adding `run: git submodule update --init` to your workflow after checkout), so I totally understand not wanting to rock your current working workflow! (👍 on the unit tests)

An alternative is to use a [sparse checkout](https://git-scm.com/docs/git-sparse-checkout), but that's client side -- maybe an option for those who really care about it?

A compromise could be to have a separate branch without the tests that people can check out (something like the reverse of https://stackoverflow.com/a/42037020). If you do proper releases, that might be somewhat reasonable -- have a `release` branch and a `develop` branch, where you periodically pull commits from `develop` into `release` (minus the tests) when you deem it good. Then point people to the `release` branch, and cutting-edge afficionados (and your GH Actions) can still follow `develop` (or `master`). But, again, more work for you.

And, yes, half the files is twice the goodness :)

**Comment by lervag** [comment]
Ok, I've removed the `issues/...` files. This should make it at least somewhat faster to get the files. I'm not sure if I want to separate the `test/tests` from the main repo, though; it feels more of a pain than it is worth IMHO.
