### ISSUE TITLE
Problem Context Math

### ISSUE THREAD

**Issue by AndreaDiPietro92** [lervag/vimtex#1863]
Hello. 
I use Ultrasnip for snippets and, with the last vimtex update it doesent work. In particular the function for the math context

```
global !p
texMathZones = ['texMathZone' + x for x in ['A', 'AS', 'B', 'BS', 'C', 'CS', 'D', 'DS', 'E', 'ES', 'F', 'FS', 'G', 'GS', 'H', 'HS', 'I', 'IS', 'J', 'JS', 'K', 'KS', 'L', 'LS', 'DS', 'V', 'W', 'X', 'Y', 'Z', 'AmsA', 'AmsB', 'AmsC', 'AmsD', 'AmsE', 'AmsF', 'AmsG', 'AmsAS', 'AmsBS', 'AmsCS', 'AmsDS', 'AmsES', 'AmsFS', 'AmsGS' ]]

texIgnoreMathZones = ['texMathText']

texMathZoneIds = vim.eval('map('+str(texMathZones)+", 'hlID(v:val)')")

texIgnoreMathZoneIds = vim.eval('map('+str(texIgnoreMathZones)+", 'hlID(v:val)')")

ignore = texIgnoreMathZoneIds[0]


def math():
	synstackids = vim.eval("synstack(line('.'), col('.') - (col('.')>=2 ? 1 : 0))")
	try:
		first = next(i for i in reversed(synstackids) if i in texIgnoreMathZoneIds or i in texMathZoneIds)
		return first != ignore
	except StopIteration:
		return False
endglobal
```
with the previous version of vimtex all works perfectly. Thank you for the support.

**Comment by lervag** [comment]
Yes, this is "expected": The latest update brings major changes, see the release notes.

In particular, the math zones are no longer named `texMathZone..`. I think the following should work quite well:

```python
texMathZones = ['texMathRegion' + x for x in ['', 'X', 'XX', 'Env', 'EnvStarred', 'Ensured']]
texIgnoreMathZones = ['texMathTextArg']
```

**Comment by AndreaDiPietro92** [comment]
Thank you so much!

**Comment by lervag** [comment]
My pleasure! :)

**Comment by Tongzhoutz** [comment]
Perfect! It does work on my nvim! Thanks for taking care of it!

**Comment by lervag** [comment]
Hi all: Please note that the newly released v2.1 reverts the naming scheme `tex{type}Region` back to `tex{type}Zone`, which means the code should now be:

```python
texMathZones = ['texMathZone' + x for x in ['', 'X', 'XX', 'Env', 'EnvStarred', 'Ensured']]
```

**Comment by AndreaDiPietro92** [comment]
Thank you..

**Comment by TornaxO7** [comment]
Where can I read all changes or where do you add this informations?

**Comment by lervag** [comment]
@TornaxO7 The best sources are:

* The [release notes](https://github.com/lervag/vimtex/releases). The first "release" was v1.0 in July this year, so this particular source is recent. However, I plan to use this as the main source for changes and important version related messages in future development.

* There is a type of changelog in the docs, see `:help vimtex-changelog`. However, this is mainly to document changes where e.g. options change name. It is not really that relevant any more since I now make more proper release notes and versioning.

* The full [Git commit log](https://github.com/lervag/vimtex/commits/master). Every detail, but of course way to verbose for most people.

**Comment by TornaxO7** [comment]
@lervag Nice! Thank you for the information! According to the release notes there are multiple zones, am I right? If yes, where can I look them up?

**Comment by lervag** [comment]
@TornaxO7 Not quite sure what you mean. But perhaps you are looking for `:help vimtex-syntax` and `:help vimtex-syntax-reference`?

**Comment by TornaxO7** [comment]
@lervag In your release notes, you wrote this sentence:
> The syntax plugin used the **naming scheme** tex{type}Region for syntax regions, e.g. texMathRegion for math-mode regions.

**Comment by lervag** [comment]
Yes. But what are you actually interested in; what do you want to do? If you want to look up all the different groups, then you should look in the source code (which is also explained in the docs I already referred to).

**Comment by TornaxO7** [comment]
For example adding to my snippets that it should add automatically `\item` if I'm in an `itemize` environment.

**Comment by TornaxO7** [comment]
Yeah! I found it under `:help vimtex-syntax-reference`. Awesome! :)

**Comment by lervag** [comment]
> For example adding to my snippets that it should add automatically `\item` if I'm in an `itemize` environment.

Essentially, your questions make a good example of the x-y problem, because it is _much_ easier to answer that specific question than the original ones, and the answer is not related to the original ones. It is not surprising that this _is_ surprising to you, though.

So: Most environments do _not_ make zones similar to math mode. There is really no need for that. Thus, you can't use the same mechanism to detect e.g. the `itemize` environment. Instead, you can use the function `if vimtex#env#is_inside('itemize') ...`.

We've now "hijacked" this issue thread for long enough. Feel free to open a new issue if you have more questions. I don't mind answering and helping, but I do prefer to keep threads separate, as that helps "discoveribility" when you search for older issues/topics.
