### ISSUE TITLE
Missing the corresponding '.aux' of subfiles missing in the build folder for a multi-file project

### ISSUE THREAD

**Issue by xarthurx** [lervag/vimtex#1879]
**Issue**

**background:** I'm doing a multi-file project with cross-file reference.

The package `zref-xr` requires the corresponding `.aux` file to obtain reference information and handle the linking correctly.

However, `vimtex` cannot handle the linking correctly when using the `subfile` package. But things are file when using the `\include{sub-file}` approach.

I examined the `build` folder and found that the reason seems to be that `vimtex` only generate the `main.aux` file but not any other `.aux` file when using the `subfile` package.
(If not using `subfile` package, those corresponding `aux` files are generated.)

**main.tex**
```tex
\documentclass[a4paper,11pt,openright]{memoir}
% \let\printglossary\relax
% \let\theglossary\relax
% \let\endtheglossary\relax

\usepackage[utf8]{inputenc}

\usepackage[colorlinks=true]{hyperref}
\usepackage[user,xr]{zref}

\zexternaldocument*{./chap1}
\zexternaldocument*{./chapter/chap2}

\usepackage{subfiles}

\begin{document}

%\subfile{chap1}  % no 'aux` file
%\subfile{chapter/chap2}  % no 'aux` file
\include{chap1} % has 'aux` file
\include{chapter/chap2} % has `aux` file

\zref{cha:main-chap}
\zref{cha:sub-chap}

\end{document}
```

**chap1.tex**
```tex
\documentclass[main.tex]{subfiles}

\begin{document}
\chapter{main folder chapter}%
\label{cha:main-chap}

This is the main-folder test chapter.

\end{document}
```

**chap2.tex**
```tex
%\documentclass[../main.tex]{subfiles}

%\begin{document}

\chapter{sub folder chapter}%
\label{cha:sub-chap}

The is the chap file in the sub folder.
%\end{document}
```

Any thoughts?

**Comment by xarthurx** [comment]
I happen to encounter this question and answer:

https://tex.stackexchange.com/questions/246/when-should-i-use-input-vs-include

Would it be related to the way how `vimtex` is processing different files? (creating `aux` file of each sub file?)

**Comment by lervag** [comment]
> Any thoughts?

Yes, I think this is not a Vimtex issue. Vimtex does not compile anything, and if you have problems with compilation of your LaTeX project, then that is due to either 1) errors in your TeX, or 2) problems with you TeX related programs.

So, again: Vimtex does not process your files. Vimtex uses `latexmk`, which is a LaTeX build tool, which in turn uses `pdflatex` by default. So, if you document does not compile correctly, then I think it is because you are doing something wrong with the packages you are using. I'm not really familiar with the `zref-xr` package, and so it is difficult to assist you further with that. Sorry.

**Comment by lervag** [comment]
I'm closing the issue, as I consider it not really a Vimtex issue, but feel free to respond and continue the thread.
