### ISSUE TITLE
Auto-indent \item in paralist (compactitem, compactenum, etc.)

### ISSUE THREAD

**Issue by applesud** [lervag/vimtex#1887]
In paralist environments (eg compactitem), `\item` is not indented by auto-indentation. It is in a standard itemize environment. It might be worth adding support for some of these popular alternative list environments.

**Expected Behaviour**
```
\begin{compactenum}
    \item ...
\end{compactenum}
```

**Actual Behaviour**
```
\begin{compactenum}
\item ...
\end{compactenum}
```

**Behaviour in Default List Environments**
```
\begin{itemize}
    \item ...
\end{itemize}
```

**Comment by lervag** [comment]
This is actually already supported through the option `g:vimtex_indent_lists`.

**Comment by applesud** [comment]
Oh, that's great, and thanks for getting back so fast. Is there any reason that this isn't enabled by default? It could be helpful.

**Comment by lervag** [comment]
> Oh, that's great, and thanks for getting back so fast. Is there any reason that this isn't enabled by default? It could be helpful.

Yes; the first and most important reason is that I didn't know of these environments. I think there are probably way more similar environments, including custom ones that people may make for themselves. So, this option exists for that specific flexibility.

Vimtex has existed since 2013, and this is the first time I've heard of `compactenum`: if you think this is so common it should be in the default list, then please give me some more references/proof.
