### ISSUE TITLE
Error while try to compile with  vimtex on vim (8.2) on Kubuntu 20.10

### ISSUE THREAD

**Issue by NOUBISSI** [lervag/vimtex#1888]
I use to have vimtex on Kubuntu 19.10. Everything was working fine. Lately, I installed Kubuntu 20.10 on my computer, used Vundle to install vimtex. Everything went fine except when I try to compile, I show me and error: 

```
vimtex: Deprecated option(s) detected!
        - g:vimtex_compiler_callback_hooks
        Please see `:help OPTION` for more info!
```

I When to my .vimrc file and remove (" let g:vimtex_compiler_callback_hooks = 0), But the problem did not get away.

Can you help me solve this ?
Thanks

vim version:
`VIM - Vi IMproved 8.2`

**Comment by NOUBISSI** [comment]
I was missing latexmk, but the error message was not clear. After install latexmk, everything is working fine.

**Comment by lervag** [comment]
> I went to my `.vimrc` file and removed `let g:vimtex_compiler_callback_hooks = 0`, but the problem did not get away.

With "the problem", I assume you mean the error message you posted. So, this does not make sense, because if you remove the option from your vimrc, the error message should of course also go away. Perhaps you forgot to restart Vim? Or perhaps you are refering to another problem?

> I was missing latexmk, but the error message was not clear. After install latexmk, everything is working fine.

The error message you are showing is not related to `latexmk`, but to the fact that you had a tried to specify a deprecated option.

I'm glad to hear things are working now. But please, take the time to read at least part of the documentation. The introduction is not too long, and should give an overview of the most important information.
