### ISSUE TITLE
VimtexCompile not triggered 

### ISSUE THREAD

**Issue by hejops** [lervag/vimtex#1891]
**Issue**
The autocommand `au! User VimtexEventInitPost VimtexCompile` is not triggered. It used to be triggered, but I recently changed my configs and somehow it stopped working.

**Commands/Input**
From https://github.com/lervag/vimtex/issues/234#issuecomment-398071943
```
.vimrc
au! User VimtexEventInitPost VimtexCompile
au! User VimtexEventInitPost VimtexView
au! User VimtexEventCompileSuccess call ZathuraSearch()
au! User VimtexEventQuit call vimtex#compiler#clean(0)

let g:vimtex_view_forward_search_on_start = 1
let g:vimtex_view_automatic = 0
let g:vimtex_view_method = 'zathura'
```

**Observed Behaviour**
Compilation should start automatically, with the message `Compilation started in continuous mode`.

**Expected Behaviour**
Compilation must be run manually.

**Output from VimtexInfo**
```
System info
  OS: Manjaro Linux
  Vim version: VIM 8.2 (1-1989)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

vimtex project: 3034
  base: 3034.tex
  root: /home/user/school/3034 qm
  tex: /home/user/school/3034 qm/3034.tex
  out: /home/user/school/3034 qm/3034.pdf
  log: 
  aux: 
  fls: 
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: Zathura
    xwin id: 54525955
    cmd_forward_search: zathura --synctex-forward 410:1:'3034.tex' '3034 qm/3034.pdf'
  qf: LaTeX logfile
    addqflist: 58
    fix_paths: 59
    set_errorformat: 57
  document class: article
  packages:
    amsmath
    graphicx
```

**Comment by lervag** [comment]
The problem is due to your config, specifically, because you are doing `autocmd!` instead of `autocmd`, see `:help :autocmd` and read about the `!`.

Generally, I strongly suggest you put your vimrc autocommands in one (or more) group(s), e.g.:

```vim
augroup vimrc_vimtex
  autocmd!
  autocmd User VimtexEventInitPost VimtexCompile
  autocmd User VimtexEventInitPost VimtexView
augroup END
```

The first `autocmd!` is used to clear the group. This also has the benefit that if you resource your vimrc file, you will not add redundant autocmds.

**Comment by hejops** [comment]
Thanks for the clarification. Sometimes this causes two zathura windows to be opened, one of which will produce the error "Document contains no pages". Do you know why this might be the case?

**Comment by lervag** [comment]
Not directly, but I suspect it can be a "race" condition. Perhaps `VimtexCompile` starts the viewer implicitly through latexmk (but it shouldn't, since you use `g:vimtex_view_automatic = 0`) or through a callback? I think the latter might be the reason: the `VimtexCompile` starts compilation in the background, and this might issue a callback that does a forward search or something similar? I have to admit, I am not sure, and to investigate it would be necessary to reproduce the problem.

I would like to propose that you don't open the viewer automatically in this way, though, and instead open it when you need it with `\lv`?
