### ISSUE TITLE
Use Location List instead of Quickfix List

### ISSUE THREAD

**Issue by salutis** [lervag/vimtex#1894]
Is it possible to make Vimtex use the _Location List_ instead of the _Quickfix List_ for displaying LaTeX warnings and errors? I am looking for something like the following in ALE but in Vimtex:

```
ALE will report problems with your code in the following ways, listed with
their relevant options.

* By updating loclist. (On by default)             - |g:ale_set_loclist|
* By updating quickfix. (Off by default)           - |g:ale_set_quickfix|
```

**Comment by lervag** [comment]
It is not currently possible. I'm not sure if it has any real value to implement it. The location list is specific to a window, but the LaTeX errors/warnings are relevant to any related buffer. Thus, the quickfix window really is more appropriate. Personally, I don't really see any value in adding an option for this. As explained above, the qf list is appropriate, and the location list is then available for other kinds of linting (e.g. grammar or specific syntax checkers).

**Comment by salutis** [comment]
@lervag 

I see. Thank you for explaining the matter to me. To describe my situation: I often have multiple _unrelated_ documents open in Vim, such as a written assignment, a personal progress list, and a learning journal entry, and VimTeX errors show up jumbled in the global Quickfix List. ALE (Asynchronous Lint Engine) uses the Location List by default which makes more sense to me, as the files I have open are not necessarily part of a single “project” that is compiled together. On top of that, seeing _both_ the Quickfix List and the Location List on a small 13” screen is confusing and unergonomic. Hence, I asked what to do about all this. For now, I “downgraded" ALE to use the global Quickfix List, but I do not like the fact that all warnings and errors (LaTeX, C, Bash, Make, …) are jumbled up. Am I using Vim “incorrectly"?

**Comment by lervag** [comment]
> I see. Thank you for explaining the matter to me. To describe my situation: I often have multiple _unrelated_ documents open in Vim, such as a written assignment, a personal progress list, and a learning journal entry, and Vimtex warnings and errors show up jumbled in the global Quickfix List. ALE (Asynchronous Lint Engine) uses the Location List by default which makes more sense to me, as the files I have open are _not_ necessarily in a single “project” that is compiled together. On top of that, seeing _both_ the Quickfix List and Location List is confusing and not ergonomic on a small 13” screen. Hence, I asked what to do about all this. For now, I “downgraded" ALE to use the global Quickfix List, but I do not like the fact that all warnings and errors (LaTeX, C, Bash, Make, …) are jumbled across unrelated files. Am I using Vim “incorrectly"?

Nah, I won't be the judge of whether anyone uses Vim correctly. Whatever works.

With your type of workflow, it seems better to avoid too much automatic stuff, because it can interrupt/get in the way of your workflow. Perhaps you should disable the automatic opening of the quickfix list with `let g:vimtex_quickfix_mode = 0`? Or, you can also disable `g:vimtex_quickfix_open_on_warning` to specify the list only to open when there are actual errors.

Please notice that there's (at least a slight) difference between the common type of warnings/errors reported by ALE and the ones from Vimtex, in that the ALE linters are typically static linters that only parse your document and report errors. The files are typically not actually compiled/run. With Vimtex (and latexmk), you are _actually_ compiling the document, and the errors and warnings are thus more important. I can understand that there are other ways to look at this, though.

Still, I'm curious if my suggested solution might suffice. Notice that you can always to `\le` (or `:VimtexErrors`) to inspect/open the quickfix list. Thus, if you notice `vimtex: compilation failed!`, then you can simply check the errors manually.

**Comment by salutis** [comment]
@lervag Thank you for your guidance. I will try the suggested configuration options and changes to my workflow. Also, thank you for working on Vimtex [*] — it has been my daily driver for quite a while now, and I cannot get enough of it. The documentation, in particular, is fantastic.

[*] The project should be called VimTeX to make spellcheckers happy. It also looks better and matches all the other projects, including TeX and LaTeX.

**Comment by lervag** [comment]
> @lervag Thank you for your guidance. I will try the suggested configuration options and changes to my workflow. Also, thank you for working on Vimtex [*] — it has been my daily driver for quite a while now, and I cannot get enough of it. The documentation, in particular, is fantastic.

Sorry for the late reply. I'm very happy to hear you like it. And please, feel free to suggest improvements (both general and to the docs)!

> [*] The project should be called VimTeX to make spellcheckers happy. Further, VimTeX looks better (IMO) and matches the standard naming that is used across the ecosystem, including TeX and LaTeX. Lastly, it is mathematically sound. _Proof._ Vim + TeX = VimTeX. QED. rofl

Heh, I tend to agree with you. I recently realized I wanted to be consistent and use the capitalized Vimtex as the proper name, instead of "vimtex". Your proof is also fun. I've been tempted to just accept this, but the pragmatist in me is reluctant to update everything and spend time on "teaching" the new name.

@clason You tend to have opinions, often good ones: what do you think? Should we adopt VimTeX?

**Comment by clason** [comment]
I think the change would be innocuous and certainly looks nice. As long as you don't rename the repository or vimscript functions and options, why not update the branding to something more fun? :) Most searches on the internet are case insensitive, so I don't see a problem there.

(I can't help but add an argument against it: This might be too close to LuaTeX and XeTeX, which are TeX compilers -- so VimTeX might suggest a new engine that uses Vim in some way. I don't really think there's any danger of confusion, though.)

**Comment by lervag** [comment]
Thanks for pitching in. Let's [check what people on Reddit say](https://www.reddit.com/r/vim/comments/lfnnzt/opinions_wanted_should_i_rename_vimtex_to_vimtex/) :)

**Comment by lervag** [comment]
I think the vote was clear, and so I've changed from vimtex and Vimtex to VimTeX.
