### ISSUE TITLE
Specific quickfix window for vimtex only

### ISSUE THREAD

**Issue by yushangakki** [lervag/vimtex#1913]
**Is your feature request related to a problem? Please describe it.**
Vimtex uses quickfix window to display the errors and warnings. Most users, including me, think the quickfix window's height should be small when the window displays error, and this could be done by [qf.vim](https://github.com/lervag/vimtex/issues/1127). However, setting this will make all the quickfix window small. Some plugins use the quickfix window to display TOCs (which is vertical), and in this case, the window is really small to see. I wish there is a way to configure the specific vimtex quickfix window

**Describe the solution you'd like**
Allow user's configuration to write in `vimtex/autoload/qf.vim`, or some guidance on configuring specifically for vertical/horizontal quickfix window. Setting on quickfix's window under vimtex is definitely preferable.

**Describe alternatives you've considered**
Making the TOC window also appear on the bottom, but it is obviously a compromise.

**Comment by lervag** [comment]
> Vimtex uses quickfix window to display the errors and warnings. Most users, including me, think the quickfix window's height should be small when the window displays error, and this could be done by [qf.vim](https://github.com/lervag/vimtex/issues/1127).

I'm following so far, although I think it is slightly far fetched to claim "most users" without evidence.

> However, setting this will make all the quickfix window small. Some plugins use the quickfix window to display TOCs (which is vertical), and in this case, the window is really small to see. I wish there is a way to configure the specific vimtex quickfix window

Now I don't follow. Which plugins? And why do you think Vimtex should change to accomodate those plugins instead of the other way around? As far as I can understand, Vimtex treats the quickfix list correctly and leaves it to the user to customize the behaviour (e.g. through qf.vim).

> **Describe the solution you'd like**
> Allow user's configuration to write in `vimtex/autoload/qf.vim`, or some guidance on configuring specifically for vertical/horizontal quickfix window. Setting on quickfix's window under vimtex is definitely preferable.

I don't understand what you want. Which configuration? As mentioned above, I think customization of the quickfix window should in general be left at the user level and not be included in Vimtex.
