### ISSUE TITLE
Support continuation indent in TeX documents

### ISSUE THREAD

**Issue by nawordar** [lervag/vimtex#1927]
I would like to indent long text in macro like this:
```latex
\caption{Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
         tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
         veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
         commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
         velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
         occaecat cupidatat non proident, sunt in culpa qui officia deserunt
         mollit anim id est laborum.}
```
I also have a custom macro, that I use like this:
```latex
\userstory{%
  as      = {a user},
  iwantto = {write \LaTeX},
  sothat  = {I can write Lorem ipsum dolor sit amet, consectetur adipiscing
             elit, sed do eiusmod tempor incididunt ut labore et dolore magna
             aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
             laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
             dolor in reprehenderit in voluptate velit esse cillum dolore eu
             fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
             proident, sunt in culpa qui officia deserunt mollit anim id est
             laborum.},
}
```
I have noticed, that actually `.bib` files are already indented like this. Would that also be possible with TeX files?

**EDIT** Just after writing that issue, I noticed a problem with that. Some macros, like `\textbf` are used mostly inline, so they shouldn't be indented like this. Maybe it would be better to indent only macros starting at a line beginning or text inside parenthesis in key-value arguments.

**Comment by lervag** [comment]
> I would like to indent long text in macro like this:
> ...
> **EDIT** Just after writing that issue, I noticed a problem with that. Some macros, like `\textbf` are used mostly inline, so they shouldn't be indented like this. Maybe it would be better to indent only macros starting at a line beginning or text inside parenthesis in key-value arguments.

Exactly: Indents are actually quite complex. In some cases, it seems nice to have indents align at the opening `{` (as in your first example). But then you notice this does not hold for all commands/macros, as you point out in your last comment. In fact, as far as I can tell, there is no good way to provide a general set of rules that would indent like this and handle all  cases properly.

Vimtex does handle indents, e.g. increasing indents in environments and for various delimiters (see e.g. `g:vimtex_indent_delims`). But I don't see a simple way to add the type of indent rules you are looking for here. I'm not saying it is impossible, but I think it is difficult and would require serious thought and effort to implement. Also, it could result in a feature that is opinionated.

So, from my point of view, it seems not so interesting to invest my time in, unless there is a clear interest from the "larger" community for improved indentation in this direction.

> I have noticed, that actually `.bib` files are already indented like this. Would that also be possible with TeX files?

Yes, I think this makes more sense for `bib` files, because the syntax is _much_ simpler and indent rules are as a result easier to define.
