### ISSUE TITLE
Move auxiliary files to a temp directory

### ISSUE THREAD

**Issue by agentfire170** [lervag/vimtex#1942]
Windows 10, latest version of Neovim

I read through the documentation and stumbled upon $VIMTEX_OUTPUT_DIRECTORY, which is able to move all of the output files to a different temp directory, but is there a way to keep the .pdf output file in the same directory as the .tex file? I don't want to delete these files as I understand that they are useful for compilation, but I want to "hide" them by moving them to another folder.

**Comment by lervag** [comment]
Sorry, this is not possible. That is, `:help g:vimtex_view_use_temp_files` exists and might work as a relevant solution. It is not exactly what you ask for, but related.

The main problem is that the output directory feature is not really handled by Vimtex, it is only _respected_ by Vimtex. The option is really a part of latexmk (which passes it on to pdflatex/xelatex/etc.). There is an `aux_dir` option for latexmk, but it is only available for MikTeX, and so I have not invested any time in respecting that because I don't use Windows (and MikTeX) myself.
