### ISSUE TITLE
[Question] Documentation of code

### ISSUE THREAD

**Issue by TornaxO7** [lervag/vimtex#1954]
This is just a question: I'm very interested in this plugin and I'm wondering, if I could help a little bit. Is there a documentation of your plugin or do I have to go through all files?

**Comment by lervag** [comment]
I would really not mind help at all, and I will be glad to consider and help with pull requests!

There is, unfortunately, not a lot of code documentation. However, I did write about the structure in the main docs, see `:help vimtex-code`. This is quite dated, but it still holds true. But it is minimal, and so it might not help much.

Documentation is hard, and I've prioritized to document the user aspects. I try hard to make the code maintainable and well written. I probably fail at times, and things I think are clear and obvious when I write it turns out to be confusing even for me a couple of years later. But still, I think I am also somewhat successful. I think a lot of things are quite clear. Still, some aspects are really quite complicated. For instance, to understand the full initialization cycle, you will probably need to understand a lot of vimscript features.

I've started to write some documentation for a more public API, see `:help vimtex-code-api`. But this is also, again, meant to be user specific, not developer specific. Thus, only functions that could be interesting to a user should be documented here.

So, to conclude: Yes, you will have to read the code, as there is not a full documentation. However, you don't need to study all of the code to be useful, it should suffice to find the right places for specific problems. And if things are not clear, feel free to let me know and I can help. I'm also available on Gitter/Element for DMs.

**Comment by TornaxO7** [comment]
Hehe, well I think that I've got an idea, what I could do for this plugin: A *little* (like filestructure, file content and so on)  dev-documentation of this plugin :)

**Comment by TornaxO7** [comment]
I'll close this issue and create a fork in the next days if I have some free time. Thank you for your fast respond :)

**Comment by lervag** [comment]
> Hehe, well I think that I've got an idea, what I could do for this plugin: A _little_ (like filestructure, file content and so on) dev-documentation of this plugin :)

Yes, that looks useful. You'll want to also read the [`CONTRIBUTING.md`](CONTRIBUTING.md) file, then, as it might also need a touch if you look into dev-documentation.

> I'll close this issue and create a fork in the next days if I have some free time. Thank you for your fast respond :)

Great, thanks. And no problem, I try to be responsive in general (I don't always succeed, of course). And I try to prioritize when people offer to spend their own time to help improve things :)
