### ISSUE TITLE
Automatically reload mupdf after compilation

### ISSUE THREAD

**Issue by scrouthtv** [lervag/vimtex#1976]
**Is your feature request related to a problem? Please describe it.**
I recently switched to mupdf as a pdf viewer, because it is very small and simplistic. When I use `vimtex` to write tex files and compile them in vim, it automatically opens, which is good. However, the pdf view doesn't update automatically. So every time after I've changed something in my tex file, I have to switch to the mupdf window, press `r` to reload and switch back to vim.

**Describe the solution you'd like**
I'd like `vimtex` to automatically update the pdf preview after compilation.

**Describe alternatives you've considered**
I could also use a different pdf viewer which does this automatically. However, I wasn't able to find a good pdf viewer that was simplistic and could do my task.

**Additional context**
Another process can update mupdf by sending a `SIGHUP` to the mupdf process.

**Comment by lervag** [comment]
> However, the pdf view doesn't update automatically. So every time after I've changed something in my tex file, I have to switch to the mupdf window, press `r` to reload and switch back to vim.

You did not provide any details on your system and setup. MuPDF should be updated automatically by a callback with the use of xdotools. Do you have that installed?

> Another process can update mupdf by sending a `SIGHUP` to the mupdf process.

Yes, this may be different mechanism for updating MuPDF. However, xdotool also allows to send arbitrary keys, which allow forward search (to go to the corresponding page). Thus, I think it is better to rely on xdotools.

**Comment by scrouthtv** [comment]
- `xdotool` is installed
 - I have to manually press `r` for changes to take effect after compilation. 
![Peek 2021-03-05 09-30](https://user-images.githubusercontent.com/23227405/110088655-6b603b80-7d95-11eb-89fe-6046d2d2ce54.gif)

Maybe it's sending the wrong key? I think for forward search, the page already has to be reloaded.

If I remember correctly, in an older version of `vimtex`/`mupdf`, refreshing would work (must be one or two years ago), however it broke after some update.

**Comment by lervag** [comment]
This works as expected on my end. Can you provide a fully minimal example? Eg. something like this:

```tex
% test.tex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```

```vim
" test.vim
set nocompatible
let &rtp = '/path/to/vimtex,' . &rtp
filetype plugin indent on
syntax enable

let g:vimtex_view_method = 'mupdf'
```

Now, in a terminal, with `vim --servername vim test.vim test.tex`; can you still reproduce the problem?

Which version of MuPDF? xdotool? Vim? etc...

**Comment by scrouthtv** [comment]
> `let g:vimtex_view_method = 'mupdf'`
If I add this one line, everything works as expected. Without it, auto reloading does not working.

> Which version of MuPDF? xdotool? Vim? etc...
```
xdotool 3.20160805.1-3
mupdf 1.18.0-1
neovim 0.4.4-1
```
`vimtex` is on 3b2993a92fff405c3e3c0dabb7e441599accf791 and `vim-plug` on `0.10.0`.

**Comment by scrouthtv** [comment]
> Let me check why

Found it:
My config consists of multiple files (e. g. `~/tex.vim`, ...):
```
let g:vimtex_view_method = 'mupdf'
```

Now in my main `vimrc`, if I do
```
source ~/tex.vim
```
It works as expected.
However, if I do
```
autocmd FileType tex source ~/tex.vim
```
It does **not** work.

Even if I open a tex file and do `:echo g:vimtex_view_method`, I get `mupdf`, however, it won't reload upon saving.

**Comment by lervag** [comment]
> > `let g:vimtex_view_method = 'mupdf'`
> 
> If I add this one line, everything works as expected. Without it, auto reloading does not working.

> My config consists of multiple files (e. g. `~/tex.vim`, ...):
> ...
> Do you have any idea why?

I don't quite understand your configuration. You have not given any details on it (except that you use different files with `autocmd`s to source them).

One possible reason is that `autocmd FileType tex` will add code that probably runs _after_ VimTeX is loaded. If that's the case, then default settings will be used. If MuPDF is also a default viewer on your system, it might be used with the defaults (through `xdg-open` or similar).

So, there is a reason why the issue template asks users to provide minimal examples: The issue in your case is very likely due to your configuration, and I will not be surprised to learn that you are doing things that are not quite right. One particular example: Why do you use `autocmd FileType tex` instead of adding the `tex.vim` file to your personal `~/.vim/ftplugin` folder? That's what it's for in the first place. Probably, because you are not aware of these things (which is not that surprising), so I hope my comment might be of help.

Unless what I already wrote does help: I propose as a next step that you provide a minimal example similar to what I already proposed in my last comment. If I can't reproduce your issue, then it is also very hard to help figure it out.

**Comment by scrouthtv** [comment]
> a minimal example
1. Create these files
```
" ~/.vimrc
call plug#begin()
Plug 'lervag/vimtex', {'for': 'tex'}
call plug#end()
autocmd FileType tex source $HOME/tex.vim
```
```
" ~/tex.vim
let g:vimtex_view_method = 'mupdf'
```
```
% ~/test.tex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```
2. Open vim and run `:PlugInstall`.
3. Close and open `vim test.tex` and press `\ll`. `mupdf` should open displaying the pdf with **one** line of *Hello world!*.
4. Press `2jyyp:w<cr>`. A second line of *Hello World!* should appear.
5. Wait for the line `VimTeX: Compilation completed`.
6. The pdf isn't updated (I'd expect there to be a second *Hello world!*, however, there isn't).

**Comment by lervag** [comment]
Thanks for the minimal example; I think it does show exactly what I wrote in my previous response. You can confirm this yourself: After you've opened `test.tex` in step 4, do `:scriptnames`. Notice how the custom `tex.vim` file is loaded as the very last file. This means that the setting `g:vimtex_view_method` is not defined when VimTeX is loaded, which is why the setting is not properly applied.

By the way: you don't need `, {'for': 'tex'}` with vim-plug for VimTeX. VimTeX is a proper filetype plugin, which means that it does not do anything except when necessary.

> > which is not that surprising
> 
> wow.

Not sure what you mean with "wow". Perhaps my wording made it look like an insult, and if so, I'm sorry - that was not my intent. My point with "which is not that surprising" was that there is a whole lot of stuff to learn with Vim (or neovim). Most people don't even read the user manual, and even if they do, it is easy to miss the part in the user manual that explains these things.

**Comment by scrouthtv** [comment]
In this case thank you for your help!

**Comment by lervag** [comment]
No problem. :)
