### ISSUE TITLE
<Plug>(vimtex-labels-open) missing

### ISSUE THREAD

**Issue by juanMarinero** [lervag/vimtex#1992]
**Commands/Input**
`\ly` or `:execute "normal \<Plug>(vimtex-labels-open)"`

Empty results searching:
- `\ly` in `:Maps`
- [vimtex.vim](https://github.com/lervag/vimtex/blob/master/autoload/vimtex.vim#L281)
- `:help vimtex-labels`

**Observed Behaviour**
Nothing

**Expected Behaviour**
Show table of Tex labels (as described in [wiki](https://github.com/lervag/vimtex/wiki/usage))

**My guess**
`\lt `+ `L` == `\ly` , thus, I guess `\ly` was deleted from plugin, but unintentionally not removed from wiki-docu nor [doc/vimtex.txt](https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt#L3643)

**Workaround**

`:help vimtex-toc`
outputs:
```
TABLE OF CONTENTS                                                  *vimtex-toc*

|vimtex-toc| displays a table of contents (ToC) for the current LaTeX document.
The ToC entries may be activated/jumped to with <cr> or <space>. There are
currently four different "layers" of entries:

- content  This is the main part and the "real" ToC
- todo     This shows TODOs from comments and `\todo{...}` commands
- label    This shows `\label{...}` commands
- include  This shows included files
```
Actually running it (`\lt`), it's advised (see next code copied) to press `L` to go to labels section (actually toggle showing only labels)
```
Layers:  L  label
         I  include
         T  todo
         C  content
```
For behaviour as docu add to `~/.vimrc` (btw maybe the docu recommended style is better: `nmap <space>li <plug>(vimtex-info)` instead of my `:execute`):
```
    " remaped if VimTex plugin NOT comes with it
    " nunmap \ly
    " nunmap \lY
    " nmap \ly :execute "normal \<Plug>(vimtex-labels-open)"<CR>
    " nmap \lY :execute "normal \<Plug>(vimtex-labels-toggle)"<CR>
    nmap \ly :execute "normal \<Plug>(vimtex-toc-open)"<CR>L
    nmap \lY :execute "normal \<Plug>(vimtex-toc-toggle)"<CR>
    " If other maps use already its fcns, then its not autoreloaded
    " nunmap \lt
    " nunmap \lT
    nmap \lt :execute "normal \<Plug>(vimtex-toc-open)"<CR>
    nmap \lT :execute "normal \<Plug>(vimtex-toc-toggle)"<CR>

```

PD: thank you very much for the plugin!! Running with Zathura is awesome!! 👏👏

**Comment by lervag** [comment]
> `\ly` or `:execute "normal \<Plug>(vimtex-labels-open)"`

You are right, `\ly` and `<plug>(vimtex-labels-open)` does not exist. And the official docs no longer mention this at all. However, if you look at `:help vimtex-toc-custom-maps`, you will see workaround mappings for this.

Please note that I actually don't personally maintain the wiki. It is already a little bit too much work to maintain the code and docs and answer all issues, so I will not attempt to keep the wiki up to date. However, I do think it might have useful information that is provided and maintained by users, which I can endorse. Still, things like this is bound to arise, and I will then strongly encourage users (like you) to update the wiki so that it is aligned with the official docs (i.e. `doc/vimtex.txt` aka `:help vimtex`).

> PD: thank you very much for the plugin!! Running with Zathura is awesome!! clapclap

Thanks, I'm happy you like it and find it useful! :)
