### ISSUE TITLE
ToC fullscreen resize behavior

### ISSUE THREAD

**Issue by evanhorn** [lervag/vimtex#1997]
**Issue**
I have mapped `j` and `k` to `gj` and `gk` to more intuitively (IMO) handle wrapped lines. However, when ToC resize is set to '1' and the window is full screen the vim screen shifts up and the corresponding movement letter (`j` or `k`) is printed below the screen. This behavior only occurs for `gj` or `gk`, not if `j` or `k` are used. If the window is subsequently resized from full screen, or if the ToC is opened while the window is not full screen, `gj` and `gk` will behave as expected, even if the window is expanded to full screen again and if the ToC is closed and reopened later.

**minimal.vim**
```vim
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
let g:vimtex_toc_config = { 'resize' : 1 }
```

**minimal.tex**
```tex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```

**Commands/Input**
Open TeX file full screen in vim, then do `VimtexTocOpen`, then `gj` or `gk`.

**Observed Behaviour**
Vim screen shifts up and `j` or `k` appear below screen.

**Expected Behaviour**
Cursor shifts up or down one line.

**Output from VimtexInfo**
```
System info
  OS: Ubuntu 20.04.2 LTS
  Vim version: NVIM v0.4.3
  Has clientserver: true
  Servername: /tmp/nvimGaUHb5/0

VimTeX project: minimal
  base: minimal.tex
  root: /home/evanhorn/minimal
  tex: /home/evanhorn/minimal/minimal.tex
  out: 
  log: 
  aux: 
  fls: 
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    addqflist: 57
    fix_paths: 58
    set_errorformat: 56
  document class: minimal
```

**Comment by lervag** [comment]
> However, when ToC resize is set to '1' and the window is full screen

The resize option is "brittle", that is, it only works as expected if Vim/neovim is able to actually resize the terminal. You can check this by doing `:set columns+=10` inside Vim in you terminal - the terminal window should expand by 10 columns.

If you do `:set columns+=...` on a full screen window, then I have to admit "all bets are off" - I don't know what will happen. I don't think it is worth the effort of debugging this, because I think it is a relatively little used and very specific type of behaviour. Also, controlling "the external environment" from within Vim is hard and making it "just right" is very hard.

Note: I am not able to reproduce your issue directly. That is, if I open a terminal (I use urxvt), make it fullscreen, then open Vim and try to reproduce, everything seems to work as expected. However, I can reproduce it when I run Vim inside tmux, in which case Vim does _not_ resize the window with `:set columns+=10`. In this case, after `\lt`, there are problems because the `'columns'` variable no longer corresponds to the real amount of columns. I assume this is the real problem on your end. If there was a good way to inspect the real number of columns, then I could fix it. But I don't think there is.

For more info, see also `:help 'columns'`.
