### ISSUE TITLE
Fail to use vimtex on Windows10

### ISSUE THREAD

**Issue by EvaWongAsuka** [lervag/vimtex#1998]
**Issue**
Hi, I am new to vim, and I got a silly question. I am using gvim8.2 on Windows 10, and I got vimtex installed through vim-plug, and I have TexLive installed. However I cannot compile any tex document by `\ll`.

Here is my `_vimrc`:

```vim
call plug#begin('D:\ProgramFiles\Vim\vim82\plugged')
Plug 'lervag/vimtex'
Plug 'xuhdev/vim-latex-live-preview', {'for':'tex'}
call plug#end()

let g:vimtex_compiler_latexmk_engines = {'_':'-xelatex'}
let g:vimtex_compiler_latexrun_engines = {'_':'xelatex'}

let $LANG = 'en'  "set message language
set langmenu=en   "set menu's language of gvim. no spaces beside '='


" Vim with all enhancements
source $VIMRUNTIME/vimrc_example.vim

" Use the internal diff if available.
" Otherwise use the special 'diffexpr' for Windows.
if &diffopt !~# 'internal'
  set diffexpr=MyDiff()
endif
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg1 = substitute(arg1, '!', '\!', 'g')
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg2 = substitute(arg2, '!', '\!', 'g')
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let arg3 = substitute(arg3, '!', '\!', 'g')
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  let cmd = substitute(cmd, '!', '\!', 'g')
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction
```

Here is the tex:

```tex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```

**Output from :PlugStatus**
```
vimtex: OK
```

**Output from :h vimtex**
```
E149: sorry, no help for vimtex
```

**Output from :VimtexInfo**
```
E492: No editor command: VimtexInfo
```

It seems that vimtex isn't properly installed, but I am not sure. Even if it is the case, I have no idea how to fix it. Thanks a lot for your time.

**Comment by lervag** [comment]
> Hi, I am new to vim, and I got a silly question.

Welcome to the club :)

> Here is my `_vimrc`: ...

I've updated your description slightly to clean up. Notice a couple of points:

* Don't mix plugin configuration with the `Plug` lines. Some type of configuration can not be done before _after_ the `plug#end()` call.
* You don't need `set nocompatible`.
* No need to set `g:vimtex_compiler_latexrun_engines` unless you actually use `latexrun` - since you say you are new, I would assume you don't need it.
* I would also propose you don't need `vim-latex-live-preview`. LaTeX compilation is not really fast enough for live updates, so IMHO it is better to settle with compilation when you write your files.

So, to your issue: I agree, it seems you did not really properly install VimTeX. Can you try to do `:PlugClean` and `:PlugUpdate`, just to make sure you have the latest version of VimTeX. Feel free to also verify that you can find the VimTeX files under `D:\ProgramFiles\Vim\vim82\plugged\vimtex\...`.

When VimTeX is installed, the help docs should be available.

**Comment by EvaWongAsuka** [comment]
I found out that vimtex wasn't properly installed, and it is now OK, but I'm not clear which step I took fixed it. 

Thanks a  lot for your help! I really really appreciate that.

**Comment by lervag** [comment]
Glad to hear it! :)
