### ISSUE TITLE
Math preview in a floating window: neovim

### ISSUE THREAD

**Issue by JackGin** [lervag/vimtex#2006]
Can we please have a math preview in a floating window, which was introduced in neovim 0.4.4?
Math preview in a floating window is a useful feature found e.g. in VSC+LatexWorkshop.
Thank you!

**Comment by andymass** [comment]
Can you give an example of what this would look like?  I.e., what it looks like in VSC+LatexWorkshop?

**Comment by JackGin** [comment]
Yes, sure. 
![image](https://user-images.githubusercontent.com/21062569/112382187-95ee4600-8cfc-11eb-92f1-c5846b11f40a.png)

**Comment by lervag** [comment]
I'm sorry, but it is not possible. The reason is simple: Vim and neovim are terminal applications and do not support graphics, thus we can't show any compiled samples in a popup like this.

The conceal feature is related, but I'm the first to admit it is not anywhere near as good as that kind of popup.

However, IMHO and personal experience, this is not a very important feature. Two reasons: 1) after working with TeX for some time, it should be quite possible to read most math quite fluently without seeing the end result, and 2) having a PDF viewer opened at the side and having it update when you save is _almost_ as good. It will be slower, but if you don't need to see the result immediately this is not a problem.

**Comment by clason** [comment]
In principle(!), this is doable in neovim using https://github.com/latex-lsp/texlab (a LaTeX LSP server that supports equation previews on `textDocument/hover` requests using markdown inline images) and a neovim GUI that can render markdown in externalized floating windows. (I am not aware that such a GUI exists.)

But: 
1. This only works decently for simple equations and breaks for more complicated equations using macros and packages. (Remember, only TeX (the compiler) can fully parse LaTeX.)
2. Will only ever work on a small subset of supported platforms.

**Comment by lervag** [comment]
Thanks, that's interesting and useful information. I was not aware texlab could do this.

In any case, I think the bottom line is that I will not spend time on this, as I don't see any good way of achieving a good result.
