### ISSUE TITLE
Add an option to stop all tex autoindentation

### ISSUE THREAD

**Issue by usualwitch** [lervag/vimtex#2007]
I am using 13-inch laptop and vimtex+skim both occupy half screen, so the extra indentation vim automatically adds makes the tex code very hard to read.

I searched "indentation" in vimtex help, and find these associate settings:
```
* |g:vimtex_indent_enabled|
* |g:vimtex_indent_bib_enabled|
* |g:vimtex_indent_delims|
* |g:vimtex_indent_ignored_envs|
* |g:vimtex_indent_lists|
* |g:vimtex_indent_on_ampersands|
* |g:vimtex_indent_tikz_commands|
```

I set them all to 0, and then vimtex won't load at tex files! I also tried multiple workarounds on the internet but none of them works. Vim still indents tex files automatically when I'm typing the line. Is it possible to add this feature in vimtex? Thank you so much!

**Comment by lervag** [comment]
Vim has automatic indentation that is not necessarily done by VimTeX. You should read about it in the docs: `:help usr_25` and specifically `:help 25.3`.

If you want to disable VimTeX indentation, then it suffices with `let g:vimtex_indent_enabled = 0` in your vimrc file. You should not touch the other settings. Most of them are not _flags_ and setting them to 0 would probably lead to errors.

So, you are not asking for a feature, but you want to know how to setup Vim to not do auto indentation. The short answer is:

* Disable VimTeX indent with the option as specified above.
* Read `:help 25.3` to learn about indentation and then configure your vimrc appropriately.

FYI: You will probably notice that some settings are activated regardless. This is because Vim ships with an indent script for TeX files, see `:edit $VIMRUNTIME/indent/tex.vim`. This file is loaded automatically as long as you have `filetype indent on` (see `:help :filetype-indent-on`). This script does not seem to have an option to disable it, and it will automatically enable `autoindent`, `nosmartindent` and `indentexpr`.

**Comment by awa5114** [comment]
the `let g:vimtex_indent_enabled=0` doesn't do it for me. I know for sure that VimTeX is responsible for adding indents because when I disable the plugin entirely by commenting the `call plug#begin()` to `call plug#end()` block things go back to normal. I have `set autoindent` in my `vimrc`, and I'd like to keep the simple indentation behavior that it provides.

**Comment by awa5114** [comment]
Nevermind. I managed to disable vimtex autoindenting behavior by adding `filetype plugin indent off` to my vimrc file. I'm not sure if this is safe but it seems to work for now...

**Comment by lervag** [comment]
> the `let g:vimtex_indent_enabled=0` doesn't do it for me. I know for sure that VimTeX is responsible for adding indents because when I disable the plugin entirely by commenting the `call plug#begin()` to `call plug#end()` block things go back to normal.

Sorry, but "you know for sure" is not really true, because you are wrong. The guard is here (see below) and ensures that VimTeX will not alter any of your indent settings if you have `let g:vimtex_indent_enabled = 0`.

https://github.com/lervag/vimtex/blob/7bfcfb7b9a734b07e04209350bbe56d7123efb48/indent/tex.vim#L13

> I have `set autoindent` in my `vimrc`, and I'd like to keep the simple indentation behavior that it provides. Any idea what I might be doing wrong?

You may be configuring your VimTeX options at the wrong place. The options must be defined _before_ VimTeX is loaded for a buffer. But to be honest, it is more or less impossible to know what you are doing wrong unless you provide more details.

> Nevermind. I managed to disable vimtex autoindenting behavior by adding `filetype plugin indent off` to my vimrc file. I'm not sure if this is safe but it seems to work for now...

This works, of course, and is safe, but it also means you won't get the normal `set autoindent` behaviour.

----

I notice you've asked some questions in closed threads. Please consider if it might be better to open a new issue. It will prompt you for more information, but adding that information will really be helpful for me to answer you properly. And you can easily refer to related threads/issues by adding `#issue-number` - e.g. #2007 (this might result in a self reference).
