### ISSUE TITLE
Conceal turns on when moving into insert mode

### ISSUE THREAD

**Issue by vuvgaG-dukgu3-wysnox** [lervag/vimtex#2017]
I expected characters to show like `$` and commands like `\textbf`

## Environment Information

- OS: mac
- neovim version: 0.4.4
- SpaceVim version: 1.7.0-dev
- SpaceVim status: 55a7b777

## Screenshots

![image](https://user-images.githubusercontent.com/75189112/113495845-2b06f100-94ec-11eb-99f8-588256702ca8.png)

**Comment by vuvgaG-dukgu3-wysnox** [comment]
https://vi.stackexchange.com/questions/17686/how-to-force-vimtex-to-display-textbf-and-textit-in-insert-normal-mode

Found this incase anyone else hits the issue.

**Comment by vuvgaG-dukgu3-wysnox** [comment]
i've set `let g:tex_conceal = ""` and still nothing.

**Comment by vuvgaG-dukgu3-wysnox** [comment]
When entering insert mode the conceal mean turns back on??

**Comment by vuvgaG-dukgu3-wysnox** [comment]
I've found the toggle option for conceal level option. `<leader> t c`. However i'm still at a missing being able to set this option on startup.

Using the set command `set conceallevel=0` inside a bootstrap function works. However once i enter insert mode the level resets.

**Comment by lervag** [comment]
> I expected characters to show like `$` and commands like `\textbf`

You are looking for `g:vimtex_syntax_conceal_default`, see the help text. You also want to read the docs on conceal in general,  especially `:help 'conceallevel'` and `:help 'concealcursor'`.

> i've set `let g:tex_conceal = ""` and still nothing. (edit: was just in the wrong place)

This option does not have anything to do with VimTeX.

Please note: VimTeX does not have anything to do with SpaceVim. When you opened an issue here, there was already an issue template. For some reason, you chose to ignore that and instead rely on the very unrelated stuff from SpaceVim. For future issues with VimTeX, please, very please, adhere to the VimTeX issue template.

**Comment by lervag** [comment]
> I've found the toggle option for conceal level option. `<leader> t c`, this function works great :). However I'm still at a miss being able to set this option on startup.

This option is neither Vim/neovim specific or VimTeX specific. I guess it is part of SpaceVim.

> Using the set command `set conceallevel=0` inside a bootstrap function works. However once I enter insert mode the level resets.

Yes, you want to read `:help 'concealcursor'`.

**Comment by vuvgaG-dukgu3-wysnox** [comment]
Yeah sorry, I'm just not sure where to get started with using a program like spacevim. It would be great if everything worked out of the box. I'm just trying to help make the information available to the packages that use other packages.

**Comment by lervag** [comment]
It takes a lot of time and effort to learn to properly use Vim, even without plugins. Plugins like VimTeX are meant to improve the editor in certain aspects, but in general, the main features of Vim are still pure Vim. I strongly advice you to first learn to use Vim. When you understand the basics (motions, editing, and especially how to read the help files and manuals!), then you should look into plugins. Of course, feel free to use SpaceVim, but you should still read the Vim docs. And of course, if you use SpaceVim, then you should _also_ read the SpaceVim docs. It is an effort, but it is worth it, because most of the answers you will be looking for are there in these documentations.
