### ISSUE TITLE
install as system package

### ISSUE THREAD

**Issue by dkwo** [lervag/vimtex#2032]
I'm trying to package `vimtex` on Void Linux, as a system package. Although the folder `/usr/share/vim/vimfiles` seems to work for me, I wonder whether it may be better to copy all relevant vimtex folders not directly there, but in a vimtex subfolder, to avoid possible conflicts with other vim plugins that also have similar folder names and may try to (over)write them in the same folder.

This is what I currently have:
```sh
vmkdir usr/share/vim/vimfiles
for dir in after autoload compiler doc ftdetect ftplugin indent media rplugin syntax; do
	vcopy $dir usr/share/vim/vimfiles/$dir
done
```
Do you think there's a better way to install it (as a system package)?

Thanks.

**Comment by lervag** [comment]
> I'm trying to package `vimtex` on Void Linux, as a system package.

Interesting. First note that, In my opinion, Vim plugins should _not_ be installed on a system level, but rather at a user level. Plugins installed on a system level makes it harder to debug various issues - e.g., I've helped people solve problems with VimTeX where the problem was a plugin clash with plugins that they were not aware of because it was installed on the root system.

But, if you know what you are doing, I of course won't object and I'll try and help with the necessary info.

> Do you think there's a better way to install it (as a system package)?

I don't really know Void Linux much, so this will be an answer at a general level. But yes, my suggestion would be to copy the entire `vimtex` folder to a system location (e.g. `/usr/share/vimplugins/vimtex`), then use a system `vimrc` file to add it to your `runtimepath`.

On Arch Linux, there's a `/usr/share/nvim/archlinux.vim` that is sourced at startup that adds the `/usr/share/vim/vimfiles` to the `runtimepath`. You could do something similar. If you start Vim, then do `:scriptnames`, you will see which script is loaded first. See `:help system-vimrc` for more info.

**Comment by dkwo** [comment]
Thanks a lot, this is very helpful.
Although the proposed package seems to work fine, I'm more inclined to take your (and others') advice, and install it at the user level instead.

**Comment by lervag** [comment]
Great, happy to hear it was helpful. :)
