### ISSUE TITLE
Files to build_dir, but pdf in main dir

### ISSUE THREAD

**Issue by vlashada** [lervag/vimtex#2036]
Hi!

I love the plugin, thank you so much for making it!!

I am trying to move all files to a build directory, except the pdf, which I want to have in the main directory. Is this possible? I currently have

let g:vimtex_compiler_latexmk = {
            \ 'build_dir' : 'build',
            \}

**Comment by lervag** [comment]
> I love the plugin, thank you so much for making it!!

Thanks! <3

> I am trying to move all files to a build directory, except the pdf, which I want to have in the main directory. Is this possible?

No, it is not supported, because VimTeX relies on e.g. `latexmk` or similar backends for compiling, and the `build_dir` option behaves as you've already noticed by moving all built files into the directory. For `latexmk`, it uses the `-output-directory` option - see [the latexmk manual](http://mirrors.ctan.org/support/latexmk/latexmk.pdf) for details. There is an alternative option, which you can specify with `g:vimtex_compiler_latexmk.options`: `-aux-directory`, but this only works with MikTeX on Windows, if I understand the manual correctly.

Sorry!
