### ISSUE TITLE
Plug 'lervag/vimtex', { 'for': 'tex' }

### ISSUE THREAD

**Issue by astier** [lervag/vimtex#2057]
Thanks for the great plugin first of all. Does it make sense to use

```vim
Plug 'lervag/vimtex', { 'for': 'tex' }
```

instead of

```vim
Plug 'lervag/vimtex'
```

Does it make it any faster?

**Comment by lervag** [comment]
Glad you like it!

The `{'for': 'tex'}` is completely unnecessary, because VimTeX is already a filetype plugin that is only loaded for tex files. But it is also loaded for `.bib` files and `.cls` and `.sty`, so adding that it is actually preventing VimTeX from loading in some scenarios.

So, the answer is: No.

**Comment by astier** [comment]
Thanks for the clarification.
