### ISSUE TITLE
Many errors when i start to write in tex file

### ISSUE THREAD

**Issue by bsjaramillo** [lervag/vimtex#2087]
So, i dont know how use this pluggin, somebody help me ?
![image](https://user-images.githubusercontent.com/33032851/124394211-06294200-dcc4-11eb-8470-4bd3091a5a83.png)

**Comment by lervag** [comment]
I've never hard about `neotex`; I don't think this is anything related to VimTeX.

**Comment by lervag** [comment]
https://github.com/donRaphaco/neotex

**Comment by bsjaramillo** [comment]
ok, i dont why happend that, i had been deleted that pluggin already. But now, i have only vimtex and i dont know how set up this requirements:
![image](https://user-images.githubusercontent.com/33032851/124396196-bb142c80-dccd-11eb-9ed0-5bb8453c78a7.png)

**Comment by lervag** [comment]
Ok; How do you expect me to be able to help you based on the information you've supplied? Basically, you've only shown an error message that asks you to read `:help g:vimtex_view_general_viewer`. I don't know anything else, except that you initially also had a plugin clash because you for some reason did not first properly remove another plugin.

When you posted the original post, did you notice that there was an [issue template](https://github.com/yongrenjie/vimtex/blob/2065-bib-foldtext/.github/ISSUE_TEMPLATE/issue_report.md)? Please, do read the issue template. It is there for a reason!

Feel free to open a new issue where you provide the details needed for me to help you. I'm locking this thread to avoid the clutter - it will be easier for me to help you if you post a better first post.

Just to be clear, I'm not trying to be rude or dismissive. The main point of the issue template is to guide you to provide the necessary details for me to help you. If I need to ask all the questions from the issue template every time, then I will never have time to actually fix bugs and improve things.
