### ISSUE TITLE
Allow disabling concealing for texttt macro

### ISSUE THREAD

**Issue by nawordar** [lervag/vimtex#2124]
While I like the concealing feature of vimtex, concealing of `texttt` macros doesn't make sense, when the whole LaTeX code is displayed in monospace.

**Comment by lervag** [comment]
Do you mean concealing makes more sense with `\textit{...}`, because the argument is then italized? If so, then I don't quite agree with that. These types of conceals are meant to hide "unnecessary" content.

Or, perhaps you mean that for `\texttt`, the command should be displayed because there is no other clear hint that the argument for `\texttt{...}` is a specific font? Then this might hold for other variants as well?

I personally don't like conceals at all, so I keep them disabled. And so I would be glad to have more opinions/thoughts here from other users who also use conceals. I'll tag some of the people who I've noticed earlier who've raised issues about conceals.

@Konfekt (I believe you [originally proposed to have `\texttt` concealed](https://github.com/lervag/vimtex/issues/1968#issuecomment-788191196)), @whisperity, @Melkster, @patricknraanes, @oblitum

**Comment by nawordar** [comment]
> Or, perhaps you mean that for \texttt, the command should be displayed because there is no other clear hint that the argument for \texttt{...} is a specific font? Then this might hold for other variants as well?

This. With my configuration, I cannot see if the text is wrapped in `\texttt` or not. I've noticed, that it holds for `\textsf` as well.

**Comment by Konfekt** [comment]
I am content if the comment is out of the way and shows up when the cursor is on the line containing `\texttt` (assuming the standard empty value of `&concealcursor`). I would not mind if it was boldfaced or underlined (as it is often used for marking links) instead.

**Comment by Melkster** [comment]
@nawordar What I do is to give the content inside `texttt{}` a special highlight so that they stand out from regular text. I personally link it to `String` because that's how [vim-markdown](https://github.com/plasticboy/vim-markdown) highlights code blocks in markdown.

Here's a minimal config that does that:

```vim
call plug#begin('~/.config/nvim/packages/')
Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_syntax_custom_cmds = [
      \ {'name': 'texttt', 'conceal': v:true},
      \]

set conceallevel=2
hi link texCTextttArg String
```

**Comment by lervag** [comment]
To be clear: I will generally not add a lot of options to control the conceal feature. So in this particular case, I want to find a reasonable compromise that most people agree on. So, either `\texttt` (and possibly similar commands) should be concealed, or it should not be concealed. I don't care so much, so I need help from the community to choose which to prefer.

As @Melkster mentions, it is possible to use custom highlights. His proposed method works, but I would strongly suggest to put custom highlights behind the autocmd event `ColorScheme`, see e.g. [this gist](https://gist.github.com/romainl/379904f91fa40533175dfaec4c833f2f).

The current relevant highlight group is _not_ `texCTextttArg`, but `texStyleArgConc` (which is shared by e.g. `\texttt`, `\textup`, and more).

**Comment by nawordar** [comment]
I somehow missed `g:vimtex_syntax_custom_cmds` in documentation. It does exactly what I wanted. Thank you for all the help!

**Comment by lervag** [comment]
Ah, nice; happy to hear this is resolved!
