### ISSUE TITLE
TOC in multi-file documents with subfiles

### ISSUE THREAD

**Issue by hildensia** [lervag/vimtex#218]
If I have a document with multiple files, using the subfiles package, it confuses the table of contents of vimtex.

Assume the following minimal example:

main.tex:

    \documentclass{article}
    \usepackage{subfiles}

    \begin{document}
    \maketitle
    \section{Test without subfile}
    \subfile{section.tex}
    \end{document}

section.tex:

    \documentclass[main.tex]{subfiles}

    \begin{document}
    \section{Test with subfile} 
    Lorem ipsum...
    \end{document}

If I open the TOC in `main.tex`, it only shows the `Test without subfile` section and in `section.tex` in also only shows `Test without subfile`.

Without the subfile package everything works fine.

**Comment by lervag** [comment]
Interesting. I am not quite sure what the best solution is here, but I know the problem. If you open `main.tex` and then `section.tex`, and finally run `:VimtexInfo!`, you will see that vimtex recognizes these both as separate projects. This is because the subfiles package is respected in order to allow compilation of a subfile document.

However, I guess we need to improve this. The problem is, I am not quite sure how to improve it. Or, rather: I am note quite sure how you want vimtex to work. If you open `sections.tex` and start compilation, should it then compile the subfile or the main file? One solution is to add an option for subfiles detection, which by default is off. Then you can enable this option whenever you want to edit a particular subfile and only compile the current sub section. When you want the entire project to be compiled (and viewed), then you disable the option.

Related issues: #155 and #200

@maxfl Do you have

**Comment by hildensia** [comment]
I like your suggested solution. It could be something like `%!enable_subfile=true` in the first line. I would argue that normally you want the TOC and labels of all files and only if you are working only on a specific subfile you want that single file to be compiled and then the TOC/labels are not that important.

**Comment by maxfl** [comment]
I agree with @hildensia, that you normally expect vim to know that subfile is a part of a larger project and want a global TOC in the same manner when you expect vimtex to know the global bibliography (as it done now). 

From the other hand you expect the current file to be compiled exclusively, because that's why `subfiles` package is needed at all. It's difficult for me to imagine a situation, when someone creates subfiles via `subfile` package, but wants to always compile the main file, because in this case you simply do not need `subfiles`. 

Sometimes it's indeed needed to compile the main file, but I would prefer if this option would be added as a flag to VimtexCompile so one could even have two hotkeys to compile main/secondary file. Since the compilation is anyway done in the same folder it seems not to difficult to do.

I, personally, dislike the idea of persistent switch like `%!enable_subfile=true`. 

I also know nothing about the overhead of implementing any of the suggested options, but I like the idea of light and simple `vimtex`.

**Comment by maxfl** [comment]
`VimtexToc` command could be also done two-faced, with an option to show a local TOC instead of default global or vice-versa.
