### ISSUE TITLE
Can't open viewer for a second file

### ISSUE THREAD

**Issue by cedb12** [lervag/vimtex#222]
Hello!

When editing two independent `.tex` files, `:VimtexView` can only open one viewer at a time. This is a bit annoying when I want to copy an equation from another document for example, and can't look at the compiled PDF file and/or use reverse search to ease the task of locating the corresponding markup in the TeX source.

A workaround that I found is to run continuous compilation, where (I suppose) latexmk handles the viewer.

**Comment by lervag** [comment]
Hi! What are your vimtex settings, and in particular settings for the viewer?

**Comment by cedb12** [comment]
A very minimal vimrc is sufficient for me to reproduce the issue:
```
filetype plugin on
let g:vimtex_view_method = 'zathura'
```

**Comment by lervag** [comment]
I assume you also need to include the plugin somehow (if you have not installed it in the old fashioned, manual way)?

In any case, it is not really surprising that this is happening with `zathura`. The reason is that I use some (simple) `xdotool` magic to prevent `zathura` from opening a new viewer if an old viewer already exists. However, this doesn't work very well when working simultaneously on multiple projects.

I'll take a new look and see if I can improve the magic, but I am not sure that I will be successful.

**Comment by cedb12** [comment]
Right. I usually use vim-pathogen, but I did the minimal testing with vimtex directly cloned into a clean .vim directory.

The issue also happens with MuPDF, but I guess the same comment about `xdotool` applies.

FWIW, I found that after opening the viewer for the first file, `:VimtexInfo` lists viewer parameters for the second file identical to the first one, even before attempting to spawn a viewer for the second one.

**Comment by lervag** [comment]
Thanks! I'll look into it. I think the viewer code detects the viewer and automatically thinks it is valid for the second file when it obviuosly isn't. I think there might be one possible solution that might work in many cases: To separate viewer sessions based on window title.

Also, you are right that the `MuPDF` has the same issue.

**Comment by lervag** [comment]
I found the problem. Please test if the fix I'm pushing in 1 minute works for you.

**Comment by cedb12** [comment]
The fix works! Thanks again.

**Comment by lervag** [comment]
Great, glad to hear it!

**Comment by maxfl** [comment]
Thanks, @lervag, will test it asap.
