### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by msaidf** [lervag/vimtex#223]
When opening tex file, it gives error message "vimtex syntax error" and "error occured while executing "open" action!"
I am using vimtex with gVim on windows 10.

**Comment by lervag** [comment]
Hi! Does this occur with a minimal vimrc file and on a minimal tex file (see `/path/to/vimtex/test/test-minimal`)?

**Comment by xu-cheng** [comment]
FYI, I come across the same error with below config.
```vim
Plug 'lervag/vimtex', { 'for': ['tex'] }
let g:tex_flavor = 'latex'
```

If I remove lazy loading `{ 'for': ['tex'] }` or `let g:tex_flavor = 'latex'`, the problem will be gone.

**Comment by lervag** [comment]
@xu-cheng Could you expand the config into a complete minimal vimrc? I.e. something like

```tex
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
filetype plugin indent on
syntax enable
```

Obviously add the relevant options.

Note: `g:tex_flavor` is not a vimtex specific option! Also, it should not be necessary e.g. when opening a normal and valid LaTeX file.

**Comment by xu-cheng** [comment]
```
$ mkdir -p /tmp/home
$ cd /tmp/home
$ curl -fLo /tmp/home/.nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
$ cat /tmp/home/.nvimrc
call plug#begin('/tmp/home/.nvim/plugged')
Plug 'lervag/vimtex', { 'for': ['tex'] }
call plug#end()
let g:tex_flavor = 'latex'
$ HOME=/tmp/home nvim -c PlugInstall
$ HOME=/tmp/home nvim test.txt
"test.tex" [New File]
Error detected while processing /private/tmp/home/.nvim/plugged/vimtex/after/syntax/tex.vim:
line    8:
vimtex syntax error: please report issue!
Press ENTER or type command to continue
```

**Comment by lervag** [comment]
Strange. I repeated your steps exactly, but I do not get the error message. I tried both with vim and nvim. Vim version 7.4.854, and nvim version compiled just now, i.e. `NVIM 0.0.0-alpha+201509121307 (compiled Sep 14 2015 08:13:46)`.

Note: The error you see occurs because the syntax file is sourced before the main LaTeX syntax file is sourced. That is, the variable `b:current_syntax` should have been already set by the `$VIMRUNTIME/syntax/tex.vim` syntax file.

**Comment by xu-cheng** [comment]
Sorry I may mistype in the comment above, it should be `HOME=/tmp/home nvim test.tex` instead of `HOME=/tmp/home nvim test.txt`.

**Comment by lervag** [comment]
Thanks, I can reproduce now. This only occurs when the plugin is lazily loaded. Interesting.

**Comment by lervag** [comment]
So, first of all: Lazy loading of filetype specific plugins is not really necessary, see [here](https://github.com/junegunn/vim-plug#on-demand-loading-of-plugins). Thus the problem may simply be solved by removing the `{ 'for': ['tex'] }` option to vim-plug.

However, I think I could update the logic at the beginning of the `after/syntax/tex.vim` file. The problem is that the `b:current_syntax` variable is not set, since the lazy loading for some reason makes the after syntax file load _earlier_ (cf. screenshot at end of post). So, I could assume that if the syntax file is loaded and `b:current_syntax` is not set, then it should be set to `b:current_syntax`.

I'll make the change. It seems to work, but I have not tested very thoroughly yet.

Screenshot explanation: It is a diff of the `:scriptnames` output with the numbers and some common lines removed.

![diff](https://cloud.githubusercontent.com/assets/998898/9856956/27f4ecb0-5b18-11e5-8668-99d6977a124a.png)
