### ISSUE TITLE
Autocommand for viewing/forward search after every save

### ISSUE THREAD

**Issue by MohamedIrfanAM** [lervag/vimtex#2320]
I want to  **view (with forward search)**  new pdf after every save.
I made an autocommand that looks like this
```
  augroup _vimtex
    autocmd!
    autocmd BufReadPost *.tex call feedkeys("\<space>ll")
    autocmd BufWritePost *.tex call feedkeys("\<space>lv") 
  augroup end
```
But the problem is compilation finishes after **forward search** and _zathura_ replaces it with the new compiled pdf. 
I also tried 
```
  augroup _vimtex
    autocmd!
    autocmd BufReadPost *.tex call feedkeys("\<space>lv")
    autocmd BufWritePost *.tex call feedkeys("\<space>ll") | call feedkeys("\<space>lv") 
  augroup end
```
But doesn't work either.
I used to use this feature with _TexLab_.
btw VimTex is great, Thank you!

**Comment by lervag** [comment]
Glad that you like the plugin! :)

So, you are trying to do two things here. First, to start compiling a document when you open it, and second, to start viewer/forward search when the document is compiled.

I would do both with VimTeXs own autocommands, like this (see also `:help vimtex-events`):

```vim
augroup _vimtex
  au!
  au User VimtexEventInitPost VimtexCompile
  au User VimtexCompileSuccess VimtexView
augroup END
```

The `VimtexCompileSuccess` event is triggered from a callback after compilation is successful. It is better to use this than to use the `BufWrite*` events, because the compilation is not instant.

**Comment by MohamedIrfanAM** [comment]
Thank you, It works almost perfectly. `VimtexView` in `auto command` doesn't highlight the line in _zathura_, but when I do `:VimtexView` it highlights perfectly.

**Comment by lervag** [comment]
Sorry, it should be `VimtexEventCompileSuccess`.
