### ISSUE TITLE
Conceal

### ISSUE THREAD

**Issue by aloispichler** [lervag/vimtex#2344]
### Description

Enjoying vimtex, this is rather a question:

1. How/ is it possible to conceal sets, i.e.,     `\{`  and `\}` to   `{` and `}`?
2. How/ is it possible to conceal   `\max,` e.g., to    `max` and other simple operators? So something like this would be useful:
    ```
    \ {'name': 'max', 'mathmode': 1, concealSTRING: max'}
    ```
3. How/ is it possible to conceal `\not\in` as `∉`?

Thanks.

**Comment by lervag** [comment]
> Enjoying vimtex

Glad to hear it!

> 1. How/ is it possible to conceal sets, i.e., `\{`  and `\}` to   `{` and `}`?

I'm not sure this is possible right now. It seems more or less unnecessary to me, and also somewhat confusing since `{...}` are very common TeX syntax. Are you sure you want this?

> 2. How/ is it possible to conceal `\max,` e.g., to    `max` and other simple operators?

This is currently not possible. The conceal feature only allows to conceal a matched part with a single character, not a string.

> 3. How/ is it possible to conceal `\not\in` as `∉`?

Why don't you use `\notin`? This should be concealed already.

**Comment by aloispichler** [comment]
Okay, thank you, got it.
Kind regards!
