### ISSUE TITLE
Early hidden href.

### ISSUE THREAD

**Issue by Katafotic** [lervag/vimtex#2348]
After typing `\href` itself becomes invisible and hides the entered URL until I start typing a description. This prevents me from seeing the URL being typed, braces, including brace that close hypertext description.

Empty or with empty description `\href` will not be displayed in the editor at all.

Because of this, it's quicker to type a hyperlink under a comment and then uncomment it. But it's not convenient.

The video also shows that until the 2nd bracket is closed, the entire next part of the document is not visible. 

It also makes editing difficult. If it's a bug, is it possible to undo the `\href` conversion? Or add a time lag. 

https://user-images.githubusercontent.com/62174444/156902962-7d8e7a93-4360-4bc2-ac97-d75873b60793.mp4

**Comment by lervag** [comment]
I believe this is because of your `concealcursor` configuration. See `:help 'concealcursor'`:

```
                                                *'concealcursor'* *'cocu'*
'concealcursor' 'cocu'  string (default: "")
                        local to window
        Sets the modes in which text in the cursor line can also be concealed.
        When the current mode is listed then concealing happens just like in
        other lines.
          n             Normal mode
          v             Visual mode
          i             Insert mode
          c             Command line editing, for 'incsearch'
```

I believe you have `i` included, which I would strongly discourage. I do not have any other solution here, except to turn off the conceal feature entirely. See also `:help vimtex-syntax-conceal` and `:help 'concellevel'` for more info.

**Comment by lervag** [comment]
I believe this is because of your `concealcursor` configuration. See `:help 'concealcursor'`:

```
                                                *'concealcursor'* *'cocu'*
'concealcursor' 'cocu'  string (default: "")
                        local to window
        Sets the modes in which text in the cursor line can also be concealed.
        When the current mode is listed then concealing happens just like in
        other lines.
          n             Normal mode
          v             Visual mode
          i             Insert mode
          c             Command line editing, for 'incsearch'
```

I believe you have `i` included, which I would strongly discourage. I do not have any other solution here, except to turn off the conceal feature entirely. See also `:help vimtex-syntax-conceal` and `:help 'concellevel'` for more info.

**Comment by lervag** [comment]
(I personally suggest you keep `concealcursor` at the default _empty_ value, but at the very least, do not include `i`!)
