### ISSUE TITLE
latest vim (between 7.4.865 and 889) causes flicker and eventual crash

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#236]
A recent patch (between 7.4.865 and 889) causes gVim and Vim 7.4.889 under Linux (OpenSUSE 13.2 under KDE and awesome) with a minimal vimrc containing
```  
let g:vimtex_view_method = 'zathura'
```
to flicker and eventually crash after
```
:VimtexCompile
```
Maybe someone can reproduce this?

**Comment by lervag** [comment]
Yes, you are right. That is very strange. I have no idea what is going on, but I am investigating.

**Comment by lervag** [comment]
It seems the problem is relatively deep inside the callback. If I comment out the sleep statement in `s:xwin_get_id()` in `view.vim`, the problem is resolved.

I remembered that the sleep statement was added in order provide some time before capturing the xwindow ID. This was necessary for the `\lv` mapping, but it should not be necessary for the callback. Thus I've moved the sleep statements to more appropriate locations.

**Comment by lervag** [comment]
Thanks for noticing and reporting! I think it should work as expected now.

**Comment by lervag** [comment]
It seems this is a bug in Vim, though. Create a file named `test.vim` with the following content:

```vimL
func! MyTest()
  sleep 50m
  echo 'done'
endfunc
```

Now start gvim with `gvim -u test.vim`. Then from the command line I do:

```sh
gvim --servername GVIM --remote-expr "MyTest()"
```

Now the gvim session freezes and crashes after a while. Strange bug. The problem does not occur except through the remote expression, it seems.

**Comment by Konfekt** [comment]
Thank you very much, even more for the distilled bug report for Vim. 

That bug caused quite a headache before realizing that it was the autoupdate to the latest Vim installment that caused it. 

Now it's narrowed down to a patch between 865 and 884.

**Comment by lervag** [comment]
No problem! :)
