### ISSUE TITLE
Regarding informing the community about knap live previewer plugin for LaTeX (works only in neovim since its a lua plugin)

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2398]
Is it worth mentioning [`knap`](https://github.com/frabjous/knap), which is a neovim-only plugin (written in lua) for LaTeX live preview? Are there any thoughts on how to configure this to play nicely with VimTeX?

**Comment by clason** [comment]
(You do know that there is also a chat for VimTeX at https://gitter.im/vimtex-chat/community, right? I think such general questions and announcements would fit better there.)

**Comment by lervag** [comment]
It does look like a well made project, but I don't quite see how to relate to it from the VimTeX perspective. I don't think the concept of live previewing is really that useful for LaTeX, since most non-trivial documents require compile times of up to 10 seconds and more.

I don't mind PRs with suggestions for updated docs/README, but I won't act on this myself.
