### ISSUE TITLE
Bad fold title with command on same line as \section et al.

### ISSUE THREAD

**Issue by mbudde** [lervag/vimtex#246]
I normally place label commands on same line as the line as the `\section` command, e.g.:
```tex
\section{Introduction} \label{sec:intro}
```
When folding the document Vim shows the section as:
```
*     Introduction} \label{sec:intro -------------------------------------
```

**Comment by lervag** [comment]
It is actually quite difficult to fix this, because the logic required becomes much more complex if I allow commands to follow the section command on the same line. The current implementation allows commands inside the section title, but it does assume that the section command is on a single line.

I actually think it is much better practice to put the label on the next line! Do you have any good arguments as to why I should fix this, instead of demanding that you simply put the label on a separate line?

**Comment by mbudde** [comment]
> Do you have any good arguments as to why I should fix this?

Not really. It was just a minor issue I thought I would bring to your attention. I do get your point about increasing complexity so I won't complain if you close it as wontfix.

**Comment by lervag** [comment]
Ok. I don't like to not fix things, but in this case I think I will leave it as not fixed. There are too many other issues to work on. I will be happy to consider a pull request if you (or anyone else) ever find a good way to solve this.
