### ISSUE TITLE
:VimtexInfo results into error

### ISSUE THREAD

**Issue by Srijandev** [lervag/vimtex#2500]
### Description

I am currently on WSL2, using the stable release for neovim, currently going through [this](https://www.ejmastnak.com/tutorials/vim-latex/vimtex.html) guide and I've added all the necessary lines in my plugins.vimrc

`filetype plugin on`
`set encoding=utf-8`

Please look into this, and help me to resolve this issue.

### Expected behavior

After running `:VimtexInfo`

Should be opening a window with various system status information, VimTeX has loaded and I will be good to go.

### Actual behavior

After running `:VimtexInfo`

`:VimtexInfo` returns `E492: Not an editor command: VimtexInfo`

### Do you use a latexmkrc file?

No.

**Comment by Srijandev** [comment]
@lervag

**Comment by lervag** [comment]
The error is due to VimTeX not being properly installed. I believe the guide you are using is quite good, but it does not explicitly explain how to install VimTeX. It is more or less assumed that people know about Vim/neovim plugins.

> Install VimTeX like any other Vim plugin using your plugin installation method of choice

Please read [the instructions in the README](https://github.com/lervag/vimtex/blob/f72d835b40946a2c934f9cb775dc2d6b1eae0b66/README.md#installation).

**Comment by Srijandev** [comment]
I already look into your docs, but my issue isn't resolved? 


> The error is due to VimTeX not being properly installed in your system. I believe the guide you are using is quite good, but it does not explicitly explain how to install VimTeX. It is more or less assumed that people know about Vim/neovim plugins.
> 
> > Install VimTeX like any other Vim plugin using your plugin installation method of choice
> 
> Please read [the instructions in the README](https://github.com/lervag/vimtex/blob/f72d835b40946a2c934f9cb775dc2d6b1eae0b66/README.md#installation).

**Comment by lervag** [comment]
What do you mean? You did _not_ follow the issue template. Do you believe VimTeX will work simply by you reading the docs? You need to _install_ VimTeX. It is a plugin. Plugins have become common on the Vim community, so I won't explain the details of this. Instead, follow the links to one of the popular plugin managers and learn how to use it.

**Comment by lervag** [comment]
But OK, can you explain in much more detail which steps you've actually tried? I.e., if you believe you have installed VimTeX, can you explain _how_ you installed it?

**Comment by Srijandev** [comment]
> But OK, can you explain in much more detail which steps you've actually tried? I.e., if you believe you have installed VimTeX, can you explain _how_ you installed it?

Alright, sure!

**Comment by Srijandev** [comment]
So, I added the plug using `Plug 'lervag/vimtex'`, ran `PlugInstall` and lastly added some lines in my `plugins.vimrc` 
Lines :

**Comment by lervag** [comment]
Please don't delete your comments. When you do, it makes my own replies out of context. I took the liberty of deleting your single comment with `@lervag` (there is _no_ need to ping me, I follow the issues on this repo).

**Comment by Srijandev** [comment]
Apologies, I accidentally did it :(

**Comment by Srijandev** [comment]
Sorry, I am completely new in this.

**Comment by lervag** [comment]
> So, I added the plug using `Plug 'lervag/vimtex'`, ran `PlugInstall` and lastly added some lines in my `plugins.vimrc` ...

This simply does not make sense. `plugins.vimrc` is not any standard file. You need to show me your configuration! Can you post a link to your vimrc file? Or post the contents here?

I don't quite understand how you think I can understand your problem based on the tiny bit of information you've provided so far. Just to be clear: I am 99% sure the problem is with your configuration. I know nothing of that, except that you have added four standard lines of configuration that may or may not be necessary.

I understand that you are new to this. The key for you is to make sure you provide enough information for me (or anyone else) to understand the problem. In this case, I need to know what you actually tried. The information you've provided is not enough.

**Comment by Srijandev** [comment]
Uh, where do I need to add this?

**Comment by lervag** [comment]
In my humble opinion, I believe you should take a couple of steps back and start by learning Vim more carefully. There are tons of blog posts that explain how to configure Vim/neovim. And if you did not already do it, then `:vimtutor` is also useful.

> Uh, where do I need to add this?

In my previous post I asked two questions and tried to explain that you need to provide more information. Your response question does not make sense. I did not ask you do "add" anything. And what does "this" refer to?

**Comment by Srijandev** [comment]
![image](https://user-images.githubusercontent.com/67185450/192453999-9c3e7910-cb4d-4a91-956d-4726b71601c6.png)
Sorry, I meant this.
If not in plugins.vimrc, where should I add those snippet?

**Comment by lervag** [comment]
I'm sorry, @Srijandev, but I get the feeling that you are trolling me here. I never told you to add that snippet anywhere.

What I **did** ask you was to share the configuration you are using _now_. Show me the contents of your neovim config files.

You keep mentioning `plugins.vimrc`: this is not a standard file. For neovim, the configuration file is `init.vim` or `init.lua`. If you have a `plugins.vimrc`, then this is because you have some "fancy" configuration. If you don't understand what I mean about that, then you are clearly using something that you don't quite understand. And I would again suggest that you take a step back. Read the neovim documentation. Read blog posts after searching for "getting started with neovim"; "how to use plugins with neovim", and so on.

**Comment by lervag** [comment]
Also, you closed the issue again now, but no explanation. Did you figure it out?
