### ISSUE TITLE
Finalize imaps feature

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#251]
Remaining tasks and problems:

- [x] Write documentation
- [x] Update README
- [x] Fix problem with `in` -> `\in` conflicts with `\begin`
- [x] Merge into master

**Comment by lervag** [comment]
I've now merged the feature into master. It remains to write the docs, so I'll keep this issue open until I've done that.

Note that I ended up removing the mappins for `in`, `sin`, `exp`, `log`, etc, since I did not find a good way to handle problems such as when `in` was expanded even when it was inside a word such as `begin`. I also moved the `q[hjklHJKL]` mappings and the mapping for `lim` to the leader mappings.

I am considering if I should remove the Ultisnips dependency and instead add a very simple snippet functionality similar to the one used in LaTeX-Suite (aka vim-latex). This uses markers such as `<++>` and a keybinding to jump to markers. It should not be difficult to implement, and it would allow nested snippets.

Please note that when I here write snippets, I still consider this to be different from a more general snippet in that the snippets defined here are automatically expanded.

**Comment by HerrmannM** [comment]
Hi 
I just updated the plugin and I found this awesome !
You may recall that once i ask about a conflicting mapping, ie. the <m-i> for "\item" is in fact a very usefull letter for the french language, the 'é'. (so, I found about this by writing a 'é' ;-) ).
Of course, I realize that you can not change the mapping for just one specific keyboard/language conflict while it is OK with the rest of the world (by the way, the  '... '-> '\dots' is super cool).
So for now I just disable the entry by hand for <m-i> in the function 's:default_collections' from imaps.vim.
It would be nice if we could disable just the entry we don't want with an option instead of turning everything off with g:vimtex_mappings_enabled.
Maybe it is planned, I'll wait for the doc. If not, I'll live with that ;-)
Thank you a lot for your awesome work, it really really help me !

**Comment by nilsbecker** [comment]
about a built-in snippet engine instead of ultisnips: why reinvent the wheel? for people who actually use ultisnips, this would be a burden because the way a snippet is invoked would be different for the built-in engine (where it may be trigger-less) from the ultisnips engine (where you can set your own trigger key and jump-to-next key).

my humble suggestion would be that it should be possible to use vimtex without ultisnips, then just missing the fancier part of the abbreviations, and to use one standard way to actually use fancy abbreviations or snippets, ie ultisnips. 

personally i dislike auto-expansion of anything that is not just a very simple abbreviation or a subscript or the like. if i'm gonna build a whole new figure float environment, i do want to actually press a trigger key.

**Comment by lervag** [comment]
@HerrmannM I understand that `<m-i>` is not very good for french. However, I am so used to this mapping that I want to keep it. I'm pushing an update in not too long where I've made it relatively simple to create your own list of mappings. Thus you can define precisily the mappings that you want with the keys you want. I previously defined several collections, but I chose to instead just make a single list.

To make your custom list of mappings, you simply define an option such as:

```vimL
let g:vimtex_imaps_default = [
        \ { 'map' : ['...',   '\dots'],               'leader' : '' },
        \ { 'map' : ['<m-i>', '\item '],              'leader' : '' },
        \ { 'map' : ['__',    '_\{$1\}'],             'leader' : '',   'wrapper' : 's:wrap_math_ultisnips'},
        \ { 'map' : ['^^',    '^\{$1\}'],             'leader' : '',   'wrapper' : 's:wrap_math_ultisnips'},
        \ { 'map' : ['((',    '\left($1\right)'],     'leader' : '',   'wrapper' : 's:wrap_math_ultisnips'},
        \ { 'map' : ['[[',    '\left[$1\right]'],     'leader' : '',   'wrapper' : 's:wrap_math_ultisnips'},
        \ { 'map' : ['{{',    '\left\\{$1\right\\}'], 'leader' : '',   'wrapper' : 's:wrap_math_ultisnips'},
        \ { 'map' : ['i',     '\int_{$1}^{$2}'],      'wrapper' : 's:wrap_math_ultisnips'},
        \ { 'map' : ['qK',    '\Uparrow'],            'wrapper' : 's:wrap_math_ultisnips'},
        \ { 'map' : ['a',     '\alpha'],              'wrapper' : 's:wrap_math'},
        \ { 'map' : ['Y',     '\Psi'],                'wrapper' : 's:wrap_math'},
        \]
```

To see the full default list, please see the `imaps.vim` file.

@nilsbecker First, I've already removed the trivial abbreviations such as `sin -> \sin`. The current list of mappings are given at the top of `imaps.vim`. I would be happy if you could comment on the current list. I want to keep it as small as possible, while at the same time very useful and convenient. It should be simple to add personal mappings.

At the moment, it is very possible to use the feature without Ultisnips. This will simply disable the mappings that require ultisnips.

Regarding the custom snippet engine: I do NOT propose to reinvent the wheel. My thought was to use something very similar to what is implemented in LaTeX-Suite, which is a very simple engine. There is one reason that I want to do this: To allow nested expansions.

**Comment by lervag** [comment]
I've now added the documentation. Please see `:h vimtex-imaps`.

@HerrmannM I've added an option `g:vimtex_imaps_disabled` that lets you disable maps from the default list.

I now think the feature is properly implemented. There might be some minor bugs or similar, but I think we will find them quickly.

I will be using this a lot myself, and I will consider whether the UltiSnips-functionality is good enough. If I get too anoyed with it, I will consider to implement my own mini-snippet-engine (please understand, this is NOT intended as a replacement for full snippets!).

**Comment by nilsbecker** [comment]
hi, yes i saw they were gone after commenting on the other issue. i will soon try out the new functionality and it's greatly appreciated! about nested snippets: would it make sense to file an enhancement request on the ultisnips side?

**Comment by lervag** [comment]
I've looked around. I found [this](https://github.com/SirVer/ultisnips/issues/528) issue on UltiSnips, and it seems there is no solution in the nearest future. However, I've opened an issue with [neosnippet](https://github.com/Shougo/neosnippet.vim/issues/293), and if Shougu would implement this feature, I will consider to use neosnippet instead of UltiSnips.

**Comment by nilsbecker** [comment]
hi, i had a look around the new addition. some suggestions:

- lowercase psi seems to be missing
- varepsilon should not be default
- uppercase Sigma is missing -- it's used sometimes.
- i've never seen uppercase Tau or uppercase Upsilon used 
- lowercase xi is missing

i might have missed something. \ell would be nice but that's not a standard symbol so maybe it's not a good idea.

**Comment by HerrmannM** [comment]
Hi,

Thank you a lot, it works very well !

I'll let you know if I find something buggy ;-)

**Comment by lervag** [comment]
@nilsbecker I've made the following changes. I hope you agree with them.

```
  `y  ->  \psi
  `e  ->  \epsilon
  `E  ->  \varepsilon
  `S  ->  \Sigma
  `x   ->  \xi
```

I've also deleted Tau and Upsilon, as I agree these are not necessary.

**Comment by Shougo** [comment]
I have implemented the anonymous snippet expansion feature in neosnippet.
It can expand nested snippets.

**Comment by lervag** [comment]
I've now added support for using neosnippet as snippet engine. This seems to work very well, and in particular, it supports nesting of snippets. Thanks, @Shougo!

**Comment by petobens** [comment]
@lervag do you neosnippet along with ultisnips? I would really like to use the new neosnippet anon snippet feature but I'm not sure if neosnippet and ultisnips play well together i.e if I use a neosnippet snippet inside an ultisnips snippet can I map  `<c-j>` to jump outside (forward) both snippets?

**Comment by lervag** [comment]
@petobens Personally, I plan to convert from Ultisnips to neosnippet and to use only a single snippet engine. I do not think it is possible to use both, combined. That is, it might be possible by using a rather nasty mapping, but I won't try that myself, anyway. My suggestion is therefore to consider if it might be possible for you to convert. If not, then it might be difficult to use the neosnippet anon feature.

**Comment by petobens** [comment]
@lervag  For me its not possible to convert (at least not in the short term). Besides I really like Ultisnips. However  this nesting problem with anon snippets is something that I would really like to be fixed [ultisnips#248](https://github.com/SirVer/ultisnips/issues/248). But it seems to be something with no possible solution (at least for a while). I thought that maybe Shougo's solution could be ported to Ultisnips but I believe that it is not possible.

**Comment by lervag** [comment]
@petobens I understand. And I think Shougo's solution will not work in Ultisnips, as I believe the snippet engines are very different. In any case, I also hope that the issue is fixed with Ultisnips, as I agree it is very good. In any case, I think it is good to support both engines, even though it might not be possible to combine them.

**Comment by Shougo** [comment]
> do you neosnippet along with ultisnips?

You cannot use both.  It will be conflicted.  It is like YouCompleteMe and neocomplete.
Please don't mix them.

> And I think Shougo's solution will not work in Ultisnips, as I believe the snippet engines are very different. In any case, I also hope that the issue is fixed with Ultisnips, as I agree it is very good. In any case, I think it is good to support both engines, even though it might not be possible to combine them.

Yes.  UltiSnips and neosnippet has different culture/aim/implementation/advantage/disadvantage.
neosnippet can implement nested expansion easily.
But in UltiSnips it is hard to implement.
UltiSnips can implement backward jump easily.
But in neosnippet it is hard to implement.
You can choose neosnippet/UltiSnips.
No perfect snippet engine is available now.

**Comment by petobens** [comment]
Thank @Shougo for the explanation. I generally use your plugins but in this case I will continue using Ultisnips because have lots of snippets written for it and not much time to port them to neosnippet.

**Comment by omrihar** [comment]
First of all I would like to say I really like `vimtex` - I have been experimenting with it in the past few days and find it really nice and handy. I especially love the TOC feature! I have one small thing which might belong to the discussion here even though it is already closed: I find the `...` mapping problematic since it basically delays every time I press a dot at the end of a sentence and sometimes the dots disappear. I disabled this mapping in the plugin code but perhaps it would be a good thing to add a setting that allows to disable/enable this?

Thanks again for a great plugin!

**Comment by lervag** [comment]
You can disable individual mappings with `g:vimtex_imaps_disabled`, please see the documentation.

**Comment by lervag** [comment]
And thanks for the kind words! :)

**Comment by omrihar** [comment]
Thanks for the very quick reply! I must read the documentation more carefully!
Works great :-)

**Comment by lervag** [comment]
No problem! :)

**Comment by nilsbecker** [comment]
@lervag i went over the default mappings once more to see if i can use them instead of the ones i had defined for myself. i have still some suggestions for improvements. 

1. the var version should never be the standard. so i think (strongly)
` 'f -> \phi` should be the mapping

2. varphi is often nice to have. it would be good if there was a standard way to go from non-var to var. for epsilon you now use capitalization. unfortunately that cannot work for phi since Phi is used. Also, Theta is used. the capitalization idea is cute but it seems to be impossible to make it work.

so i would argue for defining a standard prefix `v` and to let
```
've -> \varepsilon
'vf -> \varphi
'vk -> \varkappa
'vq -> \vartheta
'vr -> \varrho
```
and to drop the `'E` etc. 

3. this one may be personal preference to some degree. in physics and probability, `\langle` and `\rangle` are extremely common, more so than `\leq` in many cases. i would argue for 
`'< -> \langle` and `'> -> \rangle` and `'<= -> \leq` and vice versa. i find those also better for mnemonics.

4. capital greek letters should always have the capitalized abbreviation. atm this is not true for Eta at least.

5. `'Y` seems to be used twice? maybe a typo.

6. `'(` appears more intuitive for `\subset` to me (and vice versa)

cheers!

**Comment by lervag** [comment]
Thanks, @nilsbecker, I've updated accordingly. I think your suggestions are all good.
