### ISSUE TITLE
Unable to view my compiled latex.

### ISSUE THREAD

**Issue by cosigns** [lervag/vimtex#2510]
### Description

I am unable to view pdf, when I try `:VimtexCompile` it works but I don't know how to view my file, I have SumatraPDF installed(in windows), latexmk on WSL

PS: I am extremely new to this

### VimtexInfo

```yaml
compiler: latexmk
engine: -pdf
```

**Comment by cosigns** [comment]
Here is my `init.vim` 
```yaml
let g:tex_flavor = "latex"
" Viewer options: One may configure the viewer either by specifying a built-in
" viewer method:
let g:vimtex_view_method = 'SumatraPDF'

" VimTeX uses latexmk as the default compiler backend. If you use it, which is
" strongly recommended, you probably don't need to configure anything. If you
" want another compiler backend, you can change it as follows. The list of
" supported backends and further explanation is provided in the documentation,
" see ":help vimtex-compiler".
let g:vimtex_compiler_method = 'latexmk'

" Most VimTeX mappings rely on localleader and this can be changed with the
" following line. The default is usually fine and is the symbol "\".
let maplocalleader = ","
```

**Comment by lervag** [comment]
> Here is my `init.vim`

You can replace that part with this:

```vim
let maplocalleader = ","
let g:vimtex_view_method = 'SumatraPDF'
```

I've asked for the output of `:VimtexInfo`, but you did not provide that output. The two lines you provided are only a very small subset.

> I have SumatraPDF installed(in windows), latexmk on WSL

Does it mean you use Vim or neovim from WSL? You need to specify a viewer that is executable from the WSL terminal session. I.e., it needs to be reachable from your `$PATH` variable.

----

Please show me the full output of `:VimtexInfo`.

**Comment by cosigns** [comment]
yes, I use neovim from WSL. 
![Screenshot 2022-10-07 124516](https://user-images.githubusercontent.com/115212242/194493833-1481a086-cf84-4b68-8acc-742cdc47404a.png)

**Comment by cosigns** [comment]
I installed latexmk on wsl itself whereas SumatraPDF on windows.

**Comment by cosigns** [comment]
> Does it mean you use Vim or neovim from WSL? You need to specify a viewer that is executable from the WSL terminal session. I.e., it needs to be reachable from your $PATH variable.

Sorry, as I said I am preety new? how can I do that?

**Comment by lervag** [comment]
I believe it is possible to run Windows executables from WSL, but I'm not an expert. I suggest you read:
* `:help vimtex-faq-windows` (only the second bullet point is relevant now)
* `:help vimtex-faq-wsl`
* `:help vimtex-view-sumatrapdf`

**Comment by cosigns** [comment]
Alright, else everything seems fine?

**Comment by cosigns** [comment]
and yes, what about the error I am facing? 
![image](https://user-images.githubusercontent.com/115212242/194497572-64d8f281-99c2-4815-a707-699e1a144f82.png)

**Comment by cosigns** [comment]
I read the articles you linked, now I added it to path? the error is gone, now how can I view my pdf? is there a command?

**Comment by cosigns** [comment]
@lervag I added it to path using following steps:

```py
export PATH=$PATH:/mnt/c/Users/Sys/sioyek-release-windows/sioyek.exe
```
and after running `env | grep PATH` I see it's added to path

**Comment by cosigns** [comment]
Now, I am confused how can I see my pdf?

**Comment by lervag** [comment]
Ok, it seems you've changed to use Sioyek? Is that right? Or are you still using SumatraPDF?

**Comment by cosigns** [comment]
Yep, I've changed to Sioyek

**Comment by lervag** [comment]
Ok. Did you read `:help vimtex-view-sioyek`?

**Comment by cosigns** [comment]
Yes, what's now?

**Comment by lervag** [comment]
How does your current VimTeX configuration look like?

To open the viewer, you can do `:VimtexView` or `,lv` (I believe you use `,` as the local leader - the default is `\` so most people would use `\lv`).

**Comment by cosigns** [comment]
> How does your current VimTeX configuration look like?
> 
> To open the viewer, you can do `:VimtexView` or `,lv` (I believe you use `,` as the local leader - the default is `\` so most people would use `\lv`).

Nothing happens, when I do `:VimtexInfo`

**Comment by lervag** [comment]
> How does your current VimTeX configuration look like?

**Comment by cosigns** [comment]
```yaml 
let g:tex_flavor = "latex"
let g:vimtex_compiler_method = 'latexmk'

" Most VimTeX mappings rely on localleader and this can be changed with the
" following line. The default is usually fine and is the symbol "\".
let maplocalleader = ","
 if has('win32') || (has('unix') && exists('$WSLENV'))
     if executable('sioyek.exe')
       let g:vimtex_view_method = 'sioyek'
       let g:vimtex_view_sioyek_exe = '/mnt/c/Users/Asus/sioyek-release-windows/sioyek.exe'
       let g:vimtex_callback_progpath = 'wsl nvim'
     elseif executable('mupdf.exe')
       let g:vimtex_view_general_viewer = 'mupdf.exe'
     elseif executable('SumatraPDF.exe')
       let g:vimtex_view_general_viewer = 'SumatraPDF.exe'
     endif
   endif
```

**Comment by lervag** [comment]
Notice that github issues are _not_ chats. It would be more constructive if you can respond to all questions in the same reply.

As you should have notice by now, most of what you've asked for is actually quite well documented. I understand it can be hard to find, so I'm trying to help you by suggesting the right locations.

But based on the config, it seems you are not reading my answers completely. In my first comment, I tried to explain that you could simplify your config. In any case, please change your config to this and try again:

```vim
let maplocalleader = ","
let g:vimtex_view_method = 'sioyek'
let g:vimtex_view_sioyek_exe = '/mnt/c/Users/Sys/sioyek-release-windows/sioyek.exe'
let g:vimtex_callback_progpath = 'wsl nvim'
```

**Comment by lervag** [comment]
Notice that the `if executable()` statements will fail unless the argument is actually executable. So, one thing we can try is to take a step back.

Before you start neovim, can you show what happens if you type: `sioyek.exe` at the command line? Similarly for `SumatraPDF.exe`? I expect it will reply "command not found" or something similar. Next, what happens if you write `/mnt/c/Users/Sys/sioyek-release-windows/sioyek.exe`?

**Comment by cosigns** [comment]
Alright, this seems to be working now

> Notice that github issues are _not_ chats. It would be more constructive if you can respond to all questions in the same reply.
> 
> As you should have notice by now, most of what you've asked for is actually quite well documented. I understand it can be hard to find, so I'm trying to help you by suggesting the right locations.
> 
> But based on the config, it seems you are not reading my answers completely. In my first comment, I tried to explain that you could simplify your config. In any case, please change your config to this and try again:
> 
> ```viml
> let maplocalleader = ","
> let g:vimtex_view_method = 'sioyek'
> let g:vimtex_view_sioyek_exe = '/mnt/c/Users/Sys/sioyek-release-windows/sioyek.exe'
> let g:vimtex_callback_progpath = 'wsl nvim'
> ```

**Comment by cosigns** [comment]
> Notice that the `if executable()` statements will fail unless the argument is actually executable. So, one thing we can try is to take a step back.
> 
> Before you start neovim, can you show what happens if you type: `sioyek.exe` at the command line? Similarly for `SumatraPDF.exe`? I expect it will reply "command not found" or something similar. Next, what happens if you write `/mnt/c/Users/Sys/sioyek-release-windows/sioyek.exe`?

Yep, I tried this before `sioyek.exe` results `command not found` whereas ``/mnt/c/Users/Sys/sioyek-release-windows/sioyek.exe` opens viewer

**Comment by cosigns** [comment]
I also have one issue, why isn't there any latex autocompletions?

**Comment by lervag** [comment]
Great. I notice you copied verbatim the lines from `:help vimtex-faq-wsl`. Then you changed the `let g:vimtex_view_sioyek_exe` line afterwards. But you obviously did not quite _understand_ the lines you copied. I would **strongly** recommend you to avoid copying lines of configuration *unless* you understand what they do. The reason it failed was because `executable('sioyek.exe')` returns False, because `sioyek.exe` is _not_ executable - it is not in the PATH environment variable. When you removed the conditional parts, it works, because you now point `g:vimtex_view_sioyek_exe` to the correct path of the executable.

VimTeX does not do _auto_completion. It only does omni-completion, which is a Vim feature. So, after typing e.g. `\beg` you can do `<c-x><c-o>` to initiate the completion. There are a lot of autocompletion plugins that work well with VimTeX, please read `:help vimtex-complete-auto`.

And yes, when you compile a LaTeX document, it will generate a lot of auxilliary files. You should use dedicated paths for each project. E.g. `mkdir myproject` then `cd myproject` then `nvim main.tex`.

Notice that you are asking a lot of basic level questions. I understand you are new to this, and that's fine. But I would strongly suggest that you read some general introductions to both Neovim and LaTeX. These will most likely answer most of your questions. Notice that the time I spend helping you is time I can't spend on actually improving VimTeX or fixing real bugs. :)

**Comment by lervag** [comment]
Glad to help. Good luck, and don't hesitate to open new issues (although, I'd appreciate if you of course make an attempt at finding the solution in the docs first) ;)
