### ISSUE TITLE
Parenthesis matching stops working in Python scripts

### ISSUE THREAD

**Issue by mblondel** [lervag/vimtex#252]
When I use vim-tex, parenthesis matching stops working in Python files.

To reproduce:
- open a Python file (parenthesis matching works)
- open a .tex file (parenthesis matching stops working in the Python file)

**Comment by lervag** [comment]
This is actually a feature: paranthesis matching comes from the plugin `matchit.vim` that comes with vim. In order to get an improved version of the matching, vimtex implements a custom matcher and disables the default matcher. Unfortunately, this will affect the default matcher for every file type.

You can disable this feature with `let g:vimtex_motion_matchparen = 0`. But then the matcher will not work perfectly in LaTeX files.

**Comment by mblondel** [comment]
Thanks for the reply! How bad does the matcher become when using `let g:vimtex_motion_matchparen = 0`?

**Comment by lervag** [comment]
It will revert to the built-in matcher, which will match parantheses and similar. It will not, though, match things such as `\left(...\right)` pairs and environment commands.

**Comment by mblondel** [comment]
Sorry if it's a naive question but why do you need to disable the default matcher globally? Can't you activate your enhanced matcher only for .tex files?

**Comment by lervag** [comment]
Ok, so: I've tried to figure out why matchparen is disabled, and I really can't find a good answer to that. The code is adopted from LaTeX-Box, where it was added at some time with no good explanation. To me, it seems there is no need to disable matchparen. I therefore removed the code that disables it. 

I think and hope that this should solve your problem. Please let me know if you experience any issues related to this.

**Comment by mblondel** [comment]
I confirm that a93d0cbb89fe2bd6a60845b3e1d54f960b4478f9 appears to have fixed the problem for me. Thanks!

**Comment by lervag** [comment]
Great. And no problem :)
