### ISSUE TITLE
Trigger citation completion by '\citep{' or '\citet{'

### ISSUE THREAD

**Issue by smjonas** [lervag/vimtex#2572]
**Is your feature request related to a problem? Please describe it.**
I often use the `\citet` or `\citep` commands so it would be nice if they would also trigger the citation completion. 

**Describe the solution you'd like**
Pressing `<C-x><C-o>` after having typed `\citep{` or `\citet{` should trigger the citation completion. Currently this only happens with `\cite{`. Edit: for biblatex there are other commands like `\citeauthor` or `\autocite` so it would probably be more maintainable if the pattern to match the command was not hardcoded but could be overwritten by the user. 

Thanks for your time!

**Comment by lervag** [comment]
This already works. However, `\citet` and `\citep` requires that VimTeX recognizes the `natbib` package. This should work well if your document either 1) has a `\usepackage{natbib}` in the preamble, or 2) is compiled so that there is a `FILE.fls` file.

If you don't get it to work, please provide a concrete, small example and explain what you are doing. I can try to help.

**Comment by lervag** [comment]
There's no separate source, but you can use the `cmp-omni` source as explained in the docs: see `:help vimtex-complete-nvim-cmp`. :)

**Comment by lervag** [comment]
> Thank you, somehow it's working now!

Good to hear. I understand it can be surprising that some features won't work as expected until the document is compiled (which is probably the case here). It is documented, but still.
