### ISSUE TITLE
Vimtex is not using full path anymore when calling synctex 

### ISSUE THREAD

**Issue by rapid-tap** [lervag/vimtex#2575]
Commit ef7732369649b24451f240a03d8872e1c3482422 makes Vimtex use full path when using synctex for forward search. 

However, commit 944a2fc6d809462c67f7e06ad858e4e0c5411b2f brings it back to using relative path.

What is the reason for this change? 

I like the behavior when it is using full path because I don't have to worry about my current working directory in vim. Right now, for forward search to work, I have to be in the same directory as the base tex file.

**Comment by lervag** [comment]
> What is the reason for this change?

> However, commit [944a2fc](https://github.com/lervag/vimtex/commit/944a2fc6d809462c67f7e06ad858e4e0c5411b2f) brings it back to using relative path.

The reason is found in the reference given in the commit, i.e. in the #2573 thread. I believed the change was safe, so seeing this issue is surprising. Notice, though, that the latest commit is not the _same_ as the old version. The command should now use a path relative to the _current_ directory of Vim/neovim itself, not to the project root or the current file. This is why I expected it to work as expected (and I have not seen yet that it does not).

> I like the behavior when it is using full path because I don't have to worry about my current working directory in vim. Right now, for forward search to work, I have to be in the same directory as the base tex file.

Can you design a minimal example for this?

**Comment by lervag** [comment]
Ah, looking back at the old discussion in #2392 I notice the reason for the change to use the absolute path, which was that some flavors/versions of synctex uses source file paths that only works with the absolute path designation. Further, I realize that the recent update does indeed _break_ things, because the path supplied for the source file argument to synctex _has_ to be either relative to the project root _or_ absolute. It can't be relative to the Vim directory.

I've therefore pushed an update to revert 944a2fc. The reason for this change was to circumvent issues with colons in the paths, but this is not a good enough reason to revert to the relative paths as concluded in #2392.
