### ISSUE TITLE
Version control of options.vim file from an outer repository

### ISSUE THREAD

**Issue by TryerGit** [lervag/vimtex#2582]
Hello,

As suggested in the docs (`:help vimtex#imaps#add_map`), it seems possible to change and customize `~\.vim\plugged\vimtex\autoload\vimtex\options.vim` file with user defined options/changes. I would like to create a git repository of my customized files -- such as `~/.vimrc` or `~/.bashrc` and even the above `options.vim` file. However, git does not allow me to track `options.vim` from an outer repository created in `~\.git\` regardless of whatever I do in `.gitignore` files. The issue is that there is already a `.git\` repository in `~\.vim\plugged\vimtex\.git\` and my outer `~\.git\` by design, ignores any recursive lower `\.git\` it encounters.

One possible workaround to allow the outer `~\.git\` to track the inner `options.vim` file is to delete `~\.vim\plugged\vimtex\.git\` folder. Then, all files and folders in `~\.vim\plugged\vimtex\` are tracked allowing me to treat `options.vim` as just another file in my file system.

Is this the only way possible to track `options.vim` or is there a different workflow that folks here use to source control customized files within vimtex in particular and other repositories in general?

Is submodules to be used? I really don't want to source control the entire `/vimtex/` folder, but one specific file within the `/vimtex/` folder structure. Submodules seem to be targeted at tracking from `~/.git/` the entire repository in `~\.vim\plugged\vimtex\.git\` in my limited understanding.

Thank you.

**Comment by lervag** [comment]
> As suggested in the docs (`:help vimtex#imaps#add_map`), it seems possible to change and customize `~\.vim\plugged\vimtex\autoload\vimtex\options.vim` file with user defined options/changes.

Ah, no, you should _not_ customize `options.vim`. I don't agree this is suggested in the docs. If you think it is, please show me exactly which paragraph you're thinking about. I'll be happy to update it if I agree it is misleading.

I think you have a fundamental misunderstanding here. Your personal configuration should be _separate_ from any plugins you install. That is, as a general rule, you should _never_ change any of the code under `~\.vim\plugged\vimtex`. That is, you should not modify the VimTeX code, unless you _know_ what you are doing and _why_. (The main exception to the rule is if you are debugging an issue or building a new feature.)

> I would like to create a git repository of my customized files -- such as `~/.vimrc` or `~/.bashrc`

Yes, this makes sense. The concept is known as "dotfiles", and if you search the web you should find many introductions and guides on how to get started. GitHub has a nice starting point that I recommend you spend some time reading. Read some of the tutorials linked there: https://dotfiles.github.io/.

> and even the above `options.vim` file.

As said: _never_ change this file. It should not be in your dotfiles repo.

----

There are countless examples of how to do these things. Personally, I separate my Vim config from the rest of my dotfiles. I therefore have two repositories:
* https://github.com/lervag/dotnvim/ (neovim config)
* https://github.com/lervag/dotfiles/ (dotfiles; everything else)

I'm not sure if my files are very helpful here, though; I have a lot of stuff and I never cared to document it for other people. Further, I use Neovim, and there are some differences to a common Vim config (e.g. because of Lua). Thus, it may be more helpful to find other examples of dotfiles or dotvim type repositories.

**Comment by TryerGit** [comment]
> If you think it is, please show me exactly which paragraph you're thinking about. I'll be happy to update it if I agree it is misleading.

I was referring to the following line(s):

```
*vimtex#imaps#add_map*
This function is used to add new insert mode mappings.
```

that seem to suggest new insert mode mappings can be done. I thought that these new mappings would modify `options.vim`. Perhaps I was mistaken in my understanding. Where exactly would these new user added imaps reside then if not under some location inside and underneath `~\.vim\plugged\vimtex\`? I assumed they would reside someplace within that and hence was thinking of how to source control them for potential future use on a different machine. Perhaps what happens is that these settings in `.vimrc` are only loaded temporarily (i.e., they are not sourced from `options.vim`) and do not persist from session to session unless the same `.vimrc` were loaded again?

> That is, as a general rule, you should never change any of the code under `~\.vim\plugged\vimtex`

In addition to my query above (in terms of where would the user customizations "reside") I was also having this trouble with the default settings for Ultisnips. Currently, my tex snippets reside in the following folder:

`\\wsl$\Ubuntu-20.04\home\Tryer\.vim\plugged\vim-snippets\UltiSnips\plaintex.snippets`

This is also the location UltiSnips automatically shows as the place where user snippets should reside.

For e.g., when I open an empty .tex file (with a very basic .vimrc that only plug loads 

`Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'`

(even vimtex is not plug loaded in this minimal .vimrc)

and type `:UltiSnipsEdit!`, I get the following two locations where snippets will be loaded from:

```
1: /home/Tryer/.vim/plugged/vim-snippets/UltiSnips/all.snippets
2: /home/Tryer/.vim/plugged/vim-snippets/UltiSnips/plaintex.snippets
```

This is what I was trying to reconcile -- these snippet files certainly seem to be under the external repository 

\\wsl$\Ubuntu-20.04\home\Tryer\.vim\plugged\vim-snippets\.git\

Yet, the user seems to be expected to customize `plaintex.snippets`. It is still not clear to me how one can source control such files except physically copying them and maintaining backup outside of git. (I have heard of dotfile management before, but will look into it a bit more but I am not sure at present whether they would help backup `plaintex.snippets` in the above example, for instance)

Thank you for your patient explanations!

**Comment by lervag** [comment]
> > If you think it is, please show me exactly which paragraph you're thinking about. I'll be happy to update it if I agree it is misleading.
> 
> I was referring to the following line(s):
> 
> ```
> *vimtex#imaps#add_map*
> This function is used to add new insert mode mappings.
> ```
> 
> that seem to suggest new insert mode mappings can be done. I thought that these new mappings would modify `options.vim`.

Oh, no; the function will not modify any source files. It is only meant as an advanced way to make relatively simple snippet-like mappings.

> Where exactly would these new user added imaps reside then if not under some location inside and underneath `~\.vim\plugged\vimtex\`?

The functions can be considered a method for doing regular user configuration similar to changing other options. The most basic configurations (which usually work very well!) is to just keep everything in your `.vimrc` or `~/.vim/vimrc` file. Some people tend to use slightly more advanced configs, but it boils down to the same thing.

I have a separate file for my VimTeX config which is basically sourced directly from my `vimrc` file (actually `init.vim`, since I use Neovim). It is available here:

https://github.com/lervag/dotnvim/blob/main/init/plugins/vimtex.vim

I don't actually use the mentioned function, but if I did, I would call it from the same location.

> Perhaps what happens is that these settings in `.vimrc` are only loaded temporarily (i.e., they are not sourced from `options.vim`) and do not persist from session to session unless the same `.vimrc` were loaded again?

The intent of `options.vim` is _not_ for user configuration; it is to define default options and check for use of deprecated options.

Why would you want to use _different_ `.vimrc` files? In my view, the configuration you put in `.vimrc` is persistant by definition.

> > That is, as a general rule, you should never change any of the code under `~\.vim\plugged\vimtex`
> 
> In addition to my query above (in terms of where would the user customizations "reside") I was also having this trouble with the default settings for Ultisnips. Currently, my tex snippets reside in the following folder:
> 
> `\\wsl$\Ubuntu-20.04\home\Tryer\.vim\plugged\vim-snippets\UltiSnips\plaintex.snippets`

You are making the same mistake here. You should _never_ touch the content of a plugin. (Unless, of course, you have a specific reason and you know that it is what you want.)

> This is also the location UltiSnips automatically shows as the place where user snippets should reside.

Yes, because UltiSnips does not find any _other_ `UltiSnips` directories. You need to create it (`mkdir ~/.vim/UltiSnips`).

To understand where UltiSnips finds the snippet files, you need to understand how the `runtimepath` feature in Vim works. This is not really well described in the UltiSnips docs, but it is described in the user manual of Vim and of course in the reference (`:help runtimepath`). Basically, UltiSnips will load snippets from snippet files in any `UltiSnips` directory in _every_ path in the `runtimepath` list.

> `Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'`

Please note that `vim-snippets` is a plugin that simply provides a lot of premade snippets. If you want additional, custom snippets, you should put them in your _own_ directory as explained above.

----

I would recommend that you add a `.gitignore` at the root of your `.vim` folder that contains `plugged/`.
