### ISSUE TITLE
Use/relevance of macros in the presence of VimTeX and UltiSnips and autocompletion engines

### ISSUE THREAD

**Issue by TryerGit** [lervag/vimtex#2598]
Hello,

I am curious to know whether native TeX macros are of any utility at all in any of your workflows given VimTeX and snippets/autocompletion engines.

For e.g., I have seen tex preambles with the following command

```tex
\newcommand{\D}{\mathrm{d}}
\newcommand{\dbyd}[2]{\frac{\D#1}{\D#2}}
```

and then usage as `\dbyd{y}{t}` for the notation of derivative of y w.r.t. t

We can also obtain the same thing using a snippet

```
context "math()"
snippet dbyd "derivative" w
\frac{d$1}{d$2} $0
endsnippet
```

I have not felt the need for any macros and all of my work so far has gotten done using a snippets manager like UltiSnips. So, I am curious if macros help fulfil any special need that VimTeX and UltiSnips cannot.

Thank you.

**Comment by ejmastnak** [comment]
Snippets are indeed awesome! But here's one use case for macros that I don't think snippets can solve: macros make it easy to redefine command behavior file-wide

To build on your example, let's say you define the following in a document preamble:

```tex
% Differential with upright "d"
\newcommand{\D}{\mathrm{d}}
```

You might realize later you would prefer a small space after the differential `d` and the symbol that come after; it is trivial to redefine

```tex
% Differential with upright "d" and small space after "d"
\newcommand{\D}{\mathrm{d}\!}

% Or maybe you need an italic "d", as is common in some mathematics literature
\newcommand{\D}{d\!}
```

This format tweak for differentials would be much more difficult if you used a snippet that expanded `D` to `\mathrm{d}`---you would then have to manually search and replace every instance of `\mathrm{d}` in the document instead of changing one line in the preamble. As you can imagine, that's error prone and doesn't scale well.

One more example I've encountered into is switching between upright (Roman) and italic boldface vectors:

```tex
% Bold and upright
\newcommand{\vec}[1]{\boldsymbol{\mathbf{#1}}}

% Bold and italic
\newcommand{\vec}[1]{\bm{#1}}
```

It's much easier to change the `\vec` macro in the preamble than search and replace every instance of `\bm{}` in the document itself.

### Best of both worlds

Note that snippets and macros are perfectly compatible---in my setup I usually make snippets expand to semantically-named macro, e.g. (continuing your example) use a snippet

```snippets
# Of course you'd change the trigger to something better
snippet D "Differential" w
\D
endsnippet
```

And then in the LaTeX preamble define something like

```tex
% Which can easily be changed later if needed
\newcommand{\D}{\mathrm{d}}
```

You get the convenience of a snippet with the future flexibility of a macro. Basically you have an extra level of abstraction/flexibility that you (or your future self) may find useful.

**Comment by lervag** [comment]
I could not reply any better to this than @ejmastnak just did. Thanks!

**Comment by TryerGit** [comment]
Thank you @ejmastnak I see the value now. It is not much different from the usage of macros in C/C++ and other languages. I hadn't thought of the need of these in TeX to be honest. My use case is quite static -- not having to make changes and tweaks as you suggest that can make an impact project wide.

Thank you for your tutorial -- it was what got me into VimTeX :-)

**Comment by ejmastnak** [comment]
> Thank you @ejmastnak I see the value now. It is not much different from the usage of macros in C/C++ and other languages. I hadn't thought of the need of these in TeX to be honest. My use case is quite static -- not having to make changes and tweaks as you suggest that can make an impact project wide.

Great, glad to hear the answer helped! Yeah, now that you mention it the idea is similar to macros in C, I somehow hadn't made the connection until now.

> Thank you for your tutorial -- it was what got me into VimTeX :-)

:)
