### ISSUE TITLE
Custom conceal rules

### ISSUE THREAD

**Issue by Fireond** [lervag/vimtex#2634]
I have learned the command `g:vimtex_syntax_custom_cmds` but it seems it cannot support options for args and custom argstyle. For example, I want to conceal `\ket{\psi}` to `|ψ>`, conceal `\bra{A\varphi}` to `<Aφ|` (conceal `\ket{}`, `\bra{}`... commands to braket like. Thanks!

**Comment by Fireond** [comment]
Also I wonder if it is possible to change `concealchar` key to `concealstring` key, say if I want to conceal `\rank A` to simply `rank A`, but the `char` limit the concealment to only one word.

**Comment by lervag** [comment]
> I have learned the command `g:vimtex_syntax_custom_cmds` but it seems it cannot support options for args and custom argstyle. For example, I want to conceal `\ket{\psi}` to `|ψ>`, conceal `\bra{A\varphi}` to `<Aφ|` (conceal `\ket{}`, `\bra{}`... commands to braket like. Thanks!

What you are asking for is unfortunately a much more complicated conceal. It is possible by use of some hacks. I'll see if I can make a function that generalizes this for commands like `\cmd{arg}` so that we can have it replaced with `XargY` where `X` and `Y` are single characters that are provided as arguments.

> Also I wonder if it is possible to change `concealchar` key to `concealstring` key, say if I want to conceal `\rank A` to simply `rank A`, but the `char` limit the concealment to only one word.

No; VimTeX uses the legacy syntax engine and it does not have the concept of a `concealstring`. See `:help syn-cchar` for information on what is used for conceals by VimTeX.

**Comment by lervag** [comment]
I've pushed an update that may resolve this. Please see `:help vimtex_syntax_custom_cmds_with_concealed_delims` and let me know what you think.

**Comment by Fireond** [comment]
Thanks! But if seems this command doesn't work well on my neovim:
<img width="32" alt="image" src="https://user-images.githubusercontent.com/42907735/219987932-02e1dc3d-d857-4ad3-8768-125a2a9d58d7.png">
<img width="120" alt="image" src="https://user-images.githubusercontent.com/42907735/219988016-ee3479b1-0733-40af-a97a-6e0eafe7778f.png">
I just use the example config: ```

**Comment by Fireond** [comment]
Thanks! But it seems this command not work well on my neovim: I type `\ket{x}` but it just conceal to `{x}`, and I just use the example config. I havn't found the cause.

**Comment by lervag** [comment]
Sorry, my mistake. I've pushed a new update that I think works better.

**Comment by Fireond** [comment]
It works! But when the containing args have `{}`, like `\ket{\psi_{i}}`, it would fail. I don't know whether there are techniques that can detect braces to avoid this error.
<img width="53" alt="image" src="https://user-images.githubusercontent.com/42907735/220624455-c75fdb4c-dde0-4e09-9b70-eb78ed397f97.png">
<img width="193" alt="image" src="https://user-images.githubusercontent.com/42907735/220624506-8391e0b4-3fee-47ab-bfbd-fd3e8b2bf203.png">

**Comment by lervag** [comment]
Ah, yes. That is a much harder problem, because for the conceals to work, we need to match the region start and region end with the concealed groups. This means that we need the `keepend` argument for the `syntax region` command, and then we get the problem you mention now.

The example you give is trivial, though, because you could write it as `\ket{\psi_i}`; but your point is still valid because you might want `\ket{\psi_{i+1}}`.

**Comment by lervag** [comment]
I think I found another way to do it. Please update and test again.
