### ISSUE TITLE
omnicomplete func from LatexBox

### ISSUE THREAD

**Issue by hellmean** [lervag/vimtex#264]
Hi,

I only recently started to you vim. And I came across this plugin. I also tried LatexBox, and I somehow like yours better:) One good thing in LatexBox though is a very nice omnicomplete function (omnifunc), which I like way better than the one in vimtex. I just patched my version of vimtex to use LatexBox's function and I though that other users might appreciate this option as well

I can create a pull request for this I you'd like
Thanks!

**Comment by lervag** [comment]
@hellmean Thanks, but no thanks. The `omnifunc` in vimtex is based on the one in LaTeX-Box, but I removed the unnecessary stuff. The reason is to keep it simple. For instance, LaTeX-Box provides completion for keywords/commands/environments, but this is functionality that is not necessary:

- Keyword completion (which can also help for command completion) is inherent in vim through e.g. `<c-x><c-n>`
- Autocomplete plugins such as YouCompleteMe and neocomplete provide a lot of very useful completions out of the box, and they work with vimtex (see `:h vimtex-complete-auto`)
- Completion of environment names is not useful, since environments should be defined through snippet engines and similar (e.g. UltiSnips or neosnippet)

**Comment by hellmean** [comment]
I didn't use snippets before. Thanks for pointing this out. Makes total sense! Sorry for a rushed post

**Comment by lervag** [comment]
@hellmean No problem at all. And please don't hesitate to open other issues if there are things that are unclear in the docs, or if you find a bug or have a feature request.
