### ISSUE TITLE
Multiline warnings are truncated in quickfix window

### ISSUE THREAD

**Issue by lahwaacz** [lervag/vimtex#265]
Consider the following warning from the .aux file:

```
Package babel Warning: Last declared language option is `czech,
(babel)                but the last processed one was `british'.
(babel)                The main language cannot be set as both a global
(babel)                and a package option. Use `main=czech' as
(babel)                option. Reported on input line 314.
```

Vimtex shows only the first line in the quickfix window, which is unfortunately not clear at all. Is it possible to improve the .aux file parsing to recognize such multiline warnings?

**Comment by lervag** [comment]
@lahwaacz Thanks for reporting this. First, though, note that it is the `.log` file that is parsed, not the `.aux` file. And yes, it is possible to improve the parsing. However, the errorformat syntax and system is not very easy and flexible. I was able to parse the given message. Note though, that I need to manually add support for different kinds of warnings and messages. Please don't hesitate to open similar issues for different warnings, so that I can try to add more of them.

**Comment by lahwaacz** [comment]
Oops, obviously it's the log... Anyway, thanks for fixing this -- however, the message in the quickfix window now ends with `Use `main=czech' as`, as if the last line were not parsed. Or is it something else?

**Comment by lervag** [comment]
Yes, I should have mentioned: The last line contains the line number where the warning was issued. To parse this, I had to "gobble" the message, which means the last part does not show up. I don't think this should be too big a problem, or?

**Comment by lahwaacz** [comment]
Well, it's certainly better than before...

You might also want to take a look at [rubber](https://launchpad.net/rubber)'s `rubber-info` tool, which can be used to extract warnings and errors from the log. It is imperfect, but you might find some inspiration...

**Comment by lervag** [comment]
IMHO it works well enough for most people. I personally don't want to add to the complexity of vimtex by adding a new tool to parse warnings and errors. This would require an update to the `errorformat` for the output of the tool (e.g. rubber). And since I can not assume everyone has that tool, I must support the old `errorformat` as well.

Thanks, though: I was not aware of rubber. It seems like an interesting project.
