### ISSUE TITLE
Compile and produce rtf at the same time

### ISSUE THREAD

**Issue by awelormro** [lervag/vimtex#2673]
### Description

Not a dramatic issue, just want to know if vimtex provides something similar to combine the compiler and a function similar to latex2rtf to produce word-friendly results, as a need in my job I need to produce documents able to open in word and a pdf at the same time

### Steps to reproduce

not necessary

### Expected behavior

Just a way to produce a rtf file at the same time of a pdf

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
not needed
```

**Comment by lervag** [comment]
> just want to know if vimtex provides something similar to combine the compiler and a function similar to latex2rtf

Well, yes and no. VimTeX uses latexmk, by default. latexmk is a LaTeX build tool that is quite flexible. It should be quite easy to add a build step that runs `latex2rtf`. I don't know exactly how, but I think you should be able to find something helpful by searching.

However, I'm curious: why do you need to run `latex2rtf` continuously while you are working on your document. Can't you just run it when you are finished?

Also, you could possibly use a separate terminal and something like [entr](http://eradman.com/entrproject/) to run `latex2rtf` everytime a tex file is changed. IMHO, this is a very simple solution that basically solves your problem in a manner that is also useful for other similar situations.

By the way, you could also consider to use pandoc instead of `latex2rtf`. See e.g. this thread: https://tex.stackexchange.com/questions/8836/producing-doc-docx-from-latex.

**Comment by awelormro** [comment]
I know about pandoc and it's great, but latex2rtf is making me a little easier the conversion, and it's all about compatiblities, Pandoc needs a few extra steps to produce the files that I need and latex2rtf is producing directly some rtf files with the exact indicators in this case, I know, it's curious how it is working but  latex2rtf is generating a painless way to produce my documents. When I write rmd files it's amazing but sometimes it's a little bit buggier than latex2rtf
