### ISSUE TITLE
Indent of \label

### ISSUE THREAD

**Issue by Eisfreak7** [lervag/vimtex#268]
I'm not sure, weather this is a problem of vimtex since I don't understand the reasoning behind it.
However, syntactic tells me that I should remove the whitespace before a ```\label``` to "maintain correct pagereferences."
When I follow this advice, vimtex will indent it again the next time I do ```gg=G```. Is this intended?
As I said, I'm not aware of the reason why label shouldn't be indented.

**Comment by lervag** [comment]
Hi @Eisfreak7. I don't use syntactics to check LaTeX documents myself, but I have never before heard or seen that one should not have whitespace in front of `\label`s. If you find a very good reason why this is the case, then I might consider the update this, but personally I like to keep things indented, e.g., I want the indentation to work like this:

```tex
\begin{equation}
  \label{eq:my_equation}
  f(x) = x
\end{equation}
```

**Comment by Eisfreak7** [comment]
Okay then I'll just disable the warning. I thought maybe you'd know the reason and just forgot to implement it in the indentation rules, but if you don't it's probably not important.
Chktex seems pretty abandoned anyway, I'm thinking about disabling it (although it catches some legitimate errors, too).

Thanks!

**Comment by lervag** [comment]
No problem!

**Comment by Rmano** [comment]
Hi @Eisfreak7  --- labels should be attached to the thing they labels without spaces because otherwise the "invisible anchor" can ends on a different page. If you write for example 
```
... this is something \label{word:something} you have to know 
```
and then you want to `\pageref` to it, if a page break occurs just between "something" and "you", the page number can be off by one. 

Obviously, for captions and equation this is not a problem, because they don't split over pages (at least not normally).

**Comment by lervag** [comment]
Thanks for the info, @Rmano!
