### ISSUE TITLE
imap mappings suggestions

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#277]
Here a couple of observations made on the imap mappings:

- how about adding
```vim
    call vimtex#imaps#add_map( {'lhs_rhs' : [ 'U', '\Upsilon'], 'wrapper' : 's:wrap_math'} )
    call vimtex#imaps#add_map( {'lhs_rhs' : [ 'P', '\product'], 'wrapper' : 's:wrap_math'} )
``` 
and would not
```vim
    call vimtex#imaps#add_map( {'lhs_rhs' : [ 'S', '\sum'], 'wrapper' : 's:wrap_math'} )
``` 
instead of `\Sigma` be more common ?

- instead of `qh,ql,qH,qL` that clobber `q=\theta`, how about
```vim
    \ { 'lhs_rhs' : ['<-',    '\leftarrow'],  'wrapper' : 's:wrap_math'},
    \ { 'lhs_rhs' : ['<--',    '\longleftarrow'],  'wrapper' : 's:wrap_math'},
    \ { 'lhs_rhs' : ['->',    '\rightarrow'], 'wrapper' : 's:wrap_math'},
    \ { 'lhs_rhs' : ['-->',    '\longrightarrow'], 'wrapper' : 's:wrap_math'},
    \ { 'lhs_rhs' : ['<->',    '\leftrightarrow'], 'wrapper' : 's:wrap_math'},
    \ { 'lhs_rhs' : ['<-->',    '\longleftrightarrow'], 'wrapper' : 's:wrap_math'},
    \ { 'lhs_rhs' : ['=>',    '\Leftarrow'],  'wrapper' : 's:wrap_math'},
    \ { 'lhs_rhs' : ['<=',    '\Rightarrow'], 'wrapper' : 's:wrap_math'},
   ....
```
However, for the down/upwards variant no such intuitive alternative comes to mind. An aside: `\Leftarrow` often intends `\implies` and `\Leftrightarrow` instead `\iff` .

- the following maps were disabled because the clobbered common keys:  
```vim
    let g:vimtex_imaps_disabled = ['lim', '...', '_', '{{', '[[']
```
For example `lim` clobbered `l=lambda`, and `...` clobbered`.`, and `{{` clobbered `{`.
 => How about disabling the snippets by default? These are somewhat contrary to the minimalistic spirit of `vimtex` anyway, and end up clobbering common keys such as `.`, `{`, and `[`.

**Comment by Konfekt** [comment]
Perhaps also: How about setting `s:wrapper` as default ? Other than that
```vim
let g:vimtex_imaps_list = [
      \ { 'lhs_rhs' : ['0',     '\emptyset'],   'wrapper' : 's:wrap_math'},
      \ { 'lhs_rhs' : ['6',     '\partial'],    'wrapper' : 's:wrap_math'},
      \ { 'lhs_rhs' : ['8',     '\infty'],      'wrapper' : 's:wrap_math'},
      \ { 'lhs_rhs' : ['=',     '\equiv'],      'wrapper' : 's:wrap_math'},
      \ { 'lhs_rhs' : ['\',     '\backslash'],   'wrapper' : 's:wrap_math'},
...
```
is self-explanatory, and could be put in the documentation.

**Comment by lervag** [comment]
Thanks for the suggestions. There's a lot of thoughts here, so I'll try to consider all of them. I'll make checkboxes in order to ensure that we've handled all the issues.

- [ ] "Setting `s:wrapper` as default - you mean set `s:wrap_math` as default wrapper, instead of no wrapper?
- [ ] The reason I don't want to put all of `g:vimtex_imaps_list` into the doc is simply because it is long. It makes it "hard" to keep up to date, i.e., if I forget to change the doc after updating the defaults. Thus I think it is OK to state the the default value is found in the source.
- [x] `U -> \Upsilon` is OK. The reason I didn't add this in the end was because `\Upsilon ~ Y`, so I didn't think anyone needed the actual greek version. I'll add it.
- [x] You are right: `\Sum` is more common than `\Sigma`; I'll update,
- [ ] I think you are on to something with the arrow maps. How about `-j` for down array and `-k` for up arrow? Not perfect, but arguably more inline with the left and right arrows you suggest?
- [ ] Also, what do you mean that `qh` clobbers `q=\theta`?
- [ ] What do you mean with `\Leftarrow` intends `\implies` (and the rest of that aside)? Was there a suggestion here as well? Did you mean we should let `qH` (or `<=`) map to `\imples`?
- [ ] Finally, I understand your thoughts about the clobbering of the unleadered maps. Personally, I like them alot, especially `__` and `^^`. However, `lim` is leadered, so I don't understand why this is a problem? What is your imaps leader key (default is ` (backquote))? When you say they were disabled, you mean you disable them because you don't like them? Note, I might agree that these maps (or some of them) could be optional with default off.

**Comment by Konfekt** [comment]
- yes `s:wrap_math` was meant.
-  One problem is that the add function is bufferwise so that it has to be called by an autocmd. So somehow it is inconvenient to setup one's own imap. If  it's kept in the source, then perhaps putting it as a `g:imaps_list` at the beginning of the file and mentioning that in the doc.
- ...
- ...
- Yeah, these `-j/k` might be the best workaround, unfortunately the horizontal variants have more intuitive imitations in ASCII.
- by `qh` clobbering `q` is meant that `<leader>q` does not print `\theta` but waits for an additional character until it times out, which may confuse the user
- this was just a TeX aside, as I've been using `\Rightarrow` for implications which it is not intended for, better use `\implies` for that.
- `<leader>lim` clobbers `<leader>l` in the same way as `<leader>qj` clobbering `<leader>q`, since when typing `<leader>l` the user expects to see `\lambda` and not a timeout.

**Comment by lervag** [comment]
Thanks for the clarifications!

I now see what you mean with the clobbering, and I agree it is unfortunate.

So, first, for arrows: I realized that we would get the same problem: `< = \leq`, for instance. So, it is still not clear how to solve this.

I'm also not sure how to solve the conflict between `lim` and `lambda`. Do you have a suggestion?

Personally, I find these issues really difficult, because they are not a technical challenge, instead a challenge in finding the "correct" set of default mappings, and the correct map definitions. Perhaps the solution is to reduce the number of default mappings? Considering #279: If I implement a better way to define custom maps, and if I add some common maps to the docs, then it would be easy for people to use custom lists, and the demand for a large default list becomes smaller.

**Comment by Konfekt** [comment]
My suggestion would indeed be to keep the default maps at a consistent minimal, and everything more fancy be a snippet.

For example, `l` could be a snippet `lim_{1} {0}`, and thus not an imap. This also made me change my mind that, for consistency, `S/P` should be `\Sigma/Product` (as all single letters corresponding to greek ones are imaps) and (`s` a snippet `\sum_{1} {0} as well as `p` a snippet `\prod_{1} {0}). These are however up to the user that uses a snippet engine which VimTeX is meant play ball with.

**Comment by Konfekt** [comment]
Here's another imap suggestion:
```vim
      \ { 'lhs_rhs' : ['v',     '\vartheta'],    'wrapper' : 's:wrap_math'},
```
By the shape of it, it's mnemonic.

One last point was, as already touched upon, to use iabb for certain abbreviations that end at a white space or new line, such as `iabb ... \ldots` or `+++ + \dotsb +`, or `-> \rightarrow`.

**Comment by hrouault** [comment]
The mapping `S` is defined twice: once as a full snippet `\sum_{${1}}^{${2}}${0}` and once as a simple `Sum`.
The first hidden version is quite useful. Should it be mapped through `sum`?

**Comment by lervag** [comment]
Thanks! I've added the suggested mappings, and I removed the `S -> \sum` that shadowed the full automatic snippet.

@hrouault Please see #295 for a discussion about the automatic snippets. It seems I might remove the support for automatic snippets altogether, and to leave this to the user to define manually. If you have any opinions, please don't hesitate to join the discusssion.

@Konfekt I'm closing this issue for now. I think the continued work on this should be postponed until #295 is handled. Don't hesitate to reopen or to open a new issue when the outcome of #295 is clear.

**Comment by Konfekt** [comment]
Ok. For consistency, you might think about turning`P` into `\Pi` (as `S` has gone).
