### ISSUE TITLE
Write about cmp-vimtex in the docs

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#2818]
This issue is create to specify the remaining actions from https://github.com/lervag/vimtex/issues/2786:

* Write a section about cmp-vimtex in the docs
* Announce the cmp-vimtex on Reddit

**Comment by lervag** [comment]
@micangl I'll tag you when I've written something and I will not announce anything until you feel that cmp-vimtex is "ready enough" (that might already be the case, but I'm not sure).

**Comment by micangl** [comment]
I think that at this point it's "ready enough". Obviously, some polishing is still due but, since the plugin seems to be working fine, I'll take care of eventual chores and new features without such a hurry.

This are some of the features and enhancements that I'd like to take care of, in the future:
- Apply the enhancements you made to the parser.
- Allow the user to specify when a reparse should be triggered and provide a command to do so (after a time interval, when a new file requiring it is opened, etc...).
- Let the user provide a custom formatting function for the documentation window.
- Ability to enable shortcuts for online search on bibliographic databases or search engines (user-specifiable).

As to publicizing the plugin, I'll also submit it to Dotfyle. Maybe, I could tag some of the "latex influencers" of the community, like ejmastnak (as you already have), benbrastmckie, casteldev, jdhao.

**Comment by ejmastnak** [comment]
> As to publicizing the plugin, I'll also submit it to Dotfyle. Maybe, I could tag some of the "latex influencers" of the community, like ejmastnak (as you already have), benbrastmckie, casteldev, jdhao.

Just chiming in to say I'm all on board for mentioning the plugin in my tutorials. 

There's a bit of a complication though: this topic is a total gap in my Vim/LaTeX knowledge—I've hardly ever actually used Vim completion with LaTeX (or any other filetype for that matter) beyond basic `<C-n>`/`<C-p>`. Since I have no meaningful experience/personal context to draw on, I think I'll wait until the docs are updated to get a better idea of everything the plugin offers and why to use it. And of course would be grateful for any suggests from more experienced users of what is worth mentioning.

**Comment by lervag** [comment]
I've added a very brief explanation of cmp-vimtex now. I don't really want to make the docs into a full tutorial, but this is perhaps too brief? I'd be happy to get some feedback or perhaps even suggestions for improvement.

@ejmastnak I would strongly advice that you look into using nvim-cmp; I've found it is very good and works very well with VimTeX even with the old cmp-omni source.

**Comment by micangl** [comment]
Maybe, a brief list of the features could be helpful for the reader. If you agree, I'll provide one.

Regarding a full blown tutorial, do you think that cmp-vimtex documentation should include one? Or is it, maybe, better to just link an independent one when it will be available?

**Comment by lervag** [comment]
> Maybe, a brief list of the features could be helpful for the reader. If you agree, I'll provide one.

Yes, that is probably useful. I'll be happy to consider adding one if you provide it.

> Regarding a full blown tutorial, do you think that cmp-vimtex documentation should include one? Or is it, maybe, better to just link an independent one when it will be available?

I think it would be very nice if cmp-vimtex gives a brief tutorial for how to properly install and configure nvim-cmp and cmp-vimtex. I don't think it should be as verbatim as a typical blog post, but complete enough that even newbies would have a change of understanding it.

**Comment by micangl** [comment]
@lervag Sorry for the long wait, I've been swamped with study because of the midterms. With regards to the list, what about the one with the most important features at the beginning of `cmp-vimtex`'s `README.md`?

```md
Provides support for:
- Fuzzy matching against all info provided by Vimtex (including bibliographic details, useful for citations):
- Parse and display all details contained in bibtex files:
- Trimming long strings in the completion menu (adds space for the documenation window):
- Trigger the completion menu automatically after typing `\cite{` (normally, it has to be done manually).
- Conveniently toggling symbols and additional information shown in the completion menu:
- Granuarly configuring the menus, and more (check out the sections below).
```

I'll start, instead, to work on the tutorial as soon as I can. What do you think:
- Should it be included in the `README.md`?
- Or, maybe, it would be better included in a separate file (at the cost of possibly being missed by hasty users)?

I'm honestly more for the second option but, the thought of some people missing it, is all but assuring...

**Comment by lervag** [comment]
> @lervag Sorry for the long wait,

I guess that's just life. Let's just acknowledge the fact that we are all busy people. I'm glad when I have time to follow up on VimTeX stuff!

> With regards to the list, what about the one with the most important features at the beginning of `cmp-vimtex`'s `README.md`?

Yes, that seems like a good idea. I've added it now.

> I'll start, instead, to work on the tutorial as soon as I can. What do you think: …

I think it makes sense to have it as a separate file and that you make a link to it from the README file.

**Comment by micangl** [comment]
I think we're pretty much done.
