### ISSUE TITLE
Setting vimtex_indent_lists to empty will make all environments behave like list instead

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#2846]
As in the title.

The suggestion to set this variable to `[]` was made in https://github.com/lervag/vimtex/issues/2599 , but it doesn't seem to behave the expected way.

This is caused by the code:

https://github.com/lervag/vimtex/blob/master/indent/tex.vim#L234-L237

if the list is empty, the regex being constructed end up being `\\end{\%(\)`, which matches the end delimiter of every environment.

Side note, in the current situation it will also match any environment name that *starts* with one of the items in the list.

Side note 2, actually this explicit setting of `g:vimtex_indent_lists` is only necessary because vimtex cannot look backward in the document to see whether any occurrence of `\item` appeared in the current environment, right? Otherwise we can just look behind to see if any string `\item` appeared in the current environment (and not in any nested environment, which can be annoying to implement anyway)

**Comment by lervag** [comment]
> The suggestion to set this variable to `[]` was made in #2599 , but it doesn't seem to behave the expected way.

Sorry, that's fixed now!

> Side note, in the current situation it will also match any environment name that _starts_ with one of the items in the list.

This is partly intentional; the list is a list of regexes and the user has flexibility to make it more or less strict.

> Side note 2, actually this explicit setting of `g:vimtex_indent_lists`

You mean the default value? Or some other explicit setting?

> is only necessary because vimtex cannot look backward in the document to see whether any occurrence of `\item` appeared in the current environment, right?

I mean, we _can_ look backward - I do that a lot. But it is quite expensive, so I try to avoid things like that.

> Otherwise we can just look behind to see if any string `\item` appeared in the current environment (and not in any nested environment, which can be annoying to implement anyway)

Sorry about my confusion, but what are you trying to achieve? The point of the option is to allow users flexibility in when to indent the `\item`s...

**Comment by user202729** [comment]
> This is partly intentional; the list is a list of regexes and the user has flexibility to make it more or less strict.

I see. Maybe mention in the documentation (and also documentation of related settings such as `g:vimtex_indent_ignored_envs`)?

> Sorry about my confusion, but what are you trying to achieve? The point of the option is to allow users flexibility in when to indent the `\item`s...

Ah I see. (the following code is consider "correctly indented" by vimtex.)

```
\begin{quote}
	% correctly used:
	\begin{quote}
		stuff
	\end{quote}
	\begin{itemize}
		\item stuff
			stuff
		\item stuff
			stuff
	\end{itemize}
	% "incorrectly used":
	\begin{quote}
	\item stuff
		stuff
	\item stuff
		stuff
	\end{quote}
	\begin{itemize}
		stuff
\end{itemize}
\end{quote}
```

I originally thought of: if `\item` is detected in the environment body then automatically indent it as if it's a list environment, otherwise automatically indent it as if it isn't. But looks like the behavior is different when `\item` is used in a non-list environment as well.

I suppose not much point changing then.

**Comment by lervag** [comment]
> > This is partly intentional; the list is a list of regexes and the user has flexibility to make it more or less strict.
> 
> I see. Maybe mention in the documentation (and also documentation of related settings such as `g:vimtex_indent_ignored_envs`)?

Yes, good point. I'll fix that as well.

> ```tex
> \begin{quote}
> 	% correctly used:
> 	\begin{quote}
> 		stuff
> 	\end{quote}
> 	\begin{itemize}
> 		\item stuff
> 			stuff
> 		\item stuff
> 			stuff
> 	\end{itemize}
> 	% "incorrectly used":
> 	\begin{quote}
> 	\item stuff
> 		stuff
> 	\item stuff
> 		stuff
> 	\end{quote}
> 	\begin{itemize}
> 		stuff
> \end{itemize}
> \end{quote}
> ```

Yes, this output is as expected (by me). The last `itemize` becomes incorrectly indented because there is no `\item`. I think it's safe to assume that the user always wants to add an `\item` in an `itemize`.

> I originally thought of: if `\item` is detected in the environment body then automatically indent it as if it's a list environment, otherwise automatically indent it as if it isn't.

Ok, I see. If I did find a good way to implement this feature I think I would like to do it, and instead have an option to toggle it on/off. I believe users who want to indent `\item` wants that _everywhere_. But: I don't know exactly how to implement this in a good way.

I _could_ try to do a lookahead and count `\item`s in the current environment. But I don't really like that very much, because I want to make the code as stateless as possible.
