### ISSUE TITLE
Input/selection method utilizing `vim.ui.input/select` in NeoVim 

### ISSUE THREAD

**Issue by jdujava** [lervag/vimtex#2856]
Current `nvim` input/select/confirm methods are hard to customize (at least I didn't find a nice way).

It would be amazing, if there was an option utilizing `vim.ui.input` and `vim.ui.select`, which are easily customized (for example by various NeoVim plugins like https://github.com/stevearc/dressing.nvim).

**Comment by lervag** [comment]
This is unfortunately not so simple, because `vim.ui.*` are async by design and uses the invertion of control pattern. This is incompatible with the structure/style of VimTeX. See https://github.com/neovim/neovim/issues/24632 for related information.

I agree it would be nice to use more convenient and builtin input and select methods. If or when it becomes implemented as per 24632 I will likely consider to update.
