### ISSUE TITLE
 latexmk is not executable

### ISSUE THREAD

**Issue by thrisp** [lervag/vimtex#290]
I'm getting this on startup, where previously I had no issue:

```
vimtex warning:                                                                                                                                       
  vimtex#latexmk was not initialized
  latexmk is not executable
```
I can continue and all seems to be running, I can at least continue working on my tex document.

I am an infrequent user of tex, latex, and this plugin but have been using more recently. What would cause this issue and how can I troubleshoot it further? 

After removing and reinstalling, there was no issue until I reopened a file a second time -- then this notice again.

**Comment by lervag** [comment]
Do you have `latexmk` installed?

**Comment by thrisp** [comment]
Well, I do now and this resolves the problem, but this has been installed for over 18 months with sporadic use and I've never recceived that message, something in my recent explorations of use tex caused that to be needed I guess.

**Comment by lervag** [comment]
Over the last 18 months there have been LARGE changes to vimtex, so I am not surprised if sporadic use may lead to some surprises.

The warning you recieved is due to the fact that the `latexmk` features are enabled by default, and they require `latexmk`. Thus, I added a check some time ago to let users know if `latexmk` is not located. For users who are not interested in the latexmk features, these may be turned off with `g:vimtex_latexmk_enabled`.
