### ISSUE TITLE
Disgusting visual editing mode

### ISSUE THREAD

**Issue by zjhJOJO** [lervag/vimtex#2916]
### Description

First and foremost, I would like to emphasize that this issue may not be related to vimtex, but it has been bothering me for some time. I hope someone can assist me with it. Here is the problem:

When using Vim to edit a tex file, I noticed that it automatically enters the visual editor mode, similar to the visual editor in Overleaf, as shown below:
<img width="949" alt="Snipaste_2024-04-07_15-26-01" src="https://github.com/lervag/vimtex/assets/16676896/bb5b81cd-2078-4fdc-8170-ebd2aa8e34c7">
However, when I turn off "syntax", it reverts to "normal" mode but without highlighting, as shown below:
<img width="1205" alt="Snipaste_2024-04-07_15-32-04" src="https://github.com/lervag/vimtex/assets/16676896/e17c5449-2813-4141-bd80-ffa03e6ed8b2">
 

### Do you use a latexmkrc file?

yes

### VimtexInfo

```yaml
we do not use vimtex here
```

**Comment by kiryph** [comment]
I suspect the OP is referring to the concealment feature of vim and uses the term "visual editing mode" for it. This is unfortunate since vim provides a "visual mode" which has nothing to do with the concealment feature.

The concealment definitions are part of standard vim's latex syntax  file and VimTeX's latex syntax file. 

@zjhJOJO 
You can disable concealment (aka "disgusting visual editing mode") with `:set conceallevel=0` and still have syntax highlighting.

Whether it should be called "disgusting", should be left to each persons judgement. I would avoid this kind of wording, in particular, when raising an issue in an open-source repository maintained by others in their spare time.

If you like parts of the concealment, for example replacing greek letters (`\alpha`) with their unicode symbols (⍺) when the cursor is not on this line, read `:h tex-conceal` for standard syntax file or `:h vimtex-syntax-conceal` when using vimtex.

**Comment by lervag** [comment]
> I suspect the OP is referring to the concealment feature of vim and uses the term "visual editing mode" for it. This is unfortunate since vim provides a "visual mode" which has nothing to do with the concealment feature.

Thanks, @kiryph; it seems the most likely original intention and I agree it is unfortunate to confuse these terms.

> @zjhJOJO You can disable concealment (aka "disgusting visual editing mode") with `:set conceallevel=0` and still have syntax highlighting.

I would also add that we can _fully_ disable the VimTeX conceals with the option `let g:vimtex_syntax_conceal_disable = v:true`.

> ### VimtexInfo
> 
> ```yaml
> we do not use vimtex here
> ```

I don't quite understand why you wrote this instead of just including the `:VimtexInfo` output as asked for. Although it is not entirely necessary to help you here, it is still useful input that provides more context that _could_ be useful.
