### ISSUE TITLE
Automatically open quickfix window after single shot compilation?

### ISSUE THREAD

**Issue by atorg** [lervag/vimtex#293]
The help file under the g:vimtex_quickfix_mode option is pretty clear that this isn't supported by default.

Is there a workaround to create this type of behavior? 

It is possible in Latex-Box. I would love to switch from Latex-Box to vimtex but I dislike continuous compile and want compilation to be completely in the background unless there's some error.

**Comment by lervag** [comment]
Hi. I'm sorry, but no, there is no current workaround.

I know this is possible in LaTeX-Box. I actually started vimtex with Latex-Box as a base implementation, and I removed this feature specifically. The reason is simple: It was complex and error prone: The feature requires a very long and complicated shell command (`:! ...`) to work in general, and for windows it required what I would call ugly hacks. I really didn't like that, I decided that I wanted to keep things simple. So, I removed the feature.

The continuous compilation feature is clearly also quite complicated, but it is much simpler (IMHO), because it relies on the callbcak functionality of latexmk.

So, again: The feature does not exist, and there is no workaround. I do not really know how to implement this without doing the same thing as is done in Latex-Box. I would be happy to consider this feature if we could find a way to implement it that keeps things simple.

I would suggest that you either 1) learn to use the `<leader>le` mapping to check for errors, 2) consider to use the continuous feature (it might grow on you), or 3) use Latex-Box.

**Comment by lervag** [comment]
Btw: Continuous compilation is in my experience "completely in the background, unless there's some error".

**Comment by atorg** [comment]
I certainly understand your position. The whole reason I want to use vimtex is because it seems like a much improved and less error-prone version of Latex-Box. I have very little experience with the workings of vim or vimscript, so I trust you when you say that this is a problematic feature.

I might try 1) and/or 2) for a day and see if I can get used to them.

My main concern with 2) is that I often work with presentation (beamer) documents that take an awfully long time to compile (10-20 seconds). It seems like this would make continuous compilation particularly annoying. But perhaps I am wrong here, so maybe I should give it a shot before dismissing it.

**Comment by lervag** [comment]
Regarding your concern: I also work with documents that take a long time to compile, e.g. when I use the `biblatex` package for references, or when I use `microtype`. I personally think it works well with continuous compilation, but I do agree that it would be very nice to have a single compile alternative with the callback feature.

Which OS are you on? If, after you have tried out continuous mode, still feel that you want the single compile feature with callback, then I could consider to solve it for unix systems. I think I can do that without very high complexity (with shell scripts).

**Comment by atorg** [comment]
I'm using Linux.

**Comment by lervag** [comment]
Thanks. Please feel free to reopen the issue if you feel that the single compile feature with callback is still necessary after having tested the continuous compile feature for a couple of days.

**Comment by atorg** [comment]
Sounds good. Thanks!
