### ISSUE TITLE
Future of automatic snippets

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#295]
I would like some user input, so I am tagging a few of the active users of vimtex:
@Konfekt 
@nasenatmer 
@leomao 
@pluskid
@vsilv

From the user perspective: What do you expect from a good LaTeX plugin? How do you like the current state of the imaps feature?

The automatic snippets keep bugging me. It still doesn't really feel right. I am considering to either:

1) Implement a good solution for the automatic snippets that works with no extra plugins,

2) Keep the current state and insist on either neosnippet or UltiSnips, or

3) remove the automatic snippets altogether and only keep the abbreviation-like mappings. 

I am not really sure how to proceed. On one hand, I don't really think that 1) is that complicated, and so I am tempted to go for it. On the other hand, it kind of goes against my principles, since the automatic snippets can utilize the strength of other plugins. Still, I think there is a case for being pragmatic. A nice set of abbreviations, including the current set of automatic snippets, seems like a useful feature for very many people. It seems to me that it might be worthwhile to implement this as a full part of vimtex. It would make it simple for everyone, and it would make it more easy for me to maintain.

The last alternativ is also somewhat tempting, as it stays more true to keeping things simple. Those who want and need the more complex automatic (and full) snippets can get them (and create them) from the snippet plugins.

Note: I am NOT saying that I want to implement a full snippet feature! I am talking about a feature similar to the anonymous snippets in UltiSnips and neosnippet, or similar to the IMAP feature of LaTeX-Suite.

Also note: I am aware that there are still some open issues on the imaps feature (and other things). I am sorry for taking so long to address them, but I am keeping track both of the open issues and on closed issues that still have ongoing discussions.

**Comment by vsilv** [comment]
Dear Karl Yngve Lervåg,

I have never used the snippet plugin from vimtex.
However, I am using UltiSnips for quite a while and it combines brilliantly with vimtex, so I would rather consider your second option.
Since Snippets should also be coherent with autocomplete and tabbing, I would prefer an external solution so everything is modularized cleanly.
I am still having this issue with the Dead Signal Caught shutdown, but unfortunately I did not have the time yet to look into it to find the problem.
Anyway, I have used vimtex very intensively for writing my thesis last summer and I am very grateful for you having provided this plugin.

with best regards,

vsilv

**Comment by pluskid** [comment]
Thanks for asking comments! I do not like the abbreviation behavior of VIM very much because there is then no type feedback -- you do not see what you are typing until you typed out the whole abbreviation key. This might be a limitation of VIM itself so probably very difficult to solve in this plug-in. But I'm just mentioning this purely from a user's perspective.

About automation of equation typing, I really like [this sublime text plugin](https://github.com/randy3k/LaTeX-Plus). It really makes typing equations much faster and less painful (debugging when braces are not matched is not fun). It's behaviors are almost all documented [here](https://github.com/randy3k/Latex-Plus/wiki/User%20Manual). For example, you get `()` when typing a `(`, but if you type `(` **again**, you get `\left( \right)`, and similar for other brackets. Other handy stuff like `<leader>/` gives you `\frac{}{}`, `...` gives you `\ldots`, `-> ` gives you `\rightarrow`, and those greek letters using backquote leader key.

That being said, I'm kind of against the abbreviation-typed behavior because of its bad user interface. But otherwise, I'm quite OK (just from a user's perspective) with the rest stuff.

**Comment by Rmano** [comment]
I was not on the list, but I agree with @vsilv  --- UltiSnips is easy to use and really powerful, so I think that there is little gain in duplicating functionality.

**Comment by nasenatmer** [comment]
Hey, I think it's a really good idea to ask users what they use most and prefer to be there in vimtex.

I personally disabled `imaps` yesterday after wondering why vim was always taking a pause when I finished a sentence. But this is mainly because [bone](http://wiki.neo-layout.org/wiki/Bone) has `…` as a key and more importantly I don't need to write equations or math environments.

So personally, I think vimtex would be leaner and easier to maintain with option 3, but as I don't have the work to maintain it I'd prefer to abstain from the vote since there might be good reasons to go for scenarios 1 or 2.

1 has the advantage of not forcing a specific completion engine upon the user, something I think is quite a good thing as personal tastes may differ widely among users.

But then on the other hand, why re-invent the wheel and not completely outsource/make use of popular snippet enginges (which must have the same snippets that are defined in vimtex' list, haven't they?) and keep vimtex KISS?!

I'm undecided…

**Comment by Konfekt** [comment]
I'd lean towards (3). If the handy `__` and `^^` snippets can  be implemented in neosnippet or UltiSnips, how about documenting them ? If not, consider a simple function achieving what https://github.com/lervag/vimtex/issues/278 aimed at but stop there.

**Comment by fuzzybear3965** [comment]
I currently use vimtex alongside UltiSnips and I find that to be very satisfactory. Vimtex (as far as I'm aware) is intended to allow for LaTeX compilation and to introduce syntax features (delimiter jumping, text objects, highlighting, etc.). Code/Language completion/snippets is not and should not be a vimtex feature, as far as I'm concerned. The concept of snippets is broader than LaTeX and is used in many other contexts. UltiSnips is a great (and simple) tool that has already been designed to handle snippets really well. I've been using that alongside vimtex for some time and I'm really happy. There is nothing I can not do that I want to do.

My advice is this: Direct people to the great tools that already exist. Tell them about Ultisnips. It's completely satisfactory for all purposes that I've encountered.

**Comment by lervag** [comment]
If I understand the feedback correctly, it seems that option 3 would be satisfiable to most (or all) of you. This would mean the following change:

- Support for the abbreviation-like mappings will be kept as is (e.g. `´a => \alpha` and `´b => \beta`). The feature could be improved in the future, but the snippet-like functionality will never be brought back.
- The abbreviation like mappings that does not require a leader key will be turned off by default. This is in order to stay out of the users way; it is easy to add these mappings for those who like them.
- Support for the automatic snippet feature is removed, which means it will not longer be possible for the mappings with `$1` identifiers.
- The documentation will be updated accordingly, and I will add a text that points to UltiSnips and neosnippet for the snippet feature. I will also write about automatic snippets and explain how to create them with both Ultisnips and neosnippet (note that existing snippet bundles do NOT contain any automatic snippets, these must all be created manually by the user).

This change will make things much easier for me as the developer.

I am very interested to hear if this change will upset anyone! That is, if you really love the automatic snippets, and you feel it is wrong to remove them (and that you have to add these manually), please let me know! At the moment, I get the impression that everyone thinks it is OK to add snippets (including the automatic ones) manually.

**Comment by leomao** [comment]
Hi
The proposal above looks great to me.
I use vimtex mainly for compilation and some text objects and the ability to jump between `\begin`, `\end`.
I think abbreviation-like mappings (which is mentioned above) are really useful for users who write math equation frequently, so keeping them is a good idea.
But for snippets, I would like to use a general snippet engine and add personal snippets that are heavily used by me.

Thanks for asking users' comments!

**Comment by lervag** [comment]
Ok, so, I've made a first attempt at solving this issue once and for all. The update is mostly a simplification: I've removed the automatic snippets. I've also added a utility function mapped by default to `<localleader>lm` to view the list of imaps.

I'm looking forward to hearing some feedback. Feel free to open new issues or to continue the discussion here (although I'm closing this for now, since I consider it solved).

**Comment by nilsbecker** [comment]
i'm not upset :) leaving all abbreviations with arguments to the snippet engines seems like the sanest idea to me. 

nevertheless it may be good to give people an example of how to make an anonymous snippet in either UltiSnips or neosnippet or both. 

the most comfortable solution for users would be to maintain a tex snippet file for these plugins as part of vimtex, for users to copy and paste from. this full-fledged solution may not be worth the maintenance burden. maybe two simple examples in the documentation would still make sense?

**Comment by lervag** [comment]
I've updated the docs with examples. I hope you find them sufficient.
