### ISSUE TITLE
Show affected file in error messages

### ISSUE THREAD

**Issue by lbischof** [lervag/vimtex#299]
The file where the error is occurring should be shown in the quickfix window. Currently something like this appears:
```
main.tex|2 warning| Overfull \hbox (6.0pt too wide) in paragraph at lines 2--2
```
If I run latexmk:
```
) (./part1/04_firmenstandards.tex [11]
Kapitel 4.
(/usr/share/texlive/texmf-dist/tex/latex/listings/lstlang1.sty)
(/usr/share/texlive/texmf-dist/tex/latex/listings/lstlang1.sty)
Overfull \hbox (6.0pt too wide) in paragraph at lines 2--2
[][][][][][][] 
) (./part1/05_organisationderipa.tex [12]
```
Is there anyway to fix this?

**Comment by lervag** [comment]
Yes, but I've chosen not to. The reason is that it doesn't work consistently. I've explained the problem [here](https://github.com/lervag/vimtex/issues/21#issuecomment-49508495).

I really would like this to work, but as explained in the comment above, there is no way to make pdflatex (or friends) to NOT break the file paths when they get longer than 80 characters, and since ALOT of file paths (from included packages and similar) often have very long paths, this tended to become a large issue.

I hope you can live with this, although I understand the annoyence!

**Comment by lbischof** [comment]
I didn't see any long lines in my file. How often does it break? Only on windows? Maybe if it's not often you could add the correct filename to some error messages and a star or something to the rest. This means that I have to run latexmk by hand and read the ugly output when I have errors... Does any other vim plugin handle this correctly?

**Comment by lervag** [comment]
When I tested, it broke on most of my documents. I am on Linux. I also know this happened for other people.

You should know that I really tried to get this working, and that I almost did. Unfortunately, I was not able to make it work, and I do not want to add this option unless it works well.

To my knowledge, there is no Vim plugin that handles this correctly. The topic is discussed in the referenced issue (#21),

Note, though: If you happen to find a solution, I am very happy to try to implement it!

**Comment by lervag** [comment]
By the way, the file name should be at least partially parsed. Could you create a minimal working example of the problem? Perhaps I could solve this in some other way...
