### ISSUE TITLE
Fold text is not extracted from caption if there is whitespace between the optional and the mandatory argument

### ISSUE THREAD

**Issue by ehahn** [lervag/vimtex#303]
If there is whitespace between the optional argument and the mandatory argument of a `\caption`, the fold for the surrounding table has no label. 

Example 1:

    \begin{table}
        \caption[foo] {bar}
    \end{table}

Example 2:

    \begin{table}
        \caption[foo]
        {bar}
    \end{table}

**Comment by lervag** [comment]
I've fixed this for your first example. The second example is worse, and I've decided to not fix that. The reason is that it becomes much more complicated if I have to parse multiple lines, because then I have to parse multiple matching sets of braces in a more general way. This is surprisingly hard, and since it is very rarely necessary, I don't want to implement it.
