### ISSUE TITLE
Help file does not highlight some code blocks correctly

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#3031]
Apparently, unlike markdown where `` `​`​`vim ... `​`​` `` will syntax highlight the content inside as vim, in vim markdown you cannot do that.

On my machine it displays as follows.

![image](https://github.com/user-attachments/assets/3c381d09-5fb6-4396-90c8-a5e054002d51)

This causes trouble because some `|` may be interpreted as tags. A bit later in the same help entry there is:

![image](https://github.com/user-attachments/assets/7bca3253-7fa9-4b89-9bc1-67e2ef58b029)

There's some `>conf` around too.

From `:help help-writing`:

```
To quote a block of ex-commands verbatim, place a greater than (>) character
at the end of the line before the block and a less than (<) character as the
first non-blank on a line following the block.  Any line starting in column 1
also implicitly stops the block of ex-commands before it.  E.g. >
    function Example_Func()
	echo "Example"
    endfunction
```

(On the other hand, it may be worth it to ask vim maintainer to extend the feature --- because then we get more syntax highlighting, but this might break some existing help files by highlighting them incorrectly. What do you think?)

**Comment by lervag** [comment]
Ah, yes. The discrepencies between Vim and neovim are increasing, and this is one of the consequences. I personally use Neovim and I strongly prefer it to Vim these days.

Now, I could change this back (i.e., change every `>lang` to `>`) to keep full Vim compatibility. But I don't wnat that, because the convenience of having proper syntax highlighting of the listings are too big. Thus, I would claim it is a better coarse of action to ask the Vim devs to implement this nested syntax highlighting support on Vim as well.

**Comment by lervag** [comment]
To expand slightly, this is how the sections look on my end:

![image](https://github.com/user-attachments/assets/97c4459f-41dd-458d-8844-94312bdeb354)

**Comment by lervag** [comment]
Cool; for reference, the issue is here: https://github.com/vim/vim/issues/10597

> (nitpick: "course" instead of "coarse". Sorry)

Thanks! I appreciate being corrected on bad language/writing. <3
