### ISSUE TITLE
Support for live previewing

### ISSUE THREAD

**Issue by samvv** [lervag/vimtex#305]
Can Vimtex be used to live-preview your pdf-document?
With that I mean auto-refresh and forward search; without window focus.

If the plugin is not able to do so at the moment, would it be possible to implement this?

I came across [Vim-Latex Live Preview](https://github.com/xuhdev/vim-latex-live-preview) as per your suggestion, but it looks quite messy to have two conflicting build systems (Live Preview not using build configuration variables that are used by Vimtex).

**Comment by lervag** [comment]
It depends what you mean by "live preview". In my setup, the latex document is compiled everytime I save the document, after which the pdf viewer is refreshed. There is no automatic forward search; to me this seems both unecessary and annoying. Forward search can be done manually on `<localleader>lv`.

It helps if you can be more specific in what you want. If you by live preview mean that the pdf should be updated as you write, then I can already now say that I don't want to implement this feature. This is provided by [vim-latex-live-preview](https://github.com/xuhdev/vim-latex-live-preview), and I think it could work to use both. I have not tried myself though. Note that if you try, then you should probably disable the `latexmk` and `viewer` modules with `g:vimtex_latexmk_enabled` and `g:vimtex_view_enabled`.

**Comment by samvv** [comment]
Sorry for the late response.

I was indeed talking about a "preview on write"-command. Can you tell me how you implemented it?

And you are right, of course. It is perfectly possible to use both.

**Comment by lervag** [comment]
I suggest you look at the source code for vim-latex-live-preview, see [here](https://github.com/xuhdev/vim-latex-live-preview/blob/master/plugin/latexlivepreview.vim). It uses python code and vimL in combination, but it is rather easy to read the code and it is only about 200 lines.

Note, what it does is that it uses autocommands, in particular the three events `CursorHold,CursorHoldI,BufWritePost`, in order to issue the compiles.

Note also that I believe this is not that good of a feature. Many latex documents take quite some time to compile, and in these cases, "live preview" is not really possible. I think it is better to use latexmk and instead recompile whenever you update the files (i.e. write).

**Comment by chantisnake** [comment]
@samvv you can use this plugin and https://github.com/907th/vim-auto-save 

it works great!

**Comment by lervag** [comment]
I guess the combination of using `latexmk` (either through vimtex, or manually) with `vim-auto-save` might be convenient. I would note, though, that for large documents, compilation can take quite some time for LaTeX documents. Thus in these cases, I think it is more sensible to be able to plan the compilation, e.g. through manual writes.

**Comment by samvv** [comment]
@chantisnake Manual writes are OK for me, but thanks for the tip! :)
