### ISSUE TITLE
Bibliography should not be folded as part of the last section

### ISSUE THREAD

**Issue by ehahn** [lervag/vimtex#319]
In a document like the following:

    \documentclass{article}
    \usepackage{biblatex}
    \begin{document}
    \section{section}
    \printbibliography
    \end{document}

The bibliography (`\printbibliography`) is included in the section fold. I think this is wrong since in general, the bibliography is not part of any section.

**Comment by lervag** [comment]
Hi! Actually, I don't think it is this simple. I think it depends on the type of project and on opinions. I therefore suggest that you instead use the `% Fakesection` syntax for adding custom folds. This is described in `:h vimtex-folding`.

**Comment by ehahn** [comment]
On Mon, Jan 11, 2016 at 08:27:53AM -0800, Karl Yngve Lervåg wrote:
> Hi! Actually, I don't think it is this simple. I think it depends on
> the type of project and on opinions.

By default, `\printbibliography` prints a section (or chapter) heading
before the bibliography. Therefore it absolutely implies the beginning
of a new section. Why should Vimtex not treat it as such? The current
behaviour is definitely not correct.

Of course there are projects in which `\printbibliography` does not
start a new section. This could be handled with a configuration
variable. You could also check the arguments of the command 
(see the Bibtex manual[1], p.80), though that may be overkill.

> I therefore suggest that you instead use the `% Fakesection` syntax
> for adding custom folds. This is described in `:h vimtex-folding`. 

I did that but it's a hack. `\printbibliography` aleady implies a new
section -- I don't want to repeat myself. 

[1] http://www.ctan.org/tex-archive/macros/latex/contrib/biblatex/doc/biblatex.pdf

**Comment by lervag** [comment]
Hi again. I insist that it is more complicated than this. For instance, there can be multiple bibliographies, e.g. at the end of book chapters.

Note that I do agree that the bibliography is a separate section, and in principle, it could or should be folded automatically. The problem is to decide the fold level.

I propose the following update: Let `\printbibliography` start a new fold with fold text "Bibliography". The fold level should be the same as "highest" sectioning level. E.g., for books with chapters, the fold level should be the same as the chapter level, whereas for articles, it should be same as the section
level.

How does this sound?

**Comment by nasenatmer** [comment]
What a forceful way of making a point.

As I usually change the spacing in my bibliography and prepend it by a \clearpage, I was using the `Fakesection` solution in order to group these lines together and found this a nice customiable way of dealing with the matter.

This new solution means that those preceding commands will be folded underneath the section before **and** the `\printbibliography` and everything that comes after it (though it does not necessarily have anything to do with the bibliography) are folded under "Bibliography".

I'm not sure this gains anything. You can achieve exactly the same by a simple `% Fakesection Bibliography` while maintaining the code a lot more simple and leaving it in the hands of the user. At the cost of introducing another option (similar to `g:vimtex_fold_preamble`) this could be made configurable though.

**Comment by lervag** [comment]
Thanks, @nasenatmer. I agree with all of what you say. I reverted my last commit, as I think the `% Fakesection` "hack" is more suitable in this case, and it keep things more simple, clean, and more in the hands of the user.

I think it might make more sense to add this as an option, by default disabled.

**Comment by nasenatmer** [comment]
"I think it might make more sense to add this as an option, by default disabled."

Possibly as additional value in the arrays of either `g:vimtex_fold_parts` or `g:vimtex_fold_sections`. Actually, `g:vimtex_fold_preamble` could also be abandoned and moved into one of the two arrays, though I see the logical difficulty of categorising *preamble* as either *part* or *section* (same applies for bibliography, though)

**Comment by lervag** [comment]
I agree that the options seem somewhat out of place, but I don't really see a better way of handling things. For instance, the _preamble_ is not folded in the same way as sections or parts, because it is only folded until `\begin{document}`. Further, the order of the regexps in the fold level function is important, e.g. for speed.

The option for the bibliography is similar: It can't be added to the other options, because it must be handled differently.

I've considered to create a more flexible system, but I realized relatively quickly that it just becomes a lot of work for little gain. IMHO, folding is working pretty good as it is.

**Comment by nasenatmer** [comment]
I agree about the logical differences between preamble, parts and sections. If technical difficulties are complicating things even further, I agree it's best to leave it as it is, yes!

**Comment by lervag** [comment]
@ehahn Do you have any more input/considerations? I understand from your second post that you have strong opinions that `\printbibliography` should start a fold, and if you still after the above discussion think so, then I can add it as an optional feature.
