### ISSUE TITLE
Imap mappings for subscript and superscript with auto-curly braces in math mode

### ISSUE THREAD

**Issue by Hotschke** [lervag/vimtex#322]
I miss the imaps (latex-suite has them):
`__ -> _{$1}$0`
`^^ -> ^{$1}$0`

I have tried UltiSnips#Anon:

`inoremap <silent> __ __<C-R>=UltiSnips#Anon('_{$1}$0', '__')<cr>`
`inoremap <silent> ^^ ^^<C-R>=UltiSnips#Anon('^{$1}$0', '^^')<cr>`

It does only work at the beginning of the line. Does anyone has encountered this as well?  
`$e__ $` does not work.

However, my actual question is:
Are there are any plans to include them by default to vimtex?

The list in comment https://github.com/lervag/vimtex/issues/172#issuecomment-113955444 contains them.

**Comment by lervag** [comment]
The anonymous snippets were removed, see #295. It was deemed better to let the snippet plugins handle snippets, so the `imaps.vim` feature was reduced to only have "simple" abbreviation like mappings, e.g. `<imapleader>a -> \alpha`.

To define the maps, try

```vimL
inoremap <silent> __ __<C-R>=UltiSnips#Anon('_{$1}$0', '__', '', 'i')<cr>
inoremap <silent> ^^ ^^<C-R>=UltiSnips#Anon('^{$1}$0', '^^', '', 'i')<cr>
```

I plan to update the documentation in order to show how to create these kinds of maps with UltiSnips and neosnippet, but I won't add the functionality back.

**Comment by Hotschke** [comment]
Thanks for your help. I don't mind if a user has to add them by hand. Adding them to the docs is a good idea.
