### ISSUE TITLE
label completion with underscores

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#323]
label names are relatively unrestricted, apparently they can have even spaces. anyway in my case i have labels of the form `fig:la_lala_la`. i noticed that the completion offers stopped before the first `_` in a label.

**Comment by Rmano** [comment]
I had a similar problem with `-` that I use extensively in labels. I use in `.vim/ftplugin/tex.vim`: 

``
set iskeyword+=:
set iskeyword+=-
" grrrrrrrr look at $VIMRUNTIME/syntax/tex.vim and
" https://sourceforge.net/p/vim-latex/mailman/message/32406415/ 
let g:tex_isk='48-57,a-z,A-Z,192-255,:,-'
```
...I do not know if it will work with underscores, given the special meaning it has in math... I stopped using them because I hated the constant syntax-error coloring they got ;-)  

Probably it is not the best solution, but when I found it I just switched to `vim`...

**Comment by lervag** [comment]
This is not really a vimtex issue. I think @Rmano is right that this is about the `iskeyword` setting, which unfortunately is global. To set it for the `tex` filetype, you need to use `g:tex_isk`, since the internal vim plugin for LaTeX overwrites whatever you put in your `vimrc` file.

As @Rmano, I also tend to use dashes instead of underscores, partly for the same reason, but also because I find it syntactically prettier (this might be due to some experience with Lisp, I don't know...).

**Comment by lervag** [comment]
By the way, @nilsbecker: Considering you write "... offers stopped ...", it seems to imply that you use an automatic completion plugin, e.g. neocomplete or YouCompleteMe. If that is the case, then you might consider to ask the same question for that plugin as well, since it might be possible to do something about it on that end.

**Comment by nilsbecker** [comment]
ok, thanks for the explanation. i have this line in vimrc: 
`au BufRead,BufNewFile *.tex set iskeyword+=:`, i think i copied it from somewhere.

i now changed that to 
```
	au FileType tex setlocal iskeyword+=:
	au FileType tex setlocal iskeyword+=_
	au FileType tex setlocal iskeyword+=-
```
which seems to work as well.

**Comment by lervag** [comment]
Yes, I think it should work. Note (important) that `iskeyword` is a global option, so even with `setlocal` it will be set for every other file you have opened in the same vim session! I propose you change to `set` instead of `setlocal`.

**Comment by nilsbecker** [comment]
ok, good to know. that it's a global option seems a bit silly though, different file types can have different keyword rules, no?

**Comment by lervag** [comment]
Sorry, I'm stupid. I mixed it with another option. `iskeyword` is local to buffer. Blah...
