### ISSUE TITLE
Spelling correction and \" & friends

### ISSUE THREAD

**Issue by camilstaps** [lervag/vimtex#333]
It would be really cool if vimtex would take care that `\"` and friends are interpreted before spelling correction is done.

For example, in Dutch (`set spelllang=nl`), `Israël` is OK while `Isra\"el` is marked as unknown.

This is a feature request, not a bug report.

**Comment by lervag** [comment]
Interesting feature request. I don't think it is possible, though. At least not with the internal spell checker. Perhaps it is possible with an external spell checker? I tried to google it, but I could not find anything.

I think the feature could be implemented with some scripting and external spelling tools, and one could put misspelled entries in the quickfix list. However, I think it actually requires quite a lot of work, and I am not prepared to do this for vimtex, in particular because the internal spell checker works well in most cases, and because one could use utf-8 directly.

**Comment by camilstaps** [comment]
Fair enough. I don't have enough experience with vimscript to judge how much work this would be, but I can imagine, yes. Thanks for your consideration though.

**Comment by lervag** [comment]
The problem is that there is no vimscript available for doing this particular thing directly. Thus I think the only way is to first parse the tex file to convert all of those `\"LETTER` combinations to the corresponding unicode letter, and then to spell check the parsed file. The spell check result could then be loaded into vim either into the quickfix list (in which case we would want to know the line number for each spell error), or into a separate buffer that just lists the errors.

I've spent some more time to read about the internal spell checking, and I don't see any way to implement this feature. Sorry.
