### ISSUE TITLE
Can't stop vimtex from compiling automatically after changing a file

### ISSUE THREAD

**Issue by crscardellino** [lervag/vimtex#341]
Hello, I am having a problem, I set the variable `g:vimtex_latexmk_continuous` to 0, and even after it, every time I change the tex file and save it, latexmk recompiles the pdf. I don't want that, I want to compile it on my own using a command. Is this possible? Am I doing something wrong? (Maybe I didn't understood the function of the `g:vimtex_latexmk_continuous` variable)

Thanks!

**Comment by lervag** [comment]
It should work. What is the output of the command `:VimtexInfo` after you have started the compilation? In particular, I am interested in the `cmd` string for `latexmk`.

**Comment by crscardellino** [comment]
The `cmd` is the following:

`cmd_latexmk_compile : 'cd ''/path/to/dir'' && max_print_line=2000 latexmk -verbose -pdf  -e ''$pdflatex =~ s/ / -file-line-er
ror /'' -e ''$success_cmd = "\"vim\" --servername  --remote-expr \"vimtex\#latexmk\#callback(1)\""'' -e ''$failure_cmd = "\"vim\" --servername  --remote-expr \"vimtex\#latexmk\#call
back(0)\""'' -e ''$pdf_previewer = "open "'' ''file.tex'''`

**Comment by lervag** [comment]
This command should not start continuous mode for `latexmk`. I think you have a `.latexmkrc` file that somehow specifies that the continuous mode should be used.

**Comment by lervag** [comment]
Feel free to reopen if you can provide a minimal working example. That is, provide a minimal vimrc file together with a minimal tex file, as well as the steps to reproduce the problem.

**Comment by kennethsyddall** [comment]
Sorry, I'm a noob in vim and I don't know what I did, but I had the same problem and I used the next command to solv it

``if !exists('g:vimtex_compiler_latexmk')``
``let g:vimtex_compiler_latexmk = {}``
``endif``
``let g:vimtex_compiler_latexmk.continuous = 0``

But I don't know why, after adding those lines, my pdf viewer was not running after compiling, so I added this:

``let g:vimtex_view_method = 'mupdf'``

If someone could explain why it worked and why my pdf viewer was not running after compiling, I would be very happy.

**Comment by lervag** [comment]
> Sorry, I'm a noob in vim and I don't know what I did, but I had the same problem and I used the next command to solv it

Note: This issue is 4 years old. There have been a _lot_ of changes, including option names that have changed. `g:vimtex_latexmk_continuous` does not exist anymore, and as you've already surmised, you should instead use `g:vimtex_compiler_latexmk` with the `continuous` keyword. I would write it like this (no need to check if it exists, except if you often reload your vimrc file):

```vim
let g:vimtex_compiler_latexmk = {'continuous': 0}
```

> But I don't know why, after adding those lines, my pdf viewer was not running after compiling, so I added this:
>
> `let g:vimtex_view_method = 'mupdf'`
>
> If someone could explain why it worked and why my pdf viewer was not running after compiling, I would be very happy.

With continuous mode, `latexmk` will start the viewer automatically. Without it, vimtex will try to start the viewer automatically only if it has a chance of tracking the viewer. This is possible with the `mupdf` viewer, `zathura`, and also `Skim` on MacOS, but not with the default general viewer. This is why things work when you set the view method to mupdf.

**Comment by kennethsyddall** [comment]
Thanks!! I'm trying to learn and this things help me so much. Sorry for the delay but I saw the mail now.

Thanks a lot

Kenneth
________________________________
De: Karl Yngve Lervåg <notifications@github.com>
Enviado: martes, 12 de mayo de 2020 13:11
Para: lervag/vimtex <vimtex@noreply.github.com>
Cc: kennethsyddall <kensyd_98@hotmail.com>; Comment <comment@noreply.github.com>
Asunto: Re: [lervag/vimtex] Can't stop vimtex from compiling automatically after changing a file (#341)


Sorry, I'm a noob in vim and I don't know what I did, but I had the same problem and I used the next command to solv it

Note: This issue is 4 years old. There have been a lot of changes, including option names that have changed. g:vimtex_latexmk_continuous does not exist anymore, and as you've already surmised, you should instead use g:vimtex_compiler_latexmk with the continuous keyword. I would write it like this (no need to check if it exists, except if you often reload your vimrc file):

let g:vimtex_compiler_latexmk = {'continuous': 0}

But I don't know why, after adding those lines, my pdf viewer was not running after compiling, so I added this:

let g:vimtex_view_method = 'mupdf'

If someone could explain why it worked and why my pdf viewer was not running after compiling, I would be very happy.

With continuous mode, latexmk will start the viewer automatically. Without it, vimtex will try to start the viewer automatically only if it has a chance of tracking the viewer. This is possible with the mupdf viewer, zathura, and also Skim on MacOS, but not with the default general viewer. This is why things work when you set the view method to mupdf.
