### ISSUE TITLE
Should \eqref omnicomplete also show labels that aren't for equations?

### ISSUE THREAD

**Issue by atorg** [lervag/vimtex#343]
When I use omnicomplete after `\eqref{` I get a list of all `\label`s that have been declared in the file.

Similarly, after `\ref` the list also includes `\label`s that do correspond to equations.

Is this the correct behavior?

Is it possible to make it so that the `\eqref` list only has labels that correspond to an equation and the `\ref` list only has `label`s that do not correspond to an equation?

**Comment by lervag** [comment]
First: Yes, this is the current behaviour.

It is possible to make `\eqref` only complete equation labels, and I find this to be an interesting request. I don't want to make the corresponding change for `\ref`, because `\ref` is more general (it really can be used for equations as well).

**Comment by atorg** [comment]
Good point. There are situations in which one might want to refer to an equation with a `ref`.

**Comment by lervag** [comment]
Ok, I've looked at this now. It is not possible to determine what a label is for in a general way. If people consistently use prefixes for their labels, then it is possible, e.g. if you write `\label{eq:...}`, then I can use the first part `eq:` to filter with.

I think the feature then becomes to simple to bother with, at least compared to the added complexity: I would need to add an option that is disabled by default (so as not to break things for other people). You can achieve almost the exact same thing through writing `\eqref{eq:` before completing, since the `eq:` part will now be used to filter the completion directly.
