### ISSUE TITLE
what is the point of s:general.latexmk_append_argument()

### ISSUE THREAD

**Issue by nhooyr** [lervag/vimtex#345]
I don't quite understand why the pdf_previewer option is appended to the latexmk arguments. If you use the vimtex escapes (`@pdf`) it doesn't work with latexmk, if you use latexmk escapes (`%S`) it doesn't work with vimtex.

Why bother sending the argument at all, just let users configure it in `~/.latexmkrc`. The argument this function sends overrides that.

**Comment by lervag** [comment]
Because it makes it possible to configure a viewer from vim/vimtex. Did you notice the `g:vimtex_view_general_options_latexmk` option? It should be possible to use `%s` here.

Note: I agree it should be possible to configure things in `.latexmkrc`. Note, though, that one can not get the same flexibility if one does. Take for instance the `zathura` viewer, where the function in question is used to add arguments that allow backward synctex search to the correct vimserver.

**Comment by nhooyr** [comment]
@lervag zathura has its own function, separate from the general function.

**Comment by nhooyr** [comment]
Ah but I noticed the option now. Thanks!

**Comment by lervag** [comment]
No problem :)

**Comment by nhooyr** [comment]
@lervag but why are both sent as arguments? Shouldn't only `g:vimtex_view_general_options_latexmk` be sent?

**Comment by lervag** [comment]
The point is, as said, to let people configure their entire experience from vim. To be more specific, it is done this way to keep the same viewer from latexmk and from vimtex. That is, if I put `let g:vimtex_view_general_viewer = 'evince'` in my vimrc, then `evince` will be used both when the pdf is opened with latexmk and when I open with the view command in vimtex. This keeps things more simple for the user, since he/she won't need to configure the latexmkrc file.

**Comment by nhooyr** [comment]
holy shit I'm retarded, i misread it, sorry.

**Comment by lervag** [comment]
No problem! :)
