### ISSUE TITLE
ie does not work in \[ ... \] 

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#351]
Somehow `<plug>(vimtex-ae)` does no longer recognize equation environments of the form
```tex
\[
  ...
\]
```
That is, `ie` in visual mode with the cursor in the middle line does not select `...`.

**Comment by lervag** [comment]
This is true. Now `i$` and `a$` recognizes these environments instead. It seemed more appropriate. Perhaps I'm wrong? However, before I make another change, I think we should discuss what should be the correct behaviour.

**Comment by Konfekt** [comment]
Ok, then  because 
```\[ ... \]``` is synomimous to the environment ```\begin{equation}...\end{equation}``` at least `ie` should also work (and for this has a more logic to it than `i$`).

**Comment by lervag** [comment]
No, `\[ ... \]` is not synonymous to the equation environment. See [here](https://en.wikibooks.org/wiki/LaTeX/Mathematics#Mathematics_environments): `\[ ... \]` is synonymous to the displaymath environment. In any case, it could be interesting to have a discussion about this, because I am not really sure what is the expected behaviour for `ie` and `ae`. Same for `i$` and `a$`.

**Comment by lervag** [comment]
@nilsbecker You write math, perhaps you have an opinion?

**Comment by Konfekt** [comment]
Ok, `\[ \]` is synomymous to the `equation*` and `displaymath` environment. I forgot the `*`.

**Comment by Konfekt** [comment]
A last thought regarding consistency: Should then not all math enviroments, like `align`, be recognized by `i$`?

**Comment by lervag** [comment]
Good point. How about this:

1. `ie` and `ae` matches all environments, including `\( ... \)` and `\[ ... \]`
2. `i$` and `a$` matched `$ ... $` and `$$ ... $$`

**Comment by lervag** [comment]
Alternatively: `ie` and `ae` could match all environments, including `$ ... $` and all similar variants, whereas `i$` and `a$` only matches the `$` and `$$` variants.

**Comment by lervag** [comment]
Personally I think my last suggestion might be the best one.

**Comment by nilsbecker** [comment]
my opinion:

`ie` should include anything with `\begin` and `\end`.  in addition, it could also include the math.

`i$` should treat `\(` the same way as `$` and `\[` the same way as `$$` since these are just different ways to write the same thing. 

so i would prospose: `ie` for everything, `i$` for `$,$$,\(,\[`

but i'm not sure `i$` is needed at all? does functionality suffer if only `ie` exists?

**Comment by lervag** [comment]
Actually, it does, partly: If you write `\[ \begin{split} ... \end{split} \]`, then `i$` could match the `\[ ... \]`, while `ie` would match the split environment.

But I think you are right: `ie` and `ae` should match any/all environments, whereas `i$` and `a$` should match only the math shorthands. I'll make the change and push when I get the time.

**Comment by Konfekt** [comment]
Ok, but `\[` is the same as `\begin{equation*}` but not `$$` (and therefore the latter deprecated).

**Comment by lervag** [comment]
Hmm. Yes, you are right. `$$` should be avoided according to e.g. the wiki LaTeX book. Still, I think it should be supported, as there is no reason not to..?

**Comment by Konfekt** [comment]
Actually I am not fine: If * = cursor and `\begin{...} $.*.$ \end{...}` then `ae` should select everything and not only `$..$`. So rather than this change, better keep things as they are. 

It is only because `\[` is equivalent to `\begin{equation* / displaymath}` that `ie` made sense to me. But distinguishing by `ae` = `\begin{..}`  and `i$` = all  other delimiters is also plausible.

**Comment by Konfekt** [comment]
@lervag Yes, it should be supported and usually works fine (but `\[` always).

**Comment by Konfekt** [comment]
By the way, the above example also answers nilsbecker's question when i$ is useful.

**Comment by Konfekt** [comment]
So finally, sorry for the noise:

The current implementation is best, as for example in
```tex
\begin{...}
\[ .*. \]
\end{...}
```
one can select `\[ ... \]` by `i$`. But if `ie` would select `\[...\]`, then one cannot select `\begin{..} .... \end{...}` by `ie`.

Because `\[ $...$ \]` or `$$ $...$ $$` are impossible, `i$` for `\[ \]` or `$$ ... $$` does not have this interference with `$ ..$` as `ie` does.

**Comment by nilsbecker** [comment]
what about `cse` ? now this works inside `$...*..$` . i find that quite useful, for instance to promote inline math to a proper numbered equation (and back!) for logical consistency, this would require that the `e` text object always includes also a `$` environment. 

personally, i don't think selecting only the `$...$` part in \begin{...} $.*.$ \end{...} is so bad; one can just move the cursor outside the math and then do `vie`. 

alternatively, one defines `e` to not include `$` or any other math shorthand. then `cse` should not recognize `$`. one would need `cs$` in addition which would allow to change it to either math or another environment. 

as another alternative, one could possibly define a command for 'extend environment selection to the next enclosing environment'. this would then be invoked after `$..$` has been selected. not sure how feasible this is. i tried just now with `vae` inside of some `\begin \end` environment. then, in visual mode, i can modify the selection by `ie` or `ae` again. potentially, one could modify that such that `ae` in visual mode extends the selection when already a full environment is selected. however, this is probably a bad idea since it would deviate from standard vim behavior.

**Comment by nilsbecker** [comment]
other than the objection above, i also would find `e` for `begin/end` and `$` for 'abbreviations' ok since it's easy to memorize.

**Comment by Konfekt** [comment]
Ok, then I guess we agree on keeping everything as is. (As `cse` is not a visual or operator mode mapping and a different matter if there should be a `csd` for math delimiters and which for the time being can also be improvised by vim-surround.)

**Comment by lervag** [comment]
I'm sorry for not replying. It seems you guys agree that the current behaviour is good for the text objects. It remains to decide what to do with the `cs...` and `ds...` commands. Should these be updated/changed? Should I add `cs$` and `ds$` so that these correspond to the text objects?

**Comment by nilsbecker** [comment]
i think it would be nice to be consistent, so that `e` and `$` stand always for the same text object in all commands that use them. so if nothing is changed in the way the selections work now, i would argue that it's best to change `cs` and `ds` accordingly.

the one thing that may be a bit unsatisfactory is that `cs$` would allow one to change to a proper environment, not only to an abbreviation, thereby exiting the `$` class of text objects. similarly for `cse`. but i guess that's ok.

**Comment by Konfekt** [comment]
I agree with @nilsbecker, adding cs$ and ds$ is more consistent.

**Comment by lervag** [comment]
Thanks, @nilsbecker. I'll look at this sometime later, but I think I could allow to change from the shorthand environments and back. Actually, I think the code that performs the change can be the same code as is used now, only the outer shell must be different. It should not be too hard.

**Comment by lervag** [comment]
Bah, as I said, it should not be too hard. So I just did it already. Please test, I think it should work as expected.

**Comment by Konfekt** [comment]
Yep, works!

**Comment by lervag** [comment]
Great :)
