### ISSUE TITLE
Problem with the default of vimtex_imaps_list for capital letters

### ISSUE THREAD

**Issue by ernestorenanche** [lervag/vimtex#366]
In insert mode, many of the key sequence <imaps_leader> + a capital letter will produce an undefined control sequence. For instance, \Alpha does not exist in latex (since it is simply A) nor does \Nabla (but \nabla exists). See [reference about greek letters in latex](http://jblevins.org/log/greek).
This default should be either deleted either replaced by something useful. For instance A maps to \forall, E maps to \exists.
Please let me know, if you think those tweaks are worth opening a pull request.

**Comment by lervag** [comment]
I agree that the undefined control sequences should be removed. I am more hesitant as to whether one should add others, simply because it is easy to add custom maps, and I think the default maps should be intuitive.

I am not quite sure which of the mappings that do not really work. I will remove `\Alpha` and `\Epsilon` immediately, let me know if there are more bad mappings.

**Comment by ernestorenanche** [comment]
`\Beta`, `\Eta`,` \Nabla`, `\Rho` and `\Zeta` does not exist either. I think A for `\forall` and E for `\exists` is pretty intuitive due to the similarity (`\forall` is an upside donw A and `\exists` is a reflected E) but you are right those defaults are easily customizable.

**Comment by lervag** [comment]
Updated. I've added `\forall` and `\exists`.
