### ISSUE TITLE
How to disable hiding tag with replacing?

### ISSUE THREAD

**Issue by skyksandr** [lervag/vimtex#368]
If I wrote `\textbfSomeword` then `\textbf` become hidden and `Someword` become bold. Same for `\(` `\)`
It always confuse me.
I read docs twice and didn't found anything about this behavior and how to disable it.

Is it possible to disable this functionality?

**Comment by Rmano** [comment]
I think that this is conceal function. I hate it too, I have 

 `set  conceallevel=0 `

in my `.vimrc`. You can see more with `help conceal`.

**Comment by lervag** [comment]
This is not vimtex behaviour, instead, it is the internal LaTeX syntax plugin behaviour. You can turn it off with `let g:tex_conceal = ''`. See `:help g:tex_conceal` for more info.

**Comment by nhejazi** [comment]
Relatively new user of `vimtex`, so I'm late to this, but I've been having the proposed solution work. In particular, I have this in my `vimrc` (https://github.com/nhejazi/vim_lyfe/blob/master/vimrc#L127), but the concealing behavior still kicks in when editing `.tex` files. Uninstalling `vimtex` altogether disables the concealing behavior, but it's a great plugin otherwise. Would you mind letting me know what I'm missing in implementing this solution? Thanks for your help and for the great plugin!

**Comment by lervag** [comment]
Well, you should read the docs. This issue is 4 years old and things change with time. :)

In particular, see `:help vimtex-syntax` and `:help vimtex_syntax_conceal_default`. Essentially, to disable conceals with Vimtex, set the option `let g:vimtex_syntax_conceal_default = 0`. But please, DO read the docs, at least the introduction!
