### ISSUE TITLE
quickfix error window prevents exit

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#393]
after compilation with latexmk, a quickfix window with the warnings and errors appears. now quitting the main buffer with `:q` does not exit vim since the quickfix window is still there. could some option be set so that the window auto-closes either when the corresponding file buffer closes or when it's the last thing preventing exit?

**Comment by lervag** [comment]
I think this should rather be solved manually, e.g. with [an autocommand](http://vim.wikia.com/wiki/Automatically_quit_Vim_if_quickfix_window_is_the_last):

```vim
au BufEnter * call QuickFixQuit()
function! QuickFixQuit()
  if &buftype=="quickfix" && winnr('$') < 2
    quit!
  endif
endfunction
```

The reason is that this would interfere with other filetypes. There could be some ways to make this only work for LaTeX, but I think the above solution is very simple. And I like when things are simple. :)

**Comment by nilsbecker** [comment]
ok, i'll try it. i brought it up since i remembered this automatic behavior from other plugins. e.g. fugitive: if you have a :Gstatus window open but quite the main file, it quits immediately.

**Comment by nilsbecker** [comment]
there is also this:

https://yous.be/2014/11/30/automatically-quit-vim-if-actual-files-are-closed/

which i might try. 

it seems to me that it would be a good default feature for vim if it had a notion of 'this buffer is a weak buffer: it will be garbage collected at any time if no references point to it anymore'. anyway.

**Comment by lervag** [comment]
The big difference with fugitive is that the status buffer is pure fugitive. The quickfix window is "global" and used for a lot of things. As an example: In big projects (including LaTeX) I often search for stuff for instance with ack or ag so that the results are put into the quickfix window. It is not clear that I want this quickfix to close if I close the main file.

In any case, my point is that to implement a good solution I need to take some considerations, and the complexity is not trivial. Thus I think simple solutions such as the one I showed and the improved one you've found is better, because it solves the same problem for many other cases as well (if you are interested in the solution, that is).

**Comment by nilsbecker** [comment]
ok, i think i got it. the complication is that the qf window can't be considered private to vimtex. fair enough!

**Comment by lervag** [comment]
Yes, exactly. :)

**Comment by nilsbecker** [comment]
fwiw, the link i linked gets confused when switching between the main file and the quickfix buffer and quits unexpectedly. the solution provided by @lervag seems to work fine.
