### ISSUE TITLE
Question: how to conduct pdftex bibtex pdftex pdftex?

### ISSUE THREAD

**Issue by ranranking** [lervag/vimtex#394]
I am not sure how to do this by reading the doc file. For now, I could only do `<leader>ll` then go to the terminal type `bibtex <filename>` and then go back, use `<leader>ll` two more times to make sure I have citations. How to do this with vimtex? Do I have to set up my `.latexmkrc` file?

**Comment by ranranking** [comment]
Sorry, I think it was because of my tex file's problems

**Comment by lervag** [comment]
No, I think you completely misunderstand what `latexmk` is and what it does. Basically, with `latexmk`, you never do the compile cycle yourself, because it does it for you. This you don't have to do any `bibtex ...` or `pdftex` commands at all.

By default, vimtex runs `latexmk` as a running service that will compile the document everytime it is saved to file. Personally I find this very convenient.

**Comment by ranranking** [comment]
Yes, thank you for the reply! I was wrong about latexmk. I didn't get the expected output was because I got errors in my .tex an .bib files. Although in that case, I can still get the output by getting out, use bibtex, and then compile again, which was definitely not the correct way.
