### ISSUE TITLE
Syntax highlighting of subscripts

### ISSUE THREAD

**Issue by avfonarev** [lervag/vimtex#395]
I have encountered some inconsistencies in syntax highlighting.
Precisely, in the following example the visible issues are.

1. `e_1` and `e_n` look different.
2. What is less easy to explain, `\omega_i` and `\omega_n` look different.
3. Things within `$$` within `\text` look different from the same text a line above (but I suspect that this is intended and do not insist on changing behaviour).

```tex
\documentclass{minimal}
\begin{document}

\[
    i=1,\ldots,n-1
    \omega_i = \text{for $i=1,\ldots,n-1$}
    \omega_n = (e_1+e_n)
\]

\end{document}
```

### Minimal vimrc file

Vanilla vimtex.
![screen shot 2016-03-17 at 19 20 10](https://cloud.githubusercontent.com/assets/177602/13852985/2771967e-ec7e-11e5-8250-19e6b56bbd2e.png)

**Comment by lervag** [comment]
First, as explained also in #396, these are all issues with the internal Vim plugin. As such, I propose that you consider to send Charles Campbell an email.

First, though, I must mention that I do not see the same issue. I am on Vim version 7.4.1529 (see `:version`), and my tex syntax file is version 92 from february 2016 (see `:e $VIMRUNTIME/syntax/tex.vim`).

![test](https://cloud.githubusercontent.com/assets/998898/13900905/be16736c-ee11-11e5-86b2-1e6ae274ca5a.png)

Regarding the third remark, I think this is intentional.

**Comment by avfonarev** [comment]
Thank you for looking into it. I'll do some further research on my own.
