### ISSUE TITLE
Parenthesis, indentation and highlighting

### ISSUE THREAD

**Issue by avfonarev** [lervag/vimtex#396]
A couple of issues I have found.

```tex
\documentclass{minimal}
\begin{document}

(

\end{document}
```

First, `\end{document}` is highlighted differently.

Now,  go to the opening parenthesis, hit `o` and look at the indentation. Close the parenthesis and see indentation fixed. That is extremely inconvenient as sometimes text in parenthesis may spread over multiple lines. Imagine something like

```tex
\begin{document}
That is a sentence I have just written (in order
    to illustrate a bug in vimtex, which is a very
nice vim plugin).
\end{document}
```

The same issues see to hold for square brackets.

### Minimal vimrc file

Vanilla vimtex.
![screen shot 2016-03-17 at 19 42 15](https://cloud.githubusercontent.com/assets/177602/13853588/cb30c936-ec80-11e5-9b4f-bdd29134ea59.png)

**Comment by lervag** [comment]
You mention two issues:

1. Highlighting: This is not due to vimtex, but to the internal tex plugin that ships with Vim. This can easily be verified with a minimal vimrc where vimtex is not loaded. I propose that you contact Dr. Chip (Charles E. Campbell), see [here](http://www.drchip.org/astronaut/vim/index.html#SYNTAX_TEX).

2. The indentation is currently intentional. In normal text, I add one indent on each of the delimiters `{`, `[`, and `(`. I like that myself, but if you prefer, I might change it or make it optional.

**Comment by avfonarev** [comment]
Thank you for commenting. As for indentation, I do not have a strong opinion (the only concern is about multiline text in parens). Making in optional will definitely solve my problem.

**Comment by lervag** [comment]
Ok, I've decided to remove the parentheses from the list of general tex delimiters. This should solve the indentation problem. I've been thinking, and I've decided that it does not make sense to indent on normal parens in text mode.
