### ISSUE TITLE
Complicated directory names

### ISSUE THREAD

**Issue by tc-0** [lervag/vimtex#397]
Currently there is a directory ``test/issue/237/[code college-1] title/`` which breaks the plugin manager [``dein``](https://github.com/Shougo/dein.vim) under vim >= 7.4.1120 because ``dein`` calls vim's new ``delete(..., 'rf')`` function which cannot properly handle directory names with brackets. This is not really a bug of ``vimtex`` but rather one of ``vim``. Nevertheless, it seems best practice to avoid non-ASCII directory names.

**Comment by lervag** [comment]
The entire point of the test is to make sure that vimtex properly handles complicated path names, cf. #237. Thus it is really an issue with dein, and so I propose that you open an issue there instead, or perhaps an issue with neovim/Vim for the delete function.

If it is really not possible to fix this where it should be fixed, then I could consider to change the test (e.g. just add a simple shell script to prepare the test, instead of including the entire path), but I would much rather see this fixed on the dein or Vim side of things.

**Comment by tc-0** [comment]
I see. That sounds very reasonable. Thanks for your answer and for vimtex, by the way.

**Comment by lervag** [comment]
No problem! Let me know if you can't get this solved in any other ways.

**Comment by lervag** [comment]
No problem! Let me know if you can't get this solved in any other ways.
