### ISSUE TITLE
Problem with VimtexToggleToc

### ISSUE THREAD

**Issue by teto** [lervag/vimtex#400]
### Explain the issue

I would like to map <leader>lt to toggle the TOC buffer. What happens with the latest version (I updated today) is that whatever state neovim is, calling this mapping
`autocmd FileType tex nnoremap <leader>lt <plug>(vimtex-toc-toggle)`
opens the toc and focuses it. I would prefer : 
1/ the toc not to be focused on the opening:
2/ I would expect *toggle* to hide/close the TOC if already open

### Minimal working example
It's not related to the document so this one should be ok
```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

### Minimal vimrc file
Tried on neovim (on vim the mapping doesn't trigger :/).
```vim

let s:nvimdir = (exists("$XDG_CONFIG_HOME") ? $XDG_CONFIG_HOME : $HOME.'/.config').'/nvim'
let s:plugscript = s:nvimdir.'/autoload/plug.vim'

if empty(glob(s:plugscript))
  execute "!mkdir -p " s:nvimdir.'/autoload' s:nvimdir.'/plugged'
  execute "!curl -fLo" s:plugscript
		\ "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
		  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

let mapleader = " "

filetype plugin indent on
syntax enable

call plug#begin(s:nvimdir.'/plugged')
Plug 'lervag/vimtex', {'for': 'tex'}
call plug#end()

let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_index_split_pos = 'below'
let g:vimtex_latexmk_progname = 'nvr'

autocmd FileType tex nnoremap <leader>lt <plug>(vimtex-toc-toggle)
```

**Comment by lervag** [comment]
Hi! I took the liberty of simplifying your minimal vimrc file and remove comments as well as irrelevant settings. Actually, I would prefer if it was simplified even further and that you remove vim-plug as well. The reason is that it would make it easier to copy the vimrc file directly, since the only relevant path would be the path to vimtex.

Anyways, I will test this with nvim myself when I get the time. First, though: The mapping you create is NOT needed, since it is already created by vimtex. The only difference is that vimtex uses `maplocalleader`, which is `\` by default. Similar to `mapleader` this can be set in your vimrc. So, could you please try to remove your manual mapping of the toggle and instead rely on the automatic vimtex mapping? It should already map to `<localleader>lt`, and it works exactly as expected on my end.

**Comment by teto** [comment]
I found the culprit: I had this plugin enabled (though I don't use it) https://github.com/romainl/vim-qf that was hiding the qf from buffer lists, hence making the disabling fail. I realized that when trying to use Valloric/ListToggle and saw I had the same problem tyhan with vimtex.
I must have messed up sthg with my minimal.vim 'cos vimtex should have worked :s

**Comment by lervag** [comment]
No problem! I'm happy you found the problem. :)
