### ISSUE TITLE
Feature request: Add termpdf support.

### ISSUE THREAD

**Issue by ranranking** [lervag/vimtex#401]
Since iTerm 2.9, the terminal can view graphs. With the tool [termpdf](https://github.com/dsanson/termpdf), iTerm can view pdf too, which is really cool. I am wondering whether it is possible to let `vimtex` support `termpdf`?

**Comment by lervag** [comment]
Interesting. Could you please explain how you would use termpdf for LaTeX projects manually? I am not quite certain of how to integrate it with vimtex.

I would think that you could use it with the included general viewer with the correct settings.

**Comment by ranranking** [comment]
Yes, I was thinking similarly. Since the tool is just a bash script, maybe adding a  command to the plugin would not be too difficult, if I am correct. But only the command for the script would not be enough I think. Maybe when using iTerm with vim (I don't use GUI vim), by typing `<leader>lv`, it can open a new iTerm window with the command would be nice. When the tex file is updated, `<leader>lv` can refresh the iTerm window by closing the tool and reopen it?

**Comment by lervag** [comment]
One thing must be clear: I don't use OSX, and thus I don't use iTerm. This makes it impossible for me to experiment on this feature. So, in order to add any kind of support that is not already available, you must provide all of the necessary commands. That is why I asked you to explain how you would use termpdf for LaTeX projects manually.

Please see the documentation, e.g. `:h vimtex_viewer_skim`, for an example on how to setup a "general" viewer. If termpdf can not be set up through the same system, then at a minimum I will need the exact keys/commands needed to use termpdf as a viewer.

**Comment by ranranking** [comment]
OK, let look into this and if it was working, I may have a pull request. Thank you for the help!

**Comment by lervag** [comment]
Great, and no problem! I will be happy to consider a pull request. Note, though, that I try to keep things simple, and so if support for termpdf will require any hacks or unecessary complicated code, then I will not want to include it.
