### ISSUE TITLE
Update docs on required options for pdflatex

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#413]
See #408, #415.

**Comment by fuzzybear3965** [comment]
@lervag, what did you want to do with #415? You want to include in the vimtex.txt file (Troubleshooting?) information regarding the necessity for `-synctex=1` and `-interaction=nonstopmode`?

I'm unclear, also, on the need for `-interaction=nonstopmode`. When would I **not** want to use it? Why is it an option? (Maybe it's not because in the title of this page you say that these options may be "required options".)

**Comment by lervag** [comment]
Actually, I think I will add these options directly to latexmk. I think both options can be used safely, and that there is no need for any new vimtex options here. This will solve problems for a lot of people, I think, while I believe it will not introduce any problems. Thus, it seems we don't need to write anything about this in the docs.

**Comment by fuzzybear3965** [comment]
Right, okay. No more `pdflatex`. Let's mark this issue as closed as seen in #422 and #423.

**Comment by lervag** [comment]
Agreed.
