### ISSUE TITLE
[Feature] Recognize `%! TEX root = main.tex` in bibfile to enable vimtex-toc

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#433]
I like the feature `vimtex-toc` to jump to the bibfile (`,lt`). However, I miss the possibility to open the `vimtex-toc` from the bibtex file. Is it possible to recognize the corresponding tex file via `%! TEX root = main.tex` line or alternatively by the `latexmain` extension in same or above folder to show the table of contents? (BTW: comments in bibtex files do not have to have any leading symbol, cp e.g. http://tex.stackexchange.com/questions/93972/comment-out-sections-of-text-in-bib-file)

**Comment by lervag** [comment]
If you open a bib file through the table of contents, then the table of contents will be available from the bib file as well. I think this makes sense, because a bib file can be used for many projects, and as such, it should not belong to any one project. Thus, if you open the bib file through other means, then one can not really know where the bib file belongs. But if you open it through the table of contents, then the current update "remembers" the TOC and allows to reopen it.

**Comment by lervag** [comment]
Oh, and btw: the only support for bibfiles provided by vimtex is currently a custom indent function. Syntax highlighting for bib files come from Bernd Feige's syntax plugin that comes shipped with Vim, see `:e $VIMRUNTIME/syntax/bib.vim`. I propose that you contact Bernd Feige if you have comments about syntax highlighting issues.
