### ISSUE TITLE
Alignment of non-matching \left and \right

### ISSUE THREAD

**Issue by Eisfreak7** [lervag/vimtex#445]
### Explain the issue
The alignment of `left` and `right` is off, when `left` and `right` have different parameters.

### Minimal working example

The (hand-formatted)
```tex
\documentclass{minimal}
\usepackage{amsmath}
\begin{document}
\begin{center}
	$
	\left.
		\begin{pmatrix}
			0 & & * \\
			& \ddots \\
			0 & & 0 \\
		\end{pmatrix}
	\right\} n
	$
\end{center}
\end{document}
```
is auto-formatted to
```tex
\documentclass{minimal}
\usepackage{amsmath}
\begin{document}
\begin{center}
	$
	\left.
	\begin{pmatrix}
		0 & & * \\
		& \ddots \\
		0 & & 0 \\
	\end{pmatrix}
\right\} n
$
\end{center}
\end{document}
```

Similar errors occur for other non-matching pairs of `left` and `right`.

### Minimal vimrc file

The problem should be independent from the vimrc, the default minimal vimrc can reproduce it:
```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
```

**Comment by lervag** [comment]
Yes, you are right. I've been aware of this, but I have not decided if I will add support for it. However, since you ask, I will at least try to implement this.

Note, you might also notice that every other feature for the delimiters are broken for this particular case. That is, highlighting of matching delimiters won't work, toggling won't work, and jumping with `%` won't work. I will attempt to find a solution that solves things for all of these. It will be a nice challenge, but I am not sure that I will be able to solve it.

**Comment by Eisfreak7** [comment]
Thank you
Alternatively, a (dirty) solution would be to add some special comment like `% <noident> ... % </noident>` that disables autoident for a piece of code, if that is possible with vim.

**Comment by lervag** [comment]
I think this is resolved and implemented now. Please test.

**Comment by Eisfreak7** [comment]
It works for me, thanks!
