### ISSUE TITLE
Suggestion: auto \item

### ISSUE THREAD

**Issue by danielbmarques** [lervag/vimtex#455]
I do this for my `tex` files:
```
set formatoptions=tcroqln
set comments+=b:\\item
```

So when a line begins with `\item` and I do a `<CR>` another `\item` is automatically inserted right below it:

![item](https://cloud.githubusercontent.com/assets/15813674/15319665/5e2ec7dc-1c02-11e6-971a-d05c7408f90f.gif)

It would be nice if `vimtex` did this out of the box. I don't know if the way I did it is the best. It would be even better, for instance, if a second `<CR>` without adding any text would make the last `\item` disappear, instead of adding more and more until you manually delete one.

**Comment by lervag** [comment]
I think it is an interesting suggestion, but I find it is more convenient to add a simple mapping to add an item. I personally use the following:

```vim
call vimtex#imaps#add_map({
      \ 'lhs' : 'é',
      \ 'rhs' : '\item ',
      \ 'leader'  : '',
      \ 'wrapper' : 'vimtex#imaps#wrap_trivial'
      \})
```

This maps `<m-i>` (alt-i) to `\item ` in insert mode. This could of course be done with a simple mapping as well, i.e. the follow:

```vim
inoremap <m-i> \item<space>
```

The main reason I prefer this, is because I don't think that everyone wants `<cr>` to add a new `\item`, since it is very possible to write several paragraphs or hard wrapped lines as part of a single list item.

**Comment by danielbmarques** [comment]
Yes, I think the ideal solution would be something like what I mentioned, a second `<CR>` would remove the `\item` that the first `<CR>` inserted, but I don't know how to do that. As it is I think both ways are equally good; one requires a few extra key presses when adding a new item, another requires a few extra key presses when using hard wrapped lines.

**Comment by lervag** [comment]
To do that, I think you will need to add an insert mode mapping that parses the current line. If the line already contains an `\item`, then it must be removed. Else, you add a new line and prepend an `\item`. However, this should only occur within an itemize-like environment.

Compare the above with the simplicity of adding a simple mapping as I suggest. I also think it makes more sense to have more minute control of what happens. I prefer having to explicity ask for an item, instead of having to explicitly remove it.

Thus, I will not add a feature such as what you ask. I would propose that you either try to implement one yourself, or that you use the solution you've already suggested initially. If you do implement one, please post it here for future reference. You could also consider to try my other suggestion of using a mapping to add the item.

**Comment by danielbmarques** [comment]
Ok, got it!
In case someone else wants to do something like this:

```
set formatoptions=tcroqln
set comment+=b:\\item
inoremap <expr> <CR> getline('.') =~ '\item $' ? '<esc>bbdwdwa' : '<CR>'
```

**Comment by lervag** [comment]
Thanks. And no problem, I'm happy that you like the plugin :)

Btw, you can simplify the mapping:

```vim
inoremap <expr> <CR> getline('.') =~ '\item $' ? '<c-w><c-w>' : '<CR>'
```
See `:h i_CTRL-W`.

**Comment by danielbmarques** [comment]
Ah, even better! Thank you. :)

**Comment by lervag** [comment]
No problem :)

**Comment by kiryph** [comment]
I just want to add a pointer to a corresponding discussion on stackoverflow: http://stackoverflow.com/questions/2547739/auto-insert-text-at-a-newline-in-vim
