### ISSUE TITLE
Shell Escape Option

### ISSUE THREAD

**Issue by Davidnet** [lervag/vimtex#467]
Hi small question, how can I enable the shell escape option, so I can use packages like minted.

So I'm asking: How can I enable `pdflatex -shell -escape` for documents using vimtex.

Thanks.

**Comment by lervag** [comment]
You can do this in two ways:

1. Use a `.latexmkrc` file and put it in your `$HOME` or at the project level. Use e.g. the following file content:

    ```perl
    $pdflatex = 'pdflatex --shell-escape %O %S';
    ```

2. Use a custom setting for `g:vimtex_latexmk_options`, e.g.

    ```vim
    let g:vimtex_latexmk_options = '-pdf -shell-escape -verbose -file-line-error -synctex=1 -interaction=nonstopmode'
    ```

    See `:h g:vimtex_latexmk_options`.

**Comment by rohanghige** [comment]
Option vimtex_latexmk_options is deprecated. As per latest help document, it says to use 'vimtex_compiler_latexmk'. Place following code in your .vimrc:
```
let g:vimtex_compiler_latexmk = {
    \ 'options' : [
    \   '-pdf',
    \   '-shell-escape',
    \   '-verbose',
    \   '-file-line-error',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \ ],
    \}
```
See `:h vimtex_compiler_latexmk`

**Comment by hamdav** [comment]
@rohanghige From :help g:vimtex_compiler_latexmk
```
Note: Options like -pdf or -lualatex should NOT be added to this list.
          These are options used to specify the LaTeX processor/engine, see
          instead g:vimtex_compiler_latexmk_engines.
```

**Comment by lervag** [comment]
@hamdav This issue is more than 3 years old. VimTeX has changed quite a lot in that time. But, you are correct in this observation. The commit that changed to move the `-pdf` (and similar) options from this list was actually pushed just a day before @rohanghige's comment, see here:

144e60649a0214b09ee78d3aeff4eb569daea194

Still, considering the age of this thread; I'll lock from further discussion.
