### ISSUE TITLE
Error collumn while writing

### ISSUE THREAD

**Issue by chmol** [lervag/vimtex#475]
Hi,

I'm really new to vim and have the following question: how to hide the left sided column that appears after a write with errors ? 
  
Thanks

### Minimal working example
It's not the same syntax in french, so some error are not really relevant e.g: 
```tex
\documentclass{minimal}
\begin{document}

French stuff some quote : ``Stuffs [...] more french stuffs''..

\end{document}
```

![jun13-15 41 00](https://cloud.githubusercontent.com/assets/8171862/16009554/8374edb0-317d-11e6-9791-b0b1c741639e.png)

**Comment by lervag** [comment]
The left sided column does not have anything to do with vimtex. I suspect it may be due to syntastic or some other plugin.

I assume that your problem happens with your normal vimrc file. And since you are new to Vim, I understand that it might be quite difficult to understand everything. I'll try to help you.

How do you load plugins? Which plugins have you loaded? Can you reproduce the problem if you disable vimtex (comment out all vimtex parts from your vimrc file)?

**Comment by chmol** [comment]
Thanks for the kind response, I assumed it was your plugin as I didn't wrote in vim before it. It was indeed syntastic, 

Thanks !

**Comment by lervag** [comment]
No problem! :)
