### ISSUE TITLE
Unable to compile using cygwin on Windows 10: "bad options" passed to latexmk

### ISSUE THREAD

**Issue by jckegelman** [lervag/vimtex#483]
Hi there. I realize you don't use vimtex on Windows, but I am experiencing an issue I suspect is related to unix/windows strings. The closest thing I found dates all the way back to issue #40, which seems long since closed. I am using cygwin on Windows 10 (via [babun](https://github.com/babun/babun)).

I am getting this compile output (\<localleader\>lo):

```
Unquoted string "vim" may clash with future reserved word at (eval 12) line 2.
Latexmk: -servername bad option
Latexmk: -remote-expr bad option

Latexmk: Bad options specified
Use
   latexmk -help
to get usage information
```

with this info (\<localleader\>li):

```
b:vimtex : mwe
  pid : 0
  root : '/cygdrive/c/Users/Kegelman/Documents'
  aux : '/cygdrive/c/Users/Kegelman/Documents/mwe.aux'
  log : '/cygdrive/c/Users/Kegelman/Documents/mwe.log'
  out : '/cygdrive/c/Users/Kegelman/Documents/mwe.pdf'
  tex : '/cygdrive/c/Users/Kegelman/Documents/mwe.tex'
  tmp : '/tmp/vdy8CaC/1'
  cmd_latexmk_compile : 'cd ''/cygdrive/c/Users/Kegelman/Documents'' && max_print_line=2000 latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e ''$success_cmd = "''""''vim''""'' --servername  --remote-expr \"vimtex\#latexmk\#callback(1)\""'' -e ''$failure_cmd = "''""''vim''""'' --servername  --remote-expr \"vimtex\#latexmk\#callback(0)\""'' -e ''$pdf_previewer = "SumatraPDF -reuse-instance"'' ''mwe.tex'' >/tmp/vdy8CaC/1 2>&1'
  base : 'mwe.tex'
  viewer
    init : function('19')
    view : function('20')
    latexmk_append_argument : function('21')
```

I am using this MWE:

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

with this minimal .vimrc file:

```vim
set nocompatible

let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable

" vimtex options
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options = '-reuse-instance -forward-search @tex @line @pdf'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'
```

It seems like the latexmk options are not being passed correctly, causing the error. I'm also confused by the message about unquoted string "vim" because all of the instances of "vim" I could find in the info sure have a lot of quotes around them. I have the latest versions of latexmk and vimtex. I've tried various combinations of quotes in my .vimrc and played with shellslash and noshellslash to no avail. Any ideas? Thanks for the help.

**Comment by lervag** [comment]
Sorry for taking so long to respond.

It seems like the problems is the quoting. This is a hard problem, because the quotes need to be escaped correctly on various systems. As far as I understand, it should currently work well both on Windows, OSX and Linux. So, it is interesting to see that it does not work in Cygwin on Windows... :\

I force `noshellslash` temporarily, so this should not be an issue.

The relevant code is in `latexmk.vim` in line 444 (or close by). You could try to play with it. E.g. you could change

```vim
let l:cb = shellescape('""') . g:vimtex_latexmk_progname . shellescape('""')
      \ . ' --servername ' . v:servername
```

to

```vim
let l:cb = g:vimtex_latexmk_progname . ' --servername ' . v:servername
```

If that works, than it confirms our suspicion that the problem is due to the quoting.

Other things: You could try to copy the command echoed in the info to the command line, which might help in debugging. Also, I'm curious which version of Vim you are using. Does it have the clientserver (see `:h clientserver`)?

**Comment by lervag** [comment]
This is strange. I don't understand why things are different on Cygwin, but obviously they are. When searching, I see that Vim behaves somewhat special in Cygwin, see e.g.:

http://superuser.com/questions/345180/install-vim-in-cygwin
http://unix.stackexchange.com/questions/11707/are-cygwin-vim-commands-different-than-normal-vim
http://vim.wikia.com/wiki/Use_cygwin_shell
http://vim.wikia.com/wiki/Category:Cygwin

Perhaps some of the above links have some clues?

**Comment by jckegelman** [comment]
Strange indeed. Thanks for the links. Turns out the version of Vim I am running does not have the `+clientserver` option compiled in. I searched around for a way to install or recompile via Babun with `+clientserver` but came up empty. It seemed like I needed to install gvim but that turned into a horrendous headache to get to work under cygwin and xterm, so not worth it.

I also tried your suggestion and a few more options, including

```vim
set shellcmdflag=-c
set shellxquote=\"
```

but that didn't help. Now I'm not even sure if the fix I quoted above (adding `'\''` before and after `g:vimtex_latexmk_progname`) works because it does successfully compile but I don't think it is executing the success or failure commands. For now I've included the following in my `.vimrc` to get it to run without errors:

```vim
let g:vimtex_latexmk_callback = 0
```

I found that I split my work between Windows and Mac OS X so I can live without the auto-callbacks when I'm writing on Windows (it works on my Mac).

Thanks for your help and please let me know if you or any Windows users have any suggestions.

**Comment by lervag** [comment]
Ok, so without the `+clientserver` you can not use the call back features. I've added a check and a warning for this now, and the problem should no longer appear since the option is turned off it can not be applied.

In any case, I don't know how to help you get a working Vim on cygwin. Perhaps there are other ways to get Linux on windows today?
