### ISSUE TITLE
Own imap interferes with the vimtex ]] imap

### ISSUE THREAD

**Issue by matthewjohnrussell** [lervag/vimtex#486]
If I define my own imap to close the current environment (which I use just after typing `[[equation`, say) and jump back into the interior of the environment block, the vimtex imap for `]]` disappears from the list `:imap` and is not functional. This is my imap, if it is relevant:

`imap <S-CR> <ESC>o<plug>(vimtex-delim-close)<ESC>O`

The original functionality can be emulated by a new imap - something like the following does the trick:

`imap <buffer> ]] <plug>(vimtex-delim-close)`

**Comment by lervag** [comment]
Hmm. Interesting. I've added a guard that prevents vimtex from defining the default map if the map target is already used. In this case, you use `<plug>(vimtex-delim-close)` in a personal mapping, and so vimtex does not define the default mapping for `]]`.

The reason for this is to make it easy to redefine some mappings on a per-user basis. However, I never thought of cases like this, where you expect the default behaviour and simply add an extra mapping.

I am not entirely sure how to solve this. If I remove the guard, then it is more likely that user mappings may conflict with vimtex mappings. If I don't remove the guard, then you will have to add two mappings...

**Comment by matthewjohnrussell** [comment]
Thanks for the explanation as to why my map prevent the default map from being defined.

As you say, it's not clear how to solve this for the general case, since changing the behaviour may break other used-defined maps.

One solution, if it would not be too messy or complicated, is to add a vimtex option for whether or not to activate the map definition guards. Then, as long as the default value corresponds to the current behaviour, it is up to the user that changes the option (i.e. me!) to make sure their own maps do not interfere with anything.

Thanks

**Comment by matthewjohnrussell** [comment]
I should mention that, without a solution within vimtex itself, it's not a big deal for me to use my own version of the `]]` map!

**Comment by lervag** [comment]
The solution that you suggest could of course be added. However, I am very reluctant to add options. I think there are already too many, and I think very few would actually ever use this option.

I think I'll instead relax the guard. It seems safe, and I think I will rather tighten again if it ever becomes a problem.

**Comment by lervag** [comment]
The update should solve your problem, and after thinking about it some more, I now believe it should not lead to any problems.

**Comment by matthewjohnrussell** [comment]
The solution suits me (obviously :), and I suppose we'll see if it causes any other problems. Thanks again for your help

**Comment by lervag** [comment]
No problem! :)

**Comment by michamos** [comment]
Hi,

I find this change very annoying, as on the keyboard layout I use (bépo, Dvorak-like for French), both `t` and `c` correspond to directions, so I need to change a few of the default mappings. This change made it very difficult to do so (needing to resort to an `after` file with `unmap`s), so I would suggest reverting it, and documenting the behavior instead.

A workaround for @matthewjohnrussell would be  `imap <S-CR> <ESC>o]]<ESC>O` instead of invoking the `<plug>` mapping.

**Comment by lervag** [comment]
@michamos When I thought about this, I ended up thinking the new approach is better. The reason is that it does not really make sense to avoid mapping the default keys just because someone added a mapping that contains the particular `<plug>` variant. @matthewjohnrussell shows one particular example where the old behaviour was surprising. I think the new behaviour is less surprising. That is, if you want to buid upon vimtex mappings to define new mappings, this should not prevent the default mappings.

However, it would not be too much work to add a dictionary of default mappings. The different `<plug>` variants would be the keys. I.e., something like this:

```vim
let g:vimtex_mappings_default = {
  \ '<plug>(vimtex-info)' : '<localleader>li',
  \ ...
  \}
```

This would make it very easy to change default values.

**Comment by michamos** [comment]
> When I thought about this, I ended up thinking the new approach is better. The reason is that it does not really make sense to avoid mapping the default keys just because someone added a mapping that contains the particular <plug> variant.

I agree with this, the ideal solution would be for Vim to have a variant of `hasmapto` that only returns true if the rhs matches exactly. However, as there is no such function as far as I know, I don't think that avoiding `hasmapto` altogether is the correct solution because:

- It is used by many different plugins, including very popular ones like `surround` and `repeat` by Tim Pope.
- If a given functionality is already mapped, it does not make much sense to invoke the `<plug>` mapping directly, in the same way that one would map for example
~~~
nmap <leader>{ o{}<Esc>
~~~
instead of
~~~
nmap <leader>{ :call append('.', [ '{','}'])
~~~
even if morally, one could think of `o` as an interactive version of `append()`. Similarly, as I already mentioned, it would make more sense for @matthewjohnrussell to do
~~~
imap <S-CR> <ESC>o]]<ESC>O
~~~
instead of
~~~
imap <S-CR> <ESC>o<plug>(vimtex-delim-close)<ESC>O
~~~
as the mapping of  `<plug>(vimtex-delim-close)` to `]]` is an implementation detail.

> However, it would not be too much work to add a dictionary of default mappings.

If you want to go this route, please free to do so, it is your plugin after all :). However, be aware that this is different from almost any other Vim plugin around, and that you should probably provide a way for the user to only specify part of the mappings (leaving the others to default values), and also to deactivate a mapping.

**Comment by lervag** [comment]
The suggested solution should not be that different from other plugins. To make it more clear what I suggest, here is a first draft of an option documentation:

```vim
" Allow to override default mappings. E.g. to use `XX` instead of `]]` to close environments and to prevent the `<F7>` mapping from being defined, one can set it to: >

let g:vimtex_mappings = {
      \ '<plug>(vimtex-delim-close)' : 'XX',
      \ '<plug>(vimtex-cmd-create)' : '',
      \}

Default value: {}
```

So, the point is, the default values will be used if they are not overridden.

-----

Perhaps this is not necessary? What do you think, @matthewjohnrussell? Would you agree that it makes sense to revert my previous change and that you instead use `]]` as part of your mapping?
