### ISSUE TITLE
Weird bug when highlighting matching parentheses

### ISSUE THREAD

**Issue by danielbmarques** [lervag/vimtex#493]
When writing inside a pair of parentheses the highlighting for the closing parenthesis shows up in a random letter instead:

![vimtex](https://cloud.githubusercontent.com/assets/15813674/16866811/8a0e4d9e-4a44-11e6-8293-7b2092974b75.gif)

I'm not sure how I could give you a more minimal example than what I gave you at the other issue. This is what I have in my `.vimrc`:

```vim
call plug#begin('~/.vim/bundle')

    Plug 'Shougo/neocomplete.vim'
    Plug 'lervag/vimtex'

call plug#end()

let g:tex_flavor = "latex"
let g:neocomplete#enable_at_startup = 1
```

Then I just open a new buffer with a `.tex` file, write a word a few times for `neocomplete` to pick it up and try writing it inside a pair of parentheses.

**Comment by lervag** [comment]
Ok, thanks. I've reproduced it and will look into it.

**Comment by lervag** [comment]
Strange. It seems this problem is not new. However, before I started to use `matchaddpos`, there would be no highlighting because `matchadd` uses a regex that would no longer match anything.

The issue is that neocomplete opens the completion menu, and while this menu is open, newly inputted text seems to be unavailable. That is, functions such as `getline()`, `searchpos()`, etc, will only see the text inserted before the completion menu is displayed.

**Comment by lervag** [comment]
Ok, I am not able to find a solution to this. However, I found a workaround:

```vim
let g:neocomplete#enable_refresh_always = 1
```

Perhaps @Shougo knows another way to fix this/avoid this? I am not even able to detect whether the completion menu is open (`pumvisible()` always returns 0, even if the menu is open).

**Comment by danielbmarques** [comment]
Uhm, weird. But, well, it seems to be working fine with that option, so I'm happy.

Thanks again for your great work here. You should add a paypal thing or something for users to make donations. :)

**Comment by lervag** [comment]
Yes, I agree, it's a little bit weird. Unfortunately, I think there is nothing more I can do.

I'm very happy to hear you like the plugin. As I'm sure you understand, I'm not doing this for the money. It's fun in itself, and it is even more fun when other people enjoy the work. However, if people like it so much they want to donate, I would of course be even more happy. So I'll add a Paypal donate button to the readme file as you suggest. :)

**Comment by danielbmarques** [comment]
Just a little update: even with the `enable_refresh_always` set this problem still happens sometimes:

![captura de tela 2016-07-18 as 03 27 05](https://cloud.githubusercontent.com/assets/15813674/16907215/f5f32070-4c97-11e6-8577-3b30baf0984c.png)

It happens when you select one of the matches from the pop up menu. You type half the word and then use `<tab>` or whatever key you use to complete the word. The highlighting will stick to where the parenthesis was.

With other filetypes the highlighting is just gone when the pop up menu shows up, which is better, I think, but I don't know how it works, since you said `pumvisible()` always returns 0. But if I open a new buffer without any filetype and start typing I get this:

![captura de tela 2016-07-18 as 03 35 32](https://cloud.githubusercontent.com/assets/15813674/16907366/7bd2d93c-4c99-11e6-8c0b-b00964c7ef85.png)

And then when the pop up menu shows up the highlighting is gone:

![captura de tela 2016-07-18 as 03 35 41](https://cloud.githubusercontent.com/assets/15813674/16907386/9e12c502-4c99-11e6-8490-62142c49618a.png)

I don't know how `addmatchpos()` works… how do you keep the position updated? But there could be a way to only highlight if there are two matching parentheses. If when the pop up is visible you can't "see" the other parenthesis, then there wouldn't be any highlighting. I suppose this is what happens in the example above.

This is not a big deal, though, and the `enable_refresh_always` option is a big help already. I just thought I'd mention it for the record.

**Comment by lervag** [comment]
Ok, I've now updated with a new attempt. Instead of `matchaddpos` I now use `matchadd`, which should be available for most people. This becomes similar to the original version, however, I now use more complicated matching. In particular, I ensure that the delimiters only match if both delimiters are found. This seems to work well for me. Let me know what you think.

**Comment by danielbmarques** [comment]
I had `let g:neocomplete#enable_refresh_always = 1` in my `.vimrc` and with the new update the pop up menu wasn't even showing up except for some weird flashes. But now I removed it and it seems like everything is working perfectly. 🎉
I don't know if that option could be necessary for some users, but since I don't need it it's all good for me. And I guess that must be a problem with neocomplete anyway.
Thanks again for taking the time to look into this!

**Comment by lervag** [comment]
Strange. I have `enable_refresh_always` on, but the completion menu shows as expected here. In any case, I'm happy to hear that you're happy with the latest version!

**Comment by dbmrq** [comment]
@lervag I've been using [mucomplete](https://github.com/lifepillar/vim-mucomplete) instead of neocomplete and now this problem came back. :(

Which is weird, since you said that now the delimiters only match if both delimiters are found.

mucomplete doesn't do anything besides calling Vim's own completion methods, and indeed, the problem can reproduced with vimtex alone. I can reproduce it with just the following in my .vimrc:

```vim
call plug#begin('~/.vim/bundle')
    Plug 'lervag/vimtex'
call plug#end()

let g:tex_flavor = "latex"
set completeopt+=noselect
set completeopt+=menuone
```

Then edit a new .tex file, add a couple of braces and type "vimtex" between the braces a couple of times. On the third time, just type "vim", do [`<C-X><C-N>`](http://vimdoc.sourceforge.net/htmldoc/insert.html#i_CTRL-X_CTRL-N) and then type "tex". And voilà:

<img width="325" alt="captura de tela 2018-04-06 as 01 05 54" src="https://user-images.githubusercontent.com/15813674/38403095-496cb5f8-3937-11e8-8d4e-b143541f8304.png">

**Comment by dbmrq** [comment]
Seems perfect so far!

I was going to suggest updating the highlighting with `InsertCharPre` or `TextChangedI` + `pumvisible()` besides `CursorMovedI`, but this is already great. Thanks! :)

**Comment by lervag** [comment]
Great, happy to hear it works :)
