### ISSUE TITLE
Compiling only part of the document?

### ISSUE THREAD

**Issue by amca01** [lervag/vimtex#497]
The `vim-latex` plugin for vim, as well as the `auctex` mode for emacs, both contain the very nice feature of being able to compile only a selection of your document.  For example, if you're creating a complex figure (as I do a fair bit), you can select that part of your file, and compile that selection only.  What these plugins/modes do is to create a new temporary file consisting of the header material from the current file, and with a body consisting just of the selection, and compiles that file.  This saves having to compile the entire current file.

Now clearly there are workarounds for this: create your figure in its own minimal latex file and when you know it works, add it in to your main file.  But I have become so used to compiling selections that it's become an integral part of how I interact with LaTeX, and I'd love to see some similar functionality in vimtex.

Would this be possible...?

**Comment by lervag** [comment]
I guess it could be added. I suggest the following feature set:

- A function that compiles a provided range of lines
- If no range of lines is provided, it will compile the last provided range of lines, or if there is no last call, it will do nothing
- The function will be given a visual mode map, e.g. `\ll`, which will compile the selected text (should it be strictly linewise?)
- The function will be used to define a command, e.g. `:VimtexCompilePart`, which will require a range
- After (sucessful) compilation, all files will be cleaned up, including the temporary source file, except the output file
- The function will use the current view model in order to view the output file, and it will use the same latexmk options for compilation

Some restrictions I initially want to apply:

- I don't want to parse errors for a partly compile, as that seems complicated

How does this sound? Is there anything lacking here?

**Comment by amca01** [comment]
If that could be done, then it would be fabulous!  I wonder though about the function map: maybe a mapping not yet defined, say `\la` or maybe `\lL`?  There wouldn't be any need to clean up temporary files, as they would simply be overwritten by the next such command.  And sometimes it's handy to have a few extra files lying around, in case you make a mistake and delete something important (as I have done!).

Also, given that "Part" already has a formal LaTeX meaning, maybe call the function `:VimtexCompileSelection`?

But whatever you do, I will be pleased to act as a tester for your code (as long as you don't expect pdf files!).

**Comment by lervag** [comment]
I've implemented a first version. I think it works well already, but I guess it might need some tuning and perhaps some options to control the behaviour.

Obviously, I don't expect you to send me your work manuscripts while testing. It will be enough with any examples of things not working as expected or similar.

Possible changes now might be to use different default mappings, change some names, and perhaps change some of the behaviour.

**Comment by lervag** [comment]
Have you had any time to test this? I think it should work. I'll close the issue, but feel free to reopen or continue the discussion if you find bugs or have suggestions for improving the feature.
