### ISSUE TITLE
Error detected processing function highlight_matching_pair()

### ISSUE THREAD

**Issue by danielbmarques** [lervag/vimtex#505]
To reproduce, edit a new `tex` file and type this:

`i(vimtex)<esc>l:sp<cr>h`

In other words, split the window while the cursor is over a parenthesis and then move the cursor.

This probably doesn't happen very often, but I thought it's worth mentioning.

I tried replacing `s:highlight_matching_pair()` with `vimtex#motion#highlight_matching_pair()`, but it didn't work. And I'm having similar problems writing [that plugin you helped me with at stack overflow](http://vi.stackexchange.com/q/8948). Apparently weird things happen when using `autocmd`s and splitting windows. Let me know if you figure out what the problem is. :)

**Comment by lervag** [comment]
Thanks for noticing and reporting. The problem was that I used script specific variables, but the match objects are local to the windows. That is, a match ID generated for one ID will not be available for a different window, and trying to remove it will generate an error. The solution is to use window specific ID variables, i.e. `w:vimtex_match_id[12]` instead of `s:match_id[12]`.

**Comment by danielbmarques** [comment]
Ah, of course! Thanks for the explanation. :)

**Comment by lervag** [comment]
No problem! :)
