### ISSUE TITLE
\left. foo \right| not recognized as matching delimiters

### ISSUE THREAD

**Issue by fastfforward** [lervag/vimtex#510]
Example:
````
\documentclass{article}
\usepackage{amsmath}

\begin{document}

\begin{align}
  \left.
    \frac{\partial U}{\partial \beta}
  \right|_{\mathrm{max}}
  \propto L^{1/\nu}.
\end{align}

example
text

\end{document}
````
After indenting with `gg=G`, everything after `\left.` gets messed up. Since this kind of notation is rather common in physics, I think its worth implementing.

**Comment by lervag** [comment]
The problem here is `\right|`, and in particular `|`. I removed support for this some time ago (perhaps even years), because it is difficult to parse. When I parse `$`s, it's not that difficult, because I can rely on the underlying syntax matching. However, if you write `| a | = | b |`, it is difficult to know what is enclosed and what is not. See also [here](http://tex.stackexchange.com/questions/498/mid-vertical-bar-vert-lvert-rvert-divides) for some more valuable input on this.

If you change your code to `\right\rvert`, it should work properly.

**Comment by fastfforward** [comment]
This solution works indeed, thank you for that!

**Comment by lervag** [comment]
No problem! :)
