### ISSUE TITLE
gq removes indentation in first paragraph

### ISSUE THREAD

**Issue by danielbmarques** [lervag/vimtex#511]
When I do `gqip` in the *first paragraph* of my text it removes the indentation if that paragraph is indented. It doesn't happen for the other paragraphs.

---

Also, I think this is unrelated and maybe a neocomplete bug, but every time I use your `gq` now I get these errors:

```
Error detected while processing function <SNR>148_complete_delay[3]..<SNR>148_do_auto_complete[12]..neocomplete#context_filetype#set:
E117: Unknown function: context_filetype#get_filetype
E15: Invalid expression: s:exists_context_filetype ? context_filetype#get_filetype() : &filetype
```

I'm not sure if there's anything specific that's needed to reproduce it, I commented out everything from my `vimrc` except for neocomplete and vimtex and I still get that.

Edit: Weird… neocomplete only throws those errors if running `gq` is the *first thing* I do after opening a file. If I do anything else, then I can use `gq` after that and it's all good.

**Comment by lervag** [comment]
First, regarding your second issue: I am not able to reproduce it. Could you please open a new issue for this, in particular if you are able to create a minimal working example (with a minimal vimrc file)?

So, for the main issue with indentation. I'm trying to reproduce it, but I can't. Could you please provide a minimal tex file? That is, if I create the following `tex` file (with four spaces indentation of the text), I can, but in this case, I think that it is appropriate to remove the indentation:

```
  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
  tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
  vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
  gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
```

**Comment by danielbmarques** [comment]
Why is it appropriate to remove the indentation in that case? And why just for the first pragraph? I always keep my whole text a little indented because I don't like it glued to the ruller on the left, and I think of it as nested inside each `\section`. I always used it like that and the regular `gq` kept my indentation intact. Even if someone prefered it to remove the indentation, I don't see how that has anything to do with Latex specifically, so I think Vimtex, being a Latex plugin, should stick to Vim's standard behavior in this regard.

**Comment by lervag** [comment]
I have to say that I find that a very strange preference! But I can accept the argument that there is no reason for vimtex to impose rules on how people want to indent their files, and so I've pushed a minor change to allow this.

**Comment by danielbmarques** [comment]
Thanks! :)

You should try it, you'll see it's much better, haha. It's a lot harder to read the text when it's so close to the line numbers.

**Comment by lervag** [comment]
I never use line numbers. :)

And no problem!

**Comment by danielbmarques** [comment]
Ah, that explains it then. Relative numbers are great for fast movements and selections, and they're fine when coding, but for prose they're a little intrusive and it's a lot better if the text is a little farther apart.
Thanks again. I'll see if I can isolate the other problem and open another issue.

**Comment by lervag** [comment]
Great! Regarding relative line numbers, I can understand that people like them. But I find I rarely need exact motions like that, and often tend to use motions and text objects that don't require that I know the exact number of lines.

**Comment by danielbmarques** [comment]
This is still happening when there's a latex command right before the paragraph.

Take a file with just this, for instance, and do `gqip` on the text:

```tex
\section{lorem}

  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
  tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
  vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
  no sea takimata sanctus est Lorem ipsum dolor sit amet.
```

It removes the indentation here.

**Comment by lervag** [comment]
Ok, as I said, I accept that people (and we) may have different subjective habits for indentation. However, I really feel it is inappropriate to add indentation after sectioning commands. I've searched the web, and I can't see anyone who suggests this, either.

It will not be very difficult to add, but I am not sure I want to add it. Can you consider to stop using indents for sectioning?

*Note*: This issue is not really related to the formatting, but instead to indentation. If you use the indentation operator `=`, e.g. `=ip`, you will see the same behaviour. Thus, if I were to allow indentation on sectioning commands, it would be through `indent/tex.vim` and `indentexpr` function.

**Comment by danielbmarques** [comment]
Sure, it's no big deal, and I can just use `gw` for the first paragraph, like I'm doing right now. I just think it would be better if Vimtex's `gq` kept Vim's behavior for indentation, since it has nothing to do with Latex. But I get it if you want to keep it this way, no problem. :)

**Comment by danielbmarques** [comment]
Also I think what you said in the note is an argument in my favor I think: "this issue is not related to the formatting", so why should the formatting operator change the indentation? There's already another operator for that, `=`.

**Comment by lervag** [comment]
I don't agree that this "has nothing to do with Latex". I think this is a coding convention, and I think that the indentation function should adhere to some sort of "best practise", which I think that the current version is doing.

If you want Vim's behaviour for indentation, then you can turn off the vimtex indentation with `let g:vimtex_indent_enabled = 0`.

I think formatting should include indentation, which is why it must depend on the indentation expression. This way, you can properly format and indent an entire file with `gggqG`. If I do not adhere to the indentation while formatting, then formatting of larger portions of text then a single paragraph will most likely fail, because a properly formatted paragraph depends both on the indentation and on the text width.

**Comment by danielbmarques** [comment]
Uhm, I don't know, I think people do crazy things, I surely do, and then if I did `gggqG` I'd expect it to change just the *format*, and not my file's whole indentation that was carefully added by me in crazy ways. But we can agree to disagree, it's not a big deal. And it's your (great) plugin. :)

**Comment by lervag** [comment]
Ok, then. Let's agree to disagree. Except, I can accept to respect the first line indent during formatting. I think that makes for a very good compromise.

**Comment by danielbmarques** [comment]
Ah, that's perfect! Thanks. ❤️
