### ISSUE TITLE
unclear priority of main LaTeX file search methods in help docs

### ISSUE THREAD

**Issue by rionda** [lervag/vimtex#535]
The help on the different methods used by vimtex to determine the main LaTeX file is a bit unclear.
It states:

> [...] The priority of the methods are as follows:
>
>  1. Buffer variable
>  2. TeX root specifier
>  3. Subfiles package
>  4. File `.latexmain` specifier
>  5. Recursive search

It is unclear, from the docs, whether "1" is the highest priority or the lowest. In practice, it turns out to be the highest. The confusion is even greater due to the fact that the methods are then documented starting from 5, then 4, then 2, and then 1 (3 is not documented). Moreover, they are documented in such a way that it seems that recursive search is chosen first, and the other should be used only when recursive search doesn't work.

To clarify the situation a bit, perhaps the text could be changed as

> The methods are tried in the following order:
> [...]

In any case, I find the order a bit surprising: in my opinion, it should be exactly the opposite, or at least recursive search should be the first, as the current order leads to unexpected results. Consider the following example: I have a directory `paper` containing a `paper.tex.latexmain` file for a project, denoting that the main file for this project is`paper/paper.tex`, and I also a directory `paper/talk` containing a file `talk.tex`, which starts with `\documentclass{...`. Now, when I open `talk.tex` (with current working directory `paper/talk`, and activate the background compilation with `\ll`, the file that gets compiled is `../paper.tex` and indeed `paper.pdf` is opened in my PDF viewer, while I would expect to `talk.tex` to be compiled and `talk.pdf` be opened. If I remove the `paper/paper.tex.latexmain` file, then `talk.tex` gets compiled. 

It seems that the current order makes it impossible, without actively fiddling with `.latexmain` files, or TeX root specifier or others, to have vimtex automatically pick a main file in a subdirectory of a directory containing a `.latexmain` file (and the subdirectory could be many levels deeper than the directory containing the `.latexmain', I guess). This to me seems a violation of the principle of least astonishment of the user. 

I would suggest to have recursive search first, and then the other methods.

Additionally, the documentation for recursive search should probably be changed to 

> The recursive search detects the main LaTeX file by searching for a file in
>  the current and parent directories that includes the present file and that 
>  has the `\documentclass` line, or is the present file.

("or is the present file" is added at the end").

**Comment by rionda** [comment]
There also seems to be some bugs: I opened a file in one project, and started background compilation on this project. Then opened another file in another project (without starting background compilation on it). Then wiped the buffer  (:bw) containing this second file. Now when calling `\lv`, the PDF of the second project shows, rather than the PDF of the first. Also, if at this point I do `\ll` twice, the background compilation is started on the second project, of which there is not even a file open. The two project are in separate directory structures, so it doesn't seem a mainfile problem, but it still seems related to the search.

**Comment by lervag** [comment]
Just to sum up, I detect three points here:

1. Order of documentation and order of main file detection is unclear.

2. You think the order should be the opposite from what I've chosen.

3. You suggest to add "or is the present file" to a paragraph for recursive search docs.

----

I see your point on the confusion of the priority, and I think your suggestion for rewording is good. I also agree that the following documentation should come in the same order, and this is fixed in the most recent commit.

Regarding your second point, I disagree. That is, I might be persuaded to change the order, but I definately don't think the recursive search should be tried first. I've actually put some thought into this, and I think it makes much more sense to adhere to explicit instructions first, before trying implicit methods. Thus, if you specify a main file with `.latexmain`, then vimtex will use it. I am open for a discussion on this point, and there might be possibilities for improvements (for instance, one might check that the `.latexmain` file actually includes the current file before selecting it as the main candidate).

For the third point: I don't like the suggested formulation, but I can understand the point. I'll try to come up with a better way to phrase it.

**Comment by lervag** [comment]
Regarding the bug: Could you please open a separate issue for this, preferably with a minimal working example? I think I might have noticed this, barely, but I haven't been able to pinpoint it.

**Comment by lervag** [comment]
Hmm. For what I called your third point: I don't think this should be part of the recursive search, because applying the search sort of implies that the current document is _not_ the main document. Instead, I think you've detected a weakness in the current system. I should instead check for `\documentclass` in the current file _before_ searching for a main file through other means.

**Comment by rionda** [comment]
@lervag,

Thank you for your reply.

Yes, those 3 points are correct.

I saw your commit on the first and left some comments.

For the second, I wonder whether the plugin should also check whether the current file starts with \documentclass (or has  \documentclass within the first few lines, or whatever). If so, the current file is the main file.

I also think that your idea to check whether the `.latexmain` file (or one of the files included in it?) actually includes the current file is good should be implemented. 

What I do not like of the current order is the following: if there is a file with `\documentclass` in the current directory that includes the current file but the current directory is a subdirectory with a `.latexmain` file, then the file pointed by the `.latexmain` file is considered the main. This seems counterintuitive because we are "abandoning" the current directory and looking at parent directories before having exhausted the possiblities of search in the current directory.

I'll open another issue for the bug.

**Comment by rionda** [comment]
Regarding your second comment: it seems we wrote the same thing, so I agree with that.

**Comment by lervag** [comment]
Great. I've updated the docs again, I hope it is better now. I think the follow updates will solve the issue:

- [ ] Before searching for a main file, first check if the current file is a main file.
- [ ] Apply a check to main file candidates to see if the current file is really included.

I think the second task will fix your main issue, since this will make the `.latexmain` file that is erroneously selected be ignored, since the corresponding main file does not include the current file.

Do you agree, or is there something I've missed?

**Comment by rionda** [comment]
I agree that these proposed fixes be enough to fix most issues with this ordering. 

Thank you.

**Comment by lervag** [comment]
Ok, please test now. There might be some corner cases/edge cases, but it seems to work for me.

**Comment by rionda** [comment]
@lervag: seems to work 👍, thank you!

**Comment by lervag** [comment]
Great, I'm happy it works. Let me know if you have problems! :)
