### ISSUE TITLE
Comment format for bib files

### ISSUE THREAD

**Issue by dbmrq** [lervag/vimtex#540]
I'm editing a `bib` file and when I use a plugin like Tim Pope's `vim-commentary` to comment out a line it doesn't use the right characters.

So I copied this line from `vimtex`:

```vim
setlocal comments=sO:%\ -,mO:%\ \ ,eO:%%,:%
```

And pasted it in my `ftplugin/bib.vim` file, but it still doesn't work as it should.

I could ask how to fix this at the Vim Stack Exchange, but I think it would be nice if `vimtex` handled this, so I thought I'd ask here first.

**Comment by dbmrq** [comment]
Ok, I figured it out. I had to set `commentstring` instead of `comments`. Still I think it would be a good idea for Vimtex to do this by default.

**Comment by dbmrq** [comment]
While we're at it, the syntax highlighting also doesn't consider the comments. It would be nice to have that too.

**Comment by lervag** [comment]
What do you propose that we set the commentstring to? And could you elaborate about the syntax highlighting? What exactly is missing?

**Comment by lervag** [comment]
Btw: The syntax highlighting that comes with Vim is written by Bernd Feige, his email address can be found in `$VIMRUNTIME/syntax/bib.vim`. I think it would be more appropriate if you sent him an email about that, because if he updates, then it will reach all Vim users, not just vimtex users.

Note: I could fix things in vimtex in the meantime, but I prefer to keep things simple and rely on the good work of others where possible.

**Comment by dbmrq** [comment]
Well, I just added this to my `bib.vim` `ftplugin`:

```vim
setlocal comments=sO:%\ -,mO:%\ \ ,eO:%%,:%
setlocal commentstring=\%\ %s
```

I don't know if it's the best option, but it's working well for me.

As for the syntax highlighting, there just doesn't seem to be any for the comments at all (if they're inside an entry, that is).

Take this entry, for instance:

![captura de tela 2016-09-09 as 15 22 18](https://cloud.githubusercontent.com/assets/15813674/18398164/de959906-76a1-11e6-8349-3e50e314e8dd.png)

All that part after the `%` signs should be light grey, like the `@Comment` entry below.

If you're going to fix this in Vimtex I can send the changes to Bernd Feige then.

**Comment by lervag** [comment]
Regarding comments, I looked into it. I found that what you are trying to do is not really supported by bibtex, see [here](http://maverick.inria.fr/~Xavier.Decoret/resources/xdkbibtex/bibtex_summary.html#comment) and [here](https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management#Standard_templates). Thus, I don't think your suggested syntax highlighting should be added, because it would indicate that it is actually permitted.

**Comment by dbmrq** [comment]
Ah, you're right, [that only works with biblatex and biber](http://tex.stackexchange.com/a/93982/102699). Since that's all I use I didn't realize it was incompatible with bibtex.

I think ideally there should be an option like `tex_flavor` but for `bib` files. Then the user could do something like `let g:bib_flavor = 'biblatex'` and it would allow those comments. It might be overkill for just the comments syntax highlighting, but I think it would be nice. Anyway, it's up to you. Thanks. :)

**Comment by lervag** [comment]
Hmm. I don't really feel like this is a natural part of vimtex. Perhaps you could still write an email to Bernd Feige; he might be interested in this and in adding such an option? I think my solution to your SO question should work, but to fully support the biblatex/biber syntax one should allow end-of-line comments as well.
