### ISSUE TITLE
Vimtex warning: Viewer can not read pdf file

### ISSUE THREAD

**Issue by dragonxlwang** [lervag/vimtex#551]
"vimtex warning: viewer cannot read PDF file"

to reproduce:

have two tex files:

a/a.tex
b/b.tex

If I am compiling a.tex with a/latexmk.rc, and then opens b/b.tex in vertical split, and then jump back to a/a.tex (two buffers vs in one window), then the error comes.

my latexmk.rc file looks like this
```
 $pdf_previewer = "open -a /Applications/Skim.app";
  @default_files = ('main.tex');
  $pdflatex = 'pdflatex -pdf -verbose -file-line-error -synctex=1 -interaction=nonstopmode %O %S';
  $clean_ext = "paux lox pdfsync out synctex.gz";
```

I am using skim to view pdf on Mac OS X. Thanks,

**Comment by lervag** [comment]
Curious: Why are you using a `latexmk.rc` file in this particular case?

Does the problem depend on the contents of the `a.tex` and `b.tex` files? I.e., can they be minimal LaTeX files?

Does this happen with a minimal vimrc file? E.g. this:

```vim
set nocompatible

" Change the paths accordingly if necessary
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable
```

**Comment by dragonxlwang** [comment]
1. Sometimes I am also compile it from command line which case I use the latexmk.rc to store options.

2. It seems not. For example, I can reproduce the problem with the following file.

```
\documentclass{article}
\usepackage{lipsum}
\begin{document}
\lipsum
\lipsum

\end{document}
```

Yes. I used your vimrc file, except that I am using Skim for viewer so that I add the additional
vimrc regarding skim as shown in your doc.

Thanks!

**Comment by lervag** [comment]
Ok: Does the problem occur if you remove the `latexmk.rc` files?

**Comment by dragonxlwang** [comment]
yes. I used a separate directory which only contains the vimrc file you gave me 
and also the created minimal tex example. The other folder, however, is from
a clean sig-alternate template downloaded directly from acm, which does not
add any other additional config files.

hope this helps.

**Comment by lervag** [comment]
Sorry, it's a little bit confusing. Please specify the full minimal example (both `tex` files and the minimal vimrc file), and the steps to reproduce. Please be specific. I will try to reproduce, but I will have to make some modifications since I don't have a Mac, and so it is very important that I understand exactly how to reproduce it.

**Comment by nasenatmer** [comment]
I had the same error message a few days ago but imagined it to have gone away after another `:PluginInstall!`. But it could as well be that I just stopped switicheng between currently-compiling buffers and non-compiling buffers…

**Comment by lervag** [comment]
Just in case it is unclear: When I use the minimal vimrc file I posted together with the minimal tex files and do:

```sh
gvim -u minivimrc a/a.tex
```

followed by `\ll`, then `:vsplit b/b.tex`, then `<c-w>w`. No error message, everything works as expected.

**Comment by nasenatmer** [comment]
Indeed. I just tried to reproduce the issue with a minimum vimrc and MWE such as 

```tex
\documentclass{scrartcl}
\begin{document}
hello world
\end{document}
```
Opening this MWE, pressing `\ll`, then `:tabedit mwe2.tex` (opening another MWE  pressing `\lv`, `gt` and `\lv` again, no errors.

There is one thing happening that is unexpected, however: if switching back and forth between tabs, each time I press `\lv`, an additional instance of my pdf viewer opens, but maybe this is by design, not fault (because vim loses track of the pid when switchng tabs?)

**Comment by lervag** [comment]
Ah, I finally see what's happening. I can reproduce the original problem now. I'll try to fix it asap.

**Comment by dragonxlwang** [comment]
sorry that I was working on a submission then. I didn't had a time to reply. Glad you can find the problem :P

**Comment by lervag** [comment]
As you may notice if you read the commit log, the recent commit is quite big. I did a refactoring of the viewer code that I think both solves this issue, and makes the code much better. Please test. I think it should be safe and that all tests will pass, but big changes like this may lead to effects I didn't think of.

**Comment by TsukiZombina** [comment]
Recently I had which seems to be the same problem, when I press `<leader>lv` in a multiple file tex project it's unable of open the right file, it opens `texfilename.pdf` instead of main.pdf which is the document that join all tex files in my project.

I tried using the minimal vimrc:

> ```viml
> set nocompatible
> 
> " Change the paths accordingly if necessary
> let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
> let &rtp .= ',~/.vim/bundle/vimtex/after'
> 
> filetype plugin indent on
> syntax enable
> ```

But it still shows the warning Viewer can not read pdf file! I hadn't had this problem before and I didn't changed my vimrc or updated the plugin or vim or its dependencies. Also if I try to press `<leader>lv` in other tex file but the one which have the same name as the pdf file, it send a Compile error.

**Comment by lervag** [comment]
Can you please open a new issue with a full description? Thanks in advance.
