### ISSUE TITLE
How to not spellcheck words in some \func{words} ?

### ISSUE THREAD

**Issue by teto** [lervag/vimtex#562]
### Explain the issue
This is the same issue as in:
http://vi.stackexchange.com/questions/4523/how-to-configure-spell-to-ignore-some-environments-in-latex

How can I define the "commands" \command{} for which I want to ignore what is in it ? For instance I use the package glossaries and would like the spellchecker to ignore everything in "\gls{}" commands.
I search for "spell" in :h vimtex with no success.

**Comment by lervag** [comment]
Vimtex does not have this feature in itself. However, it is easy to add manually. You can add the following to your `.vim/after/syntax/tex.vim`:

```vim
syntax match texStatement '\\gls' nextgroup=texGls
syntax region texGls matchgroup=Delimiter start='{' end='}' contained contains=@NoSpell
```

**Comment by lervag** [comment]
Just to be clear: the syntax plugin is really maintained by Charles Campbell. I propose that you send him an email about this, as it would be better if improvements to the syntax plugin reaches all Vim users, not only vimtex users.

**Comment by teto** [comment]
Don't know when but I will do it (maybe once I gathered a few more keywords).
 thanks !

**Comment by lervag** [comment]
No problem. I hope it helped!

**Comment by timokau** [comment]
For other people who stumble on this issue when trying to disable spell check for certain patterns in tex files:

Here's how you can also ignore URLs and acronyms in comments:

```vim
fun s:tex()
	" Do not check URLs in comments
	" (https://vi.stackexchange.com/questions/3990/ignore-urls-and-email-addresses-in-spell-file/4003#4003)
	syntax match UrlNoSpellComment "\w\+:\/\/[^[:space:]]\+" contains=@NoSpell containedin=texComment
	highlight def link UrlNoSpellComment Comment

	" Do not check acronyms in comments
	syntax match AcronymNoSpellComment '\<\(\u\|\d\)\{3,}s\?\>' contains=@NoSpell containedin=texComment
	highlight def link AcronymNoSpellComment Comment

        " Do not spellcheck within a \gls command, can be adapted for other commands.
	syntax match texStatement '\\gls' nextgroup=texGls
	syntax region texGls matchgroup=Delimiter start='{' end='}' contained contains=@NoSpell
endfun
augroup syntax_overrides
	autocmd!
	autocmd Syntax tex call s:tex()
augroup end
```

Note that you need to know which pre-existing group the match is contained in and that you need to re-set the higlighting. Unfortunately, that makes it pretty much impossible (as far as I know) to set up similar excludes for regular text. There are just too many possible groups (search your `tex.vim` for `@Spell`).

You probably want to put that snippet near the *end* of your vimrc, since its important that the autocmd is defined (and therefore executed) late and overrides the normal syntax definitions. Alternatively, you can put the overrides into `.vim/after/syntax/tex.vim`.

**Comment by lervag** [comment]
@timokau This looks quite useful, actually, and I'm wondering if I shouldn't just add it as a general improvement in vimtex. I can't immediately see and drawbacks...

**Comment by timokau** [comment]
> This looks quite useful, actually, and I'm wondering if I shouldn't just add it as a general improvement in vimtex.

That sounds good! It would be especially nice if there was a configuration option for ignoring spelling in commands, i.e.

```
let g:vimtex_spell_ignore_commands = ['\gls', '\bibliographystyle']
```

Since the manual method is neither very discoverable nor convenient to use. You're right of course that upstreaming would be the best option, but that's probably not feasible for *every* command out there, especially custom ones.

> I can't immediately see and drawbacks...

Minor drawback: The URL regex is very naive, and might theoretically have false-positives (or false-negatives if a URL does not contain the protocol). It should be good enough for comments though.

**Comment by lervag** [comment]
I pushed some updates. Could you open a new issue if you have further ideas/suggestions? Let's end the discussion on this thread here, since we're now off topic. Reg. the option: I try to keep package related syntax in separate package scripts, and I added support for `\gls` already. Feel free to open issues about macros that should be updated with nospell.
