### ISSUE TITLE
Indicate that compilation failed due to biber not being available

### ISSUE THREAD

**Issue by lahwaacz** [lervag/vimtex#610]
When biber is not available and latexmk fails for obvious reasons, vimtex shows the build status as "failed" but does not explain why - there is no error in the quickfix window. This can easily happen e.g. due to [this](https://www.archlinux.org/news/texlive-2016-packages-are-now-available/).

**Comment by lervag** [comment]
I'm not quite sure how I should do this. I assume that you figured out the problem and fixed it, and so this is no longer a problem for you specifically. Thus you report this to help prevent others using the same amount of time figuring it out?

The thing is, I could add a check if the document requires biber (e.g. if biber is the backend for biblatex), and in that case check if biber is executable. However, I don't want to do that, because I don't think that is vimtex's responsibility.

In this case, it would be trivial to understand what was happening if one tried to compile manually in a terminal. I think that should be a basic skill everyone should have, at least everyone who uses vimtex. And so vimtex should not need to do this kind of checking.

**Comment by lahwaacz** [comment]
It's not necessary to parse the document at all. It's just very confusing to see that the compilation _failed_ and there are _no errors reported_. These conditions can be checked very easily by vimtex. If anything, you could at least refer the user to investigate the log file manually, or even put the "hidden" parts of the log back into the quickfix window.

**Comment by lahwaacz** [comment]
You might also check for this message in latexmk's output:

    sh: biber: command not found

It's probably a good idea to replace `biber` with some wildcard match to make it more generic.

**Comment by lervag** [comment]
I disagree. The messages in vimtex (with the callbacks enabled) are based on parsing the log files. Errors on the latexmk end such as these are not parsed, and I don't want to add that. This specific case is very much of an edge case, and I think vimtex is complex enough as it is.

If vimtex reports an error but is not able to show what the problem is, then the user should know enough to investigate the problem on his/her own. vimtex is a convenience layer on Vim for LaTeX, it is not a full blown LaTeX IDE, and it will never be. I don't want to add code to handle every edge case. I try to keep the code relatively uncomplicated and "simple", which I am able to do by not implementing everything.

I hope you can accept this. If not, then please make a better case of this, preferably with a form of reproducible example of an error that vimtex should be able to report/react on, but it is currently not.
