### ISSUE TITLE
main file extension

### ISSUE THREAD

**Issue by sga001** [lervag/vimtex#620]
It seems that the main file (in a multi-file project) has to have a ``.tex`` extension for vimtex to work. I usually like to differentiate my main files by naming them ``.ltx`` instead (I've seen many other people do similar things, so I don't think I'm totally batshit crazy). I thought creating a symlink with a ``.latexmain`` would be enough to solve this issue, but it turns out that vimtex removes the extension and then hardcodes a ``.tex`` later in the process.

The solution to this issue is easy enough: create a ``.tex`` symlink (instead of a ``.latexmain``). Another solution is to add support for ``.ltx`` into vimtex, but that might not be worth the development effort.

My real intention with opening this issue is the following: please add a comment about this in the documentation so that people won't spend time trying to figure out why vimtex is not working. It took me longer than I would've wanted to determine that the root cause of all my issues was my main file extension.

Thanks!

**Comment by lervag** [comment]
I've actually never ever heard anyone use the `.ltx` extension, and I don't really see any good reason why that should be supported. Why not just call your main file something like `main.tex`, `master.tex`, or similar?

I could of course update to support this alternate filename extension, but I've been an active LaTeX user for 13 years, I have worked on both LaTeX-Box and vimtex for 4-5 years, and I have never heard of anyone using this extension. Thus, I think it is safe to assume that this is a very rare use case. In order to keep things simple, I would much rather make you change your habits and use `.tex` for all files.

I searched around, and I see now that using the `.ltx` file ending is valid, but is is not used for normal user files and documents. See [here](http://tex.stackexchange.com/questions/281846/which-file-format-should-i-use-for-latex-documents-in-texshop), in particular note the comment by Christian Hupfer. Thus, I vote to not even write about this in the docs, as my feeling here is that you should not use `.ltx` for personal document files.

**Comment by TheKubek** [comment]
So if I work with a .lhs (Literal Haskell File) file, can I somehow enable Vimtex?

**Comment by lervag** [comment]
Again, as just mentioned in a different thread: Don't necrobump. Open a new issue. Feel free to give a reference to older, relevant, issues. A short answer for now: I don't work with Haskell, so I have never tried to enable Vimtex for literal haskell files. But at the moment, Vimtex is based around `.tex` files e.g. for finding the "main" project files. So, to allow some features for LHF, I think some work may be needed. Thus, again, it is much better to have a separate issue.
