### ISSUE TITLE
Troubles with nested delimiters

### ISSUE THREAD

**Issue by petkus** [lervag/vimtex#666]
There is an issue with selecting an outer delimiter using such commands as 2ad or 2id
When the curser inside somthing such as the  two '{ }', it will not be able to select the \left(, \right)

```tex
\documentclass{minimal}
\begin{document}

\left(sqrt{2}\right)

\end{document}
```

### Vimrc file

```vim
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'altercation/vim-colors-solarized'
Plugin 'terryma/vim-smooth-scroll'
Plugin 'Valloric/YouCompleteMe'

call vundle#end()
filetype plugin indent on

noremap <F8> :w<CR>:!python3 %<CR>
noremap <F12> :w<CR>:!pdflatex %<CR>
noremap <F10> :w<CR>:!g++ -std=c++11 %<CR>
noremap <F9> :w<CR>:!./a.out<CR>
nnoremap <SPACE> <Nop>
let mapleader = " "
set showcmd
noremap <Leader>y "+y
noremap <Leader>Y "+Y
noremap <Leader>p "+p
noremap <silent> <c-b> :call smooth_scroll#up(&scroll*2, 10, 4)<CR>
noremap <silent> <c-f> :call smooth_scroll#down(&scroll*2, 10, 4)<CR>
syntax on

set gdefault
set number

" Shortcut to rapidly toggle `set list`
set list
nmap <leader>l :set list!<CR>

" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:▸\ ,eol:¬
let g:neocomplete#enable_at_startup = 1
```

**Comment by lervag** [comment]
First, I took the liberty of removing all the comments from your vimrc file. What remains is interesting, for instance: Why are you opening an issue for vimtex when you are not even loading it?

Next, the question you are asking does not make sense. Commands such as `2ad` are not generally defined in Vim. However, counts are accepted for the [targets.vim](https://github.com/wellle/targets.vim) plugin, which is probably where you heard of it. They are not supported in vimtex and I do not plan to add support for it anytime in the near future. The reason is that it is too complicated to implement, especially when considering the cost/benefit.
