### ISSUE TITLE
Automatically change keyboard layout once cursor is in math mode

### ISSUE THREAD

**Issue by AlekseiSmirnov** [lervag/vimtex#670]
I have a question regarding optimization of vimtex workflow during a development of multilingual LaTex documents. 

The problem is that each time I'm in math mode I have to switch from my native language to English in order to add a formula. Currently, I use <C-^> keystroke. 

Is it possible to switch language from Russian to English automatically, once I'm in math mode and revert it back to Russian when I leave the math mode?
What is the best way to achieve this behavior?

I tried to add the following function to .vimrc file but it seems that it doesn't work
```
augroup mathmode_toggler
  autocmd!
  autocmd CursorMovedI *.tex call ToggleLangMap()
  autocmd CursorHoldI  *.tex call ToggleLangMap()
  autocmd InsertEnter  *.tex call ToggleLangMap()
  autocmd TextChangedI *.tex call ToggleLangMap()
augroup END

function! ToggleLangMap()
  let l:langmap = &iminsert == 1
  let l:mathmode = vimtex#util#in_mathzone()
  echom "Langmap" l:langmap
  echom "mathmode=" l:mathmode

  if l:mathmode != l:langmap
    let &iminsert = l:mathmode
  endif

  echo "Language map enabled:" &iminsert
endfunction
```
But it seems that it doesn't work, despite math mode is detected correctly

**Comment by petRUShka** [comment]
@AlekseiSmirnov, probably It is worth to consider using vim-xkbswitch together with Custom keyboard layout switching rules: https://github.com/lyokha/vim-xkbswitch#custom-keyboard-layout-switching-rules

**Comment by lervag** [comment]
@AlekseiSmirnov If you do not use the suggested functions, could you let me know the value of `iminsert` when you are in Russian mode and in English mode? With the above, `iminsert is set to 1 in mathmode and 0 outside. Perhaps it should be opposite, or perhaps it should be 2 and 0, not 1 and 0.

I have not heard about vim-xkbswitch, but that might also be of interest.

**Comment by petRUShka** [comment]
@lervag, possibly it is a good idea to support `vim-xkbswitch` as `vimtex` supports some third-party plugins: `unite`, `neocomplete` and etc.

Feature to switch keyboard layout to English in math mod and then back automatically could be very useful for people like @AlekseiSmirnov or me for example :)

**Comment by lervag** [comment]
Perhaps that is a good idea, but I would need help in adding this. Both because I don't have much time, and because I have no experience with vim-xkbswitch. The best, of course, is a pull request. The second best is a good description of what needs to be done for this support to be included.

**Comment by AlekseiSmirnov** [comment]
It took quite a while to figure out what's going on. It turned out that vimtex somehow conflicts with vim-colors-solarized plugin. If this plugin is enabled `vimtex#util#in_mathzone()` often stops to recognize a math mode.

Can be reproduced on the following ~/.vimrc2 file
```vim
set nocompatible

"Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
let &rtp .= ',~/.vim/bundle/vim-colors-solarized'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable
"
" Vimtex options go here
"
augroup mathmode_toggler
  autocmd!
  autocmd CursorMovedI *.tex call ToggleLangMap()
  autocmd CursorHoldI  *.tex call ToggleLangMap()
  autocmd InsertEnter  *.tex call ToggleLangMap()
  autocmd TextChangedI *.tex call ToggleLangMap()
augroup END

set cursorline

function! ToggleLangMap()
  let l:mathmode = vimtex#util#in_mathzone()
  echom "Mathmode = " l:mathmode
  if l:mathmode == 1
    hi CursorLine gui=underline cterm=underline
  else
    hi clear CursorLine
    hi clear CursorLineNR
  endif

endfunction

nnoremap <F2> :set nonumber!<CR>

map ,v :vsp ~/.vimrc2<CR>
map ,V :source ~/.vimrc2<CR>
" reload vimrc automatically after saving
autocmd! bufwritepost ~/.vimrc execute "normal! :source ~/.vimrc"

colorscheme solarized
```

main.tex
```vim

\documentclass[main.tex]{subfiles}

\begin{document}

\end{document}
```

once `vimtex#util#in_mathzone()` return `True`, current line should be highlighted in vim
Here is how to reproduce:

1) vim -u ~/.vimrc2 --servername server main.tex
2) try different math modes 
- `\(`
- `\[ \]`
- $test$
3) press ,V to reload vimrc file. Since now math mode will be detected only in a case of `$ $` and won't for others (current line will not be highlited). 
4) If you press `,v` , comment out  `colorscheme solarized` , then  `:w :qa`  and perform test again, problem will not be reproduced.  Be aware that `:qa` is nesessary as otherswise commenting out `colorscheme solarized` takes no effect.


Finally, I was able to automatically switch language (see code snippet below), but I guess due to the problem above sometimes it just stops working.

**Comment by lervag** [comment]
The reason is that `solarized.vim` uses `hi clear` during "initialization" of the colorscheme. This resets the highlight groups and thus makes the function `...#in_mathzone()` useless.

I've tried to find a way around this, but I'm sorry to say that I am failing. However, you could avoid resouring the colorscheme on reloading vimrc? E.g. something like this:

```vim
if !get(g:, 'colors_name') ==# 'solarized'
  colorscheme solarized
endif
```

**Comment by lervag** [comment]
I'm wondering if we can close this issue? It is unclear to me what remains to be discussed/solved..?

**Comment by AlekseiSmirnov** [comment]
Yes, thanks for the help. 
This problem was solved. Here is code snippet if someone will be interested. It switches language to Eng once you in math mode and return it back once you leave math mode:

```vim 
augroup mathmode_toggler
  autocmd!
  autocmd CursorMovedI *.tex call ToggleLangMap()
  autocmd CursorHoldI  *.tex call ToggleLangMap()
  autocmd InsertEnter  *.tex call ToggleLangMap()
  autocmd TextChangedI *.tex call ToggleLangMap()
augroup END

let g:wasru = 2
"0 - if when entered math mode language was english
"1 -  if when entered math mode language was russian
"2 - lang not detected yet
function! ToggleLangMap()
   let l:mathmode = vimtex#util#in_mathzone()

  if l:mathmode == 1 
    "set flag once we entered in math mode
    if g:wasru == 2
      let g:wasru = (&iminsert == 1)
    endif
    "set language to English 
    set iminsert=0
  else   
    "we switch back to language that we had once entered math mode
    if g:wasru==1
        set iminsert=1
        let g:wasru=2
    elseif g:wasru==0
        set iminsert=0
        let g:wasru=2
    endif
  endif
endfunction
```

**Comment by lervag** [comment]
No problem! And thanks for posting your final version of the language switch stuff.

**Comment by petRUShka** [comment]
I prefer for this task to be opened till all of the following conditions be accepted:

1. There is a help message or integrated solution for automated language switching using internal vim [keyboard layout switcher](http://vimdoc.sourceforge.net/htmldoc/editing.html#CTRL-^).
2. There is a vim-xkbswitch integration (via [custom rules](https://github.com/lyokha/vim-xkbswitch#custom-keyboard-layout-switching-rules)) in vimtex. This is OS-based keyboard layout swither.

The first solution is inconvenient for those who don't use to use `Ctrl+^` (only vim mapping for switching layout)  for switching. For example imagine that you have to write down following:

```
$ a = b + c, \hbox{если } d \ne 0$.
```

If your workflow is based on OS-based layout switcher you will be in trouble, because anywhere in mathmode you will be with english layout and it will be very hard to type `если` (word for `if` in Russian) if you don't use `Ctrl+^`.

**Comment by lervag** [comment]
@petRUShka Please see [here](https://github.com/lervag/vimtex/issues/670#issuecomment-280619381), where I asked for help. To me, this feature is really not necessary, so adding it is purely for the community in general. And since I don't know about the keyboard layout switcher you refer to, nor about vim-xkbswitch, I think it is not too much to ask that someone provide enough information for me to implement a solution.

My proposal is this: Either 1) You (or someone) try to implement a solution similar to what you propose and open a pull request, or 2) you (or someone) open an issue with a feature request, where the request clearly states enough details to make it possible for me to implement a working solution.

I don't mean this in a rude way. I understand why this might be a useful thing for a lot of people. And I will gladly help with the implementation. I just need more background and more details on how to do this (or better, someone to suggest a solution with PRs). :)

**Comment by petRUShka** [comment]
I totally agree with you!

I even thought about implementing it, but I'm not so familiar with xkbswitch yet. 

I propose to leave this issue open till someone (may be me or may be someone else) implement it or provide enough details. This issue is a reminder for such people. 

I personally want this issue to be open.

**Comment by lervag** [comment]
Then allow me to open a new issue (#726). Thus we can leave this issue closed. I'd say it is a good compromise. I think I've added the relevant context and information to the new issue, but feel free to add more context and details if I missed something.

**Comment by petRUShka** [comment]
Great idea. Lets move there.
