### ISSUE TITLE
Opt-in for quickfix warnings

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#671]
In addition to errors, I would like to see in the quickfix window only warnings about undefined or multiply defined labels or references. This is not really feasible using `vimtex_quickfix_ignored_warnings` since some classes and styles produce a lot of different warnings (`komascript`, I'm looking at you...)

Would it be possible to replace or augment `vimtex_quickfix_ignored_warnings` with a similar command that shows only the listed warnings (i.e., for those whitelisted warnings, `vimtex_quickfix_ignore_all_warnings` is overriden)?

**Comment by lervag** [comment]
I think this part is ready for some updates. I'm pushing an update soon that changes how to define which warnings to show. Please let me know what you think, both regarding the solution, and with regard to the default values.

**Comment by lervag** [comment]
So, the point now is to add one or more entries to the new quickfix warning setting that will give you the desired feature. Vims errorformat is not the easiest to work with, and it seems it is better to be specific.

So, if you could also provide a minimal example of the types of warnings you want to have control over, then that would be very helpful.

The goal is that you should get your desired setting through something like this:

```vim
let g:vimtex_quickfix_warnings = {
  \ 'default' : 0,
  \ 'undefined_reference' : 1,
  \ 'multiply_defined_references' : 1,
  \}
```

Note, here I used `default`. I'm thinking it is a better keyword than `disable`, since it would make it possible to change the default value of options from enabled to disabled.

**Comment by clason** [comment]
Yes, that is exactly what I am looking for (both regarding the interface and the actual settings)!

**Comment by lervag** [comment]
Great! I'll close this, then, but feel free to reopen if you find any problems. Also, feel free to open issues if you find uncatched warnings. :)
