### ISSUE TITLE
Unexpected behaviour of `tsd` with nondefault delimiter toggle modifiers

### ISSUE THREAD

**Issue by cedb12** [lervag/vimtex#681]
I wanted to replace the use of `\left` and `\right` in vimtex's delimiter modifier toggle with `\mleft` and `\mright` from the `mleftright` package. According to the documentation, this can be done by changing the `g:vimtex_delim_toggle_mod_list` variable. However, this makes the `tsd` mapping (`<plug>(vimtex-delim-toggle-modifier)`) misbehave: instead of toggling between unmodified and modified delimiters, it systematically adds `\mleft` and `\mright` to the delimiters even when they are already present.

Minimal `.vimrc` (I cloned the vimtex repository into `.vim` in a clean `$HOME`):
```vim
set nocompatible

filetype plugin indent on
syntax enable

let g:vimtex_delim_toggle_mod_list = [['\mleft', '\mright']]
```
Minimal LaTeX file:
```tex
\documentclass{article}
\begin{document}
\[
  \mleft( x \mright)
\]
\end{document}
```
When the cursor is placed at `x` and the user runs `tsd`, the line turns into
```tex
  \mleft\mleft( x \mright\mright)
```

**Comment by lervag** [comment]
Ok, so. I realized this won't work unless you also modify the list of accepted modifiers. This prompted an update where one can customize the detected delimiters. It seems to work well, and I'm pushing soon. It remains to document the new option.

To make it work, you need to set two options:

```vim
let g:vimtex_delim_list = {}
let g:vimtex_delim_list.mods = { 'name' : [
      \ ['\left', '\right'],
      \ ['\mleft', '\mright'],
      \ ['\bigl', '\bigr'],
      \ ['\Bigl', '\Bigr'],
      \ ['\biggl', '\biggr'],
      \ ['\Biggl', '\Biggr'],
      \ ['\big', '\big'],
      \ ['\Big', '\Big'],
      \ ['\bigg', '\bigg'],
      \ ['\Bigg', '\Bigg'],
      \]}
let g:vimtex_delim_toggle_mod_list = [['\mleft', '\mright']]
```

The first option, `vimtex_delim_list`, is a dictionary that defines various delimiter types, including the modifier pairs. This is used to create the various regexes, and in order to be able to toggle the `mleft/mright` pair, you need to add this pair also to the new option as above.

I will document it before I close the issue.

**Comment by cedb12** [comment]
Excellent, this works great now :)

There is a small typo in the documentation for `g:vimtex_delim_toggle_mod_list`: the example given for the `mleftright` use case has an extra closing brace at the end of the `g:vimtex_delim_list.mods.name` definition.

Thank you for the fix!

**Comment by lervag** [comment]
No problem, and thanks for noticing the typo. Fixed now. :)
