### ISSUE TITLE
g:vimtex_latexmk_options ignored? 

### ISSUE THREAD

**Issue by karolmie1** [lervag/vimtex#683]
I have only 2 requirements: 

1. Please redirect all output to `./out`
2. Please generate only dvi output

I've noticed the option `g:vimtex_latexmk_options`, and I've set it following way: 

```vim
let g:vimtex_latexmk_options=' -dvi -pvc'
```

For some reason every time I press compile (`\ll`) this darn thing stubornly generates pdf file to common folder.

I've also found `g:vimtex_latexmk_build_dir`. This did not help either!

It's like those options are totally ignored. 

I've tried using `.latexmkrc` but this did not work at all to (outside of vim it did of course). Well it kinda did, but plugin did not intercept the options, and ended up not finding the results, because they were in `./out` directory, instead of `./`.

Please tell me what I am doing wrong. 

Version: beb5d4eb59e65fd6436350e67dd10067342dc2c2
Installed by: vim-plug
Vim: neovim 0.1.7-2

**Comment by lervag** [comment]
Could you please provide a minimal example? That is,

1. A minimal tex file,
2. A minimal vimrc file (used with `vim -u minivimrc test.tex`), and
3. Steps to reproduce.

I could probably try to parse a minimal example from your post, but I have too much to do for the moment, so it will be a great help for me if you could supply the minimal working example. I think what you are trying to do should work.

Note: To set output dir, you should use `g:vimtex_latexmk_build_dir`.

**Comment by karolmie1** [comment]
Shit, when I will find just a bit of spare time I will work on that. For now I just use auto recompile outside text editor. I will reopen when I can investigate.

**Comment by tobanw** [comment]
I'm noticing this now too -- `g:vimtex_latexmk_build_dir` isn't being used. (I doublechecked that the option is set with `:echo g:vimtex_latexmk_build_dir`.) It must have been caused by an update sometime in the last few months. I have various projects where the build dir was working properly, but if I compile them now it doesn't work. I just updated to the latest version of vimtex.

A minimal example:
```tex
\documentclass{article}
\begin{document}
Doesn't use build dir...
\end{document}
```
Minimal vimrc, (using neovim and vim-plug):
```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'lervag/vimtex' "latex
call plug#end()
let g:vimtex_latexmk_build_dir = 'build'
```

**Comment by lervag** [comment]
There's been a change to the compiler feature, and all latexmk related options are now set through the dictionary valued option `g:vimtex_compiler_latexmk`. See the docs for details, but for the specifics here, this should work:

```vim
let g:vimtex_compiler_latexmk = {
    \ 'build_dir' : 'build',
    \}
```

**Comment by Neur1n** [comment]
Hi, I used vimtex maybe one or two years ago and I was able to make `g:vimtex_compiler_latexmk / build_dir` work on Windows. Recently I reinstall vimtex on my Ubuntu machine, but this option does not work for me anymore. I tried to set `$out_dir=./build` in `.latexmkrc`, the outputs did go into the build directory, but vimtex could not find the produced PDF via `<localleader>lv`. Any help is much appreciated.

**Comment by lervag** [comment]
Could you open a new issue, please? And provide a full minimal example?

**Comment by Neur1n** [comment]
After some debugging, I noticed that this issue was caused by vim-polyglot. I have noticed several old issues about vim-polyglot. Now everything works fine with your [suggestion](https://github.com/lervag/vimtex/issues/450#issuecomment-216110767). Sorry about the disturbance, and thanks for the work.

**Comment by lervag** [comment]
Great, happy to hear it works. :)
