### ISSUE TITLE
Add new text object: section (subsection, subsubsection, etc)

### ISSUE THREAD

**Issue by petRUShka** [lervag/vimtex#687]
### Explain the issue
There are following text objects at the moment:
```
  - ic ac Commands
  - id ad Delimiters
  - ie ae LaTeX environments              
  - i$ a$ Inline math structures   
```
I propose to add one more:
```
  - is as Sections (Subsections, Subsubsections, etc)
```

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\section

La-la-la

\subsection

----- Begin of subsection

some text 
----> CURSOR POSITION

\subsubsection
----- End of subsection
\subsection
La-la-la

\end{document}
```

I want `vis` to select text from `----- Begin of subsection` to `----- End of subsection`.

It is usually very useful text object (for example when you want to change notion inside one section)

**Comment by kiryph** [comment]
Since vimtex automatically defines fold for this, you can use https://github.com/kana/vim-textobj-fold and the textobjects `iz` or `az`.

Please note, `is` and `as` are  builtin textobjects for sentences (`:h is`). I would not advice to override them, even though they might not be used very often.

**Comment by lervag** [comment]
First, I think `is` and `as` would be unsuitable, both because they are already text objects for sentences, and because they are suggested text objects for [vim-sandwich](https://github.com/machakann/vim-sandwich).

Further, I think @kiryph has a good suggestion, that you can use `vim-textobj-fold` to get the desired text objects.

**Comment by kiryph** [comment]
@lervag I just realized that vimtex `ae` cannot be extended as I have described in my previous comment for the html tag textobject `at`. Would you consider improving your textojects to support this?

I add an example to illustrate this
```tex
\begin{itemize}
  \item 
    \begin{itemize}
      \item CURSOR
    \end{itemize}
  \item
\end{itemize}
```
Pressing `vae` selects
![textobject-ae](https://cloud.githubusercontent.com/assets/371756/23068499/3b027d16-f524-11e6-80d0-8bfdffe60f64.png)

When I now press `ae`, the visual area does not select everything which would be nice to have.

I think the same idea could be applied to nested commands and delimiters. Since inline math environments won't be nested, I guess it is not useful for this.

**Comment by andymass** [comment]
Hypothetical `vis` (visual inner section) is somewhat equivalent to `[]v]]` and `vas` would be `[[v]]`.  Since vimtex already provides square-bracket section motions, you might be able to wrap them with text objects.  Also check out [pandoc-sections.vim](https://github.com/gbgar/pandoc-sections.vim) for a similar feature (but in pandoc, not latex).

**Comment by lervag** [comment]
I've just pushed some bug fixes. These should make the `vaeae`, `vadad` and `vacac` work as expected. I'm a little bit unsure, though, if my recent commits also give unexpected behaviour. If so, please let me know and I'll fix it.

Also, thanks @kiryph for giving good information about vim-sandwich. I really like that plugin, and I will look into the new LaTeX buns.

**Comment by lervag** [comment]
Btw, @kiryph, I would be happy to hear if you have updated settings for LaTeX / vim-sandwich...

**Comment by kiryph** [comment]
### Extendable textobjects ac, ae, ad
Thanks for your update. After having a first look at following cases, vacac, vaeae, and vadad work.

```tex
\textbf{\emph{hello}}

\begin{itemize}
  \item 
    \begin{itemize}
      \item CURSOR
    \end{itemize}
  \item
\end{itemize}

$ \left( E = (mc^2) \right) $
```
That is really great!

Just for the record: my issue with `ac` regarding commands with several arguments (e.g. `\textcolor{red}{hello}`) which I have raised here https://github.com/machakann/vim-sandwich/issues/39 exists also for vimtex-textobject `ac` (except that vimtex handles square brackets such as `\chapter[toctitle with spaces]{title}`).

### On the topic of this issue: dedicated textobjects for sections:
Since  kana/vim-textobj-fold cannot be extended (vazaz), and often your cursor is in a math, list, or other environment and therefore you cannot directly address the current section/subsection/paragraph to do something with it,  it does not feel as 'razor-sharp' as other textobjects.
So I have actually changed my mind about this and would be in favour of a pair of textobjects for the sections.
One should recall that vim provides `ap` and `ip` for paragraphs. My suggestion to name such textobjects would be `aP` and `iP`.
@lervag What do you think? Are these good enough reasons (extendability and direct addressable) for new textobjects or do you think textobj-fold is sufficient?

**Comment by lervag** [comment]
I've pushed a PR that implements `aP` and `iP`. Please test. I would not be surprised if there are some minor issues, in particular with regard to edge cases. Let's continue the discussion there.

**Comment by petRUShka** [comment]
Great!

Thanks for changing your mind! @kiryph thanks for your very useful comments!

Sorry again for being out of discussion for a while.
