### ISSUE TITLE
<leader>ll and <leader>lv don't work

### ISSUE THREAD

**Issue by friolz** [lervag/vimtex#69]
I've installed the plugin, but <leader>ll or <leader>lv don't work.

At first the plugin also complained about not finding "latexmk" (I have latex-mk installed by Homebrew), but symlinking to "latexmk" seemed to have helped.

Unfortunately the compile and view commands won't work

**Comment by lucawrabetz** [comment]
I am having the same issue that @friolz had, but fixing `maplocalleader` was not the solution. 

Compiling the .tex files and generating the pdf in a terminal with `latexmk` and `pdflatex` are working fine. I am having the same issue where when I try a command such as `<leader>ll` or `<leader>lv`, vim immediately ignores the `<leader>` and executes a normal `l` or `v`, i.e. moving the cursor right or going into visual mode. I have tried setting both `mapleader` and `maplocalleader` to default, and I have also tried it with my usual remap of `<Space>`. In both cases, the result is the same. When I try another shortcut involving `<leader>`, it works (e.g. I have `<leader>w` remapped to `:wq`).

**Comment by lervag** [comment]
@lucawrabetz This issue was closed nearly 8 years ago. Whatever happened here is surely not relevant to your issue; VimTeX is more or less rewritten several times since then. Please, as a general rule, don't ask questions like these at the end of old issues. Instead, you should open a new issue and create a link to old issues that you think may be relevant.

Your problem is most likely thart you did not properly install VimTeX. As you do not provide any details, it is impossible for me to know for sure. So, please, open a new issue. Try and provide as much detail as you can.
