### ISSUE TITLE
Opening a .tex file is very slow when large number of other .tex files in the same directory

### ISSUE THREAD

**Issue by bartbkr** [lervag/vimtex#706]
### Explain the issue

I'm not sure if this functionality is intended or if this is a bug.
I frequently work in directories that contain large numbers of small files that
end in .tex. I've created an example set of files with the following python
script:

```python
for fname in [str(numb) + '_example.tex' for numb in range(500000)]:
    with open(fname, 'w'): pass
```

Every one of these files is empty. When I open any one of them with the vimrc
below, it takes a _very_ long time to open. I've waited minutes but still
haven't succesfully opened the file. I apologize if this directly related to
YCM, but it seems as though the combination of vimtex and YCM causes the issue.

### Minimal working example

Content of .tex files are empty.

### Minimal vimrc file

I couldn't quickly figure out how to use the rtp var to get the plugin mix
working, so here's my minimal vimrc using vim-plug.

```vim
call plug#begin('~/vimfiles/bundle')

Plug 'Valloric/YouCompleteMe'
Plug 'lervag/vimtex'

call plug#end()

set nocompatible

let g:tex_flavor = "latex"

filetype plugin indent on
syntax enable
```

**Comment by lervag** [comment]
This is not related to YouCompleteMe. I've added test files based on your example, and as you see, I only load vimtex.

The reason, though, is clear. Vimtex uses an automatic search for the "master" file if it can't find the `\documentclass` command in the current file. Thus it ends up searching through all the files, and when it becomes this many files, there is a delay.

However, I am not quite sure how to best resolve this. I don't really want to add more options...

**Comment by lervag** [comment]
I'm curious: What do you think is an appropriate solution here? First, do you understand the problem, that is, why starting vimtex is slow in your case. And do you understand the consequence of disabling the automatic search for a master file?

I think the only solution is to add an option, something like `g:vimtex_mainfile_detection_enabled` which will be true by default. Thus you could disable it to get a good startup time. However, when it is disabled, you would have to use a mainfile specifier for multifile projects. See `:h vimtex-multi-file`.

**Comment by bartbkr** [comment]
I agree with your proposed solution. It would be very useful to turn this functionality off using a flag and then specify the main file.

**Comment by lervag** [comment]
Ok, this should do the trick.

**Comment by bartbkr** [comment]
Great, thank you for your very prompt response!

**Comment by lervag** [comment]
No problem; thanks for describing the issue in a simple and reproducible way! :)

**Comment by Rmano** [comment]
Hi
Commenting here because I do not think that it's worth a new issue... following up on this new option, wouldn't be nice if it were possible to add a kind-of directory-local startup file? Like that if when I open a .tex file, if in the same directory there is a `vimtexrc` or whatever file, it is executed? 
`Latexmk` has a similar function and it's really handy at time.

**Comment by lervag** [comment]
Interesting remark. I think it could be worth a new issue. Perhaps you could open an issue and briefly write what you think such a `vimtexrc` file should contain? You say executed, but I don't think I want to execute it, because that immediately brings a security concern. Instead, I think it could be a json formatted settings file, for example, that could give project specific settings. But we would need to discuss some of the features and limitations, and I think that warrants a separate thread.

**Comment by Rmano** [comment]
Ok, opened #710
