### ISSUE TITLE
Force Zathura to use X11 Backend 

### ISSUE THREAD

**Issue by jayeshbadwaik** [lervag/vimtex#744]
### Explain the issue
When using nvim-qt on wayland, nvim-qt uses the XWayland backend, while the zathura pdf viewer uses the Wayland backend. This causes xdotool related functionality to fail to work.  This leads to creation of multiple zathura windows when viewing among other things. 

The zathura pdf viewer can be started with X11 backend by prefacing the command with the environment variable `GDK_BACKEND=x11`. However, I am not able to get this working by changing the line 

```vim
let l:cmd  = 'zathura'
```

to 

```vim
let l:cmd  = 'GDK_BACKEND=x11 zathura'
```

in `autoload/vimtex/view/zathura.vim`. This prevents spawning of new windows but the forward backward search do not yet work. 

1. Steps to reproduce:
     - Start nvim from a wayland session. Enable Livepreview with Zathura. 
     - Try to use forward/backward search and see multiple windows for zathura in forward windows. 

2. Expected behaviour: xdotool functionality should work properly.

Thank you for the nice plugin!

**Comment by lervag** [comment]
First, I'm sorry to say that I won't be fixing this issue personally. The reason is that I don't use Wayland, and it becomes too bothersome to install a system in order to work on this and for testing and so on.

However, I'm curious if we could find a workaround: Could you create an alias for zathura, or perhaps a wrapper script? Let's say you create the script `zathura`, something like this:

```sh
#!/usr/bin/bash

GDK_BACKEND=x11 zathura $*
```

Put this e.g. in `$HOME/bin` and ensure that this path is higher priority than the original `zathura` program. Further, ensure that `nvim-qt` has the same PATH variable. I would expect this to work better, perhaps even solve your problem?

**Comment by Rmano** [comment]
In the above script, substitute Zathura with the full path to avoid loops ;-). You also probably need to quote the argument(s) for spaces... 

```
#!/usr/bin/bash 
GDK_BACKEND=x11 /usr/bin/zathura "$@" 
```
You can also try to use `env GDK_BACKEND=x11 zathura` as a command --- in .desktop files, for example, plain "VAR=value" wouldn't work, whilst using `env` will. (Don't ask why).

**Comment by lervag** [comment]
Thanks, @Rmano! I've updated the script.

**Comment by jayeshbadwaik** [comment]
I can understand why you feel so. Thank you for your help. The suggested method works nicely for me.

**Comment by lervag** [comment]
Great! Happy to hear it :)

**Comment by paulrougieux** [comment]
In debian a `zathura` wrapper script containing:
```
#!/usr/bin/bash
GDK_BACKEND=x11 /usr/bin/zathura "$@"
```
Can be placed under the default user bin located at `~/.local/bin`.

**Comment by lervag** [comment]
Yes, this is a good solution. Obviously, one should ensure that `~/.local/bin` is in one's PATH (and with higher priority than system locations), which may or may not be the default on any given system.
