### ISSUE TITLE
VimtexCompileToggle no longer exists

### ISSUE THREAD

**Issue by delgrecoj** [lervag/vimtex#752]
Had the majority of my weekend thrown down the drain after updating Arch and my Vim plugins, and finding that vimtex kicks back errors about clientserver flags.  After losing all of Friday and most of today to solving the issue, either someone removed the flag from the AUR pkgbuild, or vimtex suddenly requires it when it didn't before.  Either way, I've now got Vim installed manually with the flag enabled.

After sorting that out (which I'm still raw about and don't have a good long-term solution for) I ran into more issues with vimtex.  Namely, the VimtexCompileToggle function no longer exists.  Apparently the functionality seems to have been merged into the VimtexCompile function, however the documentation still lists the VimtexCompileToggle function, which led me to waste significant time.

The documentation should be corrected, and ideally an alias function added to maintain backwards compatibility with peoples configuration files, given that people base them around function calls with the understanding this stuff will remain stable or warnings will be posted somewhere.

Breaking changes don't belong pushed to the master branch that people update from without special care being taken to inform them of changes they need to make.

**Comment by lervag** [comment]
@delgrecoj Do you realize how disrespectful and unfriendly your issue is? Do you imply that vimtex and I have had a part in "throwing your weekend down the drain"? Everything I do with vimtex is 100% free work that is done on my spare time. I share it because I think it is useful to others, and I try my best to respond to community requests.

I've fixed the documentation inconsistensy. I will not add an alias function for backwards compatibility. Vimtex is still actively developed and improved, and considering the fact that it is a one man job and a hobby project, I take the liberty of adding some breaking changes. I try to write about these in the changelog (see `:h vimtex-changelog`), but I admit I forgot about this one. This is also fixed now.

I really could not care less if you use vimtex or not, but if you do, I am more than happy to help you figure things out. I am also happy for feedback on bugs or things that don't work as expected, and I am happy to discuss feature requests. But please use a more friendly tone. If things do not work, it is not because I intend to annoy you. But it is _not_ my fault that you have wasted time. It is _not_ my fault that you have had your "weekend down the drain".
