### ISSUE TITLE
[feature] Enable the new vim jobs api for latexmk

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#766]
As part of an ongoing effort to improve the compiler layer, I have recently updated the latexmk interface to allow the use of the new asynchronous `job_start()` interface in Vim. This is currently disabled by default, but may be enabled through

```vim
let g:vimtex_compiler_latexmk = {
  \ 'backend' : 'jobs',
  \}
```

This should be enabled by default on newer Vim versions, but I must first ensure that it works as expected in general, and specifically on Windows (where it currently does not work).

Tasks:
- [x] Add support for neovim
- [x] Add and/or update documentation
- [x] Add support for Windows
- [x] Further testing

Feedback from users is (as always) appreciated!

**Comment by lervag** [comment]
I've tested this on Windows and Linux, and although there are probably bugs that I have not detected, it seems to work well both with the `process`, `jobs` and `nvim` (only Linux) backends, both for continuous mode and single-shot mode, with and without callbacks.

I'm marking this as completed, with the assumption that other users will report bugs if they find any. :)

**Comment by clason** [comment]
Seems to work fine on Mac as well (MacVim and neovim both) -- nice job (pun intended)!

**Comment by lervag** [comment]
Thanks (pun appreciated)! :)

**Comment by clason** [comment]
Hmm, this seems to have possibly been broken recently with neovim: While a continuous compilation run is going on, neovim (or maybe just vimtex?) is not fully responsive. For example, `gg=G` has the same effect as `ggG` (i.e., it works as cursor motions, but does not indent). 

A maybe related issue is that backward sync no longer works if the buffer is modified but not written. (This kinda makes sense since the target is no longer valid, but in practice the modifications are small enough that it's sufficiently close; the new behavior is kinda annoying if you want to make many small changes across a document.)

Should I open a new issue (and if so, any hints on what I could look at before to make it informative)? Or does this sound like an issue with `nvr`?

**Comment by lervag** [comment]
Could you open a new issue, please? I don't think this is related to new development, but of course I could be wrong. Thus I would not be surprised if this could be due to an update with `nvr`.

**Comment by clason** [comment]
Sure! I just wanted to make sure I'm not barking up the wrong tree. I opened two issues since they're possibly not related; the second one indeed sounds more like a neovim-remote issue, but the first one seems more "internal" to neovim since only part of the command is not working. So it's either a bug in neovim (but nothing in the commit history or the issue tracker seems related) or the way the API is used for asynchronous compilation in vimtex. It *might* be related to https://github.com/neovim/neovim/issues/6166?

**Comment by lervag** [comment]
Thanks, I'll investigate when I get the time. I'll make a note of the neovim issue in the relevant thread.

**Comment by lervag** [comment]
Sorry, I see you already did...
