### ISSUE TITLE
New command completion: be case insensitive

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#794]
My [original dictionary completion](https://github.com/lervag/vimtex/issues/650#issuecomment-273788871) example for `$\right` showed also the candidates `\Rightarrow` and `\Rrightarrow` which is not the case right now. I can get the uppercase variant when I already use the upper leading R.

IMHO this is helpful to see variants you might be interested in.

Another issue is that I do not see `\Rrightarrow` even though I added the package `amssymb` and the file `amssymb` with the correct entry exists.
```tex
\documentclass{article}
\usepackage{amssymb}

\begin{document}
\R
\end{document}
```
Pressing `<Leader>li` does not list any packages.

**Comment by lervag** [comment]
The first part: If `\right` should include `\Rright`, then the regex filter can not be anchored. I anchored it after one of your comments, because it seems natural that one starts to type the start of a command. However, I agree that we can make the filter case insensitive.

The second issue is a separate issue. However, I can't reproduce it. That is, it works as expected for me. Note that the list of packages is only parsed when initializing.

**Comment by kiryph** [comment]
Sorry, the second issue was again an outdated neocomplete menu. Pressing ctrl-x ctrl-o revealed all the candidates.

**Comment by lervag** [comment]
Ah, yes. Neocomplete does not work perfectly when there are very many completion candidates. The `refresh_always` option works, as you say, but I keep it off for the same reason you mention.
