### ISSUE TITLE
Recognize the "pipe inclosing" as "inline verbatim structure"?

### ISSUE THREAD

**Issue by llinfeng** [lervag/vimtex#808]
### Explain the issue

Currently, `ci|` does not yield comparable outcome to `ci$`. That is, we don't have a "inline verbatim structure" ready in place. 

### Minimal working example

Maybe it is outdated, but the way I represent a variable in my tex document is to use `\verb|var_name|`. I think this structure is comparable to the "inline math structure", and the difference is just by the delimiter/identifier for the "environment/structure". 

### Feature request
To enable `ci|`, for recognizing the "inline verbatim structure".

**Comment by lervag** [comment]
Actually, I don't want this, because it is already provided by other plugins such as [targets,vim](https://github.com/wellle/targets.vim). This plugin is so good I think it is not worth it to duplicate the features. See [here](https://github.com/wellle/targets.vim#separator-text-objects) for the relevant text objects provided by targets.vim.

Another reason I don't want it is because `\verb+xxx+` would be equally correct. Adding this `ci|` feature would either become complex (in that it would need to detect the delimiter, be it `|` or `+` or whatever), or it would assume the user did things in particular manner.

I hope you will agree that this is the right decision, that is, that the feature is not needed due to targets.vim.

**Comment by llinfeng** [comment]
@lervag Thank you for pointing out the specialized plugin and I do agree with your decision.
