### ISSUE TITLE
vimtex warning: Can't use callbacks without +clientserver Press ENTER to continue

### ISSUE THREAD

**Issue by hanqing0521** [lervag/vimtex#822]
```
vimtex warning: Can't use callbacks without +clientserverPress ENTER to continue
```

I am not  a fresh man for using vimtex, i disable the callbacks function in my .vimrc, it work well before upgrade.

**Comment by lervag** [comment]
Please read the issue template and provide a more complete description!

I suspect this issue is due to you recently having upgraded, but since you have not provided _any_ details, it is impossible for me to say why you get this message. You might probably come far by reading `:h vimtex-latexmk` and `:h g:vimtex_compiler_latexmk`. Also, you should note that the callback feature is enabled by default. If you run Vim in terminal, it will not by default activate the clientserver feature. See `:h vimtex-requirements` about the `clientserver` requirement.

I'm closing this, feel free to reopen when you have provided more detail.
