### ISSUE TITLE
nevoim conflict with <plug>(vimtex-reload)

### ISSUE THREAD

**Issue by malikbenkirane** [lervag/vimtex#824]
### vimtex-reload is in conflict within NVIM

I used dein package manager to install vimtex and it's working great. But in the case I call vimtex-reload, a lot of stuff is messing. For example : 

- overrides the text of vim-airline
- prints out errors about colorschemes (vim-airline-theme or custom vim colorschemes)

I'm wondering how calling vimtex-reload causes all these bugs.

**Comment by lervag** [comment]
I have no reason why the reload causes these bugs. Can you please provide a minimal example?

Note: The reload command is really meant for debugging, and you should not need it for anything.

**Comment by malikbenkirane** [comment]
### a case

I'm splitting a lot my tex files in different directories. Viewer and cross-referencing are not always well refreshed (and i am ignoring the reasons) but on top of a cleaning or a full cleaning, I sometimes reload vimtex.

> That sometimes made MacVim crash and i'm unable to set `v:servname` option using vim (with `+clientserver`)

Therefore, I'm migrating to neovim with some more reasons. Here is a minimal example :

### minimal example 

> 0a. installed vimtex with [dein.nvim](https://github.com/Shougo/dein.vim)
```call dein#add('lervag/vimtex')```
> 0b. take a coloscheme, e.g., mhartington/oceanic-next, and vim-airline/vim-airline-themes
```
call dein#add('mhartington/oceanic-next')
call dein#add('vim-airline/vim-airline-themes')
```
> 1. open a tex file (assuming `g:tex_flavor = 'late'`)
> 2. nothing happens with vimtex-compile
```
:VimtexCompile
> compiler: started continuous mode
:VimtexStatus
> compiler: not running
:VimtexCompileSS " OK
```
> 3. `:VimtexReload`
```Error detected while processing Error detected while processing $HOME/.config/nvim/bundles/.cache/init.vim/.dein/autoload/airline/themes/base16_seti.vim:
line    4:
E121: Undefined variable: g:airline#themes#base16_seti
E488: Trailing characters

...

E121: Undefined variable: g:airline#themes#base16_seti
E488: Trailing characters
Error detected while processing $HOME/.config/nvim/bundles/.cache/init.vim/.dein/autoload/lightline/colorscheme/oceanicnext.vim:
line   39:
E117: Unknown function: lightline#colorscheme#flatten
E15: Invalid expression: lightline#colorscheme#flatten(s:p)
Error detected while processing $HOME/.config/nvim/bundles/.cache/init.vim/.dein/autoload/lightline/colorscheme/oceanicnextlight.vim:
line   39:
E117: Unknown function: lightline#colorscheme#flatten
E15: Invalid expression: lightline#colorscheme#flatten(s:p)
```
```vimtex: reloaded```

### suggestions ?

I'm clearly a beginner and not an expert in terms of vim scripting and I'm unable to understand clearly the differences between vim and neovim. For example what are the reasons why neovim doesn't run your scripts. I didn't found a specific port yet and I'm migrating to [auctex](https://www.gnu.org/software/auctex/) for rescue.

**Comment by lervag** [comment]
Neovim works well with vimtex. I'm using vimtex in neovim myself. I'll look into your issue.

Note, though, that your description has several errors. Please check them:

1. You say things don't work in MacVim, then you write `v:servname`, but you need `v:servername`. To make Vim work from terminal, you need to start it with `vim --servername SOMENAME`. There are plenty of resources online that explains this in more detail. Vimtex should work as expected with the clientserver also on MacVim.

2. You write `g:tex_flavor = 'late'`, I guess you mean `'latex'`?

3. After `VimtexCompile`, the status should return running. This works as expected for me in minimal examples as well as my own config. If it does not for you, then I think there are more things that are wrong.

4. Your minimal example is _not_ minimal, and it is _not_ complete. I would much prefer that you do not provide a minimal example that employs a plugin manager, since that adds a new layer where things may go wrong. But I'll accept it. But your example is not complete. Please provide a _full_ minimal vimrc file that uses `dein` and that loads the necessary plugins. Based on your post, I extract the following vimrc file:

    ```vim
    set runtimepath+=dein.vim

    if dein#load_state('plugins')
      call dein#begin('plugins')
      call dein#add('lervag/vimtex')
      call dein#add('mhartington/oceanic-next')
      call dein#add('vim-airline/vim-airline-themes')
      call dein#end()
      call dein#save_state()
    endif

    filetype plugin indent on
    syntax enable

    let g:tex_flavor = 'latex'
    ```

    But I am not sure if this is what you meant.

**Comment by lervag** [comment]
Feel free to reopen if/when you provide more information that I can use to reproduce your issue.
