### ISSUE TITLE
VimtexCompile and VimtexCompileSS behave differently in case of warnings

### ISSUE THREAD

**Issue by heiderich** [lervag/vimtex#826]
### Explain the issue

When a warning occurs during compilation the output of VimtexCompileSS is "fail", while the output of VimtexCompile is "success".

1. Steps to reproduce

Run :VimtexCompile and :VimtexCompileSS on a document that produces a warning but no error during compilation.

2. Expected behaviour

The same behaviour in both cases, either success or fail. I guess "success" would be preferable.

3. Observed behaviour

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass[a4paper,11pt]{memoir}
\begin{document}
\ref{does_not_exist}
\end{document}
```

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The following
should often suffice:

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable
```

**Comment by lervag** [comment]
The reason is that the `VimtexCompile` will (by default) run with callback feature enabled. The callback will be run with either a success or fail status flag. And this flag may be success even if there are some warnings. Thus it reports `success`. However, the `VimtexCompileSS` needs to check for errors manually, and at the moment it simply checks if there are quickfix entries or not.

I think one solution is to make `VimtexCompileSS` check for errors in the quickfix list explicitly, and report success if there are no errors. Do you agree with this?

**Comment by heiderich** [comment]
Yes, I would prefer if VimtexCompileSS would also check for errors in the quickfix list and report success if there are no errors.

**Comment by lervag** [comment]
Done. :)
