### ISSUE TITLE
Allow creation of map to open viewer without performing forward search

### ISSUE THREAD

**Issue by andymass** [lervag/vimtex#837]
This may be somewhat related #313, #836 but is more of an independent feature request.  

The request is simple; I would like the ability to (sometimes, not always) use `\lv` or `VimtexView` without doing a forward search.  The immediate reason for this is that over a slow link, vimtex occasionally opens zathura twice, once to spawn it and again to do a forward search (which opens a new instance).  I can't reliably reproduce this and I have no minimum working example.  I notice it only happens when using X forwarding, and increasing the delay [here](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/view/common.vim#L120) removes the issue.

However, the request may be useful for other reasons- you may simply want to spawn the viewer without searching (I often want to open the viewer immediately after opening my tex file).

The ideal thing would be to expose variant mappings/commands such as `\lV`, `VimtexView!` and `vimtex-view-no-forward-search` (just hypothetical examples).

**Comment by Tyrn** [comment]
500 milliseconds! That explains a lot. No go on my ancient laptop.

**Comment by lervag** [comment]
Assuming I was able to fix the problem in Zathura: do you see an immediate use of this feature? I've personally never seen the need for this, which is why it is not there already.

**Comment by lervag** [comment]
@Tyrn What are you replying to here?

**Comment by lervag** [comment]
I was actually able to reproduce this now. The problem is actually due to Zathura. I was able to stop compilation at a point where the pdf file is not completed and thus is corrupt. In this case, if I start zathura on the terminal, then do a forward search, also on the terminal (thus, vimtex is not involved), I get the following error:

```
error: Failed to query 'filename' property from 'org.pwmt.zathura.PID-14125': GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code0: No document open.
```

Zathura then continues to open a new viewer instance, but since the pdf is corrupted, the same problem occurs.

I'm looking into finding an alternative approach.

**Comment by Tyrn** [comment]
I'm replying to **andymass**,  "I notice it only happens when using X forwarding, and increasing the delay [here](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/view/common.vim#L120) removes the issue."

**Comment by lervag** [comment]
I just pushed a commit that should prevent the duplicate zathura windows. The reason for the duplicate windows were that the viewer start and forward search both opened a window. I've now combined this, so that starting the viewer also simultaneously does a forward search. If the pdf is corrupt, there will only be a single viewer window opened. However, the viewer window will not "work", so the next time you try to open or do a forward search, it will open a new zathura window again. I think this is the best possible solution.

**Comment by lervag** [comment]
Sorry, @Tyrn, I didn't notice the link on the `here` word; i.e., I didn't read the OP good enough. Anyway, I think I've replied to and done as much as possible in this regard now. I hope you agree that things now work acceptably good with zathura.

**Comment by andymass** [comment]
@lervag, thanks for the fix!  I didn't expect this particular diagnosis of the problem but am happy if it is resolved.  I will update if I notice it happening again on a slow link.  

Regarding the request, is there already a way to simply open the viewer without forward searching?  The immediate use is the following: when I boot up vim on `file.tex`, I usually press `\lv` to open the pdf next to it.  This does open the pdf, but also performs a forward search to whatever happens to be on the line of the cursor.  Since I am merely opening the file and have not started editing yet, I do not want it to go to any particular location.  Any further invocations of `\lv` would be a deliberate forward search.

**Comment by lervag** [comment]
I see your point. How about this: We let forward search be optional on viewer start. I'll add an option, default on (since that is the current behaviour), that you can disable to make the first `\lv` only open the viewer.

That is, I propose to add:

```
*g:vimtex_view_forward_search_on_start*
  If disabled, the first invocation of the viewer will not perform a forward
  search to the current cursor position.

  Note: This option is only relevant for the following view methods (see
  |g:vimtex_view_method|):
    'mupdf'
    'skim'
    'zathura'

  Default value: 1
```

**Comment by andymass** [comment]
I think this proposal would fit my needs well (assuming your implementation burden is not too great).  I am curious, if I were to close zathura would the next `\lv` be considered a "first invocation?"

**Comment by lervag** [comment]
Yes, it would. I'll update when I get the time! :)

**Comment by lervag** [comment]
Let me know what you think after testing the new option.
