### ISSUE TITLE
``$`a$`` can't expand to `$\apha$` in a long docucment

### ISSUE THREAD

**Issue by vanabel** [lervag/vimtex#838]
With the following settings in my _vimrc:

```vim
call plug#begin('$Vim/myvim/plugged')
Plug 'lervag/vimtex'
Plug 'Konfekt/FastFold'
call plug#end()

let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options
      \ = '-reuse-instance -forward-search @tex @line @pdf'
      \ . '-inverse-search "gvim --servername ' . v:servername
      \ . ' --remote-send \"^<C-\^>^<C-n^>'
      \ . ':drop \%f^<CR^>:\%l^<CR^>:normal\! zzzv^<CR^>'
      \ . ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'
      \ . ':\%l^<CR^>:normal\! zzzv^<CR^>'
      \ . ':call remote_foreground('''.v:servername.''')^<CR^>^<CR^>\""'
```

in the newest version of `vimtex`, is there any possibility that `` $`a$`` is not auto-complete to `$\alpha$` for a long document (>1500 lines)? which is quite strange it work at some position (before line 1000) but not work for other position (after 1100 lines), and after a while it work for any position. My OS is windows7 and the environment is the same as above but with long tex document.

Also, there are force close (quite frenquently) with the error message: 

> : Send expression failed.

**Comment by lervag** [comment]
First, regarding the last part: I don't understand what you mean with "force close". Do you mean that gvim crashes and quits (I assume you use gvim since you are on windows7)? I have never seen the mentioned error message before, and I doubt this is due to vimtex. In any case, if it is a problem with vimtex, then I need much more information in order to figure out what it is. If I can't reproduce the problem, I most probably will not be able to solve it.

Regarding the `` `a `` expansion: First, I prefer calling it an expansion rather than completion, because this is not a feature that (auto) completes anything. Instead, it is a feature that expands a mapping/abbreviation. This is way it is called `:h vimtex-imaps`. Now, again it is very difficult to work on a problem if I can not get an example that reproduces this. Could you give a sample LaTeX file, e.g. filled with "lorem ipsum" or similar to the necessary length, and then the exact steps to reproduce the problem?

_Note: I took the liberty of stripping unnecessary comments from your vimrc sample._

**Comment by vanabel** [comment]
I believe that the problem is I use the wrong version of `phtyon` and `perl`, in fact I install both of them by `cygwin` which seems not so compatible with `gvim`. After I install the windows 32bit version of `python` and `perl` with the **exact correct version (3.5 for `python` and 5.4 for `perl`)**, the crashes never happens again.

For the non expansion problem, it seems related to the plugin `vim-shell`, I use it to toggle fullscreen of gvim on windows. After I remove it, the expansion works without no problem. 

Thanks for your great plugin and helping me to figure out the problem.

**Comment by lervag** [comment]
I'm happy to hear that your problems are solved and that you like the plugin! :)
