### ISSUE TITLE
Vimtex incorrectly resets chapter count on part

### ISSUE THREAD

**Issue by DelusionalLogic** [lervag/vimtex#850]
LaTex doesn't reset chapter count when it starts a new part, Vimtex does though. That's unfortunate since it creates a disconnect between the heading numbers you see in the compiled document, and the toc vimtex generates.

The document below shows a toc like
```
Preamble
1 Chapter 1
1 Part 1
1.1 Chapter 2
```

What i'd expect to see:
```
Preamble
1 Chapter 1
1.1 Part 1
1.2 Chapter 2
```

The example document:
```tex
\documentclass{report}
\begin{document}

\chapter{Chapter 1}
Hello from Part 0

\part{Part 1}

\chapter{Chapter 2}
Hello from part 1

\end{document}

```

**Comment by lervag** [comment]
FYI: This is related to #811, who proposes an option `g:vimtex_toc_reset_chapter_count_per_part` which, if enabled, will reset the chapter count for each part.

Before I update anything, I would be happy if we could agree what is the most natural behaviour, since this should the default behaviour.

**Comment by lervag** [comment]
@kiryph Feel free to add your 2cents.

**Comment by kiryph** [comment]
I agree with @DelusionalLogic w.r.t. to chapter numbering. I would prefer that the chapter numbers are NOT reset for a new part. Since this is the latex default, I would argue that the same should be true for vimtex.

However, I would prefer roman numbering for parts and I think there is no need to add the part number before the chapter. It should look like this:

```
      Preamble                                                                                                                                    0
I     First part                                                                                                                                  0
1   Hello                                                                                                                                       1
1.1 First section in chapter 1
2   World                                                                                                                                       1
II     Second part                                                                                                                                 0
3   Hello                                                                                                                                       1
4   Mars       
```

What options are necessary to make everyone happy, is not clear for me.

Right now, I would use latex defaults. The only option I would possibly enable for one of my documents would be `g:vimtex_toc_reset_chapter_count_per_part`. However, I could live without this.

**Comment by DelusionalLogic** [comment]
I agree with everything @kiryph just said.

The part number of the identifier would indeed be superfluous, and roman numerals would be a great differentiator.

**Comment by lervag** [comment]
Ok, I've fixed this now. Currently, no option, but the default should now work as you've suggested.
