### ISSUE TITLE
gf for \subimport{directory/}{file}

### ISSUE THREAD

**Issue by heiderich** [lervag/vimtex#859]
### Explain the issue

1. Steps to reproduce

Suppose you use the import package and import "file.tex" from the subdirectory "directory" using the command

`\subimport{directory/}{file}`

Then move the courser to "file" and type "gf" in normal mode.

2. Expected behaviour

I would consider it desirable if vim would open the file "directory/file.tex".

3. Observed behaviour

The error:  `E447: Can't find file "file" in path`

**Comment by lervag** [comment]
Note to self: I can use the test case for #841 for this issue.

**Comment by lervag** [comment]
I've pushed a "fix" for this. Note, though, that since I'm using the `includeexpr` and the internal `gf` command, you might be surprised by the behaviour. First, if you have a file `test.tex` in the current folder, and a file `subdir/test.tex` that you include with `\subimport{subdir/}{test}`, then `gf` will match the file in the current folder. The only way to get around this is to overload `gf` with a custom map.

I am not sure that I want to do this, though. For now at least, I think the current solution should work, as long as you use different names for the different files.

**Comment by heiderich** [comment]
Thanks. I think that for most cases this is good enough.

**Comment by lervag** [comment]
Great! :)
