### ISSUE TITLE
Command `\lv` doesn't open zathura, opens firefox instead

### ISSUE THREAD

**Issue by Ryunaq** [lervag/vimtex#869]
Executing the command `\lv` triggers a wine error and opens the .pdf in my firefox browser. I think that for some reason `\lv` triggers opening some file in one of my wine folders before trying to open the pdf.

The error message is as follows:

```
    wine: invalid directory "/home/xxxx/winefolder" in WINEPREFIX: not an absolute path
    /usr/bin/xdg-open: line 854: x-www-browser: command not found
```

I don't have much about vimtex on my .vimrc, relevant stuff is:

```vim
    let g:Tex_DefaultTargetFormat='pdf'
    let g:vimtex_view_enabled=1
    let g:vimtex_view_automatic=1
    let g:vimtex_view_general_viewer = 'zathura'
    let g:vimtex_view_method='zathura'
```

Something curious is that `:VimtexView` actually works well, isn't that same command mapped to `\lv`?

Thanks.

**Comment by lervag** [comment]
I am pretty sure that your problem is that you have both vimtex and vim-latex (a.k.a. LaTeX-Suite) installed. These plugins do not combine well. I suggest that you remove vim-latex.

Note that some people, for some reason, suggest that you install vim plugins through the system package manager. This is _very_ silly, and will only lead to trouble. Thus, even if you think you might not have loaded other LaTeX plugins, you still might have them loaded implicitly through a system installed plugin. To check this, you can scan the result of `:scriptnames` to see which Vim plugins are loaded for a given LaTeX file. It should mainly be vimtex, but in your case, I am pretty sure that you have other LaTeX plugins as well.

You can also see what `\lv` is mapped to with `:map \lv`. I bet you that it is not mapped to anything that contains vimtex.
