### ISSUE TITLE
Search for main file needs to be repeated before starting latexmk

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#879]
### Explain the issue

The search for the latex main file seems to be executed only when a buffer is opened for a file. This prevents the following (which I do quite often when creating new chapters) from working correctly. It assumes there is a `main.tex` file with working tex structure.

1. Create a new file, e.g. for a new chapter: `:sp`, `:e chapter.tex`
2. Add some content to this file and `:w`
3. Updated the `main.tex` file to `\include{chapter}`.
4. In the buffer for `chapter.tex`, start compilation via `<Leader><Space><Space>`

vimtex will invoke the compiler on `chapter.tex` and not the main file because when the buffer was opened, there was no connection between the documents and the check is not performed again before compiling.

As I am having a `latexmain` file, this is another example for why I think that the reachability check shouldn't be used here (cf. #871). This issue can probably be solved by re-triggering the main detection before starting the compiler.

### Minimal vimrc file

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
```

**Comment by lervag** [comment]
Thanks, I've fixed this now I think. Let me know if I missed something or misunderstood.

**Comment by languitar** [comment]
Thanks. Are you sure that this is the right fix for every use case? If I didn't have a latexmain file, I would still end up in a situation where the included file is compiled because the main file detection is not repreated.

**Comment by languitar** [comment]
Or maybe I misinterpreted the fix. Let me check that.

**Comment by lervag** [comment]
My fix was to let the `.latexmain` specify the fallback main file if no other main file was found. Thus, if one finds a `.latexmain` file, this will be used even if it does not include the current file. But only if no other located main file includes the current file. I think that makes sense.

**Comment by languitar** [comment]
Right, but if I just don't have a latexmain file and create a buffer the way I described it, which is only connected to the main document after it was created, I am still screwed, right?

**Comment by lervag** [comment]
Yes, correct. But in my opinion, rightly so (at the moment). Because there is no way to know which main file should include the current file.

My suggestion is either

1. I add a light variant of the "VimtexReload" function that only reloads the state for the current buffer, or

2. You change the way you add new files to your project: First include the file in the , then create it. I.e., move your step 3 from the OP before step 1.

If you would accept suggestion 2, we would not need more code, which I think is for the best.

Although, it does seem like `VimtexReload` (or `\lx`) actually works as my proposed alternative 1 above already, even though it really resources all of the code. It might have some side effects that I have not thought about.

Let me know what you think.

**Comment by languitar** [comment]
And just reloading things automatically before starting compilation is not an option? At least if it is the first time I am compiling a buffer? Somehow it just feel wrong that I cannot "start compiling in any file of the project" just because I made a special move of opening and writing some stuff.

**Comment by lervag** [comment]
No, reloading before we start compilation is not an option.

Personally, I still think that the present behaviour is OK. What you are asking is that vimtex should detect which project a new file belongs to even if there is no way of detecting it.

However, I just realized there might be one more alternative. Consider this:

1. You work on some project. It has a vimtex state.

2. You open a new, empty file that you want to add to the current project. Vimtex tries to find the correct main file (i.e., correct project), but since no main file currently includes it, and since there is no `.latexmain`, the current behaviour is to define a new project/new main file with the current (new) file.

3. Instead: Before falling back to using the current file, we could look at the alternate file (see `:h alternate-file`). If the alternate file is connected to a vimtex state, then we could fallback to this instead.

What do you think about that?

**Comment by languitar** [comment]
Sounds more like hack to me. My usual workflow is to only have a single latex project per vim instance. In these cases any of the available solutions now will work (latexmain or buffer). However, if there are really people who use multiple projects in parallel in the same vim instance, they might get trapped by this behavior because alternate file might be a file from another project which is open in parallel.

**Comment by lervag** [comment]
Yes, you are right. But in the parallell project case, you would be screwed regardless. The only thing that would work consistently would be to reload vimtex in the new file/buffer after it was properly included in one of the projects.

I think rather than calling it a hack, I would say it that the proposed solution makes an assumption. The assumption might fail if one works on two projects in parallell, but I think this will not often be the case. Thus I think it could make sense to implement it as a second fallback. However, I won't insist on this; the current version of vimtex works fine for me, and I don't need this fallback myself.

**Comment by languitar** [comment]
I don't need that either after the other fix you made. I am just not happy that it doesn't look consistent in all cases ;-)

**Comment by lervag** [comment]
Ok. I'll leave things as they are now, then.
