### ISSUE TITLE
VimtexClean seems not working

### ISSUE THREAD

**Issue by Weiming-Hu** [lervag/vimtex#880]
Hi there. I'm having problems with both the commands `VimtexClean` and `VimtexClean!`. They are supposed to delete the extra files like `*.log`, `*b.blg`, and so on. However, when I run `:VimtexClean` or `:VimtexClean!` inside my vim, the process succeeds but those files are still there. What's even more strange is that the compiled pdf will be opened automatically.

Here is the screenshot if it helps.

![screen shot 2017-06-21 at 5 42 01 pm](https://user-images.githubusercontent.com/16421338/27411135-1251c606-56a9-11e7-8b24-0decb6decef1.png)

Thank you.

**Comment by Rmano** [comment]
Are you sure you do not have `latexmk` running in background? Try `<localleader>ll` to see what it says. 

For the complete cleaning I have this in my `~/.latexmkrc`: 

```
push @generated_exts, "cb";
push @generated_exts, "cb2";
push @generated_exts, "spl";
push @generated_exts, "nav";
push @generated_exts, "snm";
push @generated_exts, "tdo";
push @generated_exts, "nmo";
push @generated_exts, "brf";
push @generated_exts, "nlg";
push @generated_exts, "nlo";
push @generated_exts, "nls";
push @generated_exts, "synctex.gz";
push @generated_exts, "tex.latexmain";
push @generated_exts, "run.xml";
```

**Comment by Weiming-Hu** [comment]
It looks like I need to first stop the `latexmk` and then run the `clean` method. Then everything works. If I just run `<localleader>ll` and then run `<localleader>lC` the above issue will occur.

Thank you!

**Comment by Weiming-Hu** [comment]
So I think the `clean` is working. But I don't understand why there is this issue. Do I need to stop the `latexmk` manually everytime I want to clean my directory?

**Comment by Rmano** [comment]
Because your `.tex` files depends on the `.aux` and other files; so if you delete them, the running `latexmk` logic thinks that it has to recompile your document (correctly, btw) , and the various files will be generated again...

**Comment by Weiming-Hu** [comment]
Thank you. This is very helpful.

**Comment by lervag** [comment]
Thanks, @Rmano, for helping out! Just to fill in: The point is that the standard behaviour of vimtex is to turn on/off continuous compilation. Thus, if you turn it on with `\ll` or `VimtexCompile`, then a subsequent `VimtexClean` or `\lc` would first clean all files, then continue to compile the documents as usual. This does not "allow" that the document is not compiled, and so it is to be expected that the output files are regenerated.

If you want to keep you directory "clean", I suggest you look at the `build_dir` setting, e.g. see `:h vimtex_compiler_latexmk`. This allows to define an output directory where all generated files are put when compiling.

**Comment by clason** [comment]
One thing that `vimtex` could do is for `VimtexClean` to check if continuous compilation is running and stop it before cleaning. Depending on what the actual intention is, that might -- or might not -- be the expected behavior. I see two use cases for `\lc`:

1. I'm done for now; I want to stop compilation and clean up my workspace. In this case, having `\lc` terminate first would be convenient.

2. Something went wrong; I want to delete all auxiliary files and start over. In this case, having `\lc` terminate first would be inconvenient, because I'd have to manually restart continuous compilation.

The current status quo is better adapted to 2. (although I usually explicitly stop, clean, and restart; possibly after first trying to compile via the command line to see the full output) than 1., but no option is clearly better. 

Possible concrete suggestions:

1. Make the behavior controllable via an option (e.g., `vimtex_stop_before_clean`).
2. Provide a new function `VimtexStopClean` which people can map to `\lc` if they prefer that behavior (or something different if they want to have the choice -- maybe `\lS`?)
3. Point out explicitly in the documentation that files will of course be immediately regenerated if `VimtexClean` is called while continuous compilation is running.

**Comment by lervag** [comment]
As you also note, I've currently implemented case 2. When I implemented it, I sometimes "needed" this. But I am not quite sure if it is the most intuitive case.

I don't want an option for this, because I think we should avoid options unless necessary.

My preference is that we decide which case is the most intuitive, and then either switch or perhaps add a minor comment to the docs to clarify.

**Comment by clason** [comment]
My vote is for the lazy option (do nothing, or add a minor comment) :)

**Comment by Rmano** [comment]
Moreover, if you prefer the "stop and clean", shouldn't be that as easy as to redefine `\ls` as executing `VimtexStop` and then `VimtexClean`? (I am too lazy now to see at exactly how to do this)...

**Comment by lervag** [comment]
Yes, @Rmano. You could do that. Something like this should work:

```vim
nnoremap \lc :VimtexStop<cr>:VimtexClean<cr>
```

**Comment by habamax** [comment]
In win10 no files are removed when I use `:VimtexClean`.

**Comment by habamax** [comment]
For me it looks like this, @lervag :
![vimtex-clean-issue](https://user-images.githubusercontent.com/234774/130083391-33908fac-d94d-42e4-a4dd-dd261c840121.gif)

I was expecting `VimtexClean` to remove at least some files :)

**Comment by lervag** [comment]
> In win10 no files are removed when I use `:VimtexClean`.

Hi @habamax; this thread is more than 4 years old. Can you please open a new issue and describe your problem in more detail?
