### ISSUE TITLE
Movements and text objected defined by blank comment lines

### ISSUE THREAD

**Issue by tschijnmo** [lervag/vimtex#898]
A lot of LaTeX users seem to have the habit of using blank comment lines to separate special parts of paragraphs.  For instance, for an inline or display equation complex enough, it might frequently be written as

```
...Texts...
%
\[
    A display equation
\]
%
...more texts...
%
\(
    An inline equation
\)
...the remaining texts...
```

When this style is used, it might be have convenient to have some motion commands like jumping to the previous/next part, like the built-in `{` and `}` command, but with empty comment lines taken as delimiter as well.

This issue is related to issue #436, where there is still an unchecked item for possible environments where line-joining is automatically suppressed.  With motion or text objects defined by this, maybe we can have an unopinionated way of handling that unchecked box.  Maybe the parts not intended to be reformatted, like a large equation with its own indentation and line break, can simply be put between pairs of empty `%` lines.  Then by something like `gq` + the text object to be defined, the part of the paragraph up to the special environment can be reformatted.  At the same time, something like `gqap` could be use to reformat the entire paragraph across the boundaries.

Any comment or pointer for contribution is deeply appreciated.

**Comment by lervag** [comment]
You say "A lot of people", but I have never seen this myself. Just saying.

The motions you ask for are quite easy to add, for instance the following would sort of work:

```vim
nnoremap } /^$\\|^%$<cr>
nnoremap { ?^$\\|^%$<cr>
```

This can (and probably should) be improved, e.g. by updating so that the last search registers are not modified, e.g. through using the `search()` function instead of the `/` command.

I did not quite understand exactly your idea of how the `%`s should work for the formatting. It would help with some examples. I think it better to continue this discussion as a separate issue, since it is easier for me when each issue has one single topic. I hope that is OK.
