### ISSUE TITLE
Spring-Clean all .aux and related files

### ISSUE THREAD

**Issue by curvi** [lervag/vimtex#902]
After compilation, latexmk leaves a lot of *.aux, *.bbl,.. and similar files. Using VimtexClean I can easily delete most of them, but still some files remain, e.g. the main.auxlock or .aux files of settings.tex files, which are things from the preamble.

I'd love to hear if there is a way I can specify the types of files I want to clear and get rid of all of the files I don't want.
Since I don't know if vtClean uses some sort of latexmk-clean I'm asking here. Also I think this would be a convenient setting for anybody to use, who wants to keep/remove certain files.

Thanks for a great plugin!

**Comment by lervag** [comment]
Thanks for the compliment!

Since Vimtex uses latexmk for cleaning (by default, one may also use `latexrun`), you will have to configure latexmk for which files are considered "garbage" or "generated". As an example, I use the following lines in my own `~/.latexmkrc`:

```perl
push @generated_exts, "cb";
push @generated_exts, "cb2";
push @generated_exts, "spl";
push @generated_exts, "nav";
push @generated_exts, "snm";
push @generated_exts, "tdo";
push @generated_exts, "nmo";
push @generated_exts, "brf";
push @generated_exts, "nlg";
push @generated_exts, "nlo";
push @generated_exts, "nls";
push @generated_exts, "synctex.gz";
push @generated_exts, "run.xml";
```

I think this should mostly solve your issue. However, the aux files from you `settings.tex` should be cleaned by default, so I don't quite understand why it does not work. Could you provide a minimal example where the aux files are generated but not cleaned?
