### ISSUE TITLE
Restarting continuous compilation breaks automatic pdf refreshing in Mupdf.

### ISSUE THREAD

**Issue by YesButWhyThough** [lervag/vimtex#903]
### Description
If continuous compilation is turned on then turned off, Mupdf will no longer automatically display an updated pdf after every write. 

### Minimal Working Example 

1. Open a TeX file, `gvim -u ~/.minimalvimrc hello.tex`

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

2. Turn on continuous mode with `\ll`
3. Make a change to the file, Mupdf will update with the new version. 

```tex
\documentclass{minimal}
\begin{document}

Goodbye World!

\end{document}
```
4. Turn off continuous mode `\ll`
5. Turn on continuous mode `\ll`
6. Make a change to the file, Mupdf will not update. Using `:VimtexView` does not force an update. Selecting the Mupdf window manually and pressing `r` will display the proper updated state of the PDF. However, doing so does not restore continuous updating. 
```tex
\documentclass{minimal}
\begin{document}

Goodbye Cruel World!

\end{document}
```

### Minimal vimrc file

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
let g:vimtex_view_method = 'mupdf'
set runtimepath^=~/.vim/plugged/vimtex "Plugin Location. 

```

**Comment by lervag** [comment]
Thanks, I've reproduced this. I'll look into it when I get the time.

Note, though, that I suspect that this might be difficult to fix. If I remember correctly, latexmk updates mupdf through signals, and this is set up when mupdf is opened from latexmk. I suspect that we see the same problem if you start the viewer manually with `\lv`, then start compilation afterwords. In any case, I'll see what I can do...

**Comment by lervag** [comment]
Ok, I've tried to fix this by using manual refreshes if possible. This means that MuPDF is refreshed from Vim, not from latexmk. It only works if you use the callback feature, but it looked like you already did.

Note though, that this will only update MuPDF on successful compiles.

I hope you agree this solves the issue.

**Comment by gkapfham** [comment]
Hello again @lervag! Thanks again for your continued development of `vimtex`. As you know, I use the plugin frequently and I really appreciate the time and knowledge that you invest into the development and maintenance of it.

I am speculating that the code you added to handle this request may have caused some of the key features of `vimtex` to stop working with `nvim`.

When I used exactly the minimal `.vimrc` file and `minimal.tex` and `NVIM v0.2.1-dev` with a correct `:CheckHealth` and a correctly working `nvr` I no longer see vimtex working correctly.

For instance, if I load the `minimal.tex` file and then run `\ll` the `mupdf` window does not load automatically. However, if I run `\lv` this will correctly load the `mupdf` window. Yet, now I have to always press `r` inside of `mupdf` to see the changes to the document.

Interestingly, I cannot reproduce this issue with `VIM - Vi IMproved 8.0 Included patches: 1-134`. That is, the minimal example will work as expected with `vim` but not work with `nvim`.

Finally, I can confirm that I see exactly this same behaviour, for both `nvim` and `vim` when I use my full `.vimrc` file and any of the papers that I am writing in LaTeX. That is, `\ll` brings up `mupdf` correctly and it reloads on changes when using `vim` and this expected behaviour is not evident when using `nvim`.

Okay, I hope that this has given you an acceptable description of my current situation. Please let me know if you need more details. Do you think that it is possible to make `vimtex` work again for both `nvim` and `nvim`? Or, is this perhaps an issue related to a new bug in `nvim`?

**Comment by lervag** [comment]
@gkapfham Hi. Sorry that the last update break things for you! The point of that change was that instead of relying on latexmk to pass signals to MuPDF, vimtex would do it. This is possible whenever the callback feature is activated, and so it should work if the callbacks work. Further, the point was that if we rely on latexmk to pass the signals, MuPDF will not update automatically if you for some reason close the viewer and then open again with `\lv` (as explained by the original post in this issue). Thus, my change was supposed to fix this by letting vimtex pass the `r` key to update MuPDF with xdotools.

However, I am now thinking that I can sort of combine both of these ideas. That is, I guess it will never hurt to make MuPDF refresh from the callbacks, and it seems to fix the current issue. However, there does not seem to be a good reason not to allow latexmk to refresh when that is possible. So I pushed a commit that should fix this. Please test.

**Comment by gkapfham** [comment]
Hello again @lervag! I am writing to confirm that the most recent update seems to resolve the issue for me. I can now correctly edit and compile papers with `vimtex` using my standard workflow in `nvim`. I will keep you updated as to whether I notice any further problems related to this issue. Thanks for the fix!

**Comment by lervag** [comment]
Great, thanks. And no problem :)
