### ISSUE TITLE
Request: A bit of context for \ref & \cite?

### ISSUE THREAD

**Issue by m3adi3c** [lervag/vimtex#912]
The only thing I miss from the LaTeX suite is the fact that if I want to reference an equation, say, an trigger completion for `\ref{eq:`, it opens a split with a bit of context, not just the labels. Same for `\cite{`.

Therefore, I'm writing this as a feature request which I find essential to consider for future updates.

If such a feature exists, please excuse my ignorance and let me know. I'm quite new to vim and its universe.

Thanks,
Adrian

**Comment by lervag** [comment]
I understand that this context can be useful. However, the completion in vimtex is implemented in a different manner than that of vim-latex/LaTeX-suite; I use the `omnifunc` capability of Vim/neovim. I could show more context in a preview window, which I've been trying out a little right now for bibtex completion. However, I personally don't find this very useful, since the completion menu already shows author, year and title. For me, that is and seems sufficient.

If I were to show more context, e.g. the full bibtex entry for a cite, or the definition of the label, I would need to rewrite much of the completion backend for these two types of completion. To me, this is too much work for too little gain, so I hope you can respect that I don't want to add this feature.

I'm sorry for the inconvenience.

**Comment by m3adi3c** [comment]
Of course I understand and respect that. Thank you very much for clarification!

**Comment by lervag** [comment]
Thanks. :)
