### ISSUE TITLE
RFC: VimtexInfo sort packages alphabetically

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#922]
Writing a larger latex document leads often to the inclusion of many packages. Since some packages require to be loaded after or before others, they are not sorted alphabetically in the preamble. 

Occasionally, I want to check whether I have already added a certain package, I use `<Leader>li` to see which packages are already added.

However, scanning a non-sorted listed for a certain package takes more time than when it is sorted alphabetically:

![packages](https://user-images.githubusercontent.com/371756/28611414-0569f5ae-71ec-11e7-821a-56dfe49222ce.png)

On the other hand, since load order is important I also see a reason to show them in load order. But this can be checked in the log file as well.

What do you think?

**Comment by andymass** [comment]
Actually, the order is completely arbitrary, since the packages are stored in a vim dict, not a list.

Somewhat related question for you: when you scroll down and up the info does it behave weirdly?  For me it seems to introduce a blank line every other, which is disorientating and makes it very hard to read the list when it is very long like this.

```vim
--- a/autoload/vimtex/state.vim
+++ b/autoload/vimtex/state.vim
@@ -516,7 +516,7 @@ function! s:vimtex.pprint_items() abort dict " {{{1
   endif

   if !empty(self.packages)
-    call add(l:items, ['packages', keys(self.packages)])
+    call add(l:items, ['packages', sort(keys(self.packages))])
   endif

   call add(l:items, ['compiler', get(self, 'compiler', {})])
```

**Comment by lervag** [comment]
First, @andymass is correct that the current order is random (obv. not truly random, I don't really know exactly how the order becomes from `key(a_dict)`).

I also think @andymass's suggested diff seems reasonable. It is better to show the packages in some order than in no order.

**Comment by lervag** [comment]
I don't think it is worth the bother to allow to see the package list in the order defined in the preamble. I hope that's OK.

Regarding @andymass comment on the printing of the info: Please open an issue for this. I'm actually planning on changing the vimtexinfo into a buffer instead of a long printed message.
