### ISSUE TITLE
indent uses &shiftwidth instead of shiftwidth()

### ISSUE THREAD

**Issue by andymass** [lervag/vimtex#927]
### Explain the issue

Using = across the example below, nothing gets indented.
vim allows `set shiftwidth=0`, and specifies that the behavior should be like `set shiftwidth=tabstop`.  You can use `shiftwidth()` to get the "effective" value.

### Minimal working example

```tex
\documentclass{minimal}
\begin{document}
\begin{foo}
Hello World!
\end{foo}
\end{document}
```

### Minimal vimrc file

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

set tabstop=4 shiftwidth=0
```

**Comment by lervag** [comment]
Thanks. This should be fixed now. Note that `shiftwidth()` seems to be rather new, since the docs suggest to define a backwards compatible variant in indent scripts that falls back to `&shiftwidth` if necessary.

**Comment by andymass** [comment]
This certainly works for my example, thank you.  Although (and I hope I don't sound demanding) would it be better to check each time in case shiftwidth is set to something else after script load?  (p.s. `&sw` is also used in `indent/bib.vim`).

**Comment by lervag** [comment]
Good point; but how about making it buffer local? It seems unlikely that anyone would change the shiftwidth _during_ and editing session..?

**Comment by andymass** [comment]
Sure, maybe, but then you wouldn't you need to detect when buffers are opened to properly set it? isn't that more complicated?  Are you concerned about the performance impact of just doing
`function! s:sw() | return exists('*shiftwidth') ? shiftwidth()  : &shiftwidth | endfunction`?

**Comment by lervag** [comment]
The `indent.vim` file would be loaded for each buffer, so that happens automatically. But I think the change I just made solves your point while keeping things at the simplest level.

I am not really that concerned about performance impact, I just want to keep things as simple as possible. I think the current version does that. However, I've also worked some time on keeping the indentation expression efficient, and so I am trying to avoid doing things that give unnecessary overhead.
