### ISSUE TITLE
vimtex makes <plug> mappings even though I have provided my own

### ISSUE THREAD

**Issue by andymass** [lervag/vimtex#933]
### Explain the issue

Basically, I would like to remap `tsd` and friends to something else because I frequently use vim's "till" command.  So, in the vimrc below I have provided my own.  The documentation suggests that if I have provided a custom mapping, vimtex will not create it's default one.  However, in the MWE below `:map ts` clearly shows the mappings are still being created.

````
x  tsd          @<Plug>(vimtex-delim-toggle-modifier)
n  tsd          @<Plug>(vimtex-delim-toggle-modifier)
n  tsc          @<Plug>(vimtex-cmd-toggle-star)
n  tse          @<Plug>(vimtex-env-toggle-star)
````

### Minimal working example

```tex
\documentclass{minimal}
\begin{document}
Hello World!
\end{document}
```

### Minimal vimrc file

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable

" Vimtex options go here
nmap cd <plug>(vimtex-delim-toggle-modifier)
xmap cd <plug>(vimtex-delim-toggle-modifier)
nmap cO <plug>(vimtex-env-toggle-star)
nmap co <plug>(vimtex-cmd-toggle-star)
```

**Comment by lervag** [comment]
Ah, this was supposed to work, but for some reason I forgot to check `hasmapto()` on the right-hand side. Fixed now.

**Comment by andymass** [comment]
Thank you!  :smile: :+1:

**Comment by kiryph** [comment]
I am also not very happy with the default mappings `tse,tsc,tsd` for the same reason (they overwrite `ts` (move till next `s`)).

So first of all thanks for this update and raising this issue.

I am already thinking for a while about good alternatives which do not clash with builtin mappings or other plugins I use.

1) The suggestion by @andymass
```
nmap cd <plug>(vimtex-delim-toggle-modifier)
xmap cd <plug>(vimtex-delim-toggle-modifier)
nmap cO <plug>(vimtex-env-toggle-star)
nmap co <plug>(vimtex-cmd-toggle-star)
```
clashes with unimpaired.vim `co` (even though tpope has changed it recently to `=o` which I am not a fan of). `cd` is very good but I have already considered using this for different things (e.g. change pwd to directory of current file). To put this simple these are too strong mappings to be ft-specific mappings. I will most likely use them for something more general.

2) Since I use the plugin [sandwich.vim](https://github.com/machakann/vim-sandwich), I can achieve the effect of `tsd` with following mappings
- `sr(m(` and vice versa `srm((` (explicitly selecting which parenthesis are changed and to what)
- `srmam(` and vice versa `srma(` (math-auto object `ma`)
- `srbm(` and vice versa `srb(` (sandwich auto object `b`)

For further sandwich objects see https://github.com/machakann/vim-sandwich/blob/master/after/ftplugin/initex/sandwich.vim.
If you use [tpope surround style mappings](https://github.com/machakann/vim-sandwich/blob/master/macros/sandwich/keymap/surround.vim), replace `sr` with `cs`.

However, they are bit clumsy compared to the original mapping `tsd`.

3) My current idea is to extend the usage of `s` as sandwich.vim has done (`sa`, `sr`, `sd`) and use

- `std` (surround-toggle-delimiter)

and similarly for `tsc` and `tse` to toggle starred  command or environment
- `ste` (surround-toggle-env-star)
- `stc` (surround-toggle-cmd-star)

Of course, they are also overwriting a  builtin mapping and therefore are not perfect but IMHO better than using `t`.

4) Another idea for toggling starred `cmd` and `env` is to modify `vimtex-cse` and `vimtex-csc` by filling the prompt with the existing name.
Changing a command or env would now require to clear the prompt  by `ctrl-u` if you want to change to a completely different command or environment.Adding or removing a star would be intuitively clear:
    1) `*<CR>` add star
    2) `<Backspace><CR>` remove star
 However, this could also be useful for other circumstances, e.g. if you like to change `tabular` to `tabularx`.

**Comment by andymass** [comment]
@kiryph 
Does vim-sandwich provide a super-set of the functionality of vim-surround, in the sense that I could uninstall vim-surround if I used vim-sandwich.  Or do they merely behave nicely next to each other?  I strongly prefer `cs` to `s`,  and I did not know you could use this mappings in vim-sandwich because of the vim-surround conflict.

To add to your idea 5., I think it would be pretty reasonable to make `csc<cr>`/`cse<cr>` or `csc*`/`cse*` toggle a star of the command or environment (currently, I think these do nothing since no commands/environments begin with a <cr> or star).  `csd<cr>` is a bit clunky for me, but I would simply continue to use my own custom mappings (or use a macro, repeat, etc..).

**Comment by kiryph** [comment]
@andymass Yes, vim-sandwich provides a super-set of the functionality of vim-surround. If you prefer the mappings as chosen by tpope's surround, see https://github.com/machakann/vim-sandwich/blob/master/doc/sandwich.txt#L386 and https://github.com/machakann/vim-sandwich/blob/master/macros/sandwich/keymap/surround.vim. I have uninstalled vim-surround myself.

**Comment by lervag** [comment]
@kiryph Thanks for the interesting thoughts on this. My thoughts are as follows (numbers are not related to your numbers):

1. I don't want to change the current deault mappings. To me, they make sense. All of the alternatives will alter Vim behaviour. To me, changing `t` is less bad than changing `s` or `c`. Besides, `t` still works, except that `ts` will require one to wait. Further, it is now easy to define custom mappings that disable the default maps. One may also disable a map by doing `nmap <nop> <plug>(vimtex...)`.

2. I love vim-sandwich, it works very well. I have not started to use the specific mappings for LaTeX yet, but I might do at a time. Thanks for the tip on the vimtex alternatives. I actually think it could be interesting to add a small section about this to the vimtex docs, perhaps in the faq chapter. What do you think? I would be very happy to consider a PR for this.

3. I think your idea about letting `cse` and `csc` start with the current name inserted is interesting. I am inclined to think it would make the `tse` and `tsc` unnecessary. To make it easier for me to keep track of things, perhaps you could separate this as a feature request in a new issue?

4. To me it seems un-intuitive that changing an environment to an empty string will toggle stars. So I either want to keep the toggle mappings or, possibly, continue the discussion about changing the `cse` type of maps.

**Comment by kiryph** [comment]
@lervag Thanks for your response. I reply to your thoughts in your order:

1. You are right `tsd`, `tsc`, `tse` do not overwrite, they just add a delay. They are customizable and therefore this is certainly not an issue. However, I do not like these delays.
BTW, combining `c` with `s` does not interfer with the builtin `c` at all. See e.g. following article by Drew Neil about custom vim mappings http://vimcasts.org/blog/2014/02/follow-my-leader/ or his slides https://speakerdeck.com/nelstrom/follow-my-leader (slide 9 and 10) from a talk he gave about this (video on vimeo no longer available).

2. I had already the same thought that a note about sandwich.vim would be interesting for many vimtex user. There are already many links to other plugins for certain features such as completion, snippets, linting, tag generators, latex documentation, faster folds. Let me see if I find to write a short paragraph the next days and create a PR.

3. I think this is a sensible thing to do. However, I am not sure whether everyone likes it.

4. And yes, I agree this is unintuitive.

**Comment by lervag** [comment]
Again, thanks. The present discussion has several different topics, and all of them are actually off topic. I propose that we open new issues for the topics that are interesting. I'll give some short replies here, but for further discussions, as said, I prefer we open new issues.

1. Good point. You are right about `cs` and `co`. I may be convinced to change the default maps, since I agree it is bad to interfere with vim defaults. However, such a change may be annoying to users, and I would prefer to allow more people to comment on this before I change defaults (in particular, these mappings have been in vimtex a long time). So, if you still think this makes sense, please open a new issue for it. 

3. I agree; I am also not sure if others will agree this is a good change. So, the question here is: Does it make sense to prefill the "change env/cmd input"? If you think it does, I'll be happy to consider it if you open an issue.

Note, I am not trying to be difficult, here. I just want to think things through properly before changing things that I expect a lot of people are using. I am personally fine with how things are now, even though I agree you both have valid points here.

**Comment by kiryph** [comment]
Do not worry. I think that your request for separate issues to keep discussions ordered makes things much easier, e.g. later on one can refer to it instead to some coment in some issue.

However, I usually open only issues if I really like to see something changed.

1. I have no problem with keeping tse,tsd,tsc (even though IMHO it is not good plugin practice). 

2. And prefilling the input for cse,csc is also something, I am not too desperate to have. It would be nice but it is not something I really missed and since some people might not like it, I also do not feel like the need for opening an issue.

So sorry for this blabla without any change request.

**Comment by lervag** [comment]
No problem. It is interesting, and having such discussions helps me to remember good practice in the future. I am trying to maintain vimtex on the path of good plugin practice. :)
