### ISSUE TITLE
Zathura works without xdotool, but Vim sends an error message anyway

### ISSUE THREAD

**Issue by dahlbaek** [lervag/vimtex#940]
First of all, thank you for this great plugin! I think I found a minor 'issue', or perhaps I detected a 'non-issue'.

I do not have `xdotool` installed, but it seems that `zathura` is working out of the box, including forward and backward search. Thus, I would expect vim to not give any error messages. However, when I open a .tex file in Vim, I get the following error message
```
vimtex: Zathura requires xdotool for forward search!
```
Note that my findings seem to contradict the findings in Issue #663. I would not know if zathura has changed since then, or if this is due to some local configuration on my end.

I have a .latexmkrc file present, but I don't think this should have any signficant effect. Anyway, its contents are
```
$pdf_previewer='start zathura';
$bibtex_use=2;
$clean_ext='synctex.gz';
```

Minimal setup: For simplicity, all files are put in the folder `~/test`.

Minimal .vimrc
```vim
set nocompatible

let g:tex_flavor='latex'

" Load Vimtex
let &rtp  = 'vimtex,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
let g:vimtex_view_method='zathura'
```

Minimal LaTeX example: Two files, test.tex
```tex
\documentclass{minimal}
\begin{document}

Hello World!

A line from file 1

\input{test2.tex}

\end{document}
```
and test2.tex
```
A line from file 2
```

Finally, in the same folder, goes the `vimtex` folder. Thus, in a terminal in the `~/test` folder, I see
```
$ ls -a
.  ..  test2.tex  test.tex  .vimrc  vimtex

```

Now, if I run
```
$ vim -u .vimrc --servername VIM test.tex
```
I get the error message 
```
vimtex: Zathura requires xdotool for forward search!
```
But everything seems to be working just fine. That is, I can do forward search with `\lv`, and backward search from Zathura with ctrl+left-mouse. Even backward search into `test2.tex`.

After pressing `\ll`, the output of `\li` is (I removed the lines with the names of the project files)
```
System info
  OS: Ubuntu 17.04
  Vim version: VIM 8.0 (1-95)
  Has clientserver: true
  Servername: VIM

  document class: minimal
  compiler: latexmk
    backend: jobs
    output: /tmp/vGwBZFW/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
    job: process 10200 run
    cmd: max_print_line=2000 latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e '$new_viewer_always = "0"' -e '$pdf_previewer = "zathura  -x \"vim --servername VIM --remote +\%{line} \%{input}\" \%S"' -e '$success_cmd = "'""'vim'""' --servername 'VIM' --remote-expr \"vimtex\#compiler\#callback(1)\""' -e '$failure_cmd = "'""'vim'""' --servername 'VIM' --remote-expr \"vimtex\#compiler\#callback(0)\""' 'test.tex'
  viewer: Zathura
    xwin id: 0
    process: 
      pid: -
      cmd: zathura -x "vim --servername VIM --remote +\%{line} \%{input}" --synctex-forward 1:1:'/home/username/test/latex/test.tex'  '/home/username/test/latex/test.pdf' >/dev/null 2>&1 &
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1
```

Bonus-info: The behaviour of Neovim is slightly different. Here, there is no error-message, and everything still works, but if I do a backward search from Zathura into `test2.tex`, Neovim does not open the file until I change the focus to Neovim. However, if I install `xdotool`, Neovim behaves exactly like Vim without `xdotool` (except that there is no error message). For this to work though, `neovim-remote` must be installed. A minimal init.vim for this (assuming `nvr` is in `${PATH}`) is
```vim
set nocompatible

let g:tex_flavor='latex'

" Load Vimtex
let &rtp  = 'vimtex,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
let g:vimtex_view_method='zathura'
let g:vimtex_compiler_progname='nvr'
```
and neovim can be started with
```
$ nvim -u init.vim test.tex
```
After pressing `\ll`, the output of `\li` is
```
System info
  OS: Ubuntu 17.04
  Vim version: NVIM v0.2.1-dev
  Has clientserver: true
  Servername: /tmp/nvimXYDfeM/0

  document class: minimal
  compiler: latexmk
    backend: nvim
    output: /tmp/nvimXYDfeM/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
    pid: 10371
    cmd: max_print_line=2000 latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e '$new_viewer_always = "0"' -e '$pdf_previewer = "zathura  -x \"nvr --servername /tmp/nvimXYDfeM/0 --remote +\%{line} \%{input}\" \%S"' -e '$success_cmd = "'""'nvr'""' --servername '/tmp/nvimXYDfeM/0' --remote-expr \"vimtex\#compiler\#callback(1)\""' -e '$failure_cmd = "'""'nvr'""' --servername '/tmp/nvimXYDfeM/0' --remote-expr \"vimtex\#compiler\#callback(0)\""' 'test.tex'
  viewer: Zathura
    xwin id: 0
    process: 
      pid: -
      cmd: zathura -x "nvr --servername /tmp/nvimXYDfeM/0 --remote +\%{line} \%{input}" --synctex-forward 1:1:'/home/username/test/latex/test.tex'  '/home/username/test/latex/test.pdf' >/dev/null 2>&1 &
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1
```

**Comment by andymass** [comment]
Perhaps this is veering into various separate issues, but the zathura handling needs to be re-worked a bit in general because it often does not behave with multiple instances of vim/zathura.  A few problems right now are:
  1. If you close vim and open vim with a different `--servername`, the same instance of zathura will be used, but inverse search doesn't work because zathura still knows the old `--servername`.  AFAIK, there is no way to change the `-x`/`−−synctex−editor−command` argument after launch other than typing it in to zathura manually (or with xdotool).  Perhaps vimtex should close and re-open zathura.
  2. vimtex uses xdotool to locate an existing zathura using the filename's basename (e.g. `main.pdf`).  This is a problem for people who use `main.pdf` on all their documents.  Two ways around this would be either use `dbus-send` to retrieve the filename instead of `xdotool`, or, if `window-title-basename` is `false`, use the entire filename when looking for the window.  Right now, unfortunately, xdotool is doing more harm than good, since zathura already handles itself single instance correctly, using the full filename (but this does not address  1.)
  3. vimtex uses xwin ids which are easily repeated (just close and re-open zathura, and it gets the same id).
  4. After spawning a new zathura, vimtex assumes the last window returned by xdotool is the correct one.  I am not sure if this can fail due to being out of order, but it is definitely a race-condition (although this is not very serious).

**Comment by lervag** [comment]
@dahlbaek I'm happy you like the plugin! So, in a way, I can agree it is confusing that `xdotool` is counted as a dependency. However, it is needed in order to keep track of Zathura windows in order to (try to) prevent opening multiple windows. For instance, with `xdotool`, if you already have a viewer opened, vimtex will try to use it instead of opening a new. However, as @andymass has addressed, there are some issues with how vimtex uses xdotool for zathura (and I think also MuPDF).

@andymass Yes, I agree. I did spend quite some time trying to get these things right, but I was never quite able to get it all the way. When I got a version that seemed relatively good (to me), I settled on that state. However, I will be very happy if you (or anyone) would be willing and able to find a better way to do these things. Some comments, though:

* I want to keep the requirements for making it work as light as possible.
* Zathura should work on both linux and osx. Thus we should not require linux only or osx only dependencies to make things better.
* I rarely use backward sync, and so I never really thought about your problem 1 before. I think your idea of closing and reopening seems like a pragmatic solution. But then, of course, we should be pretty sure that the zathura instance we close is not a false positive.
* Number 4: Yes, this is a race condition, but it seems pretty safe.

**Comment by lervag** [comment]
Btw, @dahlbaek: Thanks for the thorough description. I think I'll close this, as I still think people should have xdotool installed when using Zathura to get the best experience.

**Comment by dahlbaek** [comment]
@andymass Oh, I never noticed those issues! I usually let vim open my pdf-viewer, and close that pdf viewer again when I close vim. That workflow seems to mitigate most/all of those problems. For what it is worth, I would prefer a solution where vim never takes over or closes a pdf-viewer that was not opened by the same vim-session; but this seems to be what you have in mind already. It seems reasonable that a pdf session opened by vim is killed when vim is killed. I wish I could offer my assistance, but I do not really know anything about vimscript (or pdf-viewers, or vimtex).

@lervag I see, in that case I will install xdotool!
