### ISSUE TITLE
Suggestion: shortcuts on the TOC

### ISSUE THREAD

**Issue by dbmrq** [lervag/vimtex#942]
I'm working on a big project and I use Vimtex's TOC all the time. It's getting a little annoying to move the cursor to the section I want and type `<CR>`. I thought it would be handy if there were shortcuts… there could be a letter beside each section, for instance, and you'd just tap something like `<leader>` + that letter and you'd get to the section. Or maybe just type a single letter for chapters and a combination of two letters for sections, something like that... since the buffer isn't modifiable most commands wouldn't be missed.

So the TOC would look something like:

```
1       [A] A chapter
1.1     [B] A section
1.2     [C] Another section
1.3     [D] Yet another section
2       [E] Another chapter
2.1     [F] This chapter also has sections
2.2     [G] Ok, I think that's enough
```

And you'd type `<leader>e` to go to the second chapter.

This is not a huge priority, of course, and the TOC is already great, I just thought the idea is worth mentioning. :)

**Comment by lervag** [comment]
I've made a prototype implementation that is off by default. You can enable it with the following option:

```vim
let g:vimtex_toc_hotkeys = {
    \ 'enabled' : 1,
    \ 'keys' : 'asdf',
    \ 'leader' : ';',
    \}
```

By default, ; is used as a leader and the alphabet is used for the keys. Thus you can simply just use the `enabled` key to see how the default version looks and behaves like. Feedback is of course very welcome. I think it currently seems to work pretty well, but I guess we could improve with some better highlights and perhaps minor modifications?

I think I want to keep this option disabled by default, so that users enable it knowingly. But it could be advertised in the feature list, perhaps, to make people aware that it exists.

**Comment by dbmrq** [comment]
Fantastic, it works great! 🎉 

It would be nice if the hotkeys could be all highlighted the same way, something different from the rest but not too flashy, but that's just nitpicking, this is great already. Thanks! :)

**Comment by lervag** [comment]
Great! I've made some minor improvement (handle multibyte characters, etc) and added highlighting. I think this should solve the issue.

Btw: I've used the `Comment` highlighting as default, but you can change all highlighting if you want.

**Comment by dbmrq** [comment]
Awesome, thank you. :)
