### ISSUE TITLE
dse does not delete additional arguments for some environments

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#950]
### Explain the issue

Deleting an environment that has additional arguments in curly braces (for instance `block` in beamer) does not remove those arguments.

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass{beamer}
\begin{document}

\begin{frame}
    \begin{block}{Title}
        content
    \end{block}
\end{frame}

\end{document}
```

Using `dse` when the cursor is place on `begin` leaves a `{Title}` in the document.

### Minimal vimrc file

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
```

**Comment by lervag** [comment]
Actually, `dse` will never remove extra arguments. The reason is that it is hard to know what is actually an argument. E.g.: `\begin{foo}{\color{red} bar}\end{foo}`; it is not possible to know if the `{\color{red} bar}` is an argument to the opening part of the environment, or if it is content.

However, one could make the heuristic that anything that follows directly without any spaces is "naturally" an argument. This would work, I guess, but it would also mean that people need to adhere to this as a stylistic preference. I don't want to add more options, though, so we would have to agree that this is the more appropriate behaviour...
