### ISSUE TITLE
Pause when closing brackets - going back to visual mode

### ISSUE THREAD

**Issue by stevenjgilmore** [lervag/vimtex#953]
First off, apologies if this has been addressed before, I looked through the past issues and found similar problems but none of the solutions there worked for me. 

Second thanks for the plug-in! 

My issue: 
When I close a bracket (either `[]` or just `]`) and then attempt to back to command mode (`Ctrl-c`), the closing bracket `]` is deleted. If I wait for a few seconds, vimtex 'highlights' the bracket and then I can exit insert mode without deleting the bracket.  

I am working in macOS, with vim 8.0.1050 installed from brew. I am on the latest version of vimtex, commit: 918fd8123b81c83d0e8e0ba3c2dc8c9d8df06756. 

### Minimal working example

Here is a minimal working example. I'm not sure how to type this up, since it only occurs when exiting into command mode. Hitting `ctrl+c` or `esc` directly after writing `]` will delete the bracket unless I wait 2,3 seconds. 

```tex
\documentclass{minimal}
\begin{document}
] 
\end{document}
```

### Minimal vimrc file

The below .vimrc is enough to reproduce this issue. Have tried with and without the indent_enabled (saw that solution on another issue). 

```vim
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

let g:vimtex_indent_enabled = 0
```

I tried to keep the summary succinct, would be happy to provide more information. Thanks again!

Edited: wrote 'visual mode' when I meant 'command mode'

**Comment by andymass** [comment]
This is happening because of vimtex's ]] mapping to close environments/delimiters which is being canceled half-way by CTRL-C.  I'm guessing this doesn't happen for you with escape.

You have a few options:
1. Don't use CTRL-C to exit escape mode, use CTRL-[ or escape.  CTRL-C does _not_ in general behave the same as escape (e.g., it also does not fire InsertLeave autocommands).

2. Change the map ]] to something else.  For example, the vim-endwise style map,
    `imap <silent> <c-x><cr> <plug>(vimtex-delim-close)`

3. Explicitly map ] CTRL-C to work around this particular case:
   `inoremap ]<c-c> ]<esc>`

4. Map CTRL-C to something "safer."  I don't really recommend this because CTRL-C is vim's "stop what you are doing right now" command
    `inoremap <c-c> <esc>`

(p.s. I think you mean normal mode not visual or command mode).

**Comment by stevenjgilmore** [comment]
Thanks for the informative reply, I'll close this issue. I thought I had tested with escape, my apologies.

**Comment by lervag** [comment]
Thanks, @andymass, for looking into this and responding to @stevenjgilmore.
