### ISSUE TITLE
Project donations?

### ISSUE THREAD

**Issue by copyme** [lervag/vimtex#955]
I have to say that vimtex is just great and I do not see myself writing LaTeX without it. Well, I would like the project to be active, and I would like to give me support for it in a more profitable way. So, is there anyway to make a donation? @lervag do you have a paypal account?

**Comment by copyme** [comment]
I just saw it on the main page.

**Comment by lervag** [comment]
Thank you so much for the kind words! I am very happy to hear that people enjoy the plugin. It feels good to contribute to the Vim community. :)

I'll admit I have been somewhat inactive the last month, mostly due to personal matters. I expect to get on top of the open issues in not too long, though.

Please don't hesitate to open issues for comments, suggestions for improvements or bug reports!
