### ISSUE TITLE
spaces in filename for bib file makes omni complete fail on Windows.

### ISSUE THREAD

**Issue by JackeJR** [lervag/vimtex#965]
As above. If you have a space in your bib filename, omni complete for citations fail.

E.g.
FAIL this is a file with spaces.bib
OK  this-is-a-file=without-spaces.bib

The main tex file has spaces and is in the same folder as the bib file. Adding quotes (single or double) seems to trip up latexmk (unable to find bib file) so I didn't investigate further on that.

I haven't had time to dig into where the path handling occurs. I took a quick look at complete.vim but didn't see anywhere obvious that could be the problem.

System:
- Windows 10 Pro x64
- gvim 8.1159
- latest vimtex (https://github.com/lervag/vimtex/commit/ae0b19440a0081ca75d8abecee719e7064f92549)
- StrawebryPerl 5.26.1.1
- TexLive 2017, updated today

Will try to investigate further.

**Comment by lervag** [comment]
Noted. Will look into it when I get the time. Obv., you should be able to get things working by choosing a (sensible) file name without spaces. Still, I agree this should be fixed.

**Comment by lervag** [comment]
Actually, bib files should not have spaces, see [here](https://tex.stackexchange.com/questions/112606/how-to-make-space-recognized-in-bib-filename-when-setting-bibliography) and [here](https://tex.stackexchange.com/questions/102258/referencing-bib-files-with-spaces-in-the-filename). The method for obtaining the completion entries rely on bibtex and will therefore not work if there is a space in the file name.

I'm therefore closing this issue, since I think you can solve the problem by using a different file name.

**Comment by JackeJR** [comment]
I see, thanks for looking it up. I was not aware of this before.

**Comment by lervag** [comment]
No problem. :)
